### ISSUE TITLE
Фича: улучшить дизайн поля для комментариев в темной теме

### ISSUE THREAD

**Issue by pavel9609** [vas3k/vas3k.club#10]
Когда ты используешь темную тему, поля для комментариев и постов, все равно остаются белыми, что немного бросается в глаза.
![Не баг а фича](https://user-images.githubusercontent.com/15073091/80358835-aba58200-8885-11ea-85ea-18eae7f5940d.png)

**Comment by ninedev-i** [comment]
Думаю можно закрывать
