### ISSUE TITLE
Добиться 100% по производительности в lighthouse

### ISSUE THREAD

**Issue by nikolay-govorov** [vas3k/vas3k.club#101]
Это приличный эпик, на несколько задач.

В #33 мы ужали ресурсы c `1 MB` до `684 KB` на главной странице, и суммарно увеличили оценку на 15% (замерял на одной машине подряд).

<table>
<tr>
<td>
<img width="1440" alt="Screenshot 2020-05-04 at 09 45 16" src="https://user-images.githubusercontent.com/24303010/80942078-98963300-8dec-11ea-9a0d-83f470db3875.png">
</td>
<td>
<img width="1440" alt="Screenshot 2020-05-04 at 09 44 53" src="https://user-images.githubusercontent.com/24303010/80942075-96cc6f80-8dec-11ea-8f4e-5abb1fbdadd6.png">
</td>
<tr>
</table>

Предлагаю с самого начала задать высокую планку производительности, тем более что мы не строим SPA — дальше будет сложно.

Сейчас, когда у нас совсем немного фронтенда мы можем встроить аудит в CI, и не допустить разрастания в будущем.

Что вы думаете об этом?

**Comment by vas3k** [comment]
Честно говоря, я не верю в Lighthouse. Я считаю его манипулятивным инструментом, который использует Google чтобы навязывать свои или угодные себе технологии (тот же webp или pwa для андроидов), угрожая понизить «некачественные» сайты в выдаче. Это рак и дно.

Потому я против того, чтобы гнаться за мнимой циферкой, усложняя всем жизнь. Если что-то можно сделать безболезненно — пожалуйста. Добавляйте новые теги, минификаторы, итд.

Если для этого требуется хранить картинки в пяти разных форматах и собирать фронтенд по пять минут каждый раз — нет.

Ну и для начала нужен CI, да. Как для фронтенда, так и бекенда.

**Comment by nikolay-govorov** [comment]
Я говорю, скорее о некоторой планке — зачастую при добавлении новых фич и зависимостей разработчик не замечает как бандл разрастается и превращается в мегабайты JS.

Lighthouse — это лишь один из возможных инструментов, и я предлагаю его как отправную точку, а не истину в последней инстанции. Другим инструментом может быть [size-limit](https://github.com/ai/size-limit) от создателя PostCSS.

**Comment by nikolay-govorov** [comment]
Другими словами, меня беспокоит что средний современный фронтенд весит по 10MB и грузится минуту — хочется избежать этого в родном чатике. Мой опыт показывает что гораздо легче сразу задать рамки, чем потом оптимизировать.

Работа над производительность не будет бесплатной — это требует ресурсов и экпертизы, но мне кажется что игра стоит свеч.

**Comment by vas3k** [comment]
Тогда ок, с удовольствием посмотрю как правильные ребята это делают :)

**Comment by skywinder** [comment]
Я будет круто увидеть PR с такой оптимизацией 👍
Но что бы не накапливать технический долг и пока мастеров оптимизации у нас нет - закрою таску до лучших времен.
