### ISSUE TITLE
Принудительно конвертировать загружаемые в комментах картинки в JPG

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#102]
В кото-треде люди загружают фотографии котов в PNG (!!!) и даже при ресайзе до 1400 пикселей они все равно весят по два мегабайта. Так нельзя.

Пример: https://vas3k.club/post/939/#comment-44db3721-743a-41df-969d-968a1df1bfcf

В комментах точно, для постов посмотреть

**Comment by nikolay-govorov** [comment]
Это круто поможет #101.

В целом, картинки можно ужимать конвертировать и ресайзить на лету. Например через крутой https://imgproxy.net

**Comment by vas3k** [comment]
@nikolay-govorov ага, у меня есть свой такой, написанный лет 8 назад https://github.com/vas3k/i.vas3k.ru

Мне с ним попривычнее, хоть я и давно хочу переписать его на Go. Щас впилю туда быстро авто-конвертацию :)

**Comment by FMajesty** [comment]
@vas3k 
Зачем на Go? Погнали на Rust переписывать:)
Кстати, с 522c147b294cd0610c686162175350cd9fca0295 иссуй всё?

**Comment by vas3k** [comment]
На Go потому что он быстрее и надежнее как байтодробилка, что и надо для прокси картинок. В Rust не вижу смысла для этой задаче. Да, я закрою тикет когда проверю, что все работает.

**Comment by shrddr** [comment]
а можно как-то перед конвертацией проверить, фотография перед нами или текст или график которые и в PNG отлично пожмутся и при этом не потеряют в качестве?
