### ISSUE TITLE
Баг: комменты второго уровня не приходят автору поста в бота 

### ISSUE THREAD

**Issue by shkaff** [vas3k/vas3k.club#1029]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Автору поста не приходят уведомления о комментариях второго уровня. Это прямо критично для модерации автором поста: я так упустил не один срачик, не увидев его в боте. Почти уверен, что раньше приходили все комменты. 

Из чата: 
1. https://github.com/vas3k/vas3k.club/blob/a1c3af8305c78cdefad7204c627fbb04152accf9/posts/views/posts.py#L248
2. https://github.com/vas3k/vas3k.club/blob/a1c3af8305c78cdefad7204c627fbb04152accf9/notifications/signals/comments.py#L51

@devcooch пишет в чате:

> А вот этот if mode == "create" по первой ссылку у Оскара - он не похерился после того, обязательно делать превью до публикации?

## Ожидаемый результат

Каждый коммент приходит автору поста по дефолту

**Comment by shkaff** [comment]
Продолжаю наблюдение: в [вопросе из прошлого коммента](https://vas3k.club/question/17887/) перестали прилетать комменты второго уровня. Кажется, отметка в 50шт что-то сделала (но это не точно).

**Comment by igoose1** [comment]
Кажется, я разобрался, в чем проблема. Кнопка "подписаться на комментарии" срабатывает дважды: когда прожимаешь эту кнопку (js отправляет запрос) и когда отправляешь новый комментарий (django обрабатывает форму). Во втором случае оно не "уважает" прошлую подписку.

Мне кажется, это легаси, от которого забыли избавиться.

https://github.com/vas3k/vas3k.club/blob/0fdc0c0c43b7919966965c796b9159b7cccbd520/comments/views.py#L61

**Comment by skywinder** [comment]
Походу это происходит при подписке здесь:
https://github.com/vas3k/vas3k.club/blob/f1a76890facd0e7d7adcbb42b6102c328ac0b798/comments/views.py#L64

в целом если кто хочет подебажить-разобраться, стоит посмотреть где и как проставляется 
https://github.com/vas3k/vas3k.club/blob/f1a76890facd0e7d7adcbb42b6102c328ac0b798/posts/models/subscriptions.py#L9

```python
    TYPE_ALL_COMMENTS = "all"
    TYPE_TOP_LEVEL_ONLY = "top"
```

**Comment by igoose1** [comment]
Подождите, я же указал строчку с ошибкой. Она именно из-за того, что обработка запроса не уважает старую подписку. В прошлый раз я много слов "кажется" написал: забудьте про мою былую неуверенность, баг именно там.

Дебажить не надо, надо кому-нибудь фиксить.

**Comment by vlle** [comment]
попробую посмотреть и взять на себя issue

**Comment by igoose1** [comment]
@vlle, отлично! Поставь меня ревьюером, пожалуйста. У меня много контекста по багу.
