### ISSUE TITLE
Replace EasyMDE with a modern editor

### ISSUE THREAD

**Issue by nikolay-govorov** [vas3k/vas3k.club#103]
Сейчас для редактирования постов/комментов используется [simplemde](https://github.com/sparksuite/simplemde-markdown-editor), но он 5 лет не обновляется и весит 100KB (тянет огромный и заброшеный [CodeMirror](https://codemirror.net)).

Возможно, стоит посмотреть на более современные и легковесные инструменты, например:
[ckeditor5](https://github.com/ckeditor/ckeditor5) или [quill](https://github.com/quilljs/quill.js) (~50kb).

Может есть редакторы которые вам нравятся? Какие критерии у вас для подбора такого инструмента: MD, загрузка изображений, что ещё?

**Comment by vas3k** [comment]
С удовольствием перееду на аналог, если он выглядит и работает так же. Особенно интересует поддержка drag-n-drop загрузки файлов. Остальное пофиг.

Главное — никакого WYSIWYG и json-блоков. Чистый Markdown.

**Comment by nikolay-govorov** [comment]
@vas3k, привет. Как тебе [tui.editor](https://github.com/nhn/tui.editor)? MD, есть и WYSIWYG и текстовый режим. Есть официальная обёртка для Vue. Вроде не заброшен и как-то поддерживается. Поддерживает Live Preview.

Работа с изображениями тоже есть. Сходу не увидел drag-n-drop для файлов, но вроде и докрутить не сложно — поддерживает плагины.

**Comment by vas3k** [comment]
@nikolay-govorov щас потыкаю демки. WYSIWYG режим, конечно, сразу надо отключать, это жесть :)

Главный вопрос остается как раз про драг-н-дроп загрузку и автосохранение в local storage чтобы текст не терялся при креше браузера.

**Comment by nikolay-govorov** [comment]
@vas3k, как тебе? Чего-то не хватает?

**Comment by vas3k** [comment]
Ну я написал выше. Если это есть (и вообще удастся полностью воспроизвести поведение текущего редактора) — давай впиливать, я за. Лишь бы это не было очередной блестящей штучкой, которую через полгода задеприкейтят и опять придется переделывать.

**Comment by syabro** [comment]
> автосохранение в local storage 

мне кажется это проблема компонента-обертки а не редактора :)

**Comment by vas3k** [comment]
Я просмотрел все варианты выше и в интернете, и не нашёл ни одного редактора, который бы умел в визуальный маркдаун, и автокоррект на iOS, и в системную орфографию, и в другие запрашиваемые людьми фичи. Ищем дальше. Я открыт к предложениям

**Comment by vas3k** [comment]
Как и ребята в треде выше, я пока заменил SimpleMDE на его более современный форк — EasyMDE. Для пользователей не должно ничего поменяться, зато в нем меньше уязвимостей и код посовременнее.

**Comment by mlnchk** [comment]
На оф сайте vue есть сэндбокс с `dead simple md editor` — https://codesandbox.io/s/github/vuejs/vuejs.org/tree/master/src/v2/examples/vue-20-markdown-editor

По большому счету это собственный велосипед, использующий marked под капотом, но в целом это не так плохо

**Comment by skywinder** [comment]
> Как и ребята в треде выше, я пока заменил SimpleMDE на его более современный форк — EasyMDE. Для пользователей не должно ничего поменяться, зато в нем меньше уязвимостей и код посовременнее.

Не знаю, есть ли такоой баг в оригинальном SimpleMDE, но про EasyMDE вот тут нашли небольшую багу https://github.com/vas3k/vas3k.club/issues/81

**Comment by vas3k** [comment]
Ладно, вроде опыт показал, что обновленный форк более-менее всех устраивает, так что закроем тикет до появления конкретных идей что еще можно улучшить
