### ISSUE TITLE
Баг: плашка «автопополнение» дублируется при досрочном пополнении членства

### ISSUE THREAD

**Issue by sultee** [vas3k/vas3k.club#1041]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать
(если честно, я этого не знаю, так как у меня лишь один профиль в Клубе)

## Описание бага

Если в профиле включено автопополнение, но юзер досрочно продлил подписку, то в профиле будет отображаться два автопополнения — прошлогоднее и новое. Как и когда в действительности спишутся деньги, я (пока) не знаю.
![Screenshot 2023-01-24 at 23 05 02](https://user-images.githubusercontent.com/10268931/214415473-156a3da7-f255-4f31-8e5f-deeed6cbb108.png)

На скриншоте верхняя плашка автопополнения — «свежая», а нижняя — «прошлогодняя».

## Ожидаемый результат

Вместо старой плашки со старой суммой — новая с новой.

## Шаги к воспроизведению

1. Зайти в свой платежный профиль (/monies/)
2. Вручную продлить членство в клубе на год
3. Вернуться на страницу профиля и увидеть вторую плашку над изначальной

**Comment by vas3k** [comment]
Нет, она не дублируется, ты реально оплатил ДВЕ подписки и они обе показываются. Так что давай там отмени одну из (ну либо не отменяй, плоти долор, это даже лучше :D)

**Comment by vas3k** [comment]
Вот еще волшебная линка, чтобы проверить все активные подписки через Stripe. Он должен показать это чуть более детально (линка публичная и для всех, так что пофиг) https://billing.stripe.com/p/login/6oEcMM7Sj7YfaWIbII

**Comment by dolshevsk** [comment]
Может добавить подсказку, если у человека больше одной подписки? Действительно может быть не очевидно для пользователей

**Comment by vas3k** [comment]
@dolshevsk подписку не отследишь пока она не истекла. В текущей ситуации, когда у 80% юзеров раньше были привязаны российские карты, а теперь нет, это будет только путать. Ведь подписка есть, а реального чарджа нет
