### ISSUE TITLE
Баг: В любых полях ввода текста не работает автокомплит, замена текста, автокоррект и умные знаки препинания на macOS и iPadOS

### ISSUE THREAD

**Issue by e-zubak** [vas3k/vas3k.club#1044]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

При написании поста или комментария в клубе (по крайней мере в Safari) автоисправление ошибок, замена текста, умные кавчки и прочие смарт прибамбасы набора текста от Apple работают на iPhone, но не на iPad и MacOS

## Ожидаемый результат

Хотелось бы, чтобы поведение было в соответствии с настройками устройства, а именно ожидание, что работать будет на всех типах устройств

## Шаги к воспроизведению

1. На устройстве с MacOS или iPadOS в браузере Safari поместить курсор в поле для ввода текста комментария
2. Набрать кавычки, стринг на замену, слово с ошибкой
3. После этих действия нажимать пробел
4. Указанные фичи набора не работают

**Comment by skywinder** [comment]
too narrow case. 
закрою, если будут идеи как это можно исправить - пишите. но разбираться с этим врд ли кто-то будет
