### ISSUE TITLE
Баг: Filtering links on feed page points to unknown URL (leading / trailing slash problem)

### ISSUE THREAD

**Issue by kefzce** [vas3k/vas3k.club#1050]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага
Feed page (filtering links) points to unknown (404) URLs since missing `trailing slash` problem.

Possible 'cause of the latest changes in code bellow:

https://github.com/vas3k/vas3k.club/blob/c6a828a38f956e076638cd4d1cffb98260b2abdf/frontend/html/feed.html#L73-L82

Any of these links points to the correct endpoint, ***BUT*** without the slash at the end.
All of them would work as expected if we manually add this by ourselves, so assume it's either frontend related problem or misconfiguration on server-side. 
## Ожидаемый результат
For my taste, both URL with/without leading slash should work the same.
So suggesting to fix it on server-side instead.

## Шаги к воспроизведению

1. [First](https://vas3k.club/)
2. Click `Best`
3. Now we're able to see dropdown with filtering criteria ([top_week/top_month/top_year](https://github.com/vas3k/vas3k.club/blob/master/posts/views/feed.py#L21-L23) and so on...) <img width="199" alt="image" src="https://user-images.githubusercontent.com/8298339/217431725-a7baf025-cde4-4d18-b848-102d03c7cd21.png">
4. Click on any of these to get an error ( or try [this one ](https://vas3k.club/all/top_week) )
5. Add slash after any of these from step 4 to opened it up as [expected](https://vas3k.club/all/top_week/) :^)

**Comment by igoose1** [comment]
Fixed by 4f16361.
