### ISSUE TITLE
Подписка на ежедневную рассылку после еженедельной не работает

### ISSUE THREAD

**Issue by VBodrov** [vas3k/vas3k.club#106]
После очаровательного скриншота ежедневной рассылки Васи в чатике я плохо сплю по ночам, и даже сменил частоту рассылки в профиле с еженедельной на ежедневную.

Но рассылки приходят только еженедельные.

**Comment by vas3k** [comment]
Ежедневная рассылка приходил только по будням, за исключением понедельника, ведь тогда выходит еженедельный дайджест. Такова логика, все равно на выходных интернет никто не читает.
