### ISSUE TITLE
Не разворачивать ссылки на YouTube/Twitter/картинки если они сделаны через тег

### ISSUE THREAD

**Issue by cazorla19** [vas3k/vas3k.club#107]
Нашел странное поведение markdown-движка, пока доделывал свое интро.

```
В прошлом году я сделал по этой теме доклад для DevOpsDays Moscow.

https://www.youtube.com/watch?v=E4CBGdx9mco
```

Разворачивает YouTube-окно автоматом, что здорово.

```
В прошлом году я сделал по этой теме доклад для [DevOpsDays Moscow].(https://www.youtube.com/watch?v=E4CBGdx9mco)
```

Точно так же разворачивает YouTube-окно автоматом, что непонятно. По идее это должна быть простая гиперссылка, на которую юзер может кликнуть и перейти на сайт YouTube.

Дайте знать, баг это или фича. Возможно, это связано с особенностями SimpleMDE? Есть кейсы, когда не хочешь пихать YouTube в свой пост, оставив обычную ссылку на источник.

**Comment by vas3k** [comment]
Это фича парсера. Возможно, стоит ее отключить для явных ссылок. Оставить только для вставок голого URL.

**Comment by cazorla19** [comment]
Спасибо! ❤️

**Comment by vas3k** [comment]
Хах, обращайся :)
