### ISSUE TITLE
Баг: Бот палит неопубликованные посты

### ISSUE THREAD

**Issue by imyaro** [vas3k/vas3k.club#1090]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага
Бот посылает сообщения о комментах моих чуваков к постам, которые мне недоступны

## Ожидаемый результат

~~Хочу увидеть этот пост~~
Бот не оповещает о комментариях на посты, которые мне недоступны

## Шаги к воспроизведению

1. Подписываемся на vas3k
2. Ждем
3. Бот присылает сообщение
![image](https://user-images.githubusercontent.com/7985237/234798633-a682e918-6b22-423a-a408-52ed8ee44384.png)
4. Тыкаем на сообщение
5. 404

Судя по всему, этот пост не был опубликован, а некоторые всё же могут читать и комментить такие посты.

**Comment by vas3k** [comment]
Фича
