### ISSUE TITLE
Баг: неверные почтовые серверы MX в DNS

### ISSUE THREAD

**Issue by DavidOsipov** [vas3k/vas3k.club#1091]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага
Почтовые MX серверы, привязанные к домену https://vas3k.club/, тухлые. От этого письма с кодами активации могут попадать в спам (у меня все письма в спам ушли)

<details>
  <summary>Скриншот под спойлером</summary>
  
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/38164582/235291895-46e71d7a-3cbc-4ecd-9c79-7a965e4221c2.png">
  
</details>

## Ожидаемый результат

В MX записи занести сервера Яндекса. Вроде с них отправляются письма. Проверить на всякий случай DKIM, SPF, DMARC записи

## Шаги к воспроизведению

1. Зайти [сюда](https://www.hardenize.com/report/vas3k.club/1682753515#email)
2. Посмотреть ошибки в MX записях

**Comment by vas3k** [comment]
А можешь рассказать поподробнее как ты к этому пришел?

1. Яндекса там давно нет, Клуб работает через Fastmail и AWS SNS

<img width="1054" alt="Screen 2023-04-29 at 10 16 00" src="https://user-images.githubusercontent.com/176344/235292581-020f396e-81ca-4b22-9bb0-b6e169062b74.png">

2. Сам Fastmail говорит, что все прекрасно и жалоб на спам у нас не больше обычного (их всегда есть какое-то количество, этого не избежать)

<img width="751" alt="Screen 2023-04-29 at 10 19 05" src="https://user-images.githubusercontent.com/176344/235292590-9c9b8d4d-ba4a-48bf-a4af-cecdaba030d4.png">

3. Все наши DNS обёрнуты в Cloudflare и по твоей ссылке сервис почему-то пытается пинговать именно сервера Cloudflare, из-за чего конечно же фейлится, потому что насколько мне известно, Cloudflare не любит когда его ноды пингуют. Ты точно уверен в его валидности?

**Comment by igoose1** [comment]
Добавлю наблюдений: почти все письма от клуба попадут в спам у провайдера riseup.

**Comment by DavidOsipov** [comment]
Извините, что пропал. Похоже MX серверы не отвечают только одному инструменту. Закрываю
