### ISSUE TITLE
Баг: не дают остаться в одиночестве и грусти

### ISSUE THREAD

**Issue by ganqqwerty** [vas3k/vas3k.club#1092]
## Чеклист

- [х] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [ ] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Я нажимал на кнопку отписки от клубного журнала уже раз десять, а он все равно преодолжает приходить.

## Ожидаемый результат

Не будут приходить емайлы.

## Шаги к воспроизведению
в конце письма с дайджестом нажать на кнопку «отписаться»

**Comment by vas3k** [comment]
Отписал тебя руками. Других жалоб за 3 года не было
