### ISSUE TITLE
"Nested" комментарии

### ISSUE THREAD

**Issue by VBodrov** [vas3k/vas3k.club#11]
На мой взгляд, недостаток одного уровня комментариев, потеря дискуссии если она возникла. И что гораздо важнее, её очень трудно заметить со стороны тем, кто в дискуссии не участвует.

**Comment by vas3k** [comment]
Но ведь уровня там два 🤔

**Comment by VBodrov** [comment]
Ну основной момент, что они там ограничены. Вот на примере ваших с Ашотом ответов в реплае про ракету. В его комментарии по сути две ветки комментариев: его и твоя. А все сидят во втором уровне.

**Comment by pavel-voronin** [comment]
Комментарии - разве место для дискуссии? Лично мне хороший комментарий сразу отвечает на вопрос, зачем я его прочитал. Это либо actionable advice, либо раскрытие темы поста, либо законченное одобрение/осуждение. Комментарии к комментариям - это уже приглашение к диалогу и чаще всего полезно только двоим, для этого есть личка в телеге. Имхо, 2 уровня вполне достаточно, остальное от лукавого.

**Comment by skywinder** [comment]
*Время чистить брошенные таски* 

месяц не говорили, и конечная мысль, что фишка не нужна. (А тех.долг проекта тем временем растет) 

Для таких идей и для беклога можно сделать отдельный майлстоун и туда складывать подобные фичи, что (пока) не получили поддержки.

Предлагаю issue закрыть и положить в milestone  с лиричным названием: ”Unfullfilled promises and broken dreams”.
