### ISSUE TITLE
Сортировка комментариев в посте

### ISSUE THREAD

**Issue by akimkooo** [vas3k/vas3k.club#110]
Новые / По лайкам

PS сейчас когда видишь, что в популярном (много комментов) появились новые комменты, то хрен найдёшь их.

**Comment by vas3k** [comment]
Согласен. Опять же, в этом тикете я бы сначала отталкивался от UI. Накодить это не проблема, вопрос как сделать удобным и ненавязчивым

**Comment by altmind** [comment]
селектбокс "sort by" над комментами ?

видено много раз.

**Comment by akimkooo** [comment]
Фильтр не работает, при переходе в тематические комнаты (Трактор, Кухня)

На главной странице переключаем фильтры - всё работает. Заходим в комнату, нажимем на любой фильтр - нас выбрасывает на главную

**Comment by vas3k** [comment]
А причём тут комментарии в посте? :)

**Comment by vas3k** [comment]
И да, это баг, его стоит завести тикетом
