### ISSUE TITLE
Проверка орфографии при написании поста

### ISSUE THREAD

**Issue by ephimoff** [vas3k/vas3k.club#111]
Было бы хорошо иметь проверку орфографии и пунктуации во время написания поста.
Ну и предпросмотр поста перед публикацией. А то сейчас нужно сохранять в черновики, потом его открывать, потом нажимать на редактирование и публиковать.

**Comment by vas3k** [comment]
И типограф! Но начнем с орфографии, ок :)
Вот только фронтенд доделаем и можно будет туда все либы подключать, чтобы прям 15 мегабайт сразу и грузилось минуту!

А если серьезно, скорее всего решится сменой редактора в #103

**Comment by skywinder** [comment]
Активности в таске нет. Желающих сделать (пока) тоже. 
Если кто захочет взять эту таску - пишите, переоткроем.
Закрою в пользу #103 - можно будет там обсудить детали.
