### ISSUE TITLE
Баг: неверный формат даты в эндпоинте /feed.json

### ISSUE THREAD

**Issue by weazyexe** [vas3k/vas3k.club#1110]
Клуб поддерживает выдачу постов в формате JSON Feed, но в полях `date_published` и `date_modified` дата лежит в неверном формате.

Спецификация JSON Feed: https://www.jsonfeed.org/version/1/

### Шаги к воспроизведению:
- Дёрнуть https://vas3k.club/feed.json
- Смотрим на массив `items`, у айтема поля `date_published` и `date_modified`

### Текущее поведение:
- Дата формата `yyyy-MM-ddTHH:mm:ss.SSS` (пример `2023-06-24T15:17:25.207755`)

### Ожидаемое поведение:
- Дата в формате стандарта RFC 3339 `yyyy-MM-ddTHH:mm:ssX` (пример `2023-06-24T15:17:25Z` или `2023-06-24T18:17:25+03:00`, как удобнее будет, в целом это один стандарт)

**Comment by vas3k** [comment]
Хороший баг, надо фиксить

**Comment by igoose1** [comment]
Прикреплю еще результаты jsonfeed validator:

https://validator.jsonfeed.org/?url=https%3A%2F%2Fvas3k.club%2Ffeed.json

Помимо проблем с датами, иногда content_text = null.

**Comment by vlle** [comment]
попробую взять на себя ишью, вроде нужно поправить формат конвертации в post.to_dict всего лишь
