### ISSUE TITLE
Баг: в поиске выдаются удаленные посты

### ISSUE THREAD

**Issue by glader** [vas3k/vas3k.club#1127]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

https://vas3k.club/search/?q=%D0%BC%D0%B5%D0%BC%D1%8B
второй пост - удаленный

![Снимок экрана от 2023-08-01 13-47-59](https://github.com/vas3k/vas3k.club/assets/494361/5844911f-6e15-4bfd-8501-c6841d0b88af)

## Ожидаемый результат

Пост не должен выводиться в поиске

## Шаги к воспроизведению

1. Перейти по ссылке https://vas3k.club/search/?q=%D0%BC%D0%B5%D0%BC%D1%8B
2. Нажать на второй пост (https://vas3k.club/post/20454/)

**Comment by igoose1** [comment]
Неактуально. Пояснения:
> там в клубе индекс по крону обновляется, мб просто еще не было реиндексации
> https://t.me/vas3k_club_dev/16723

Сейчас проверил, больше не воспроизводится.
