### ISSUE TITLE
Баг: Карта в разделе "Люди" показывает людей не в местах, указанных в профиле

### ISSUE THREAD

**Issue by boredcity** [vas3k/vas3k.club#1129]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Карта показывает чуваков в Мегхалая, Индия:
![Screenshot 2023-08-11 at 13 17 39](https://github.com/vas3k/vas3k.club/assets/3993495/664cc2a9-86a2-4aca-bfd6-f70482aa942f)
![image](https://github.com/vas3k/vas3k.club/assets/3993495/f623d0eb-52ec-4336-a654-8b830bfad9e6)

А они совсем не там:
https://vas3k.club/user/nmode/ (Гоа)
https://vas3k.club/user/rarms/ (остров в Таиланде)

## Ожидаемый результат

Люди отображаются в указанных странах и городах (а в идеале могут сами выбирать точку, что полезно для децентрализованных городов)

## Шаги к воспроизведению

1. Прийти на https://vas3k.club/people/
2. Найти Мегхалая :)

**Comment by Programistich** [comment]
`Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues`

**Comment by stfbee** [comment]
Дубликат #682 получается

**Comment by ReDetection** [comment]
@stfbee @Programistich не согласен. та бага про то, что sf bay area не очень точно показывается, а новый чувак жалуется, что точка совсем вообще не там! у меня тоже точка стоит в Новосибирске, хотя я уже почти год в 4500км на Кипре

**Comment by magusch** [comment]
В общем проблема, что Гоа это не город, зато он нашёл другой город с началом на Гоа. Есть конечно идея проверять на точное написание в начале города, потом региона, а уже потом если не нашёл то искать хоть что-то. 

<img width="1007" src="https://github.com/vas3k/vas3k.club/assets/1834052/9cd07282-ecb4-42c4-bd4b-f24ed1e24fd6">

<img width="973" src="https://github.com/vas3k/vas3k.club/assets/1834052/4384b3aa-6225-412d-af51-3a9223c03cdc">

**Comment by ReDetection** [comment]
УРА, товарищи https://vas3k.club/post/32617/#Teper-mozhno-dvigat-s
