### ISSUE TITLE
Баг: разрешить исправлять "Кратко ваш аргумент почему" в баттлах

### ISSUE THREAD

**Issue by igoose1** [vas3k/vas3k.club#1131]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Если написать аргумент в баттле, попросит три поля: за что аргументируем, кратко о чем аргумент, длинный аргумент.

Когда хочешь отредактировать аргумент, дает только одно поле, как будто это обычный комментарий. Если опечататься в поле "Кратко ваш аргумент почему", то эту опечатку исправить нельзя. Приходиться удалять аргумент и пересоздавать его.

## Ожидаемый результат

Форма для редактирования обычных комментариев и форма для редактирования комментариев баттла должны быть разные. В последнем случае нужно еще уметь исправлять "Кратко ваш аргумент почему".

## Шаги к воспроизведению

1. Написать аргумент к баттлу
2. Попробовать его исправить

**Comment by arscool3** [comment]
могу взяться если не вы против

**Comment by arscool3** [comment]
я добавил и возможность поменять выбор стороны

**Comment by arscool3** [comment]
думаю нужен коммент @vas3k, нужна ли возможность изменения выбора стороны в батле
