### ISSUE TITLE
Блокировать кнопку «ответить» при отправке комментария

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#114]
На iPhone не в браузере нажал случайно несколько раз кнопку ответить и отправилась три одинаковых сообщения.![image](https://user-images.githubusercontent.com/3356474/81031602-00b14b80-8eb7-11ea-8778-ca59ac46e2c3.jpeg)

**Comment by altmind** [comment]
минус вот это. 

часто проблемы с интернетом решаются переподключением и перепосылкой, с знатным кол-вом ре-сабмитов. та же самая пробема с двойными комментами мб решена добавкой чего-нибудь уникального в запросе.

**Comment by malcolmmadsheep** [comment]
Привет, я займусь им

**Comment by skywinder** [comment]
@vas3k  Это пофиксили или просто решили забили? Давай я сделаю, коли так

**Comment by malcolmmadsheep** [comment]
@skywinder я пофиксил. Не заметно? 😢
