### ISSUE TITLE
Отображать время написания комментариев

### ISSUE THREAD

**Issue by andriisych** [vas3k/vas3k.club#115]
Если укомментариев отображается хотя бы дата написания, то в ответах на них вообще ничего нет. Хотелось бы видить дату и время.

**Comment by severin-d** [comment]
Удваиваю.

@vas3k, в каком формате лучше выводить? Сухом, но надежном `MM.dd HH:mm` или в человекопонятном?

**Comment by vas3k** [comment]
Мне нравится когда так: в первые 5 дней после постинга показывается "человекопонятный" с округлением, то есть «6 часов назад» или «3 дня назад» (в джанге должна быть для этого функция), потом начинается только дата типа «2 мая», а когда сменяется год — он автоматом добавляется, делая «2 мая 2020». Или типа того, когда как :)

Щас найду функцию из бложека чтобы вы могли использовать для примера. В обычных комментах я бы тоже на нее заменил

**Comment by vas3k** [comment]
Не, не нашел. Но суть понятна, надо сделать свой template filter. Пакет называется [humanize](https://docs.djangoproject.com/en/3.0/ref/contrib/humanize/#naturaltime).

**Comment by altmind** [comment]
вы точно этого хотите? вам важно что коммент был оплавлен "2 hr ago" а не в "8:35 AM"?

имхо, "ago" это бесполезная фича, которая вообще скрывает важные данные. мб отображать просто даты всегда?

**Comment by vas3k** [comment]
А на этот вопрос очень простой ответ: таймзоны. Потому 8:45 уже никто не пишет.

**Comment by altmind** [comment]
пишут, its ok.

"posted almost 2 years ago" - так тоже пишут, и лучше бы они не писали. даты везде. в браузере они есть, в профиле тоже ДБ.

**Comment by altmind** [comment]
если их нет, это тема для semanic web(processable by any server side processor)

<date-garbo>1588874772.03</date-garbo>

**Comment by altmind** [comment]
> А на этот вопрос очень простой ответ: таймзоны. Потому 8:35 уже давно никто не пишет.

ну а люди читающие "about 2 years ago" тоже недовольны
