### ISSUE TITLE
Не работает кнопка-рейтинг интро для ширины экрана < 1024px

### ISSUE THREAD

**Issue by Heiden88** [vas3k/vas3k.club#118]
![Интро️_ #intro от @AndreyBondarenko — Вастрик Клуб](https://user-images.githubusercontent.com/39517635/81065203-3bda6b80-8f05-11ea-9433-7eb716a204bb.png)

**Comment by vas3k** [comment]
Хороший баг. Должно быть легко пофиксить даже новичку. Либо я займусь как будет время
