### ISSUE TITLE
Баг: 404 вместо поста, который не был скрыт автором

### ISSUE THREAD

**Issue by AlexWoodblock** [vas3k/vas3k.club#1185]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

При попытке открыть статью "Водительские права в Германии на примере Берлина. Долго. Дорого. Терпимо" через поиск выдается 404.
С автором статьи связались, и он подтвердил, что после написания пост не был скрыт или удален. 

## Ожидаемый результат

Должен открыться пост с названием "Водительские права в Германии на примере Берлина. Долго. Дорого. Терпимо".

## Шаги к воспроизведению

1. Пытаюсь открыть https://vas3k.club/post/23485/
2. Получаю 404

**Comment by vas3k** [comment]
Значит пост был удален админами. Там и правда какой-то черновик, а не пост
