### ISSUE TITLE
Баг: вижу комментарий в списке своих комментариев, но не вижу в треде

### ISSUE THREAD

**Issue by ivkrotova** [vas3k/vas3k.club#1188]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Написала комментарий. Вижу его в списке своих комментариев последним с 3-мя плюсами, но не вижу своего сообщения в теме (искала поиском по странице в том числе).

## Ожидаемый результат

Все комментарии должны быть видны в треде.

## Шаги к воспроизведению

1. Зайти в [мой профиль](https://vas3k.club/user/irina_krotova/).
2. Мой последний комментарий в теме к этому [посту](https://vas3k.club/question/22369/#comment-03b45461-9bcb-4956-a3b7-e8c78ae019c2), содержит в себе текст "@evgenia_kochkina" (ответ пользователю).
3. Перейти в сам пост.
4. Комментарий и сама ветка дискуссии не отображаются, но и сообщений "Комментарий удален" тоже нет.

**Comment by vas3k** [comment]
Это странно, я всё вижу. Ты не скрывала тред случайно? 
<img width="482" alt="Screenshot 2024-03-20 at 16 29 30" src="https://github.com/vas3k/vas3k.club/assets/176344/e391dd9f-1555-437b-bf42-751872c27ab5">

**Comment by ivkrotova** [comment]
@vas3k Точно, никогда этой фичей не пользовалась, и случайно нажала, видимо. Ложная тревога.
