### ISSUE TITLE
Много картинок в посте == умирающий браузер

### ISSUE THREAD

**Issue by ppavel** [vas3k/vas3k.club#1192]
Люди жалуются на фризы/зависания браузеров
причина - клиент пытается прогрузить все картинки и упирается в лимит на кол-во соединений
<img width="226" alt="Screenshot 2024-04-03 at 12 43 15" src="https://github.com/vas3k/vas3k.club/assets/389810/c3dc2d62-67a8-499e-b643-013ad506f428">

решается одной тривиальной правкой (на аватарах уже есть, на других картинках нет): включить встроенный в браузеры lazy load - картинки будут загружаться когда до них докрутили.
Было:
<img width="501" alt="Screenshot 2024-04-03 at 12 45 49" src="https://github.com/vas3k/vas3k.club/assets/389810/568786e2-6bc3-419f-96e7-55f3e2de2284">
Стало:
<img width="469" alt="Screenshot 2024-04-03 at 12 54 25" src="https://github.com/vas3k/vas3k.club/assets/389810/ef934c18-dd61-43e2-baa3-980b394c0d7b">

PR: https://github.com/vas3k/vas3k.club/pull/1193

**Comment by igoose1** [comment]
Когда ты создавал issue, Github должен был дать тебе чеклист. Один из них: "Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues". Почему-то в твоем issue чеклиста нет, а он здесь оказалася важен: в списке issues и PR есть точно такие же issue и объяснение, что lazyload ломает.

https://github.com/vas3k/vas3k.club/issues?q=lazy

https://github.com/vas3k/vas3k.club/pull/1083

https://github.com/vas3k/vas3k.club/pull/880

Это issue должно быть закрыто.
