### ISSUE TITLE
Непоследовательное использование шрифтов в профиле

### ISSUE THREAD

**Issue by devcooch** [vas3k/vas3k.club#120]
В окне профиля интро написано шрифтом без засечек, а если открываешь его как пост - то с засечками.
**Профиль:**
![image](https://user-images.githubusercontent.com/2089015/81068262-5e0dc280-8ee0-11ea-89f2-b904ca752005.png)
**Пост:**
![image](https://user-images.githubusercontent.com/2089015/81068272-6403a380-8ee0-11ea-9593-6d0b4c7e9425.png)

**Comment by Vostenzuk** [comment]
А как в итоге-то должно быть? 
Сейчас как будто весь интерфейс без засечек, а любой длинный текст с засечками. Надо в профиле интро сделать с засечками?

**Comment by vas3k** [comment]
@Vostenzuk 
> Надо в профиле интро сделать с засечками?

Да :)
У людей ОКР обостряется, ты не понимаешь!
