### ISSUE TITLE
Просмотр ленты хронологическом порядке по дате создания поста

### ISSUE THREAD

**Issue by rozhok** [vas3k/vas3k.club#122]
Сейчас лента отображается по дате последнего комментария. Если не заходил несколько дней то не знаешь какой пост был написан за время твоего отсутствия, потому что он мог утонуть под давлением более популярных тем.

Хотелось бы иметь возможность сортировать ленту не по дате последнего комментария а по дате создания поста. Тогда можно будет переключаться между популярным/последним и ничего не пропускать.

**Comment by vas3k** [comment]
Готово

<img width="424" alt="Screenshot 2020-05-06 at 12 04 52" src="https://user-images.githubusercontent.com/176344/81165135-cd8fba80-8f91-11ea-8f9f-c4627aee48fc.png">
