### ISSUE TITLE
Баг: пост без комнаты при нажатии "только в комнату" можно найти только по прямой ссылке

### ISSUE THREAD

**Issue by shkaff** [vas3k/vas3k.club#1272]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [ ] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Если запостить пост, выбрать "только в комнату", но при этом не выбрать комнаты, кажется, пост улетает в лимб и не ищется, и не отоброжается нигде. Напр. https://vas3k.club/project/26412/

## Ожидаемый результат

Если комната не выбрана, но стоит галка "только в комнату", выдает ошибку.

**Comment by vas3k** [comment]
Это фича
