### ISSUE TITLE
Баг: Активация инвайтов

### ISSUE THREAD

**Issue by cudjo** [vas3k/vas3k.club#1280]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Не совсем уверен, что это баг, скорее не продуманная логика активации инвайтов. Скопировал секретную ссылку из новости и попытался активировать инвайт. Попал на страницу активации и отвлекся (ушел в другое приложение), таск манагер посчитал, что браузер необходимо прибить. Открываю браузер снова и ссылка уже протухла, инвайт активировать невозможно. Получается забрал инвайт, но активировать его не могу. Либо у меня счетчик дней не увеличился. Мой ник в клубе cudjo.

![image](https://github.com/user-attachments/assets/c9f18b70-84b4-4a1c-a33f-6dcaead6abc6)
![image](https://github.com/user-attachments/assets/bb9f811c-8729-45fe-aec9-e08f7095491c)
![image](https://github.com/user-attachments/assets/458d7c65-2637-4552-ac25-31f5404490ae)
![image](https://github.com/user-attachments/assets/7c2960b0-ed14-494f-8840-ee4688f69403)

## Ожидаемый результат

Думаю нужно сохранять в куках/сессии/бд (зависит от юзера, анонимус или зарегестрированный) какой-то флаг, что именно этот инвайт не активирован и выводить информацию об активации пока юзер не активирует инвайт. Таким образом сохранится возможность активировать инвайт при нештатных ситуациях (случайная перезагрузка, умер браузер, выключили свет и тд).

## Шаги к воспроизведению

1. Переходим по ссылке инвайта.
2. Попадаем на страницу активации.
3. Обновляем страницу.
4. Получаем сообщение о том, что инвайт уже использован.

**Comment by vas3k** [comment]
Выглядит как будто ты просто не успел. Точнее ты успел одним из первых открыть страницу инвайта, но пока отвлекался, инвайт забрал уже другой человек (некий Станислав). Потому по клику тебе показало уже что инвайта больше нет, не успел, хех

**Comment by cudjo** [comment]
> Выглядит как будто ты просто не успел. Точнее ты успел одним из первых открыть страницу инвайта, но пока отвлекался, инвайт забрал уже другой человек (некий Станислав). Потому по клику тебе показало уже что инвайта больше нет, не успел, хех

Тогда можно ишу закрыть, показалось другое поведение)
