### ISSUE TITLE
Визуализировать результаты батлов

### ISSUE THREAD

**Issue by Vostenzuk** [vas3k/vas3k.club#129]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/19980512/81127819-1f135780-8f48-11ea-83bc-7c56e6e849e4.png">

Было бы круто как-то визуализировать полоску в зависимости от результатов баттла. Чтобы такой раз — и увидел результат, а не подсчитывал, где больше аргументов и плюсов

**Comment by vas3k** [comment]
В заголовок это запихать будет тяжело, но вот под постом рисовать какую-то статистику — я за. Вопрос в том как и кто продумает там UI :)

**Comment by Vostenzuk** [comment]
У меня в голове была двигающаяся полоска вот как в заголовке, только отдельная)

Фёдор

**Comment by Takheer** [comment]
Как насчёт чего-то такого?
![Bildschirmfoto 2020-05-07 um 16 37 36](https://user-images.githubusercontent.com/11667674/81290210-18d4c680-9081-11ea-82f4-aa5d3e0fe8e6.png)

**Comment by vas3k** [comment]
@Takheer вот это нормас! Сделаешь — будет круто :)

**Comment by Vostenzuk** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/19980512/81292049-9691d580-9073-11ea-9438-5d6d18363b5a.png">
Я вот над такими двумя думал, но я не дизайнер совершенно
