### ISSUE TITLE
Профиль - ссылки

### ISSUE THREAD

**Issue by ElSpirit** [vas3k/vas3k.club#13]
label:improvement
в заголовке профиля ссылки пишутся подряд - предлагаю их принудительно разделять (при заполнении писал их на разных строках, а в шапке они "склеились")

**Comment by FMajesty** [comment]
Там просто markdown. Строку пропускать два раза надо ¯\_(ツ)_/¯

**Comment by ElSpirit** [comment]
@FMajesty согласен.
 офтопну слегка:  как тут привязать тег к заметке?

**Comment by FMajesty** [comment]
Пока никак. А есть боты какие?
@ElSpirit

**Comment by ElSpirit** [comment]
@FMajesty у меня? нет пока ))

**Comment by vas3k** [comment]
Да, я бы хотел чтобы кто-то добавил в маркдаун-парсер чтобы он ставил <br> при одиночном переводе строки. Я даже сам пытался, но быстро не нашел где. Половину проблемы бы это решило :)

**Comment by vas3k** [comment]
Открыл для этого PR #18

**Comment by alex-pobeditel-2004** [comment]
@FMajesty 
> Там просто markdown. Строку пропускать два раза надо  
  
Некропост, но: 
```
два пробела в конце строки  
перед нажатием Enter  
никто не отменял же ещё.
```
А то иначе именно новый абзац начинается.
Вроде стандартная для markdown фигня, да и необходимость в < br > пропадает практически

**Comment by FMajesty** [comment]
@alex-pobeditel-2004 
Для многих не совсем очевидно думаю, хз

**Comment by alex-pobeditel-2004** [comment]
Но тем не менее документированное поведение, и если уж писать в markdown, то по канону)

**Comment by FMajesty** [comment]
@vas3k
