### ISSUE TITLE
Научить всратый AI присылать комментарии из батлов с указанием выбранной стороны

### ISSUE THREAD

**Issue by Vostenzuk** [vas3k/vas3k.club#131]
Сейчас комменты из батлов приходят таким образом, что догадаться, за какую сторону проголосовал пользователь, можно только по контексту.

**Comment by vas3k** [comment]
Норм. Надо аккуратно добавить название стороны из post.metadata во все шаблоны коммента в телеграме: https://github.com/vas3k/vas3k.club/tree/master/notifications/templates/telegram

**Comment by Vostenzuk** [comment]
А как можно это протестировать локально?

**Comment by vas3k** [comment]
Скорее всего никак. Ну либо регать своего бота, канал, прописывать туда токен и все такое. Это не стоит того ради 1 строчки HTML

**Comment by altmind** [comment]
Я добавил тупое логирование всех telegram сообщений(даже если bot_id пустой). полезно даже в  проде. логи могут перестать однострочными, правда - в сообщениях мб переносы. Cообщения в выводе `docker-compose up`

напишите правильный текст в шаблоне плз.
