### ISSUE TITLE
Странный код на странице подтверждения почты

### ISSUE THREAD

**Issue by malcolmmadsheep** [vas3k/vas3k.club#132]
Привет!

Я не нашёл похожего ишью. Что вообще предполагалось здесь выводить?

![image](https://user-images.githubusercontent.com/12401969/81209197-e1aada80-8fd8-11ea-984a-1160568925da.png)

**Comment by vas3k** [comment]
Хах, это смешной баг, который очень смешно получился. Спасибо!
