### ISSUE TITLE
Draft-посты попадают в поиск

### ISSUE THREAD

**Issue by FMajesty** [vas3k/vas3k.club#135]
Например https://vas3k.club/post/1353/
По запросу "Берлин".

**Comment by vas3k** [comment]
А он тебе виден по клику потом? Надо понять это два бага в одном или один

**Comment by FMajesty** [comment]
@vas3k, не виден:)

**Comment by vas3k** [comment]
Фуф, окей, тогда не сильно критично, оставлю на фикс от коммьюнити. 

Нужен кто-то, кто аккуратно умудрится сджойнить результаты поиска и отфильтровать их дополнительно по is_visible (то же самое для комментов и юзеров), не наделав сотню лишних SQL запросов :)

**Comment by altmind** [comment]
мб не добавлять черновики в индекс in the first place?
