### ISSUE TITLE
Возвращать после авторизации на страницу с которой авторизовался, а не на собственный профиль.

### ISSUE THREAD

**Issue by Muntello** [vas3k/vas3k.club#137]
Например, если браузер тебя не распознал, а ты хочешь оставить коммент к статье, то после нажатие на «Войти» и авторизации в Patreon открывается твой профиль в Клубе и приходится заново искать статью, к которой хотел оставить коммент.

**Comment by vas3k** [comment]
Норм идея. В коде даже уже есть поддержка параметра ?goto=, который редиректит куда надо после авторизации. Кто-нибудь мог бы аккуратно передавать его в форме логина из поста

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
