### ISSUE TITLE
Автоматическая привязка профилей к телеге

### ISSUE THREAD

**Issue by a-x-** [vas3k/vas3k.club#139]
В профилях участников нет их ников в телеге. Не порядок,

Зачем: находить профили людей из чата в клубе и наоборот, чтобы дополнить портрет и связать во едино, посмотреть посты и вопрсы, ну короче, очевидно мастхев.

Связать это легко через бота. Мы такое в рокетбанке сделали: каждый сотрудник через бота привязывает себя.

Для тех, у кого нет ников можно id юзать в ссылке, если правильно помню

**Comment by a-x-** [comment]
upd: вижу что привязка технически есть, осталось сделать поиск по никам телеги и отображение в профиле

с списке ссылок в анкете тоже можно добавлять, чтобы человек не дублировал

**Comment by vas3k** [comment]
Это вопрос прайваси. Кто хочет — сам укажет в био. Не вижу смысла городить здесь логику для защиты персональных данных.
