### ISSUE TITLE
Профиль - альтернативная активация бота

### ISSUE THREAD

**Issue by ElSpirit** [vas3k/vas3k.club#14]
не нашел кнопки "привязать бота" - да, возможно интернет ломает Роскомнадзор, но нужна альтернатива, как это можно сделать, и да, бот действительно игнорирует просто так ему написавших. проверено.

**Comment by vas3k** [comment]
Я был бы рад, если бы кто-то подсказал как правильно вставлять кнопку логина в телеграме в обход Стены Роскомнадзора.

**Comment by FMajesty** [comment]
@vas3k 
По-моему никак.
Что насчет сделать хеш для пользователя, который надо будет передать боту командой какой? 👀

**Comment by krepver** [comment]
Или наоборот - бот бы выдавал ссылку ал-я vas3k.club/aibot/link/{hash} с хешем для привязки.

**Comment by FMajesty** [comment]
О, тоже отличный вариант.

**Comment by vas3k** [comment]
Надо попробовать. Я думал, что телеграм требует именно чтобы его авторизовали, но я не вижу пока преград сделать ссылку с хешем
