### ISSUE TITLE
Вопрос по поводу contribution

### ISSUE THREAD

**Issue by malcolmmadsheep** [vas3k/vas3k.club#140]
Привет!

Такое дело - смотрю на проект и аж руки чешутся что-то сделать. Я вижу, что куча вещей лежит в TODO или Bugs, которые можно было бы сделать. Заметил, что начали делать на вью - очень круто, я никогда с ним не работал, но буду рад научиться, да в целом будет полезно познакомиться со стеком. Так, хватит комплиментов, к делу.

Есть пара вопросов, которые меня останавливают:

1. In Progress в Trello - информация, которой можно верить? Я имею в виду - карточки там могут двигать 3 человека. Из этого вопрос - если кто-то по своей инициативе начал фиксить какой-то баг или пилить фичу - каким образом можно обновить Trello? Какое-то доверенное лицо или что?
2. Есть ли у задач какие-то приоритеты и ограничения по времени: например, я хочу сделать какую-то фичу, чтобы было красиво, или пофиксить баг, чтобы не было не красиво, но я могу поковыряться в коде 3 - 4 часа в неделю. И если что-то нужно сделать ASAP, то я, например, не буду брать в оборот, потому что уверен, что не смогу закрыть ASAP, но смогу 
пофиксить баг, который мешает жить 2 - 3 человекам.

Ну и напоследок, хотел бы взять какой-то ленивый баг пофиксить, чтобы поковыряться в проекте, а то делать делать это без цели не хочется.

**Comment by vas3k** [comment]
Привет!

Тикеты в трелло актуальны, да. Их двигаем мы, пока этого хватает. Остальные наблюдают.

Брать тикеты можно из issues. Находишь какой нравится, описываешься у него в комментах, что берешь его, делаешь, присылаешь PR. Если есть вопросы по интерфейсу — можно прямо в issue вкинуть скриншот чтобы провалидировать ок или не ок.

В трелло я стараюсь сортировать колонки по значимости. Сверху — важнее, а потом как пойдет. Лучше начинать с багов, конечно.

Ограничений по времени нет. Критические тикеты я пока беру на себя. Работай в своем темпе, главное отпишись в комментах что взял, чтобы остальные видели. Простого «я попробую поработать над этим на выходных» будет достаточно. Не получилось, хрен с ним, отпишись чтобы следующий взял.

Для первого бага можешь смотреть по лейблу good first issue. Они как раз для этого :)

Велкам!

**Comment by skywinder** [comment]
Твой ответ прямо добавить в contribution guidelines надо! :)

**Comment by vas3k** [comment]
Я как раз их описал в новом REAME после этого issue :)
