### ISSUE TITLE
Написать кастомную регулярку для парсинга Medium, как уже сделано для Github и YouTube

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#143]
Сейчас когда постишь ссылку на Medium, глупая машина не может распарсить ее из-за защиты.

<img width="901" alt="Screenshot 2020-05-08 at 12 35 05" src="https://user-images.githubusercontent.com/176344/81397863-71ab6a00-9128-11ea-92ad-ab1f6d5d84b2.png">

Нужно придумать что-то чтобы было красиво. На усмотрение автора. 

Вот здесь лежат все парсеры: https://github.com/vas3k/vas3k.club/blob/master/common/embeds.py#L18

По сути это регулярки с html-шаблонами.

**Comment by nerorenaissance** [comment]
@vas3k 
Как эту  машину локально-то заранить, сиквенс, я так полагаю, связан с созданием ссылки? 

Получаю ебалу в виде
```
club_app            |   Resource punkt not found.
club_app            |   Please use the NLTK Downloader to obtain the resource:
```

**Comment by vas3k** [comment]
О, ну можешь за одно и с этой неприятностью разобраться, да :D Надо устанавливать nltk при создании докера

**Comment by nerorenaissance** [comment]
@vas3k 
Посидел чутка, похоже сам Клаудфлер хер обойдешь, а хитрожопцы с Медиума постарались знатно, у них из апишки есть разве что RSS, но он ограничен для бесплатного парсинга — что-то около 10 последних записей.

Есть какие-то всратые сервисы, которые ресейлят доступ к их апи, но такое.
https://embed.ly/code
https://api.rss2json.com/v1/api.json

Я еще покурю, но такое ощущение, что нам придется либо идти по десяти последним статьям в RSS, либо расчехлять какую-нибудь вундервафлю типа селениума.

**Comment by vas3k** [comment]
Да забей тогда, можем просто отключить парсер для медиума. В клубе сейчас куча критических багов и фич, чтобы тратить на такую фигню время
