### ISSUE TITLE
Добавить возможность предложить исправление в тексте автору.

### ISSUE THREAD

**Issue by karavaevitalii** [vas3k/vas3k.club#144]
Если читаешь текст и видишь грамматическую/пунктуационную/любую другую ошибку было бы классно иметь возможность указать на это автору без комментария. Возможно, сразу указать исправление, которое применяется после ревью от автора

**Comment by skywinder** [comment]
https://github.com/vas3k/vas3k.club/issues/283#issuecomment-646098678

> @skywinder мне привычен вариант, который когда-то предложил Котеров: выделяешь текст, нажимаешь Ctrl+Enter и во всплывающем окне пишешь пояснения. Дополнительно где-то внизу поста можно оставить ссылку-кнопку "Сообщить об ошибке автору", которая по клику будет вызывать тоже самое окно.
> 
> Если что, то так много кто делает. На ум пришли [Хабр](https://habr.com/ru/company/habr/blog/442208/), [TJournal](https://tjournal.ru/tech/179416-zoom-peredumal-vvodit-skvoznoe-shifrovanie-tolko-dlya-platnyh-akkauntov-i-poobeshchal-ego-vsem-polzovatelyam) и хотя бы та же Медуза. Сходите по ссылке, попробуйте выделить текст и нажать Ctrl+Enter

**Comment by ktaranov** [comment]
@skywinder идея разумная, нет сил запилить, пока закрываем. Граманаци придется страдать, либо писать в личку авторам.
