### ISSUE TITLE
При сабмите ссылки   Resource mpunkt not found.   Please use the NLTK Downloader to obtain the resource

### ISSUE THREAD

**Issue by altmind** [vas3k/vas3k.club#151]
Добавляя ссылку на /create/link/ получаю exception:

https://medium.com/sketch-app-sources/five-app-prototyping-tools-compared-form-framer-origami-pixate-proto-io-c2acc9062c61

```
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
```

Похоже надо добавить шаг для закачки nltk данных в makefile

**Comment by vas3k** [comment]
Я бы решал эту проблему в корне. Создал тикет #158 для этого
