### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by altmind** [vas3k/vas3k.club#155]
Я вижу что используется postcss, при этом вложеность в исходных css как бы намекает что эти css тоже были из чего-то сгенерены.

как насчет поддержки scss?

чтобы эти(с этими ручными отступами которые херачатся форматтерами IDE-шки)
```
.compose-form {
}

    .compose-form-title input {
    }

    .compose-form-text textarea {
    }
```

можно было схлопнуть до 
```
.compose-form {
&-title input {}
&-text textarea {}
}
```

дополнительный бонус - легче работать с префиксами для рулов. из недавнего
```
.CodeMirror-code{
color:#333
  body.dark &{
    color: #CCC;
  }
}

**Comment by vas3k** [comment]
Пока нет на это времени и желания. Доверить кому-то такое большое изменение тоже не могу
