### ISSUE TITLE
Language preference in a profile

### ISSUE THREAD

**Issue by altmind** [vas3k/vas3k.club#157]
Its a question of time when the club will outgrow the russian-speaking community.
Should we prepare for the club going international and introduce some internationalization?
We can probably start with something as simple as having a select box in the profile "what is your preffered interface language". The translation framework and translations can follow.

**Comment by vas3k** [comment]
Мне не известно ни одного примера коммьюнити, которое бы изменило язык. От локализации было решено намерено отказаться чтобы не усложнять процесс разработки. Если вдруг по каким-то причинам мы захотим английскую версию — мы запустим отдельный сайт с отдельной кодовой базой. Но пока у нас нет ни причин, ни ресурсов чтобы делать это. Фокусируемся на одном языке.
