### ISSUE TITLE
Пиши - разделы

### ISSUE THREAD

**Issue by ElSpirit** [vas3k/vas3k.club#16]
![image](https://user-images.githubusercontent.com/5953485/80382126-92fb9300-88aa-11ea-8f9d-67f06d8f241b.png)
решил начать писать, запнулся на выборе категории ))))
с учетом "жесткости модерации" не очень понятно разделение - что есть что?
или не важно и пишем что пишется в любой категории?
или категория на усмотрение автора?
или есть какие-то правила/особенности для каждой из категорий?

в моем видении: пост, вопрос и боль почти синонимы.

возможно нужен хелп или краткие описания.

**Comment by vas3k** [comment]
Так нажми на что-нибудь, там появится описание прямо сверху

**Comment by ElSpirit** [comment]
@vas3k да, внутри нашел. но практика короткой подписи на кнопке, как в профиле на Проектах мне кажется удобнее.

**Comment by vas3k** [comment]
Я не знаю как объяснить, например, суть батлов, чтобы она уместилась в кнопке. Плюс, мне кажется, новое коммьюнити всегда подразумевает небольшой период привыкания к местным названиям и форматам. Это неизбежно и нормально. Мы не стремимся к тому, чтобы каждый мог быстро напостить постов одной красивой кнопкой, как в свой инстаграм. Я наоборот хочу сделать процесс постинга более вдумчивым. Так что пока я не вижу здесь проблемы. Усложнение процесса работает на качество.
