### ISSUE TITLE
Рендеринг страницы ломается если в тексте использовать {{variable}}

### ISSUE THREAD

**Issue by rozhok** [vas3k/vas3k.club#160]
Хотел я значит написать пример использования handlebars шаблона и вставил в текст комментария
`{{username}}`

Теперь мой пост не отображается, а в консоли js ошибка:
```ReferenceError: "username is not defined"
    anonymous main-645266a7fbc5e4feb819.js line 7 > Function:3
```

Ccылка на пост: https://vas3k.club/question/1503/

**Comment by vas3k** [comment]
Хороший баг. Надо чинить. Пока отредактирую твой комментарий

**Comment by vas3k** [comment]
Пофикшено в https://github.com/vas3k/vas3k.club/commit/57819313eba5da77fe81bee01067772d4706c76e

Вернул твой коммент как было чтобы протестить. Вроде ок.

Жестокий баг. Любой мог так сломать рендеринг. Спасибо, что быстро зарепортил.

**Comment by rozhok** [comment]
Глагне оно не будет ломать? Если кто-то сообразит использовать `{{}}` в названии поста?

**Comment by vas3k** [comment]
Я полностью отключил `{{`-шаблоны, оставив их только для кастомных vue-компонентов. Это должно исключить проблему на корню.
