### ISSUE TITLE
В выдаваемых в поиске комментариях нет ссылки на оригинальный пост

### ISSUE THREAD

**Issue by Vostenzuk** [vas3k/vas3k.club#164]
В результатах поиска видишь комментарий (или вообще реплай), но неизвестно, к чему.
Нужно показывать пост и уметь переходить с комментария в результатах поиска к этому комментарию в посте

**Comment by devcooch** [comment]
Или опять сломали, но с мобилы я по поиску не вижу к какой теме комментарий
