### ISSUE TITLE
Кнопка «ответить» к комментарию в результатах поиска не работает

### ISSUE THREAD

**Issue by Vostenzuk** [vas3k/vas3k.club#165]
`TypeError: null is not an object (evaluating 'i.style')`
Можно пофиксить вместе с #164 — по кнопке «Ответить» линковать на комментарий внутри поста

**Comment by valentin-khomutenko** [comment]
@vas3k Это актуально? Вроде сейчас нет кнопки «ответить» в поиске вообще после редизайна https://github.com/vas3k/vas3k.club/pull/335
