### ISSUE TITLE
По клику на "+i новых" в строке с комментариями вести на новые комментарии

### ISSUE THREAD

**Issue by Vostenzuk** [vas3k/vas3k.club#166]
Чтобы не листать и не искать новые комментарии, стоит переключать хотя бы на первый комментарий из списка новых

**Comment by vas3k** [comment]
Думаю, отчасти это станет лучше когда сделаем #110. Не хочу переусложнять логику скроллинга страницы, всё равно её никто не поймет без README (а их никто не читает)
