### ISSUE TITLE
Safari post writing - jumping page

### ISSUE THREAD

**Issue by CovectbCobaka** [vas3k/vas3k.club#169]
Если в последнем Сафари на последней макоси с макбука писать или редактировать пост и пытаться править текст не в конце поста, курсор перемещается как надо, но view страницы скачет по экрану. Строка с курсором становится второй снизу, а не там где было когда юзер решил переместить курсор. 

То есть пишу я пост, а тут решаю отредактировать пред-предыдущий абзац. Навожу курсор куда надо, но тут страница прыгает и мне приходится искать место где я пишу. Прыгает обычно куда-то вниз, так что строка с курсором ставится второй или третьей снизу экрана. 

Баг плавающий, логику понять пока не удалось. Иногда есть, иногда нет. Чаще есть. 
Воспроизвести можно если открыть Сафари на маке и попытаться отредактировать/написать любой текст. В других браузерах не проверяла. Воспроизводится со старыми и новыми постами и раздражает если много писать.

**Comment by ephimoff** [comment]
Люто плюсую! Жутко бесит. Особенно когда длинные посты пишешь.
Заметил такое возникает когда язык переключаешь и когда маркдаун синстаксис ставишь.

**Comment by vas3k** [comment]
Стало ли лучше сейчас?

**Comment by CovectbCobaka** [comment]
Нет, не стало.

**Comment by bel0v** [comment]
Походу дело в css `position: absolute` у textarea, в которой набирается текст. Кто-нибудь помнит, зачем он там? Может, подскажу решение.

**Comment by skywinder** [comment]
Fixed in #382
