### ISSUE TITLE
Запретить в интерфейсе голосовать за свои посты и комменты

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#17]
На бекенде это уже нельзя, но на сайте при наведении счетчик всё еще подсвечивается как будто на него можно нажать и потом даже нажимается, но не обновляет цифру. Это выглядит странно. Надо сделать счетчик к своим постам и комментам некликабельным вообще. Придется в каждый темплейт вставить IF.

<img width="945" alt="Screenshot 2020-04-27 at 16 45 49" src="https://user-images.githubusercontent.com/176344/80385639-98ef7500-88a6-11ea-90ef-ed69f704d022.png">

**Comment by VBodrov** [comment]
Или сдернуть с онанистов одеяло и показывать, кто поставил плюсики. )

**Comment by Windrushfarer** [comment]
Может для больших кнопок со стрелкой тогда имеет смысл убрать стрелку и показывать контент по центру?
![](http://s.csssr.ru/U439TP407/20200429215332.png)

**Comment by FMajesty** [comment]
@Windrushfarer 
Отличный вариант, да. Как раз недавно экспериментировал с ним) 
Там надо во всех местах тестить, оно там из раза в раз бывает меняется.

**Comment by vas3k** [comment]
Хз, мне тоже текущий апвоут не нравится, но тут прямо с первого раза совсем не понятно, что это кнопка

**Comment by Windrushfarer** [comment]
Так если непонятно без стрелки, что это кнопка, значит и нажимать не будут. А цель как раз добиться этого, ну и выключить саму возможность

**Comment by vas3k** [comment]
Ах, черт, я потерял контекст! Я думал вы про вообще все кнопки, а тут только для себя. Тогда да, так офигенно. Тогда я бы убрал и «+» из своих комментов :)
