### ISSUE TITLE
Некорректные ссылки на подписку-отписку в еженедельном дайджесте на сайте

### ISSUE THREAD

**Issue by rozhok** [vas3k/vas3k.club#170]
В почте ссылки нормально заинтерполировались а вот на сайте имеем ссылку вида
`https://vas3k.club/notifications/switch/nope/%user_id%/%secret_code%/`

Багу смотреть тут: https://vas3k.club/weekly_digest/2020_19/

**Comment by vas3k** [comment]
Надо скрывать их на сайте

**Comment by nlopin** [comment]
@vas3k как сгенерировать дайджест для теста? 

Я могу получить отрендерный дайджест через `http://127.0.0.1:8000/notifications/renderer/digest/weekly/`, но как его превратить в пост?

**Comment by vas3k** [comment]
@nlopin попробуй в консоленьке набрать `pyenv run python3 manage.py send_weekly_digest`

А вообще вот https://github.com/vas3k/vas3k.club/blob/master/notifications/management/commands/send_weekly_digest.py#L41

**Comment by nlopin** [comment]
Как ты видишь решение? 

Я вижу два варианта, но из меня питонист так себе:
- парсить отрендеренный html и выкидывать `footer` перед сохранением поста. Не нравится, потому что слишком неочевидно
- добавить к запросу на рендеринг дайджеста параметр запроса `no_footer`, который будет рендерить страницу без футера со ссылками. Это более читаемо, но тогда при рассылке придется два раза кинуть запрос на рендер дайджеста — с футером и без него
