### ISSUE TITLE
Едет верстка в рассылке в клиенте mail.ru на Android 9

### ISSUE THREAD

**Issue by devcooch** [vas3k/vas3k.club#176]
Профиль автора поста находится на довольно большом отступе сверху от содержимого статьи, но с достаточном малым отступом от следующей статьи, поэтому создаётся ощущение, что это автор следующего поста.
![Screenshot_20200512-131009](https://user-images.githubusercontent.com/2089015/81808612-3f32b000-9520-11ea-9cc6-949c14878754.png)

**Comment by vas3k** [comment]
Верстка под email-клиенты — это ад. Назови каким пользуешься ты, я попробую найти его эмулятор и пофиксить.

**Comment by devcooch** [comment]
Это был банальный мейл.ру на Андроиде

**Comment by vas3k** [comment]
Скажи версию андроида или название девайса.
Я не знаком с каждым "банальным" андроидом наизусть :)

**Comment by vas3k** [comment]
Позволил себе переименовать баг чтобы было точнее

**Comment by devcooch** [comment]
Android 9, Sony Xperia Premium XZ

**Comment by ktaranov** [comment]
@devcooch извини, но Андроид 9 больше не поддерживается в проекте, обновись до 11 или перейди на IOS.

P.S. надеюсь иронию понял, большая благодарность, что нашел время зарепортить, но поправить пока некому( если найдется желающий - обязательно переоткроем. И да, Sony Xperia Premium XZ - говно, у сестры 6 месяцев проработал и сдох)
