### ISSUE TITLE
Мобильная версия Клуба | Нет меню "Главная, Вопросы Клубу, Расскажи где болит,  Батлы, Проекты"

### ISSUE THREAD

**Issue by 5388835** [vas3k/vas3k.club#178]
**Шаги воспроизведения:**

1. Открыть https://vas3k.club/ в браузере телефона;
2. Перейти в раздел "Проекты";
3. Открыть на телефоне версию сайта на ПК/Desktop site;
4. Перейти в раздел "Проекты".

---
**Ожидаемый результат:**
С телефона можно переходить по разделам "Главная, Вопросы Клубу, Расскажи где болит,  Батлы, Проекты".

---
**Фактический результат:**
В мобильной версии клуба меню нет, а разделы можно открыть переведя сайт в десктопную версию.

**Comment by vas3k** [comment]
Согласен. Нужно меню. Но я не люблю бургер-меню, надо придумать что-то покрасивее. Потому помечу как idea и буду ждать предложений по UI

**Comment by baradusov** [comment]
@vas3k, основное меню можно вынести в шапку и сделать прокручиваемым. На мобильных поможет инерция в добавок. Но я не уверен, что будет удобно, если в меню добавить ещё, например, пять пунктов. 

![notion-club](https://user-images.githubusercontent.com/29180060/82881814-41016800-9f51-11ea-9875-ce22594b723d.gif)

**Comment by vas3k** [comment]
@baradusov выглядит интересно. Если у тебя уже есть это готовое решение без новых JS либ — можем принять его как временное :)

Вообще для меню я хотел сделать круглую кнопочку в левом нижнем углу экрана, вызывающую меню с поиском, списком комнат и типов на весь экран.

За ноушн спасибо!

**Comment by KELiON** [comment]
@vas3k накидал по-быстрому [такой](https://github.com/vas3k/vas3k.club/pull/244) вариант, но мне пока не очень нравится, что получилось)
