### ISSUE TITLE
Обсуждаемое | Новые #intro и посты без комментариев отображаются в "Обсуждаемое"

### ISSUE THREAD

**Issue by 5388835** [vas3k/vas3k.club#179]
![#179](https://user-images.githubusercontent.com/20776447/81942105-5cd84600-9602-11ea-94fd-02137630665d.png)
**Шаги воспроизведения:**

1. Открыть "Обсуждаемое" https://vas3k.club/all/activity/ ;
2. Найти в ленте любое #intro с количеством комментариев +0.

---
**Ожидаемый результат:**
В "Обсуждаемое" отображаются посты с новыми комментариями.

---
**Фактический результат:**
Новые #intro и новые посты без комментариев отображаются и во вкладке "Обсуждаемое", и во вкладке "Новое".

**Comment by vas3k** [comment]
"Обсуждаемое", возможно, плохое слово. Но "главная" еще хуже. Принимаю идеи как поменять, но тикет закрою чтобы не мешал
