### ISSUE TITLE
Markdown-парсер должен поддерживать одинарный перевод строки как <br>

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#18]
Вот [этот класс парсера](https://github.com/vas3k/vas3k.club/blob/master/common/markdown/club_renderer.py#L14) сейчас заменяет два перевода строки на абзац, но полностью игнорирует одинарные переводы строк. Это неудобно. Надо чтобы было так:

- Одинарный перевод строки: < br >
- Двойной перевод строки: < p > (уже есть)

В качества парсера я использую [Mistune в версии 2.0](https://github.com/lepture/mistune) и похоже они сломали это в апдейте. В 1.0+ все работало как надо.

**Comment by VBodrov** [comment]
Так поддерживает жи.
Два пробела в конце строки.

**Comment by vas3k** [comment]
Fixed
