### ISSUE TITLE
Пост | Нет возможности быстро вернуться к началу длинного поста или поста с множеством комментариев

### ISSUE THREAD

**Issue by 5388835** [vas3k/vas3k.club#180]
**Шаги воспроизведения:**

1. Открыть длинный пост с комментариями (например, https://vas3k.club/post/beta/);
2. Прочитать самый нижний комментарий к посту;
3. Быстро вернуться на главную или в начало поста.

---
**Ожидаемый результат:**

Есть кнопка "Наверх", или [ ↑ ], или другая возможность вернуться к началу поста быстро и без затяжного скрола.

---
**Фактический результат:**

Чтобы вернуться к началу поста или к шапке сайта для возврата на главную, нужно несколько раз свайпать/скроллить наверх.

**Comment by vas3k** [comment]
Обсуждали вот здесь: https://github.com/vas3k/vas3k.club/pull/136
Никто так не убедил меня, что плавающий по странице мусор удобнее кнопки PgUp. Всё еще жду.
