### ISSUE TITLE
Поиск | Не работает поиск по двум символам

### ISSUE THREAD

**Issue by 5388835** [vas3k/vas3k.club#181]
![#181-1](https://user-images.githubusercontent.com/20776447/81945313-a32fa400-9606-11ea-9dea-e15a96ccc7eb.png)

**Шаги воспроизведения:**

1. Перейти на главную https://vas3k.club/;
2. Найти с помощью поиска все упоминания "VR".

---
**Ожидаемый результат:**

Поиск по двухсимвольным аббревиатурам отображает все упоминания их.

---
**Фактический результат:**

- Поиск по двум символам отображает ошибку "Please lengthen this text to 3 characters or more."
- Обойти можно, добавив любой символ перед "VR". Например: "!VR" / "#VR" / "@VR" /"*VR" etc.
![#181-2](https://user-images.githubusercontent.com/20776447/81945294-9c089600-9606-11ea-8ae6-5f9867a2b472.png)

**Comment by vas3k** [comment]
Пока так задумано. Не баг
