### ISSUE TITLE
Теги | Админские теги к записям не кликабельны

### ISSUE THREAD

**Issue by 5388835** [vas3k/vas3k.club#182]
**Шаги воспроизведения:**

1. Открыть запись с тегом "Все ебанулись": https://vas3k.club/post/939/ ;
2. Перейти по тегу к другим записям с таким же тегом.

---
**Ожидаемый результат:**
Админские теги кликабельны, как и теги комнат. По ним можно перейти в список постов с таким же тегом. 

---
**Фактический результат:**
Теги записей выглядят, как кнопки с тегами комнат, но нажать и перейти куда-то по ним нельзя.

![#182](https://user-images.githubusercontent.com/20776447/81948885-e4c24e00-960a-11ea-86bf-6777f6e2c125.png)

**Comment by devcooch** [comment]
Вроде работает, закрываем.
