### ISSUE TITLE
Комнаты | Сортировки "Обсуждаемое", "Новое", "Лучшее" в комнатах выводят результаты всех записей в клубе

### ISSUE THREAD

**Issue by 5388835** [vas3k/vas3k.club#184]
**Шаги воспроизведения:**

1. Перейти в любую комнату, например https://vas3k.club/room/dumbasshome/ ;
2. Отсортировать записи в комнате по "Лучшим".

---
**Ожидаемый результат:**
Записи в комнате отображаются в порядке выбранной сортировки.

---
**Фактический результат:**
Сортировка ведет на страницу всех записей клуба, отсортированных в выбранном порядке.

![#184](https://user-images.githubusercontent.com/20776447/81961006-72f20080-961a-11ea-87d1-46874e30814a.gif)

**Comment by vas3k** [comment]
Дубликат #171
Но спасибо за клевую анимацию :)
