### ISSUE TITLE
Типы записей | В меню на главной нет типа записей "Пост" и "Ссылка"

### ISSUE THREAD

**Issue by 5388835** [vas3k/vas3k.club#185]
**Шаги воспроизведения:**

1. Зайти в раздел создания записей https://vas3k.club/create/ ;
2. Вернуться на главную, найти, где можно посмотреть все записи типа "Пост" и "Ссылка".

---
**Ожидаемый результат:**
В левом меню на главной можно посмотреть все записи каждого типа записей:  "Пост", "Вопрос", "Боль", "Ссылка", "Батл", "Проект".

---
**Фактический результат:**

- В левом меню можно посмотреть все типы записей кроме постов и ссылок. 
- Посмотреть все записи можно если вручную ввести в браузере https://vas3k.club/post/
а ссылки – https://vas3k.club/link/

![#185](https://user-images.githubusercontent.com/20776447/81962977-29ef7b80-961d-11ea-8b0f-c898bf31f8e5.png)

![#185-2](https://user-images.githubusercontent.com/20776447/81962822-fca2cd80-961c-11ea-82b7-c94347d845b3.png)

**Comment by vas3k** [comment]
Так задумано. Никто и не обещал, что они должны быть эквивалентны
