### ISSUE TITLE
Создание записи | Разрешение и положение чек-бокса видимости в "Большом Интернете" не соответствуют стилю сайта

### ISSUE THREAD

**Issue by 5388835** [vas3k/vas3k.club#187]
**Шаги воспроизведения:**

1. Перейти в создание записи;
2. Активировать чекбокс "Линк виден в Большой Интернет?".

---
**Ожидаемый результат:**
Чекбокс ровный, с хорошим разрешением и не разрывает сердца перфекционистам.

---
**Фактический результат:**

- Разрешение активированного чекбокса ниже разрешения других элементов на сайте.
- Активированный чекбокс выходит за рамки элемента.
![#187](https://user-images.githubusercontent.com/20776447/81967148-2eb72e00-9623-11ea-8167-d6b816a23972.png)

**Comment by devcooch** [comment]
Неактуально
