### ISSUE TITLE
Добавить дублирование уведомлений Бота где-то в профиле клуба.

### ISSUE THREAD

**Issue by lopar** [vas3k/vas3k.club#190]
Бот кидающий обновления в телегу это круто и практично, но если на устройстве больше одного браузера и default_browser!=personal_browser, то удобная фича превращается в кошмар: открыть ссылку в телеграме > попасть в браузер > подождать редиректа и обновления ссылки(1) > скопировать > вставить в соседний браузер. То есть ну прямо слишком много телодвижений. Если бот крякнул уведомление, это хорошо, но хочется чтобы в самом клубе можно было сходить на это обновление вручную параллельно ссылке бота.

(1) Обновление ссылки это, на примере, переход от ссылки типа 
`https://vas3k.club/post/1022/comment/02f16415-a7e6-4024-82ab-eabac71c66e5/#comment-02f16415-a7e6-4024-82ab-eabac71c66e5`
до ссылки типа
`https://vas3k.club/post/1022/#comment-02f16415-a7e6-4024-82ab-eabac71c66e5`
Хотя открывают, казалось бы, одно и то же.

**Comment by vas3k** [comment]
Дубликат #172 
Там же в обсуждении я рассказал почему эта фича пока не планируется https://github.com/vas3k/vas3k.club/issues/172#issuecomment-629195212
