### ISSUE TITLE
Научить всратый AI пересылать стикеры в телеге

### ISSUE THREAD

**Issue by StVl** [vas3k/vas3k.club#193]
сейчас он только в тексты умеет.

Раньше я в ботов никогда не писал, так что если кто-то рукастый, вроде @vas3k  сможет вкратце здесь накидать, что нужно сделать - я справлюсь.

**Comment by vas3k** [comment]
Надо разобраться в каком формате телега шлет стикеры и правильно вставлять их в коммент. Должно быть несложно, кто-нибудь может заняться

**Comment by StVl** [comment]
попробую

**Comment by vas3k** [comment]
Думаю, если телеграм отдает их прям URL'ами, можно вставлять картинки прямо напрямую с серверов телеграма. Если же байтами — придется поплясать. Со стикерами тоже, им скорее всего нужен будет свой CSS-класс, тут надо придумать как об этом сообщать в маркдауне

**Comment by altmind** [comment]
ref https://github.com/vas3k/vas3k.club/issues/177

**Comment by altmind** [comment]
@vas3k а как сейчас тестируются/интегрируюся входящие телеграм сообщения? с прод токеном?

**Comment by skywinder** [comment]
@altmind я поднял телеграм бота локально - собщения он шлет. За деталями в dev чатик: https://t.me/vas3k_club

ps.
я бы объеденил эту таску с  https://github.com/vas3k/vas3k.club/issues/4 и оставил одну из них.

**Comment by skywinder** [comment]
Закрою, т.е. активности в таске нет и желающих сделать (пока) тоже. 
Если кто захочет взять эту таску - пишите, переоткроем.
