### ISSUE TITLE
Переместить поле для нового комментария наверх

### ISSUE THREAD

**Issue by poctek** [vas3k/vas3k.club#194]
Сейчас листал [тред](https://vas3k.club/post/1494/), где больше 100 комментариев, большинство из которых с фотографиями. Чтобы добавить свой пришлось порядком поскроллить. Думаю, подобные треды не будут редкостью, форма нового комментария сверху могла бы помочь.

**Comment by vas3k** [comment]
Пока не кажется это проблемой, понаблюдаю еще
