### ISSUE TITLE
Дата поста вылазит за границы поста в мобильной версии если указана длинная должность

### ISSUE THREAD

**Issue by andriisych** [vas3k/vas3k.club#195]
![Screenshot_20200517-111252](https://user-images.githubusercontent.com/47759596/82139375-04868b80-9830-11ea-874e-05639b25ec93.png)

**Comment by OdSt** [comment]
Да и не только дата. В принципе верстка едет при длинных описаниях.

**Comment by vas3k** [comment]
Вроде должно стать лучше, проверьте
