### ISSUE TITLE
Текст внутри тэга pre вылезает за пределы блока

### ISSUE THREAD

**Issue by ganqqwerty** [vas3k/vas3k.club#196]
Вот пример [самоописания одного товарища](https://vas3k.club/intro/relyativist/)

![image](https://user-images.githubusercontent.com/697308/82147243-bcc32c80-984e-11ea-9ae9-3888a05b92a4.png)

По-моему, надо либо внутри pre добавить горизонтальную прокрутку, либо word-wrap.

**Comment by altmind** [comment]
а кто вставляет pre, сам редактор? в pre нельзя делать word-wrap.

**Comment by ganqqwerty** [comment]
я так понимаю, да, участник вставил.  я тоже думаю, что word-wrap - противоречащая идее pre штука, а вот горизонтальную прокрутку можно и вставить

**Comment by vas3k** [comment]
Я за горизонтальную прокрутку, да. Жду PR с пофикшеным CSS :)

**Comment by araslanov-e** [comment]
![image](https://user-images.githubusercontent.com/1290711/82329694-23854900-99fb-11ea-81e0-e2e74d4d508f.png)
Почему это хуже прокрутки?

**Comment by vas3k** [comment]
Потому что тег pre используется для кода, а не для текста. Переносы строк в коде ухудшают его читаемость. В твоём примере от pre надо вообще избавиться и писать обычный текст :)

**Comment by araslanov-e** [comment]
![image](https://user-images.githubusercontent.com/1290711/82330501-5f6cde00-99fc-11ea-91d7-8dd2a100efed.png)
Понял, получается что то типо этого.

**Comment by vas3k** [comment]
Ага, пусть будет так. Хотя бы не пидорасит страницу
