### ISSUE TITLE
Нет кнопки "+Пиши" в портретном режими мобильной версии 

### ISSUE THREAD

**Issue by ephimoff** [vas3k/vas3k.club#197]
Когда переворачиваю в лэндскейп кнопка появляется

**Comment by vas3k** [comment]
Кто-то мог бы предложить здесь альтернативный вариант шапки, да

**Comment by vas3k** [comment]
Но вообще я не вижу проблемы. Я бы убрал кнопку "Пиши" с мобил вообще. Никто не сможет ничего дельного написать с телефона
