### ISSUE TITLE
Хочу список всех своих комментов

### ISSUE THREAD

**Issue by ephimoff** [vas3k/vas3k.club#198]
Вижу только несколько недавних. Пытался тут найти один из комментов, но не смог.

**Comment by ElSpirit** [comment]
Предлагаю расширить идею:
сделать кнопку "Следить" - чтобы приходили все комменты по интересующей статье.
сделать ее автоматической для тех постов, которые хоть раз комментил.

**Comment by vas3k** [comment]
@ElSpirit кнопка следить уже есть. Оповещения приходят в телеграм-бота и в дейли-дайджесте по почте. В профиле, я так понимаю, люди хотят видеть именно комментарии определенного юзера.

**Comment by ElSpirit** [comment]
@vas3k и впрямь, кнопка появилась, спасибо.
исходя из темы я так понял что в личном кабинете человеку хочется видеть все свои комментарии, а не "Последние комментарии".

**Comment by kadron141** [comment]
Пока их можно найти через поиск ника по клубу ( `https://vas3k.club/search/?q=kadron141` ), но это немного костыль

**Comment by vas3k** [comment]
Сейчас выводится последние три коммента в профиле. Я бы сделал табы на простеньком JS типа «Посты» | «Комменты» | «Лайки», спрятал списки туда и переключал по клику. Табы решат проблему с пажинацией.

**Comment by nlopin** [comment]
Какой у этого юзкаейс? Нам точно нужны табы? 

Можно сделать для каждой секции на странице кнопку «догрузить следующие N»:
![image](https://user-images.githubusercontent.com/1469636/87862012-e03c4d80-c94b-11ea-8714-85459a60d47a.png)

**Comment by vas3k** [comment]
Наконец-то сделали, можно закрывать :)
