### ISSUE TITLE
Профиль не прошедший ревью может смотреть всё по ссылочкам

### ISSUE THREAD

**Issue by FMajesty** [vas3k/vas3k.club#2]
Собственно, сабж (или так и запланировано?)
Пример: https://vas3k.club/link/4/

UPD: апвоуты не тыкаются, комментарии не успел затестить

**Comment by vas3k** [comment]
Вот это хорошая находка. Если пост отмечен как «доступный извне» — он должен быть виден всем, даже не прошедшим ревью. Но конкретно этот пост был изначально отмечен как «только для своих» и это явный баг. Я добавлю проверку на активное членство в клубе чтобы такого не повторилось
