### ISSUE TITLE
Выделять непрочитанные комментарии внутри поста

### ISSUE THREAD

**Issue by VBodrov** [vas3k/vas3k.club#20]
В карточке поста написано сколько новых сообщений появилось, но что это за сообщения уже внутри не очевидно.

**Comment by vas3k** [comment]
Согласен, я бы назначал им специальный css-класс и выделял их фоном другого цвета

**Comment by pavel-voronin** [comment]
В рамках этой задачи я бы добавил навигационную панельку, как у Хабра, с навигацией по непрочитанным комментариям и отметкой о прочтении.

**Comment by pavel-voronin** [comment]
Из списка постов по клику на количество непрочитанных комментариев, конечно, нужно идти на первый таковой внутри поста.

**Comment by FMajesty** [comment]
@vas3k 
Это срочно, срочно надо сделать!! Я листаю пост с кошачестями и всё время в них теряюсь, чтобы найти, под какой же еще кошатостью добавили комментарий или какую новую запостили!
Ты говорил, что это для этого уже есть даже данные о непрочитанных комментариях. Куда воевати!

@Windrushfarer, у тебя не будет случайно предложений по цвету непрочитанного комментария?

**Comment by Windrushfarer** [comment]
А имеет смысл прям фон делать? Можно какой-нибудь рамочкой обводить, какие новые. А то ведь есть еще аргументы в батлах, у которых есть свои фоны. Мб что еще появится.

**Comment by FMajesty** [comment]
@Windrushfarer 
Предложение неплохое! Но вот какой надо подумать, хм

**Comment by Windrushfarer** [comment]
@FMajesty чисто первое, что пришло в голову
![](http://s.csssr.ru/U439TP407/20200430214159.png)

**Comment by lespaul1488** [comment]
Рамка громоздко, достаточно бордера с одной стороны, например так 
<img width="804" alt="Снимок экрана 2020-05-03 в 00 36 01" src="https://user-images.githubusercontent.com/6555305/80892881-34814b00-8cd6-11ea-8c15-36fc20aa141f.png">

**Comment by vas3k** [comment]
Рамка говно (хотя респект за отсылку к старой лепре). Бордер ок, но я бы поработал над цветом и общим внешним видом, чтобы оно не превращалось в кучу черточек, если в посте много новых комментов :)

**Comment by lespaul1488** [comment]
Ну прямые черточки конечно отстой, но можно их модно закруглить, но я не настоящий дизайнер, конечно, надо подумать

<img width="620" alt="Снимок экрана 2020-05-03 в 00 48 19" src="https://user-images.githubusercontent.com/6555305/80893156-86c36b80-8cd8-11ea-9c11-a5d89866f78a.png">

<img width="720" alt="Снимок экрана 2020-05-03 в 00 52 24" src="https://user-images.githubusercontent.com/6555305/80893159-8c20b600-8cd8-11ea-8567-7ecfeee962b0.png">

**Comment by vas3k** [comment]
Не, закругленные еще хуже. Работаем дальше (с)
Посмотрю на днях референсы как другие делают в интернете, можно чего придумаю. Вы тоже кидайте

**Comment by lespauI** [comment]
Сколько я не ходил по инету ничего кроме мерзкого фона не встречал, но мне фон прям вообще не нравится, я за минимализм. 

Классический вариант с фоном фи
<img width="804" alt="Снимок экрана 2020-05-03 в 01 31 50" src="https://user-images.githubusercontent.com/6555305/80893764-f0924400-8cdd-11ea-9ab2-3b40003f152d.png">


Самый минимализм поставить какую-то маленькую отметку напротив нового комментария, точку например
<img width="842" alt="Снимок экрана 2020-05-03 в 01 29 22" src="https://user-images.githubusercontent.com/6555305/80893779-0f90d600-8cde-11ea-906a-ecec0f10b29b.png">

**Comment by Windrushfarer** [comment]
У точки есть две проблемы, ее либо не видно, либо непонятно к чему она относится

**Comment by Konfuze** [comment]
Очень не хватает этой фичи, "стоит" не дорого, а жизнь сильно облегчит.

Вариантов, кажется, не много:
* Выделение цветом фона — всего коммента или части (см. хабр)
* Бордер (целиком или с одной стороны)
* Индикатор (кружок, лейбл "new", etc)

Я адепт подхода tjournal / vc:
* Выделение фоном
* Удаление выделения по маусоверу

![image](https://user-images.githubusercontent.com/131331/82839066-d4e21e00-9ed6-11ea-8ad2-a3d962e46d26.png)

Правда, остаётся проблема с батлами — там каждый коммент верхнего уровня уже имеет свой фон. Как вариант, выделять фоном новые комменты, по ховеру возвращать цвет, предусмотренный батлом — визуально это не большая проблема, т. к. у каждого коммента уже есть "за ..." и выравнивание по стороне.

**Comment by vas3k** [comment]
@Konfuze мне нравится. Дай коды цветов для светлой и темной темы или пришли PR. Никто больше не хочет делать этот Тикет похоже :)

**Comment by Konfuze** [comment]
Я могу запилить фронт, если у комментов будут нужные классы.

Ну или так:
```
.reply {
   border-radius: var(--block-border-radius);
}

/* Для светлой темы */
.comment--unread {
   background: #F4F5F7;
}

/* Для темной темы */
.comment--unread {
   background: #33373F;
}
```

**Comment by vas3k** [comment]
@Konfuze в два цвета любой дурак может. Давай ка по-нормальному в один с прозрачностью :) RGBA код пойдёт. Дальше я сам запилю

**Comment by Konfuze** [comment]
@vas3k, дык, всё равно ж темы на переменных. Ну, тогда `rgba(128, 128, 128, 0.07)` или `rgba(129, 196, 255, 0.1)`, если цвета хочется.

Контрастность, правда, хромает.

**Comment by vas3k** [comment]
Первая версия готова https://github.com/vas3k/vas3k.club/commit/e5528ed3a8f0bb7695d21379a602afbdc3ca8a55
