### ISSUE TITLE
Редактирование старых постов + Общий интерфейс мелких незначительных жалоб

### ISSUE THREAD

**Issue by omnster** [vas3k/vas3k.club#200]
Я хотел исправить опечатку в своем посте недельной давности и наткнулся на "Этот комментарий больше нельзя редактировать".

Я думаю, было бы уместно разрешить некоторое редактирование, возможно, с аппрувом модераторами или кто там это делает, потому что ну не хочется свои опечатки видеть отлитыми в бронзе.

Вообще, я подумал, что жалобы вроде этой неясно, куда слать.  Это вроде бы не очевидная техническая проблема, от которой кто-то может пострадать, а дискуссионный момент, и чо с ним делать?  Короче, я несколько минут думал, чо делать, и кажется, инструкция для таких моментов была бы полезна.

**Comment by vas3k** [comment]
Привет.

Редактировать комментарии можно. Там ограничение на первые 3 часа по-моему. После этого нельзя, комментарий отливается в бронзе чтобы никто не смог заабьюзить дискуссию. Так сделано во многих сервисах, например, в телеграме, и мне пока такой подход нравится больше всего.

Жалобы, баги, предложения надо слать сюда. Ты правильно сделал. Об этом написано в первом посте, в разделе о клубе и в README. Открывай новые issue если будут еще идеи, мейнтейнеры их читают и могут обсуждать
