### ISSUE TITLE
Разные виды сортировки в баттлах. 

### ISSUE THREAD

**Issue by metya** [vas3k/vas3k.club#201]
Сейчас в баттлах только один тип сортировки, по плюсикам к аргументам. Это создает положительную обратную связь. Самые верхние аргументы всегда будут больше рейтинговаться, из за того, что лень листать вниз. А хорошие аргументы внизу так и останутся забытыми. 

Предлагаю ввести сортировку по плюсикам, по количеству комментариев к аргрументу и по новизне.

**Comment by skywinder** [comment]
Закрою, т.е. активности в таске нет и желающих сделать (пока) тоже. 

@vas3k  вообще фича выглядит простой - если ты за - можно поставить тег что бы new-comers  ее взяли

**Comment by skywinder** [comment]
За пол года никто не решился это сделать.
Закрываю как неактуальную т.к. активности  по таске нет.

**Comment by metya** [comment]
пичалька(
