### ISSUE TITLE
Кнопка для скрола вверх в постах

### ISSUE THREAD

**Issue by zsemenyuk** [vas3k/vas3k.club#204]
Обычный скрол вверх, чтобы быстро попадать к шапке-навигации в длинных постах

**Comment by vas3k** [comment]
Уже обсуждали, я забрил идею https://github.com/vas3k/vas3k.club/pull/136
Мне не нравится плавающий мусор на странице. Если кто-то покажет пример, где это сделано ненавязчиво, я подумаю
