### ISSUE TITLE
Черновик не открывается

### ISSUE THREAD

**Issue by kartashovata** [vas3k/vas3k.club#205]
При попытке открыть черновик показывает Server Error (500). 
При попытке сделать такой же пост опятъ, жалуется на дубликат.

**Comment by vas3k** [comment]
Пофиксил, спасибо

**Comment by vas3k** [comment]
P.S.: Встраивать видео с ютюба можно просто положив голую ссылку в тексте поста или коммента. Парсер сам все распарсит :)

**Comment by kartashovata** [comment]
>>PS
Спасибо ^_^
