### ISSUE TITLE
Возможность видеть дату последнего поста в треде находясь на главной

### ISSUE THREAD

**Issue by nerorenaissance** [vas3k/vas3k.club#206]
Вот ночью сидишь — и как бы с главной непонятно, когда там было последнее сообщение.

![image](https://user-images.githubusercontent.com/44898262/82506972-bdd3b280-9b09-11ea-90b9-946907760f21.png)

**Comment by vas3k** [comment]
Предлагай UI, обсудим

**Comment by hexyo** [comment]
Я бы сделал что-нибудь такое, фичи правда очень не хватает для комфортного скроллинга
<img width="1072" alt="Screenshot 2020-06-01 at 13 40 45" src="https://user-images.githubusercontent.com/20154888/83401497-8f10e280-a40d-11ea-9160-a0582cee0cd2.png">

**Comment by vas3k** [comment]
Ну это прямо совсем надсмешка над UI получилась :D 

![6a0120a85dcdae970b0128776fec64970c-pi](https://user-images.githubusercontent.com/176344/83512492-94833100-a4d0-11ea-932f-86cc5de08342.png)

**Comment by skywinder** [comment]
А в чем смысл абсолютной даты на основной странице? 
фраза напротив комментариев «+2 новых» решает вопрос актуальности топика.

**Comment by skywinder** [comment]
Активности в таске нет. Желающих сделать (пока) тоже. 
Если будут еще идеи как это реализовать - пишите, переоткроем. 👍
