### ISSUE TITLE
Неконсистентно отображаются ники юзеров

### ISSUE THREAD

**Issue by bel0v** [vas3k/vas3k.club#210]
Комментарии верхнего уровня подписываются **именем** человека + его профессией.
Вложенный комментарий, а также сам пост подписывается **ником**. Приходится в голове мапить, что Вася Пупкин и  @nagibator2006 это один и тот же человек (ну или запоминать аватарку)

**Comment by vas3k** [comment]
Твои предложения?

**Comment by bel0v** [comment]
Пока не знаю. Думаю, надо собрать все кейсы, когда подписывается автор, и подумоть над системой. В целом лично мне нравится видеть имя человека, добавляет камерности, что ли. С другой стороны, ник это уже часть интернет-культуры и самоидентификации, вроде как.

ещё кейсы увидел: 
посты типа "Вопрос":  имя + профессия 
Головной пост батла: имя + профессия

**Comment by OdSt** [comment]
Да, тоже столкнулся с этой проблемой. И это раздражает, просто ощущение, что какая-то наёбка.
Как решение - добавить в подпись поста ник. Аккурат между кратким описанием и датой.

**Comment by bel0v** [comment]
(накидываю) м.б. по ховеру на ник показывать имя + профу? В случае сокращённой подписи

**Comment by bel0v** [comment]
#229 вот тоже похожий кейс - есть ник, но не понятно, кто за ним стоит

**Comment by skywinder** [comment]
Ну что, давайте решим, что делать, что бы таска не висела. 
Варианта 2 вижу: 

1. подписать в верхнем уровне ник перед датой, аналогично вторуровневым коментам
вот скрин

![image](https://user-images.githubusercontent.com/3356474/85717338-9d55d400-b717-11ea-8da0-b8436f6b4dda.png)


2) **забить.** 
т.к. в целом меншены - для того что бы того кого заменшенели увидел. а многопоточные дискуссии - это редкость, так что там обычно  понятно кто кому отвечать.

**Comment by OdSt** [comment]
Все же первый вариант предпочтительнее. Оно и места немного занимает, и выглядит аккуратно.

**Comment by kirillku** [comment]
Еще один пример:

В журнале в разделе с новенькими пишутся только полные имена.

![image](https://user-images.githubusercontent.com/3331461/102715101-a8ab4600-42db-11eb-8afa-fba80e842f95.png)

Дальше во всех остальных секциях используются только ники.

![image](https://user-images.githubusercontent.com/3331461/102715132-e4461000-42db-11eb-9dfd-9e896677fcad.png)


Я бы везде писал ники и показывал полное имя по ховеру (или наоборот). Либо в полной версии когда много места показывать полное имя и ник, а в короткой только ник.

**Comment by nitso** [comment]
У проблемы отображения ников в комментах есть несколько уровней неконсистентности:
![image](https://user-images.githubusercontent.com/443011/105096720-8eba7a00-5ab8-11eb-98ff-3d02c7d03546.png)

1. Юзеринфо корневого коммента отображается без ника
2. Меншн объединяется с аватарой, делая его похожим на ник комментатора второго уровня
3. Ник отображается без `@`, связь с комментарием воспринимается сложно, тире дает ощущения цитирования
4. Стрелка скорее похожа на эмоджи, чем на экшн-поинт. 

## Вариант решения в лоб

Привести к единому виду рутовый коммент и ответы на него. У ротового коммента обображается полная шапка как и раньше, у чилдов минимальная (расширенную инфу в обоих случаях можно выводить попом/ховером). У рутового комментария стоит выводит сначала имя, потом ник, как в профиле (скриншот сделал до того, как об этом подумал, а делать еще варианты уже лениво). 

![image](https://user-images.githubusercontent.com/443011/105099608-ff639580-5abc-11eb-84de-198a60f056b0.png)

Бросаются в глаза бесчисленные кнопки "ответить". Их можно отрисовывать при ховере. И у рутового комментария тоже - это сократит пробел между рутовым комментом и ответами, визуально объединит дискуссию.

**Comment by Yurymd** [comment]
>     2\. Меншн объединяется с аватарой, делая его похожим на ник комментатора второго уровня

Сто раз да! Это постоянная боль. Ники мельтешат, соответствие близости ава-ник нарушено, лишний ник в ответе. Мне кажется нужно отталкиваться от того что имя важнее аватара, т.к. его допустимо менять.

Не думаю, что нужно изобретать что-то новое, посмотрим как реализовано на крупных сайтах. +моё субъективное мнение о деталях:

**Reddit**
- вложенность задаётся только отступами, как-то выживают без упоминания имени, нравится;
- рейтинг комментария и все функциональные кнопки идут в ряд, рейтинг комментария считывается хуже, чем сейчас в клубе
![image](https://user-images.githubusercontent.com/61903187/105898970-207f3580-602b-11eb-9785-f824f3642299.png)


**vc.ru**
- рейтинг комментариев вынесен вправо и легко считывается, поддерживаю;
- при вложенных комментариях иерархия создаётся и отступами и ссылкой на исходных комментарий с ником пользователя. мне кажется отступов достаточно;
- квадратный аватар с именем и временем мне кажется легче для восприятия чем круглый, текст равноудалён от его грани, а у круглого имя и время стараются оторваться от фигуры. я сделаю крупнее чтобы было заметнее, что скажете?
![image](https://user-images.githubusercontent.com/61903187/105890984-1c4e1a80-6021-11eb-81a0-33c01dd52a47.png)
- кроме кнопок "ответить" и сохранения остальное спрятано в меню;
![image](https://user-images.githubusercontent.com/61903187/105890373-54089280-6020-11eb-92d6-411446a8b88b.png)

**habr qna**
- дублируют имя и ник, зачем?
- ветки вложенных комментариев по умолчания свёрнуты, раскрываются без перезагрузки страницы. поддерживаю, пролистывать 200 комментов второго уровня так себе удовольствие;
- поделиться можно только комментарием первого уровня (одобряю). но только в соцсетях, просто ссылку получить нельзя - это фиаско, по-моему;
- выделен автор поста, думаю это очень важно и правильно;
- можно обратиться по нику, он, в отличие от клуба, что важно, находится строго под ником автора ответа, претензий не вызывает, выделение цветом помогает;
- яркие цвета для "нравится" и "ответить" - не одобряю, рябит в глазах от них.
- время ответа перенесено в самый низ блока, мне кажется это выглядит не очень удобно.
![image](https://user-images.githubusercontent.com/61903187/105892658-37218e80-6023-11eb-9102-ee71be5e671d.png)

В первом приближении на примере скриншота выше в переписке я предлагаю:
1. Попробовать сделать единым оформление комментария первого уровня и остальных (единые размеры шрифтов, правила написания имени, стиль кнопки ответа).
2. Попробовать оставить подпись к нику только в первом уровне комментов (в целом эта подпись у меня вызывает вопросы: неужели беседа ценна только при условии указания должности собеседника?)
3. Попробовать квадратный вариант аватара.
4. Попробовать убрать символ стрелки для ответа. 
5. Попробовать скрыть под спойлер ветки второго уровня больше 5 комментов.
6. Попробовать либо вообще убрать технический ник, начинающийся с собаки, или, как на тостере, сделать его менее заметным.
7. Попробовать визуально отделить уровень вложенности.

Грубый набросок до-после, что скажете?
![v1](https://user-images.githubusercontent.com/61903187/105900144-b10a4580-602c-11eb-9fa6-c7eaa24ee22f.png)

**Comment by devcooch** [comment]
@Yurymd я бы дату/время в той же строке оставил, что и имя, не стоит эта информация отдельной строчки вертикальной.
Аватар мне лично пожалуй круглый больше нравится. Линеечки я бы не рисовал пока или как-то менее заметно. Если посмотреть на reddit и vc - никто не делает горизонтальных, только вертикальное. Но имхо не первая необходимость. Очень нравится идея подсветить автора, я бы это прям асап сделал независимо от решений/обсуждений в этом тикете. Сорри, что на негативном сфокусировался, в остальном твой вариант воспринимается как улучшение текущего, но послушаем и других.

**Comment by Yurymd** [comment]
Я не понимаю как ответить с упоминанием ника) Я время не менял, взял существующее оформление из профиля клуба, может и в одну строчку, это не принципиально, как и виуальная иерархия. Принципиальное отличие - меньше мусора, обращение друг к другу по именам, и самое важное на мой взгляд больше нет ситуации когда рядом аватар одного человека и ник другого на одной строчке, это меня не перестаёт сбивать с толку:
![image](https://user-images.githubusercontent.com/61903187/105902132-4ad2f200-602f-11eb-84f8-2ce6f981bb96.png)

**Comment by devcooch** [comment]
Неактуально
