### ISSUE TITLE
Автоматический дамп текущей базы для dev-окружения

### ISSUE THREAD

**Issue by Konfuze** [vas3k/vas3k.club#213]
Для полноценного тестирования изменений необходимо иметь на dev-окружении дамп текущей базы, т. к. не все тестовые данные удобно и возможно создавать руками.

**Comment by vas3k** [comment]
Как ты предлагаешь создать такой дамп?

**Comment by Konfuze** [comment]
Понимаю что одна из проблем - закрытость клуба, просто так отдавать базу всем не получится.
Для начала можно, хотя бы, отдавать её вручную по запросу контрибьюторов, удалив все черновики и рандомизировав всю сенситив инфу (почты, хэши паролей, etc).

А можно, конечно, обойтись сидером.

**Comment by vas3k** [comment]
Да даже если бы клуб был полностью открытым, дамп базы никто бы просто так не отдал. Там же пароли, имейлы, токеты доступа в телеграм, сессии, другая чувствительная информация. Всё очищать — это несколько дней работы. Плюс потом надо постоянно поддерживать консистентность дампа. Когда добавили новое поле в базу — надо добавить его в каждую запись. Кто этим будет заниматься? Я точно нет, мне хватает локально созданных тестовых постов и юзеров

Так что я не вижу пока перспектив у этой идеи. Кто увидит — переоткрывайте тикет
