### ISSUE TITLE
Хотет в ежедневном дайджесте ежедневный дайджест

### ISSUE THREAD

**Issue by OdSt** [vas3k/vas3k.club#217]
![image](https://user-images.githubusercontent.com/2988881/82741454-417fe000-9d52-11ea-825e-08533f859ddc.png)

Кликаем вот сюды в профиле, а там вместо того, что в названии просто переключалка и чаты.

В общем, хотет архив ежедневных дайджестов не только на почте, но и тут. 
Может быть даже с аналитикой!

**Comment by vas3k** [comment]
Архив делать пока не планируется. Но за идею спасибо, подумаю.
