### ISSUE TITLE
Отображение моих комментариев в личном кабинете

### ISSUE THREAD

**Issue by AshotPilosian** [vas3k/vas3k.club#22]
Хочу иметь возможность видеть всё, что я написал под своими и чужими постами, сейчас невозможно понять, что и где я писал, это не очень удобно.

**Comment by syabro** [comment]
@vas3k а чего закрыли? Я бы хотел видеть все комментарии а не последние три

**Comment by vas3k** [comment]
@syabro так присылай PR. Таких тикетов уже по-моему штук пять открытых валяется

**Comment by syabro** [comment]
@vas3k у меня уже хватает опыта чтобы прежде чем присылать пиар надо спросить надо ли ваще такое )
