### ISSUE TITLE
Добавить к новым интро в ленте компанию и должность автора

### ISSUE THREAD

**Issue by johnspade** [vas3k/vas3k.club#229]
Приходит много новых людей, читать все интро подряд сложно, хотя встречаются очень интересные жизнеописания. Компания и должность рядом с никнеймом нового члена Клуба в ленте могут служить хорошим заголовком для интро и помогут решить, прочитать его или нет.

![Screenshot from 2020-05-25 14-49-44](https://user-images.githubusercontent.com/12059380/82810376-fde2be80-9e96-11ea-8d37-31a22c6ebeb0.png)

**Comment by vas3k** [comment]
Хм, а неплохо. Только я бы делал не под ником, а рядом. Иначе кучи интро заполонят все страницы :)

Можешь попробовать прислать PR с невратым дизайном. Не обещаю, что сразу пойдет в прод, но посмотреть на это стоит.
