### ISSUE TITLE
Возможность подписаться на обновления в чужих постах

### ISSUE THREAD

**Issue by AshotPilosian** [vas3k/vas3k.club#23]
Хочу нажать куда-то, чтобы бот меня пинговал о каждом новом комментарии к посту, даже если это не мой пост и не ответ на мой комментарий. Удобно следить за батлами, например и раздавать всем лукасы онлайн.

**Comment by vas3k** [comment]
Норм. Я бы за одно добавил сюда и возможность отписываться от своих, раз уж для этого все равно придется делать модельку в БД

**Comment by v2nek** [comment]
Еще было бы клево иметь страницу, куда бы собирались посты на которые я подписался или в которых оставлял комментарий
