### ISSUE TITLE
Минорный баг: Гороскоп в ежедневном дайджесте. Всегда "как и вчера"

### ISSUE THREAD

**Issue by tyhonchik** [vas3k/vas3k.club#231]
![image](https://user-images.githubusercontent.com/30229764/82890698-406ad080-9f55-11ea-82d0-e7c10f331c53.png)
![image](https://user-images.githubusercontent.com/30229764/82890787-62fce980-9f55-11ea-9fcc-3894e0f921cf.png)

**Comment by vas3k** [comment]
Дубликат #211
Нет сейчас планов это фиксить
