### ISSUE TITLE
Всратый AI | Научить его плюсовать комментарии

### ISSUE THREAD

**Issue by ElSpirit** [vas3k/vas3k.club#232]
В телеге можно ответом на комментарии запостить ответ.
Предлагаю чтобы ответом на комментарий и специальной командой (например ++) ставить комментарию "+1"

**Comment by vas3k** [comment]
Норм, можно

**Comment by skywinder** [comment]
Да, класная штука.  Готов поработать над этим.

- предлагаю upvote делать через `[+, +1, ++, 👍]`

сейчас разберусь с переменными  нужна помощь: как завести тесирвыз пользователй на локал машине  #241 

(после если надо - распишу подробный гайд, чтоб newcomers могли быстрее включаться в процесс и не задавать глупые вопросы)

**Comment by Anatolt** [comment]
Кажется эта фича уже реализована

**Comment by vas3k** [comment]
Ага
