### ISSUE TITLE
В чужом профиле можно нажимать на тэги, при этом этот тэг изменится в твоем профиле

### ISSUE THREAD

**Issue by O4epegb** [vas3k/vas3k.club#233]
В чужом профиле можно нажимать на тэги, при этом этот тэг изменится в твоем профиле.
В чужом профиле он тоже визуально поменяется после клика, но по факту, после перезагрузки, все будет ок.

Т.к. я глупый фронтендер, то у меня не получилось засидировать базу, поэтому не смог в деве это воспроизвести и пофиксить. По-хорошему нужно какой-то дефолтный сид данных иметь, т.е. набор тегов стандартных, плюс еще может хотя бы одного юзера сделать, кроме годмода, чтобы можно было тестировать вот такие кейсы, когда чужой профиль смотришь.

По сути нужно в `profile.html` прокинуть в `<user-tag />` флаг, что тег должен быть редактируемым только в своем профиле, т.е. когда `me.id == user.id`. А потом в `UserTag.vue` обработать этот флаг, т.е. при клике ничего не делать, если профиль не твой. Совсем топчик если еще убрать ховер стили для данного кейса.

Если кто-то скажет, как мне сделать еще юзера и накидать тегов, или пульнет такой сид в репу, то я могу попробовать пофиксить

**Comment by vas3k** [comment]
Да можно было их просто заменить на span :)
Пофиксил https://github.com/vas3k/vas3k.club/commit/c117eb6510fed6c97edb433f1bbfbd33d9d5a834

**Comment by O4epegb** [comment]
Тогда немного абстракция компонента течет (супер дедовская фраза, я знаю), но в целом да :)

**Comment by vas3k** [comment]
Всегда можно сказать, что это два разных компонента, так как не наследуют логики друг друга, и внутренний дед станет кряхтеть чуть меньше :)

А вообще да, пока не болит, пусть так будет. Понадобится — абстрагируем
