### ISSUE TITLE
Рассылка помечается как спам / не доверенная

### ISSUE THREAD

**Issue by reenko** [vas3k/vas3k.club#236]
1. Подписался на рассылку
2. Получил письмо в спам
3. Добавил отправителя письма в контакты
4. Новое письмо снова в спаме.
 
![изображение](https://user-images.githubusercontent.com/11948740/83111811-d0cc2100-a0cd-11ea-9178-1098d3006281.png)

Объяснение почему нельзя доверять письму
https://tutanota.com/faq/#mail-auth

**Comment by vas3k** [comment]
Хм, интересно.

В DNS прописаны DKIM, DMARC, SPF записи как надо.

<img width="1066" alt="Screenshot 2020-05-28 at 11 02 16" src="https://user-images.githubusercontent.com/176344/83121568-c1030b80-a0d2-11ea-9206-36fa18df38ad.png">

По статистике отправок лишь меньше процента писем не доходят до адресатов, это тоже нормальный показатель.

<img width="863" alt="Screenshot 2020-05-28 at 11 01 51" src="https://user-images.githubusercontent.com/176344/83121615-d37d4500-a0d2-11ea-906a-e6f6ec86f0c9.png">

Пока нет идей что может не нравиться твоему почтовому провайдеру. В логах отправки на твой адрес все письма помечены как "ОК". То есть провайдер их принял.

Оставлю этот тикет на будущее и буду рад если кто-то подскажет чего еще не хватает для честного прохождения самых жестких антиспамов.

**Comment by Spmart** [comment]
@reenko Приложи пожалуйста технические заголовки этого проблемного письма из своего ящика. Вдруг я что наковыряю.

**Comment by reenko** [comment]
У меня была подписка на gmail.com ящик и оттуда отправка на другой ящик, который выдавал эту ошибку, сменили адрес на прямой, теперь нет ошибки, что отправитель фейковый, наверное, гугл что-то не удачно сделал при пересылке.

Падает в спам все равно, но без красного сообщения, мне кажется можно закрывать задачу.
@Spmart приложил заголовки для двух разных вариантов

[without_forward.txt](https://github.com/vas3k/vas3k.club/files/4705295/without_forward.txt)
[with_forward.txt](https://github.com/vas3k/vas3k.club/files/4705296/with_forward.txt)

**Comment by Spmart** [comment]
В первом почему-то:

`dkim=permerror reason="domain not found" header.d=mailgun.vas3k.club header.s=smtp header.b=Hpare27V
Received: from w1.tutanota.de ([192.168.1.162])`

Во втором:

`dmarc=fail (dis=reject p=reject; aspf=r; adkim=r; pSrc=dns) header.from=vas3k.club;
dkim=permerror reason="domain not found" header.d=mailgun.vas3k.club header.s=smtp header.b=EsqJDp+T;`

Я не эксперт в почте, но могу предположить, что хочет он dkim для mailgun.vas3k.club. Он есть только для основного домена:

`% dig +short txt mail._domainkey.vas3k.club
"v=DKIM1; k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+T9RCaTAep33ey9nA34J02C1bKubtN4WiztMvMvndJnovgYzt/BRPpUUsfVz8UkSBhU/+CILQcBHMcXu/L6ZpcZY86n2bdZdUqaztVjNaAotUYJY9U+0Z9Tp8FqE8oU09X/54bmpdml1OvmtoqIf2S/ihy5wApfbAkV+v7OCuzQIDAQAB"`

А для поддомена его нет:

`% dig +short txt mail._domainkey.mailgun.vas3k.club`

Поправьте меня, если я неправ. В сложных схемах с рассылками еще не разбирался.

**Comment by yaroslavkorenskoy** [comment]
1. Могу настроить почтовые офисы, для аналитики — что влетает в ящики, а что нет. postoffice от яндекс. postmaster от мейлру и жмейла(у него статистика на базах до 100К подписчиков едва отображается, но нам хватит);
2. Перепроверить DKIM, DMARC, SPF;
3. Возможно что-то ещё по ходу, чего пока не вижу — например, у меня не подтверждён адрес емейла в клубе, и нажатие кнопки «вы не подтвердили емейл» — а там «пишите нам на почту». Это занимает ручное время. Можно автоматизировать, готов взяться и за эту задачу;

**Comment by skywinder** [comment]
@yaroslavkorenskoy Супер. по 1 и 2: Вроде эта ошибка самоустранилась - так что эту таску закрываю.

 по поводу пункта 3 - будет круто, если сделаешь. Под это есть таска: https://github.com/vas3k/vas3k.club/issues/238
