### ISSUE TITLE
Кнопка повторной отправки письма-подтверждения почты

### ISSUE THREAD

**Issue by kartashovata** [vas3k/vas3k.club#238]
У меня в аккаунте "Вы не подтвердили свой адрес электронной почты...", а письмо в почте где-то потерялось. Я не  смогла найти кнопку "отправить ещё раз", и, по-моему, без неё мне так на рассылку и не подписаться.

**Comment by vas3k** [comment]
Да, есть такое. Ссылка на подтверждение приходит в "Велком дринке", но когда удалил его — больше никак :) 

Пока можно писать нам на  club@vas3k.club с того же адреса почты и модераторы подтвердят руками.

**Comment by skywinder** [comment]
А кто-то пробвал для тестов настроить мейл-агент? там кроме MAILGUN api keys надо что-то править?

**Comment by ktaranov** [comment]
> Пока можно писать нам на club@vas3k.club с того же адреса почты и модераторы подтвердят руками.

Отличный воркфлоу.
