### ISSUE TITLE
Pre-loaded old post when writing a new one

### ISSUE THREAD

**Issue by CovectbCobaka** [vas3k/vas3k.club#239]
Сафари, макось. Priority: minor если оно не трогает существующие посты. 

Нажимаю Пиши -> пост и вижу тест своего последнего поста, с пустым заголовком. 
Удивляюсь. Перелогинюсь. Иду в другой браузер. Не помогает. 

Редактирую первый абзац этого странного презагруженного поста. Сохраняю в черновики. Нажимаю Пиши еще раз. Ура, здравствуй дорогой Мартин Алексеевич. 

Пост в черновики не ушел. Пост, который предзагрузился, не изменился. 

Воспроизвести не удалось. Что это было?

**Comment by CovectbCobaka** [comment]
А не, в черновики он ушел. Но все равно фигня какая-то.

**Comment by vas3k** [comment]
Это конфликт автосейва. Придется его вообще отключить чтобы не смущать людей :)
