### ISSUE TITLE
[Digest] Notifications for wrong user

### ISSUE THREAD

**Issue by stumyp** [vas3k/vas3k.club#240]
(я не разработчик, поэтому могу только пожаловаться)

В последнем дайджесте мне пришло уведомление, что меня _упомянули_ но упомянули совсем не меня. Похоже на какую то коллизию имён. 

умные люди говорят, что проблема здесь: https://github.com/vas3k/vas3k.club/blob/master/notifications/views.py#L152

скрин из дайджеста
![image](https://user-images.githubusercontent.com/5258641/83161066-f3face80-a0d5-11ea-9d8b-420853b446bc.png)

при этом мой ник просто Tim

**Comment by seankalejs** [comment]
Привет!

Да, имеет место быть такой баг, занес на Трелло. Спасибо, что обратил внимание на него :)

**Comment by vas3k** [comment]
Возможно, его даже пофиксил кто-то в истории PR. Надо проверить. Баг все еще повторяется?

**Comment by vas3k** [comment]
А, я наврал, пофиксили другое. Ладно :)
