### ISSUE TITLE
обойти oAuth Pateron для тестирования? 

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#241]
Хочу помочь с issues. Нужна помощь с тестированием и деплоем:

- запускаю `docker-compose up`
- по кнопке войти c http://0.0.0.0:8000/ ссылка на 'http://0.0.0.0:8000/auth/patreon` и редирект -> https://www.patreon.com/oauth2/errors?error=invalid_request&error_description=Invalid+client_id+parameter+value

Как засетапить движок для тестирования логина у себя локально баз патреона?

<img width="844" alt="image" src="https://user-images.githubusercontent.com/3356474/83253961-18d76a80-a1d8-11ea-8326-fd1d35b55663.png">

---
ps.
можно идти в обход через `godmode`, но хочу проверить, как это работет от простых пользователей.

**Comment by vas3k** [comment]
Почитай README :)
Потом открой http://127.0.0.1:8000/godmode/dev_login/

**Comment by skywinder** [comment]
я написал внизу про это. что можно через годмод, но хочу проверить без него

**Comment by vas3k** [comment]
А что ты хочешь протестировать?

**Comment by skywinder** [comment]
Систему голосований и апвоуты и Система учета голосов в батлах , например.
Везде, где нужно >1 действия от разных пользвателей.

Могу перефомулировать вопрос в более общий:
Как создать тестового пользователя, что бы проверить взаимодейсвие между пользователями.

**Comment by seankalejs** [comment]
@skywinder Привет! Завел issue #255 по твоему вопросу (можешь взяться за него, если хочешь 😄 )

**Comment by skywinder** [comment]
> @skywinder Привет! Завел issue #255 по твоему вопросу (можешь взяться за него, если хочешь 😄 )

Дайте две, беру! :)

**Comment by seankalejs** [comment]
Есть ещё 48 кроме неё, можешь посмотреть всех и выбрать самые красивые 😏

**Comment by skywinder** [comment]
> Есть ещё 48 кроме неё, можешь посмотреть всех и выбрать самые красивые 😏

Сделал теперь можно тестить и другие штуки. 
сейчас разберусь как DEV бота поднимать (можно вас куда-то в личку спросить детали по нему?) и сделаю плюсовалку #232

**Comment by seankalejs** [comment]
По тех вопросам лучше прям @vas3k в личку пиши (где тебе удобно, ТГ или Твиттер или еще куда 😄 )

**Comment by vas3k** [comment]
Ох, с дев-ботом будет тяжело, там нужны коллбек URL'ы внешние и всякое такое. Не уверен, что это вообще можно протестить локально

**Comment by skywinder** [comment]
@vas3k я попробую сначало сам, потом спрошу помощи там, где встряну. И постараюсь это задокументировать для последующих энтузиастов.
первая задача - воспроизвести `./vas3k_club.env` :)
