### ISSUE TITLE
Бейдж "Nintendo Switch" в "О себе"

### ISSUE THREAD

**Issue by Spmart** [vas3k/vas3k.club#242]
Есть PlayStation и Xbox, но нет Switch. Сейчас нинтендобои не могут видеть друг друга издалека, как мастера мыла, обладатели ящиков и пекабояре.

В общем, необходим бейдж для обладателей Nintendo Switch.

**Comment by skywinder** [comment]
Больше! Больше сучностей :)

(идея)
*сделать вложенные бейджи. И разом геймеров запихать туда, а там пусть в под-лейблах делятся на приставки-жанры игр-рассы.

**Comment by seankalejs** [comment]
Привет! Спасибо за предложение!
На Трелло есть специальная [карточка](https://trello.com/c/VRF7LhBp) для вариантов новых тегов, там уже есть подобный запрос, так что закрою данный issue как дубликат тех предложений :)

Касательно вложенных тегов: ИМХО чересчур громоздко получится (да и зачем?), но мб у @vas3k другое мнение будет. Энивей, это уже на отдельный issue тянет 😄

**Comment by vas3k** [comment]
Да, я помню про бейдж нинтендо и за него есть несколько голосов в Трелло, может он и появится в одном из апдейтов. Тикет можно закрыть чтобы не мешался в списке :)
