### ISSUE TITLE
Retract upvote (downvote)

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#243]
Предлагаю добавить возможность отозвать +1 (как это сделано на SO, Reddit, etc).
(Все ошибаются)
![odown](https://user-images.githubusercontent.com/3356474/83289159-d2513280-a20e-11ea-8c55-9139c02a3f90.gif)

Или для того, чтобы случайно не отменить поставленый +1, 
Можно также, как с комментарием подтеврждение через `onclick="return confirm('Удаляем?')`

**Comment by skywinder** [comment]
ps 
для тестов этой штуки и нужно было #241

**Comment by nlopin** [comment]
@vas3k могу запилить. Думаю разрешить отозвать свой голос только в первые 3 часа, по аналогии с редактированием. Норм?

**Comment by vas3k** [comment]
@nlopin давай попробуем. Только чтобы с UI консистентно всё было :)
