### ISSUE TITLE
Содержимое поля не выровнено по вертикали на странице "Добавить проект" 

### ISSUE THREAD

**Issue by niya3** [vas3k/vas3k.club#246]
сабж в конце страницы https://vas3k.club/create/project/

![image](https://user-images.githubusercontent.com/1140412/83336433-ff0f5380-a2bb-11ea-93da-ad3283ff6abb.png)

При этом на странице "Редактировнаие профиля" с этим норм.

![image](https://user-images.githubusercontent.com/1140412/83336533-eb182180-a2bc-11ea-8d45-85fb4ee67c84.png)

Linux, Firefox 76

**Comment by skywinder** [comment]
fixed in 79d3c61a92ca8d6651a9baeb8c31d75a66f77f87
