### ISSUE TITLE
Редактирование Профиля | Нет превью аватарки

### ISSUE THREAD

**Issue by ggoshanov** [vas3k/vas3k.club#247]
**Шаги воспроизведения:**

    1. Перейти в редактирование профиля;
    2. Кликнуть на инпут с аватаркой и выбрать картинку

**Ожидаемый результат:**
Выбранная картинка появляется рядом с инпутом
![tg_image_4162410178](https://user-images.githubusercontent.com/56938362/83352710-3b8f8d80-a356-11ea-8421-79e011315415.jpeg)

**Фактический результат:**
Превью отсутствует

**Comment by vas3k** [comment]
Fixed :)
