### ISSUE TITLE
В телеграме добавить голосовательную кнопку к комментариям

### ISSUE THREAD

**Issue by MarinaKonyaeva** [vas3k/vas3k.club#249]
Предложение добавить возможность через бота, не открывая веб-версию, голосовать за комментарии:
![изображение](https://user-images.githubusercontent.com/66025160/83357319-5e309f00-a374-11ea-8b4b-ca800d6b8be6.png)

Кроме как предложить ничем помочь не могу - не умею :(

**Comment by vas3k** [comment]
Ага, вот тут уже предложили как сделать: https://github.com/vas3k/vas3k.club/issues/232
Закрою как дубликат

**Comment by MarinaKonyaeva** [comment]
добавила в свою табличку, что надо продумать как предупреждать и менеджить появление дубликатов

**Comment by skywinder** [comment]
@MarinaKonyaeva Гитхаб об этом подумал уже - когда пишешь название таски - он вверху предлагает посомтреть таски с похожими словами.

А так только еще бы рекомендовал ставить Dublicate в этой таске, что бы понимать не заходя внутрь причину закрытия
