### ISSUE TITLE
Список комментариев юзера в профиле

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#250]
Сейчас выводится последние три. Хотелось бы все. Я бы сделал табы на простеньком JS типа «Посты» | «Комменты» | «Лайки», спрятал списки туда и переключал по клику. Табы решат проблему с пажинацией.

**Comment by vas3k** [comment]
Дубликат https://github.com/vas3k/vas3k.club/issues/198

**Comment by uhbif19** [comment]
> Табы решат проблему с пажинацией.

Не до конца понимаю почему решат. Комментов же все будет слишком много, нет?

**Comment by vas3k** [comment]
@uhbif19 с табами можно будет сделать пажинацию в каждом списке,  без табов — только в одном (как сейчас)
