### ISSUE TITLE
Сохранение адреса при переходе на логин

### ISSUE THREAD

**Issue by vorant94** [vas3k/vas3k.club#253]
Сейчас если я захожу не авторизованным на, например, закрытый пост, то мне собственно сам пост не показывается и сайт предлагает авторизоваться. После собственно авторизации меня перебрасывает на страничку моего профиля

Было бы удобно, если бы сайт запоминал тот адрес, откуда я перешел на авторизацию, чтобы потом открыть его, что избавит от необходимости дважды переходить по ссылке, если первый раз почему-то был не авторизован

**Comment by vas3k** [comment]
Сделано в https://github.com/vas3k/vas3k.club/commit/7fc35c65a514e72aaac5e865f486d298c2053fed
