### ISSUE TITLE
Возможность локально создавать дополнительных тестовых юзеров

### ISSUE THREAD

**Issue by seankalejs** [vas3k/vas3k.club#255]
Заводится по результатам обсуждений в #241 

Есть необходимость для тестирования решений различных issues создавать дополнительных "обычных" юзеров, чтобы проверить взаимодействие между ними (сейчас можно только самому зайти через _godmode_).

"Можно сделать эндпоинт, чтобы на каждый вызов заводил случайного юзера и логинил под ним, типа `/godmode/dev_login/random/`" - Vas3k.

**Comment by skywinder** [comment]
Беру 👌

**Comment by skywinder** [comment]
@seankalejs у меня только вопрос: а как вы это тестили без такой фичи? На проде?! :)
*Или где-то есть зеркало «прода» для тестов?

**Comment by seankalejs** [comment]
Сделаю красиво и передам право ответа @vas3k 😅

**Comment by vas3k** [comment]
Никак не тестили, раньше всем хватало одного юзера
