### ISSUE TITLE
Автосейв на клиенте для комментов

### ISSUE THREAD

**Issue by vorant94** [vas3k/vas3k.club#259]
Очень неприятно, когда из-за лагов браузера на телефоне страница обновляется и слетает коммент, который я хотел написать, а он уже в 20 строк длинной... понятное дело, это вина телефона/браузера и так далее, но было бы круто, если бы в клубе была подушка безопастности специально для таких случаев

**Comment by vas3k** [comment]
Там раньше был автосейв на клиенте, но люди жаловались "чо это мои старые недописанные комменты мне подсовываются, это баг, срочно почините!!!", ну я и отключил его :D 

Будет хорошо если кто-то сделает как надо. У редактора есть даже встроенная фича для этого.

**Comment by vorant94** [comment]
Может сделать драфт с таймером? Чтобы через условные сутки или какой-либо другой срок, когда драфт становится «старым комментом», он сгорал?

**Comment by vas3k** [comment]
Можно кеш с таймером, да, ну и не забывать обнулять его при отправке. Кто-нибудь может заняться.

**Comment by Konfuze** [comment]
Как вариант – класть коммент в локалсторадж в виде структуры "таймстемп - коммент" с ключом равным айди поста.
При запуске приложения (или модуля с редактором комментов) удалять все комменты старше суток, а при попытке ответить в другом посте сохраненный коммент не будет отображаться.

**Comment by skywinder** [comment]
Закрываю как неактуальную т.к. активности и финального решения по таске нет.

**Comment by skywinder** [comment]
p.s. про таймер - показывать таймер - слишком сложно. 
не показывать таймер - народ будет спрашивать - куда делся мой драфт?!?!?!?

Также как сейчас спрашивают (почему я не могу редактировать свой ответ)
