### ISSUE TITLE
На странице профиля в блоке "последние комментарии" видны комменты к удаленным(скрытым) постам

### ISSUE THREAD

**Issue by fr33mang** [vas3k/vas3k.club#262]
Замечено, если откомментировать пост, который позже скрыли, то в блоке "последние комментарии" этот коммент все равно остается. 

Предполагаю, что нужно всего лишь поправить фильтр запроса на комментарии, добавив проверку на видимость связанного поста.

Чуть позже смогу завести проект у себя на локалке и сделаю PR :)

**Comment by skywinder** [comment]
Да, и также видны скрытые проекты в разделе черновики. 
Например админы скрыли пост - у товарища https://vas3k.club/user/yuhenobi/ - 
но проект виден в профиле.

(хотя тогда надо бы показывать, что проект скрыт\удален\вчерновиках, а не Not found, как сейчас: https://vas3k.club/project/2790/ )

Я решил, что это фича, а не баг и не открывал даже таску.

@vas3k, будем с этим что-то делать?

**Comment by skywinder** [comment]
Вообще, выглядит несложно.  

---

Если кто захочет взяться вот, куда смотреть: https://github.com/vas3k/vas3k.club/blame/3250518f7a052541666db0b14ebd7ca1ca3c93f9/auth/helpers.py#L69
 - это для юзеров. Надо сделать аналогично для проектов.

Комит 3250518f7a052541666db0b14ebd7ca1ca3c93f9
