### ISSUE TITLE
class="block feed-post feed-post-question feed-post-is-new" лихорадит

### ISSUE THREAD

**Issue by donottalk** [vas3k/vas3k.club#263]
Странное поведение карточки в Chrome на iOS при длительном тапе.

![RPReplay_Final1591168529](https://user-images.githubusercontent.com/19312017/83859668-eb824380-a726-11ea-99ba-76f911ed9d82.gif)

**Comment by skywinder** [comment]
Да, так открываются ссылки в хроме на айпаде по лонг тапу. 

В чем  странность? и какой expected behavior?

**Comment by donottalk** [comment]
Аву обводочка перекрывать не должна, по-моему. Если должна и это просто придирки по мелочам в дизайне, то закрываем вопрос.

**Comment by skywinder** [comment]
А, аватарка перекрывается. 
Я бы не отвлекался на такие дизайнерские мелочи. узкий кейс и на функционал не влияет
Оставляю решение за @vas3k

**Comment by vas3k** [comment]
Делайте что хотите, вы же сами не глупые. Я не буду принимать решения по каждой едущей аватарке в каждом нестандартном браузере :)

**Comment by donottalk** [comment]
Сойдёмся на том, что мы законодатели трендов, и это тренд такой теперь новый.

**Comment by vas3k** [comment]
Для меня главное чтобы решение проблемы было соизмеримо с ее размером. Если это добавление 1 CSS стиля — ок. Если оно требует переверстки нахер всех постов в клубе с вероятностью поиметь еще 100 новых проблем — такое сделает меня грустным на кодревью :)

**Comment by skywinder** [comment]
мелкине one-liner's PR можно рассмотреть.
ps
@vas3k не так важно, на каком, но читать одно удовльствие. даже просто комментарии. этакие  hidden gems для нердов.
