### ISSUE TITLE
Фича: заметки к пользователям

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#265]
Нужна возможность написать для себя заметку об определенном юзере. Как на хабре, лепре и других сообществах. Никому кроме меня она не будет видна. Фича поможет модераторам чтобы помечать на что обращать внимание, а простым юзерам чтобы не забыть "того самого чувака, который в девопсе разбирается норм". Можно будет отображать везде под ником, так даже смешнее.

**Comment by ElSpirit** [comment]
в развитие - можно сделать "персональную записную книжку"
чтобы отмеченные пользователи и заметки к ним были доступны из личного кабинета

**Comment by ktaranov** [comment]
По праву перворожденного оставляем https://github.com/vas3k/vas3k.club/issues/237, этот закрываем как дубликат.
