### ISSUE TITLE
Возможность сохранения постов в "Закладки"

### ISSUE THREAD

**Issue by Jarith** [vas3k/vas3k.club#266]
Было бы здорово иметь возможность по клику на кнопку добавить пост в "Закладки" и просматривать сохраненные посты в профиле. Например, как на Хабре

**Comment by vas3k** [comment]
Примерно пятый дубликат. Пока не планируется. Не вижу проблем использовать Pocket и другие специализированные для закладок тулзы

**Comment by skywinder** [comment]
Шестой дубликат. Для референса  #198
