### ISSUE TITLE
комната про IT / tech / Dev

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#267]
сделать комната про IT / tech / Dev и вещи  вокруг этого.

Примеры: 
- [Поделитесь своим проверенным VPN-провайдером ](https://vas3k.club/question/1005/)
- [Невероятно полезные, но неизвестные миру тулзы ](https://vas3k.club/post/1657/)
- [ Поясню за JS фреймворки ](https://vas3k.club/post/1222/)

подобные разговоры  хочется отфильтровать и посмотреть разом, но без отдельной комнаты в главном это сложно.

**Comment by seankalejs** [comment]
Под такую задачу (поиск по группам постов) напрашивается даже не комната, а _теги_. То есть автор ставит теги к своему посту (или из заранее внесенных и "захардкоженных", или берет из существующих + добавляет свои), а в поиске можно по этим тега искать. Комнатами мы такое вряд ли перекроем (или перекроем вполне? 🤔 ). Но любая подобная новая функциональность требует серьезной разработки (и проработки), так что пока можно ограничиться подобной комнатой.

В целом мб и нет смысла в тегах, ибо комнатами минимально мы перекроем в них необходимость, если добавлять новые комнаты при появлении необходимости. Но тут вопрос в том, чтобы комнаты поддерживать тогда такие, дабы они сами по тематике не пересекались (тут встает вопрос, а не создаст ли комната "Про IT" проблем для авторов постов под категорию "Дом Дурачок"? Формально, одно есть подмножество другого...). Но мб данную проблему можно порешать, если разрешить авторам выбирать больше одной комнаты для их поста. Но мб это будет противоречить с целью комнат, которую преследовал Вастрик. Что-то меня понесло в рассуждения...

Короче, против такой комнаты ничего не имею, хорошая мысль. По остальным моим мыслям (как и по теме issue) был бы рад услышать @vas3k, если у него будет на это время 😁

**Comment by vas3k** [comment]
Про теги я высказывался вот здесь: https://github.com/vas3k/vas3k.club/issues/48#issuecomment-623289943

Комнату айти пока не знаю. Это как делать отдельную комнату для пьющих внутри бара :D

**Comment by skywinder** [comment]
> Комнату айти пока не знаю. Это как делать отдельную комнату для пьющих внутри бара :D 

Все входят в «бар» и сразу видят указатель и выбор из комнат. И ни одна из них не про то ИТ (не считая тематического «дурачка»)

Так что без такой комнаты - получается бар без барной стойки :Р

**Comment by skywinder** [comment]
И вот еще пост-кандидат в эту комнату как раз: 
[MacOS tips & tricks ](https://vas3k.club/post/3318/)

p.s.
Закрою идею, что бы не висела. Если кто-то еще посчитает полезным такой раздел - пишите в комментарии.
