### ISSUE TITLE
Неправильное количество аргументов в батле

### ISSUE THREAD

**Issue by Windrushfarer** [vas3k/vas3k.club#27]
Если посмотреть на карточку батла, то количество аргументов будет неправильным, т.к считается еще и количество комментариев тоже.
На карточке [19 аргументов](http://s.csssr.ru/U439TP407/20200428122156.png)
На самом деле [13 аргументов](http://s.csssr.ru/U439TP407/20200428122235.png)

**Comment by vas3k** [comment]
Я бы переименовал в «комментариев» и забил

**Comment by FMajesty** [comment]
@vas3k 
А там тип не разный у этих комментариев?

**Comment by Windrushfarer** [comment]
Да можно и переименовать
