### ISSUE TITLE
Не все посты видны на странице «Новое»

### ISSUE THREAD

**Issue by hudochenkov** [vas3k/vas3k.club#271]
Случайно обнаружил, что некоторые посты не видны в [Новом](https://vas3k.club/all/new/). Я слежу за новыми постами там, чтобы ничего не пропустить. В телеграмме видел ссылку на пост [про чай](https://vas3k.club/post/2297/), а в списке его нет.

**Comment by vas3k** [comment]
А ты прав 🤔

**Comment by hudochenkov** [comment]
Вот это скорость! Спасибо!

**Comment by hudochenkov** [comment]
Что-то пошло не так. Пост теперь вижу, но “Клубный журнал. Итоги недели. Выпуск #2” вылез в самый верх.

**Comment by vas3k** [comment]
Был косяк с тем постом. Поправил
