### ISSUE TITLE
Ошибка при открытии страницы с картой при локальном запуске

### ISSUE THREAD

**Issue by AntYats** [vas3k/vas3k.club#272]
Хотел заняться проблемой #245, а страница, видимо, не прописана.
![Screenshot_2](https://user-images.githubusercontent.com/33600479/84429404-beef8f80-ac30-11ea-881e-fbe39627a12b.png)

**Comment by vas3k** [comment]
Есть такое, ага. Происходит потому что в базе нет тегов. Был бы рад, если бы кто-то поправил

Локально можешь починить вызвать в соответствующем докере `pipenv run python manage.py update_tags`
