### ISSUE TITLE
Фича: приватные комментарии

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#283]
### Юзкейс: 

иметь возможность написать автору комментарий (например об опечатке / битой ссылке)

### Текущий юзерфлоу:
Идти в профиль, искать контакт, копировать ссылку, писать в телегу - долго и 90% случаев лень.
Писать в публичный комментарий тоже не очень хочется - это никому не интересно, кроме автора.

### Предложение 

Сделать чекбокс / кнопку для отправки приватного комментария, который виден только автору поста и автору комментария

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/3356474/84988011-6f96eb00-b16b-11ea-8553-342fd5b9fd41.png">

**Comment by vas3k** [comment]
На первый взгляд, какая-то фича ради фичи. Как снежинки в новый год. Как она сделает Клуб лучше в долгосрочной перспективе? Какие минусы могут возникнуть? Не порвет ли это дискуссии нафиг, что люди перестанут в них разбираться?

**Comment by skywinder** [comment]
В начале хотел сделать пропоусал - предлагать change request в пост (как на стековерфлоу). Но это сложно. 
Заметил что уже много раз хотелось написать "поправь Х". Но лень идти в профиль.

> Клуб лучше в долгосрочной перспективе?

потенциально повысит качество постов, т.к. сейчас много опечаток и битых ссылок. Появиться эффект коллаборации.

>  Какие минусы могут возникнуть?

усложнение интерфейса на лишнюю кнопку/чекбокс.

> Не порвет ли это дискуссии нафиг, что люди перестанут в них разбираться? Как отвечать на такие комменты?

О! такая идея: для простоты сделать односторонними комментарии.
Что бы  была возможность закинуть автору сообщение "ссылка на ХХХ не работает и тебя в слове ХЙ буква пропущена"

> Как учитывать их в счетчиках?

никак.  вычитать их.
на них нельза отвечать, нельзя плюсовать. это только бросить обратную связь.

> Почему нельзя просто написать в телеграм из профиля?

написал выше: зачастую лень делать многоходовку из 10 кликов, скролов копипасты и перехода в другое приложение только ради того, что бы сказать про битую ссылку. (и в коментах мусорить не хочется. Такой же вариант был бы лично мне удобен. отметил косяк - быстро на той же странице бросил автору месседж внизу страницы.

**Comment by jtraub** [comment]
> О! Такая идея: для простоты сделать односторонними комментарии.

Так может и вовсе не делать тогда комментарии, а просто форму в которую пишешь свои предложения/замечания, а бездушная машина за тебя отправит автору сообщение в телеграм? Ведь текущая проблема пока, как я понимаю, заключается в том, что для сообщения о битой ссылке или опечатке нужно сделать многоходовочку из 5-7 кликов. 

Второй тип комментариев - это как-то слишком сложно, можно на самом деле запутаться и увести часть дискуссии в такие комментарии.

**Comment by skywinder** [comment]
@jtraub да, действительно можно и так. проблема решается, кода меньше.
Есть идеи, каким образом это реализовать в UX?

**Comment by jtraub** [comment]
@skywinder мне привычен вариант, который когда-то предложил Котеров: выделяешь текст, нажимаешь Ctrl+Enter и во всплывающем окне пишешь пояснения. Дополнительно где-то внизу поста можно оставить ссылку-кнопку "Сообщить об ошибке автору", которая по клику будет вызывать тоже самое окно.

Если что, то так много кто делает. На ум пришли [Хабр](https://habr.com/ru/company/habr/blog/442208/), [TJournal](https://tjournal.ru/tech/179416-zoom-peredumal-vvodit-skvoznoe-shifrovanie-tolko-dlya-platnyh-akkauntov-i-poobeshchal-ego-vsem-polzovatelyam) и хотя бы та же Медуза. Сходите по ссылке, попробуйте выделить текст и нажать Ctrl+Enter

**Comment by skywinder** [comment]
Да, мне нравиться такой вариант имплементации. это даже удобнее будет. 👍

**Comment by l4l** [comment]
А не рассматривался вариант сделать личные сообщения? Контактов может быть недостаточно (например юзер указал только какой-нибудь вотсап, а тебе там совсем не хочется регаться). Плюс эта фича чуть шире, например можно:

- напомнить о чем-либо (напр. написать какой-нибудь обещанный пост),
- запросить рефер в компанию или скинуть оффер/релевантную вакансию,
- позвать потусить оффлайн,
- спросить узкоспециализированного совета в чем-либо,
- етц.

Не уверен, что все эти пункты являются положительными, но кмк фича выглядит более общей при +/- (наверное) тех же усилиях, в сравнении с "зарепорить очепятку".

**Comment by skywinder** [comment]
@jtraub предложила вариант, который уже описан в  #144
Закрываю как дубликат
