### ISSUE TITLE
Список всех подписок

### ISSUE THREAD

**Issue by hudochenkov** [vas3k/vas3k.club#285]
Добавить страницу или блок куда-нибудь с подписками на посты. Сейчас, если подписался на пост, то уже не найдешь его, если в закладки браузера не добавил.

**Comment by skywinder** [comment]
Related to https://github.com/vas3k/vas3k.club/issues/198

**Comment by skywinder** [comment]
И вот этот https://github.com/vas3k/vas3k.club/issues/3

Вот не знаю, оставить 3 похожих issue или объеденить их все в одну?

**Comment by hudochenkov** [comment]
Мне кажется, что это больше схоже с #3, чем с #198.

Список подписок был бы уместен на странице `/edit/notifications/`, как мне кажется.

**Comment by skywinder** [comment]
Да, есть еще #50 и #22  - все примерно об одном. 

Надо бы их собрать, а то расплодилось.

[цитируюя Вастрика](https://github.com/vas3k/vas3k.club/issues/22#issuecomment-631293924)

>так присылай PR. Таких тикетов уже по-моему штук пять открытых валяется

**Comment by skywinder** [comment]
Вастрик описал #198:

>Сейчас выводится последние три коммента в профиле. Я бы сделал табы на простеньком JS типа «Посты» | «Комменты» | «Лайки», спрятал списки туда и переключал по клику. Табы решат проблему с пажинацией

 подписки можно аналогично вставить отдельным табом - суть таже.

 так что закрою эту фичу в пользу #198.
