### ISSUE TITLE
При публикации черновика пост падает вниз в истории к дате создания черновика

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [vas3k/vas3k.club#29]
Похоже, что у постов нет отдельной даты создания и даты публикации (или сортировка происходит по дате последней активности в посте, а публикация не считается за такую активность - т.к. в заглавии поста стоит сегодняшняя дата).  
Я начал писать пост вчера, а закончил сегодня - после публикации он болтается далеко внизу ленты 
Пример поста: [https://vas3k.club/post/300](https://vas3k.club/post/300/)

**Comment by vas3k** [comment]
Хороший баг, спасибо. Пост тоже очень крутой!

**Comment by alex-pobeditel-2004** [comment]
И тебе спасибо за всё!
