### ISSUE TITLE
Некоторая возможно чувствительная информация о постах палится для незалогиненных пользователей

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [vas3k/vas3k.club#292]
Баг это или фича, но при открытии топика с чувствительной темой без логина на сайт я заметил вот что:
![изображение](https://user-images.githubusercontent.com/14791483/85681598-1f240e00-b6d4-11ea-9711-5cb75a26e93e.png)

Видимо это делается специально для генерации превьюшек, но на всякий случай сообщаю

**Comment by vas3k** [comment]
Фича для превьюшек, да
