### ISSUE TITLE
Тайтл интра имеет повторенное #intro #intro

### ISSUE THREAD

**Issue by omnster** [vas3k/vas3k.club#293]
В теге `<title>` слово intro повторяется дважды.

Кажется, это можно поправить, заменив 

    title=f"#intro от @{user.slug}"

на

	title=f" от @{user.slug}"

в этом файле.

https://github.com/vas3k/vas3k.club/blob/a70a89e02054a44257247a79ffd160ea45dc7aa5/posts/models.py#L242

Я не уверен, что это соответствует best practices, и вообще это костыль, поэтому не создал пулл-реквест.

**Comment by skywinder** [comment]
ок, есть такое.
![image](https://user-images.githubusercontent.com/3356474/87384946-2ea5c100-c5c7-11ea-86ef-7ca179faa65d.png)

Я думаю можно поправить в PR. @vas3k ок, на счет фикса?


ps.
только править это надо не в том файле, где ты указал, а непосредсвенно в html. Иначе новые интро будут везде без префикса

**Comment by vas3k** [comment]
Это надо править пиздец как аккуратно, ибо для интро переиспользуется файл поста и там с легкостью можно накосячить. Надо создавать новый файл
