### ISSUE TITLE
Фича - плавающая кнопка upvote

### ISSUE THREAD

**Issue by GellTorn** [vas3k/vas3k.club#294]
Очень часто, хочется плюсануть пост уже после того как прочитал его, нередко во время прочтения.
Сейчас после прочтения необходимо подниматься к началу страницы, а потом только к комментариям.
Небольшая фича, но очень необходимая.

`position: sticky;` очень помогла бы в этом вопросе или что там есть еще.

**Comment by GellTorn** [comment]
@vas3k не могу поставить лейбл

**Comment by skywinder** [comment]
я поставлю :)

**Comment by skywinder** [comment]
@GellTorn Эта тема уже обсуждалась вот тут https://github.com/vas3k/vas3k.club/issues/32
и в немного другом общем контексте: #136

т.е. уже очень много людей сказало б этом -  ты можешь там высказаться и предложить, как сделать лучше 👍
