### ISSUE TITLE
После перелогина возвращать пользователя на ту же страницу

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/vas3k.club#297]
Меня почему-то постоянно разлогинивает из Клуба, и каждый раз, когда я хочу оставить комментарий, я жму «Войти» и после логина оказываюсь на странице своего профиля, а не там, где мой ФЛОУ был жестоко прерван.
Надо возвращать туда же, где было!

**Comment by vas3k** [comment]
По поводу разлогинивания глянь в следующий раз время жизни куков и вообще какую-нить еще инфу?

А редирект посмотрю, ок. Там надо просто добавить параметр ?goto= на кнопку :)

**Comment by mutantcornholio** [comment]
![Screen Shot 2020-07-01 at 13 11 54](https://user-images.githubusercontent.com/588262/86232347-7fb3bf00-bb9c-11ea-93b1-36e8d875e191.png)
Выглядит как две недели. Вполне может быть, что меня разлогинивает раз в две недели, просто на трёх девайсах.
