### ISSUE TITLE
Просмотр апвоутных постов\комментариев

### ISSUE THREAD

**Issue by FMajesty** [vas3k/vas3k.club#3]
Чтобы не терять.

Или можно запилить отдельную фичу с добавлением в **избранное**

**Comment by gavvvr** [comment]
Мне больше нравится идея с отдельным "избранным". Потому что "апвоут" - это просто "нравится"/+1. А есть вещи, которые прямо не хочется потерять, чтобы вернуться к ним позже.

**Comment by skywinder** [comment]
Закрою эту issue в пользу #198 - там уже обсуджается этот функционал:

>Сейчас выводится последние три коммента в профиле. Я бы сделал табы на простеньком JS типа «Посты» | «Комменты» | «Лайки», спрятал списки туда и переключал по клику. Табы решат проблему с пажинацией
