### ISSUE TITLE
Ник человека в профиле утекает за карточку

### ISSUE THREAD

**Issue by FMajesty** [vas3k/vas3k.club#30]
![Screenshot_20200428-112739_Vivaldi](https://user-images.githubusercontent.com/14141649/80471297-824b2b80-8943-11ea-85e3-a0ebd4e1e458.jpg)

412x892

**Comment by FMajesty** [comment]
Как оказалось, не на мобилочках тоже.
Сделал ник во все 32 доступные символа:
![Screenshot_20200428_130810](https://user-images.githubusercontent.com/14141649/80480707-69497700-8951-11ea-988d-684a0ff3ecc9.png)

**Comment by mxeo** [comment]
Я поправлю

**Comment by FMajesty** [comment]
@mxeo noice
