### ISSUE TITLE
Поиск в мобильной версии

### ISSUE THREAD

**Issue by echernyavsky** [vas3k/vas3k.club#302]
Не нашел поиск по сайту в мобильной версии, приходится переключаться на desktop view, чтобы что-то найти. 😭😭

**Comment by AntYats** [comment]
Кнопка меню сливается просто.
![Screenshot_2](https://user-images.githubusercontent.com/33600479/87223140-22c9bd00-c383-11ea-9040-570f790b97ac.png)

**Comment by echernyavsky** [comment]
> Кнопка меню сливается просто.
> ![Screenshot_2](https://user-images.githubusercontent.com/33600479/87223140-22c9bd00-c383-11ea-9040-570f790b97ac.png)

Спасибо!
