### ISSUE TITLE
Кнопка выбора комнаты при создании поста с темной темой на ios

### ISSUE THREAD

**Issue by s-salamatov** [vas3k/vas3k.club#306]
При создании нового поста, ссылки, вопроса или батла кнопку выбора комнаты почти не видно. Одинаково плохо выглядит в Chrome и Safari. На Android не смотрел. Со светлой темой все в порядке. 
![248A758E-B56F-4292-BDCA-0674DB35B13B](https://user-images.githubusercontent.com/55296341/87384741-2f2d6000-c5a5-11ea-8403-68d1f8a7b649.png)
![16F2D8F0-17C3-4044-BFB2-947857C06C33](https://user-images.githubusercontent.com/55296341/87384760-39e7f500-c5a5-11ea-9887-337dc04b8584.png)

**Comment by vas3k** [comment]
Пожалуйста, в таких багах всегда указывайте браузер и версию айос. Судя по кривым шрифтам ты на бете 14-й, да?

**Comment by s-salamatov** [comment]
> Пожалуйста, в таких багах всегда указывайте браузер и версию айос. Судя по кривым шрифтам ты на бете 14-й, да?

Cоре, первый раз репорчу баг. iOS 14.0 beta 2, Chrome 83.0.4103.88

**Comment by skywinder** [comment]
Если это бета, я бы писал об этом баге эпл. 
Тут вряд ли что-то можно поменять, не поломав другие вещи.

**Comment by vas3k** [comment]
Не, там проблема глубже. Оно и раньше не работало, а теперь стало тоже не работать, но по-другому :D
