### ISSUE TITLE
Сменить стиль выделения комментария по ссылке?

### ISSUE THREAD

**Issue by lopar** [vas3k/vas3k.club#31]
Когда пилишь комментарий и отправляешь его, он выделяется красненьким, что невероятно вымораживает, потому что подсознательно это цвет ошибки. И ты такой недоумеваешь: Не отправилось? Премодерация? Ошибка сервера? Сохранить и переотправить? Вот это вот всё.
![image](https://user-images.githubusercontent.com/1093237/80474915-c4c73500-8950-11ea-883f-49d6b3621f73.png)

В то же время, зелёненький, обычно — цвет успеха. Причём в цветомом восприятии есть опыт, когда чем насыщенней цвет, тем выше важность блока, который выделен. В данном случае выделенное сообщение стоит просто оттенить от фона, а не ярко засветить. Например так:
![image](https://user-images.githubusercontent.com/1093237/80475235-415a1380-8951-11ea-9097-7f096dc75953.png)

Возможно стоит рассмотреть изменение цветовой маркировки?

**Comment by vas3k** [comment]
Дай, пожалуйста, код своего цвета. Не забывая, что он должен быть на 40% прозрачным, чтобы смотрелся хорошо в темной и светлой теме.
Например, сейчас это `rgba(255, 48, 48, 0.4);`

**Comment by FMajesty** [comment]
@vas3k 
Ну-к, зацени 
HEX: 538083
RGB: 82, 138, 131
![Screenshot_20200428_212714](https://user-images.githubusercontent.com/14141649/80529091-3d50e480-8997-11ea-874c-bd053e63c487.png)
![Screenshot_20200428_212721](https://user-images.githubusercontent.com/14141649/80529099-3de97b00-8997-11ea-828e-3c3da03d1ea9.png)

**Comment by FMajesty** [comment]
Так наверное получше `rgba(82, 163, 131, 0.6);`
![Screenshot_20200428_215237](https://user-images.githubusercontent.com/14141649/80531269-a423cd00-899a-11ea-9bea-faf11a714c51.png)
![Screenshot_20200428_215242](https://user-images.githubusercontent.com/14141649/80531271-a4bc6380-899a-11ea-8c7d-fbb6fa50c662.png)

**Comment by lopar** [comment]
Я вообще брал прозрачность не 0.4, а 0.2 для блеклости.
#7de87d33 \ rgba(125, 232, 125, 0.2)

**Comment by Windrushfarer** [comment]
Синенький цвет не хотите попробовать? http://s.csssr.ru/U439TP407/20200430223007.mp4
Можно еще еще попробовать анимацию плавного перехода фона.

**Comment by vas3k** [comment]
Взял зелененький, спасибо
