### ISSUE TITLE
В поиске не видно, какие посты были уже апвоутнуты

### ISSUE THREAD

**Issue by gavvvr** [vas3k/vas3k.club#311]
В примере пост, который уже получил +1 от меня. На странице поиска этого не видно, кнопка выглядит будто я ее не нажимал. Я снова жму +1, визуально кнопка меняется, но цифра на ней остается прежней (что логично). Далее я открываю сам пост, чтобы продемонстрировать, что он уже был апвоутнут.

![upvote-in-search](https://user-images.githubusercontent.com/1719646/88020178-eb51d200-cb33-11ea-828f-3aa82ca0245a.gif)

**Comment by nlopin** [comment]
Я недавно менял функциональность кнопки. Посмотрю-поправлю 👍

**Comment by nlopin** [comment]
Оказалось, что это сделать нелегко, поэтому кнопки станут readonly
