### ISSUE TITLE
Страница “новое” показывает старые посты

### ISSUE THREAD

**Issue by hudochenkov** [vas3k/vas3k.club#312]
Что-то старые посты повылезали в Новом. Например, https://vas3k.club/battle/3877/ — 13-й в списке. Дата публикации поста — вчера, хотя комменты под постом несколько уже несколько дней как опубликованы.

Еще странный пост с датой публикации вчера, хотя пост старый https://vas3k.club/project/3876/.

**Comment by vas3k** [comment]
Ты прав. Эти два поста были скрыты и опубликованы заново, потому у них и обновилась дата. Я сейчас добавлю условие, но это даст другой возможный баг. Я не знаю пока правильного решения :)
