### ISSUE TITLE
Поиск показывает сообщения, отсутствующие в посте

### ISSUE THREAD

**Issue by devcooch** [vas3k/vas3k.club#316]
Ищу про капсульную кофе-машину:
https://vas3k.club/search/?q=%D0%BA%D0%B0%D0%BF%D1%81%D1%83%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F
Все результаты:
![image](https://user-images.githubusercontent.com/2089015/88346976-f3835a80-cd49-11ea-9a34-52eeb9260d6b.png)

Иду в пост:
https://vas3k.club/post/2259/

Ищу того самого Колю (Ctrl+F -> "Коля") - ничего не находит.

**Comment by vas3k** [comment]
https://vas3k.club/question/3054/#comment-dc3aaa8b-8805-409f-a87a-5c0dfe3f4ef4

**Comment by vas3k** [comment]
Нужно кликать на дату комментария. Жду более лучших дизайнов

**Comment by devcooch** [comment]
Да, но тогда значит неправильно показывается пост, к которому относятся комментарии. Поправлю описание.

**Comment by vas3k** [comment]
Все правильно, это поиск, там ничего не привязываетсч

**Comment by devcooch** [comment]
А зачем тогда сверху плашка поста? Я думал это группировка из другого тикета.
