### ISSUE TITLE
[Bot] "За 'None'" в нотификации об ответе на аргумент

### ISSUE THREAD

**Issue by IllanFed** [vas3k/vas3k.club#317]
![image](https://user-images.githubusercontent.com/3023033/88404752-fc6e3d80-cdd6-11ea-9039-a7d3451ea71f.png)

Не дебажил еще, если `comment` имеет инфу о сообщении-родителе, то фикс в одну строчку.
https://github.com/vas3k/vas3k.club/blob/2968f82989a156e67c1af69b65f041de7bf53d31/notifications/templates/telegram/comment_to_post.html

Возможно сам займусь на днях.

**Comment by vas3k** [comment]
Хороший баг. Но для реплаев не надо вообще выводить эту строчку :)
