### ISSUE TITLE
Предложение. Кнопка для прокрутки поста вверх. Кнопка лайк менее акцентная без ховера и двигается со скролом.

### ISSUE THREAD

**Issue by Gfirey** [vas3k/vas3k.club#32]
Иногда хочется почитать пост сначала. А сейчас ещё и лайк только на самом верху.
Пример как на хабре:
![image](https://user-images.githubusercontent.com/3421670/80480262-fba14900-8958-11ea-8c5e-fd1d868e1cc2.png)

По кнопке upvote если она будет на экране всегда, то вероятность нажать на неё выше :)
![Вастрик Клуб_ запускаем бету — Вастрик Клуб 🤘✖️👩_💻_ - Google Chrome 2020-04-28 14-13-35](https://user-images.githubusercontent.com/3421670/80481365-f47b3a80-895a-11ea-8683-46e14cda5096.gif)

**Comment by FMajesty** [comment]
Классная идея. На мобилках, наверное, можно, либо снизу в углу сделать фиксированно, либо еще одну кнопку в конце поста ¯\_(ツ)_/¯

**Comment by skywinder** [comment]
Тоже считаю, что для этого есть спец кнопки на клаве. Возможно такое можно будет вынести в настройки (когда-нибудь потом)

коли закрыли pr #32 с этой фичей, то и эту таску закрываю.

**Comment by moofkit** [comment]
@skywinder а что если кнопку `upvote` просто перенести вниз поста? я думаю немногие ставят :+1: не прочитав самого поста

как вариант можно тупо продублировать, одна кнопка сверху - вторая снизу)

**Comment by skywinder** [comment]
> @skywinder а что если кнопку `upvote` просто перенести вниз поста? я думаю немногие ставят :+1: не прочитав самого поста
> 
> как вариант можно тупо продублировать, одна кнопка сверху - вторая снизу)

Вариант с дублем внизу мне нравится Технически. Как это по дизайну будет смотреться вопрос. 

И это Скорее то на что сейчас обратит внимание vas3k :)

**Comment by moofkit** [comment]
> Вариант с дублем внизу мне нравится Технически. Как это по дизайну будет смотреться вопрос.

на небольших постах (меньше одного экрана) будет стремно конечно. но по идее с помощью css магии можно вычислить занимает ли пост больше одного экрана и если да, то показывать.
