### ISSUE TITLE
Фича: Дополнительный раздел, где можно сделать признание.

### ISSUE THREAD

**Issue by Yogendrovich** [vas3k/vas3k.club#322]
Конечно возможно, что это никому не нужно и даже идет против правил клуба, т.к мы любим анонимов и возможно уже кто-то предлагал, но я не нашёл. 

Идея в том, чтобы добавить дополнительный раздел, по аналогии с вопросами. Где можно признаваться в каких-то грехах, конфликтах на работе, проблемах, историях о том как потратил все бэкапы и бизнес рухнул, уволил человека просто так etc... В общем, если хочется выговориться, спросить у людей совета и перетереть за топики, в которых побоялся бы признаться. Разумеется автора поста и личностей комментаторов в этом разделе не видно. Мы ведь не идеальны и безгрешны, у каждого есть какие-то скелеты в шкафу и иногда мысли, которые не дают покоя.

**Comment by vas3k** [comment]
Идея-то ок, но можно использовать префикс, хештег или лейбл. Всё уже готово. Мы делали это уже с каминг-аутами, было збс

**Comment by Yogendrovich** [comment]
> Идея-то ок, но можно использовать префикс, хештег или лейбл. Всё уже готово. Мы делали это уже с каминг-аутами, было збс

Ну моя идея была в основном в анонимности, мало кто решится делать такие топики, когда в клубе уже тысячи человек. Т.е и в посте и в коментах не видно автора. Но что-то мне теперь эта идея не кажется такой уж хорошей.
