### ISSUE TITLE
Фича: личные закладки/избранные посты

### ISSUE THREAD

**Issue by jackyfox** [vas3k/vas3k.club#323]
Предлагаю добавить пользователю возможность сохранять понравившиеся посты в личные закладки (раздел профиля «Избранное»). 

Есть много годных постов про книги, полезные покупки и прочее, к которым хотелось бы возвращаться время от времени. Не хватает возможности собирать такие посты в свою личную копилку средствами сайта.

**Comment by jackyfox** [comment]
Прошу меня извинить за оригинальность идеи и отсутствие вменяемых предложений по реализации.
Понимаю, что умных дохуя, а референсы никто предлагать не хочет.

Вот я тут нарисовал и подписал самый минимальный функционал для внедрения закладок в Клуб с моей дегенеративной точки зрения. Извините.

![vas3k club bookmarks 01](https://user-images.githubusercontent.com/693161/89319462-cc515500-d688-11ea-924a-c52e0b61bc11.png)
![vas3k club bookmarks 02](https://user-images.githubusercontent.com/693161/89319466-cd828200-d688-11ea-8ddc-65082c849720.png)
![vas3k club bookmarks 03](https://user-images.githubusercontent.com/693161/89319463-cce9eb80-d688-11ea-84e9-ec5433a1e030.png)

**Comment by fr33mang** [comment]
> Вот я тут нарисовал и подписал самый минимальный функционал для внедрения закладок в Клуб с моей дегенеративной точки зрения. Извините.

А что с пагинацией? 
Либо как и с комментариями, покажем N последних. 
Для закладочек это будет не очень, кмк.

**Comment by jackyfox** [comment]
> А что с пагинацией?

Пагинацию с главной страницы можно использовать?
Только уменьшить количество карточек на странице до 10-15, чтобы не скроллить, как главную страницу 12 экранов :)

![image](https://user-images.githubusercontent.com/693161/89320352-0cfd9e00-d68a-11ea-852e-a616caf1e3c1.png)

**Comment by jackyfox** [comment]
Вариант кнопки добавления в закладки. «Спокойное», ховерное и активное состояние

![image](https://user-images.githubusercontent.com/693161/89322878-96fb3600-d68d-11ea-9457-90414182c1b2.png)

**Comment by jackyfox** [comment]
Уменьшаем вес кнопки закладок (для 1% аудитории © @vas3k), реорганизуем отображение меты поста

![image](https://user-images.githubusercontent.com/693161/89326874-b006e580-d693-11ea-898a-44239dc9717d.png)

**Comment by jackyfox** [comment]
Сохранил акцент на метку «Только для своих», заменил иконки на однотонные

![bookmarks](https://user-images.githubusercontent.com/693161/89329990-43dab080-d698-11ea-8ac4-1cb7e0267b9a.png)

**Comment by vas3k** [comment]
Обсудили в чате. Последний вариант нравится. Давайте попробуем запилить. Кто начнёт? :)

**Comment by fr33mang** [comment]
> Обсудили в чате. Последний вариант нравится. Давайте попробуем запилить. Кто начнёт? :)

Я готов попробовать :)

**Comment by vas3k** [comment]
@fr33mang давай

@jackyfox давай пока ещё подумаем где будет та кнопка, ведущая на страницу закладок. Заменять «плюсики» на неё как-то пока не хочется. Дофаминчик страдает!

**Comment by jackyfox** [comment]
Для работы над редизайном нарисовал в Фигме страницу поста. 
Два варианта. Отличаются длиной заголовка и статусом закладки

https://www.figma.com/file/RVwz0TLpIvRiSd4AgRMUeA/vas3k.bookmark

**Comment by jackyfox** [comment]
> где будет та кнопка

Мне самому не нравится, но пока отталкиваюсь функционала (группировка активных элементов). Подумаю еще.
Если есть идеи, пишите. Пойду пока на биханс, покопаюсь

![image](https://user-images.githubusercontent.com/693161/89337277-5a3a3980-d6a3-11ea-9818-206e4387653c.png)

**Comment by jackyfox** [comment]
Короче, чо я парюсь. Пять элементов же помещается. Верстка там свободная

![image](https://user-images.githubusercontent.com/693161/89339931-a2f3f180-d6a7-11ea-87c5-be84568e6301.png)

**Comment by jackyfox** [comment]
Если не трогать существующие элементы, и внести дополнительный блок перед интро

![vas3k-bookmarks](https://user-images.githubusercontent.com/693161/89391865-6d83ee00-d711-11ea-9da6-5b4f61afd274.png)

**Comment by fr33mang** [comment]
#### Вопрос всё еще открытый, в чате вроде как не приняли такой вариант

> Если не трогать существующие элементы, и внести дополнительный блок перед интро
> 
> ![vas3k-bookmarks](https://user-images.githubusercontent.com/693161/89391865-6d83ee00-d711-11ea-9da6-5b4f61afd274.png)


***

#### Есть еще проблема с шаблоном батла, который не похож на остальные :)
Нужно придумать, как кнопка будет выглядеть на нём.
![image](https://user-images.githubusercontent.com/13254668/89705508-a5d03a00-d966-11ea-87a7-fa8fc8a1104c.png)

**Comment by jackyfox** [comment]
> шаблоном батла

Вастрик доволен таким вариантом 

![image](https://user-images.githubusercontent.com/693161/89707267-4168a700-d975-11ea-8cfc-0c7ac58ed284.png)

Вывод меты для обычного поста также обновил. 

![image](https://user-images.githubusercontent.com/693161/89707306-812f8e80-d975-11ea-9aeb-82db19a1b928.png)

Макеты тут: https://www.figma.com/file/RVwz0TLpIvRiSd4AgRMUeA/vas3k.bookmark?node-id=0%3A1

С профилем пока не разобрались. Нужен штурм.

**Comment by vas3k** [comment]
Мне очень нравится. По поводу профиля, предлагаю разместить кнопку закладок прям в хедере между кнопкой «Пиши» и автаркой. Таким же серым флажочком должно быть ок

**Comment by jackyfox** [comment]
> разместить кнопку закладок прям в хедере

Вот так вот?

![image](https://user-images.githubusercontent.com/693161/89708850-56e4cd80-d983-11ea-8805-3d770b9de5e7.png)

**Comment by vas3k** [comment]
Ну это слишком. Убери обводку нахер и opacity 50%. Будет примерно то, что я имел в виду (очевидно, надо будет дорабатывать чтобы смотрелось гармонично)

**Comment by jackyfox** [comment]
@vas3k так? Ховер, соответственно, 100% opacity

![image](https://user-images.githubusercontent.com/693161/89717438-641fad80-d9bf-11ea-86fc-12afd2b3874e.png)

**Comment by vas3k** [comment]
Ага. Я бы поменьше сделал на треть, но отдам это решение тебе :)

**Comment by jackyfox** [comment]
> поменьше сделал. Поддерживаю. Так аккуратнее

![image](https://user-images.githubusercontent.com/693161/89717661-7864aa00-d9c1-11ea-92c9-b4b6e00ba95e.png)

**Comment by jackyfox** [comment]
На случай, если кто-то кликнет по этой кнопке до того, как сохранит что-то в закладки, нужно какое-то сообщение на странице закладок вывести:

«Тут будут храниться посты, которые вы добавите в закладки. Ищите специальную кнопку под заголовками постов»

**Comment by metya** [comment]
Хм. Фича уже есть, а ишью не закрыт. 
Тогда докину в ишью фиче реквест - хочется, чтобы добавлять в закладки можно было не только посты целиком, а отдельные комментарии. Потому что они часто именно то, что хочется запомнить. А не весь пост.

**Comment by vas3k** [comment]
Да, я тоже хотел бы избранное для комментов тоже. Давайте только заведём для этого отдельный ишью чтобы обсудить. Этот закрою как успешно сделанный 👍

**Comment by metya** [comment]
тока рилейтед сделайте сюда новый ишью.
