### ISSUE TITLE
Оптимизировать размер фронтенда

### ISSUE THREAD

**Issue by nikolay-govorov** [vas3k/vas3k.club#33]
Голая страница весит ~350KB (после gzip) — не успевает загрузиться в метро, пока стоим на станции. Можно ощутимо оптимизировать, если:

- Объединить и минифицировать CSS и JS;
- Выкинуть из шрифтов ненужные начертания и языки;
- Выкинуть костыли для старых браузеров из `normalize.css`;

**Comment by vas3k** [comment]
Да, я был бы рад, если бы кто-то занялся фронтендом по-науке

**Comment by Windrushfarer** [comment]
Это интересно. Посмотрю завтра вечерком

**Comment by vas3k** [comment]
Чтобы сделать по уму, надо явно в папку frontend тащить настоящий webpack и завязывать его с Джангой через тот же django-webpack-loader и пересобирать статику при релоаде сервера или типа того. Не совсем тривиальная задача. Потому я бы хотел чтобы кто-то из мира фронтенда сначала отписал как тут можно лучше всего сделать (SPA не предлагать, так любая обезьяна может).

**Comment by vas3k** [comment]
Ах да, плюс это все должно работать в докере (включая хот релоад) и не засирать временную директорию новыми файлами на каждый чих (а это поведение по умолчанию)

**Comment by nikolay-govorov** [comment]
Я бы предложил не строить космолёт с `webpack`+`webpack-dev-server` а начать с небольшого `gulp/webpack`-конфига с watch таской.

Вполне возможно что для `не-spa` этого хватит.

**Comment by vas3k** [comment]
Я примерно так это и представлял. Только вопрос как это все гонять в девелоперском докере теперь. Не заставлять же каждого запускать два терминала — с джангой и вебпаком

**Comment by vas3k** [comment]
Я просто ничего не понимаю во фронтенде :(

**Comment by nikolay-govorov** [comment]
Я бы сказал что 2 консоли — это ок. В любом случае 2 процесса и логи у них отдельные. Так например предлагает [`django-webpack-loader`](https://github.com/owais/django-webpack-loader).

Но, если это прям безумно принципиально то, наверное, можно сделать общую команду где-нибудь на уровне в `make` или `docker-compose`. Хотя, не уверен что это удобно.

**Comment by Windrushfarer** [comment]
Для простоты можно поэкспериментировать еще c zero-config решениями, типа [Parcel](https://parceljs.org/)

**Comment by tyhonchik** [comment]
> Для простоты можно поэкспериментировать еще c zero-config решениями, типа [Parcel](https://parceljs.org/). Для задач таких простых задач они работают хорошо

плюсую
Вебпак для текущего фронта будет лишним, кмк. Вот если б спа, babel, ts, препроцессоры всякие + это было бы самоостоятельным приложением, то возможно.
Сейчас же папка frontend - это по сути просто папка с шаблонами страниц? Т.е. идет запрос на на сервак -> питон собирает данные из БД и обрачивает это все в html -> отдает пользаку готовую статику?
Если есть необходимость в том только, чтоб все сбандлить и минифицировать, то parcel - то, что нужно

**Comment by vas3k** [comment]
@tyhonchik 

> Вот если б спа, babel, ts, препроцессоры всякие + это было бы самоостоятельным приложением, то возможно

Препроцессоры для CSS и минификации шрифтов — это разве не оно? Как раз этот тикет починим :)

> Сейчас же папка frontend - это по сути просто папка с шаблонами страниц? Т.е. идет запрос на на сервак -> питон собирает данные из БД и обрачивает это все в html -> отдает пользаку готовую статику?

Да, сейчас это django-шаблоны. Я хочу добавить в них большей интерактивности, но не хочу превращать это все в жирный SPA, где даже хистори приходится изобретать.


Parcel уже смотрю, спасибо!

**Comment by Windrushfarer** [comment]
Кстати и Parcel и Webpack по умолчанию упаковывают все импорты через свои специальные require и выдают изолированный модуль. В результате ты не сможешь ничего оставлять в глобале (читай `window`) неявно, т.е прямо не указывая `window.ajaxify = ajaxify`. Сейчас например прописать функции в `main.js`, то можно спокойно использовать в шаблонах навешивая через всякие `onclick` и пр.

**Comment by nikolay-govorov** [comment]
Parcel is great, but I would still look towards webpack. There is now also some zero-config, but it is larger, more ecosystem and it works much better with multiple entry points.

I'm afraid if you choose parcel you will have to migrate soon enough.

**Comment by nikolay-govorov** [comment]
@vas3k, тебе нужна какая-то помощь?

**Comment by tyhonchik** [comment]
Короче, что скажу: все как обычно зависит от цели. Если цель - закрыть эту таску, то наверняка питон-webpack плагин это сделает. А если хочешь, чтоб фронт вастрик клуба был максимально динамичным и независимым от  фулстак питон девелоперов, то надо разделять эти яйца по разным корзинкам.

Это к тому, что фронтов много, но из-за завязки на питон, много хороших фронтовых решений будет отваливаться. Питонистам фронт вряд ли очень интересен, чтоб его улучшать.
В общем, "Нихуя я умный"(с)

**Comment by vas3k** [comment]
Цель — сделать заебись структуру чтобы будущие фронтендеры не заговнякали ее костылями на прототипах. Для этого, видимо, придется задать ее самому. Скоро пришлю PR.

**Comment by Windrushfarer** [comment]
Тут на само деле нормально рак работы, если хочется сделать красиво. Я у себя в форке сделал сборку, но думаю над тем как оптимизировать шрифты и css, включая для font-awesome, т.к используется всего ничего иконок. Может svg даже будет лучше.

**Comment by vas3k** [comment]
Запилил PR #82 с вебпаком. Давайте теперь его улучшать. Минификация CSS — done.

**Comment by nikolay-govorov** [comment]
Круто! Ты проделал большую работу, получилось здорово.

Я бы прислал PR с небольшими доработками, если ты не против.
