### ISSUE TITLE
Фича: избранное

### ISSUE THREAD

**Issue by neonick** [vas3k/vas3k.club#334]
Хочу собрать коллекцию самых крутых постов, чтобы знать где советовали про туристическую снарягу или про специи.

**Comment by vas3k** [comment]
<img width="530" alt="Screenshot 2020-08-03 at 18 14 26" src="https://user-images.githubusercontent.com/176344/89203633-2e408a80-d5b5-11ea-8e39-a9fb39b91b06.png">

**Comment by neonick** [comment]
Сорри, забыл поискать тут, а в трелло не увидел :(
