### ISSUE TITLE
Починить загрузку анимаций в постах

### ISSUE THREAD

**Issue by hgenru** [vas3k/vas3k.club#339]
В чатике @vas3k упомянул, что загрузка гифок видяшками должна работать, но она не работает. Я попытался пофиксить это, но не разобрался как тестировать загрузку картинок в локальной инсталляции.

При этом если залить видяшки на свой CDN, то их можно будет вставить как обычную картинку.

# Что может мешать загрузке видосов
В фронтовых скриптах используется модуль InlineAttachment, который по дефолту кушает только [["image/jpeg", "image/png", "image/jpg", "image/gif"]](https://github.com/vas3k/vas3k.club/blob/master/frontend/static/js/inline-attachment.js#L141).
**Как чинить: расширить список дозволенных типов если плагин это позволяет**

При этом судя по [этим строчкам](https://github.com/vas3k/vas3k.club/blob/master/frontend/static/js/App.js#L26) на фронте происходит принудительная конвертация картинок в jpeg. Т.е. gif-картинка загружается, но если по ней кликнуть в отрендеренном посте, то откроется просмотр в лайтбоксе и после этого картинка будет статичной.
**Как чинить: отключить принудительную конвертацию картинок в жпег**

# О чём стоит договориться
* Будем ли мы давать людям загружать gif картинки. Какого максимального размера они должны быть?
* Какой установить максимальный размер для mp4/mov клипов?
* Будем ли мы сохранять видяшку полностью на сервере клуба перед отправкой на CDN?

Я готов впрячься и починить эту штуку, но если тут есть более маститые и сообразительные питонисты, то можно отдать эту таску им на растерзание, потому что фронтовой работы там совсем немного.

UPD: Оказалось, что питоновский код, который я нашёл не участвует в загрузке файлов — они грузятся напрямую на файловый сервер. Все файловые лимиты тоже разруливаются этим сервером.

**Comment by vas3k** [comment]
Думаю будет достаточно лишь добавить новые mime-типы в inlineAttachment. Прокси поддерживает видосы из коробки, я их не отключал. Можешь попробовать прислать PR с новыми типами и проверим. Думаю, mov и mp4 будет достаточно.

**Comment by hgenru** [comment]
А, я только щас втупил, что этот питоновский код не участвует в загрузке.

В общем я добавил нужные типы и научился локально тестировать. Но сервер загрузки падает с 500 при загрузке видеофайлов. Причём как для mov, так и для mp4. По времени видно, что загрузка идёт, но, видимо, где-то в конце что-то не клеется. В сообщении об ошибке пустой объект.

Пробовал как с отключёнными так и со включёнными опциями конвертации и сжатия жпегного.

![image](https://user-images.githubusercontent.com/2411525/89450672-8ddc9880-d763-11ea-8c0a-6c33481bc6b3.png)

**Comment by vas3k** [comment]
Понял, ща проверю

**Comment by vas3k** [comment]
И правда был косяк. Починил. Вот видос для теста: https://i.vas3k.club/71944d7430c461f0cd6e7fd10cee7eb72786352a3678fc7bc0ae3d410f72aece.mp4

Маркдаун на сайте должен жрать их так же как картинки.

**Comment by hgenru** [comment]
Проверил, всё работает

**Comment by vas3k** [comment]
Отлично!
