### ISSUE TITLE
Полоска в профиле «ваши увлечения схожи на 90%»

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#341]
А что если анализировать какие теги в профиле накликал человек, сравнивать их с моими и выводить некую полоску насколько вы похожи? Хммм.

Вопрос как сравнивать. По какой формуле? Учитывать ли false negatives и всякое такое?

Можно обсудить

**Comment by fr33mang** [comment]
Идея интересная, имеешь в виду, нужно ли минусовать результат, если допустим у меня "жаворонок", а у него "сова"?
Тогда придется городить дополнительный сущности, определяющие взаимоисключающие тэги, звучит как оверхэд :)

Есть еще предложение выводить где-то список одинаковых тэгов у вас двоих, помимо, либо вместе с предложенной тобой полоской :))

**Comment by vas3k** [comment]
@fr33mang  да, взаимоисключающие сущности городить не будем, это оверкилл. Вопрос в том как считать «похожесть» — по количеству общих тегов относительно всего их количества? По пропорции похожих vs отличающихся тегов? Как-то еще хитро? Сейчас даже в голову не приходит никакой формулы, которую можно было бы сюда подогнать :)

**Comment by fr33mang** [comment]
Конкретных предложений по формуле рассчета предложить не могу, но возможно, стоит попробовать закодить несколько вариантов рассчета, и выбрать понравившийся :)

**Comment by Takheer** [comment]
Делал подобный функционал для одного проекта. Там была похожая идея с интро и тегами у людей, и мы придумали две метрики. 
Первая — просто пересечение множества тегов. Можно нормировать на количество тегов: пара людей, у которых всего два тега в профиле и оба совпали, по-любому больше сходятся, чем люди, у которых 20 тегов и только 3 общих. 
Вторая — считаем близость интро. Просто через TF-IDF делаем вектора из слов интро, считаем релевантность двух по косинусному расстоянию. TF-IDF сразу решает проблему стоп-слов и вообще достаточно прост для понимания. Работало вообще заебись, но только на демо, как это присрать к продакшену и как быть с необходимостью хранить и актуализировать весь корпус текстов интро мы как-то не придумали.

**Comment by kadron141** [comment]
Что если просто подсвечивать теги, совпадающие с твоими, когда заходишь в чужой профиль? Оч дешёвое решение же

**Comment by skywinder** [comment]
@kadron141 клевая идея, предожи интерфейс и давай обсудим!

**Comment by devcooch** [comment]
Попробую что-то сделать с этим.
