### ISSUE TITLE
Баг: Лишний символ в профиле пользователя в разделе "Для других членов Клуба я..."

### ISSUE THREAD

**Issue by ivannikovdv** [vas3k/vas3k.club#344]
Лишний символ в _Профиле_ в разделе **Для других членов Клуба я...**

Помоему, когда я нажимал на редактирование своего профиля была такая же бага, квадратики, которые я убрал удалением и больше они не появлялись (после сохранения профиля). 
В моем профиле так же, каждое предложение начинается с иконки.

Видим квадрат перед Иконкой...

![telegram-cloud-photo-size-2-5292144847299391420-x](https://user-images.githubusercontent.com/69361612/89672085-d4113380-d8ec-11ea-8ac0-bc2bd9b8a9fc.jpg)

**Comment by neonick** [comment]
@ivannikovdv еще воспроизводится? Кажется после [вот этого](https://github.com/vas3k/vas3k.club/commit/4dbe5e9d3987d9c2c44a785a0e6fec84c2492ea1#diff-53e64c36ef424524da7dba78a98fb16aR133) должно было уйти, я по крайней мере не могу воспроизвести никак. Если всё еще да — опиши окружение.

**Comment by Eatric** [comment]
![image](https://user-images.githubusercontent.com/16813968/126030717-cff4bcd1-2701-4769-834d-a7c1d3a3daaa.png)

Предлагаю закрыть, кажется не актуальным, не воспроизводится
