### ISSUE TITLE
Баг: При попытке добавления экспертизы в Профиль ошибка Server Error (500)

### ISSUE THREAD

**Issue by ivannikovdv** [vas3k/vas3k.club#345]
https://vas3k.club/profile/expertise/add/

Это если попытаться добавить Экспертизу с таким же именем каким уже была добавленна, хотел для теста попробовать такую же добавить, но с другим уровнем экспертизы. Получил ошибку Server Error (500).

**Comment by vas3k** [comment]
Срабатывает duplicated key в БД. Нужно ловить эксепшен. Оставлю для новичков
