### ISSUE TITLE
Фича: Возможность Фолловить пользователя и мониторить изменения его профиля и не только

### ISSUE THREAD

**Issue by ivannikovdv** [vas3k/vas3k.club#347]
Возможность Фолловить пользователя и изменения его профиля и не только (новые комменты, новые посты, новые проекты и прочее) с выбором того что хотелось бы мониторить. В плоть до изменнеия уровня экспертизы или добавления нового увлечения.

Для нуждающихся эту опцию опционально можно отключить чтобы было в своем профиле, чтобы не могли тебя фоловить, или фоловить только опредленные действия.

**Comment by vas3k** [comment]
Пока не планируется, но спасибо за идею
