### ISSUE TITLE
Баг: В разделе сайта Люди (карта) плохо работает фильтр ("хватает" другие города) при запросе

### ISSUE THREAD

**Issue by ivannikovdv** [vas3k/vas3k.club#349]
По запросу Воронеж, выскакивают 6 человек с Москвы, хотя я проверил, у всех "лишних" профилей указано Москва. (скрин 1)

https://vas3k.club/people/?query=Воронеж

В итоге из 28 найденных пользователей, критерию соотвествуют 22 (Воронеж) из 6 (Москва)

Зато если вверху нажать **В том же городе** и нажать внизу **Отфильтровать**, то фильтр работает исправно. Даже если в строке поиска указан так же Воронеж как в первом случае (скрин 2).

https://vas3k.club/people/?query=Воронеж&country=&filters=same_city

**Скрин 1**

![image](https://user-images.githubusercontent.com/69361612/89679879-9adfc000-d8fa-11ea-9ac7-e9ee82839d18.png)

**Скрин 2**

![image](https://user-images.githubusercontent.com/69361612/89680552-d4fd9180-d8fb-11ea-9d7b-3b3547b041e7.png)

**Comment by vas3k** [comment]
Не баг. Матчитася любое совпадение города с целью найти, например, людей, понаехавших из одного города
