### ISSUE TITLE
Фича: Митапы

### ISSUE THREAD

**Issue by Vollmond** [vas3k/vas3k.club#357]
**Саммари**
Смотря на раздел комьюнити и недавние митапы мне кажется клубу очень не помешает фейсбуковские встречи на минималках. В сущности это может быть просто отдельная категория постов только с дейтпикером и городом.

**Нафига?**
Допустим человек хочет собрать людей из клуба на Вастрик.Митап или просто попить пивка. Сейчас для этого 2 пути:
- [Большой пухлый пост](https://vas3k.club/post/3548/)
- Сходить в чатики или постучаться в лички.

Писать пост для это перебор и неудобно, залетать в локальные чаты (а они к тому же есть не везде) - тоже. Так, недавние митапы на Кипре и в Берлине пролетают мимо людей которые читают только клуб. 

**Как?**
Желающий собрать сходку делает пост, типа: "Пойдемте совместно читать книжки", тыкает город и тыкает возможные даты. Потом другие участники тыкают в даты которые им подходят, в комментах или в личках уже договариваются о деталях, профит.

**А не оверкилл?**
Для совсем локальных сходок на 3 человека в городе - оверкилл. Где это может сработать это на более крупных митапах (типа трех недавних) и междугородних/международных запросах типа "Ребят, я буду в городе N в таких то числах, пойдемте гулять/покажите город/etc". Возможно эти штуки стоит отфильтровывать из основного фида.

**Comment by vas3k** [comment]
Идея крутая, мне нравится. Давайте обсуждать. У кого есть виденье как это можно сделать — накидывайте эскизы и предложения сюда в тред

**Comment by vas3k** [comment]
Сделали ивенты: https://vas3k.club/event/
Как MVP сойдет. Если у кого-то появятся новые идеи — поднимайте тикет заново или создавайте новый.
