### ISSUE TITLE
Кнопка «Удалить профиль»

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#36]
Проставлять флаг is_deleted, переименовывать юзера в DELETED, удалять всю информацию пользователя, но оставлять все его посты и комменты на сайте. Короче, полностью анонимизировать юзера.

Отдельно надо продумать защиту от «случайных» удалений. Потому что как только мы сделаем эту кнопку, обязательно появятся те, кто случайно на нее нажмет :D

Я бы редиректил на специальную страницу, где бы заставлял пользователя ввести свой ник в качестве подтверждения. Как это сделано на гитхабе когда удаляешь или копируешь репозиторий.

**Comment by altmind** [comment]
sorry. im just gonna leave this is HARD.  godpeed.
foreign keys wont help here. but maybe its not that hard(??)
it needs triage :)

**Comment by altmind** [comment]
Надо ли продумать возможность восстановления удаленного юзера, особенно если он пришел с патреона с теми-же membership_platform_id?

**Comment by vas3k** [comment]
Думаю, пока достаточно будет показывать ему экран «обратись в саппорт». Не хочу делать эту функцию автоматической, иначе ее начнуть абьюзить для обхода банов, например (забанили — удалил акк — зашел заново — разбанился). Ну и другие места.

Вообще, пока не бери этот тикет. Мы его все активно обсуждаем внутри и наверное я его сам запилю.

**Comment by nikbrain** [comment]
А что если сделать удаление более мягким? Например, пользователь нажал удалить, его посты и комменты анонимируются, как указано тобой, а акк попадает в очередь на удаление, скажем через 30 дней его персональные данные точно удалятся. В таком случае у пользователя будет "окно" на передумать и случайность)

**Comment by skywinder** [comment]
@vas3k полагаю mission complete? :)
