### ISSUE TITLE
Баг: не работают ссылки отписки из email-дайджеста

### ISSUE THREAD

**Issue by nitso** [vas3k/vas3k.club#360]
В футере email-дайджеста присутствуют ссылки на "отписаться" и "переключиться на ежедневный/еженедельный" вида:

    https://vas3k.club/notifications/switch/{type}/{uuid}/{key}/

Они не работают ни для авторизованного, ни для анонимного пользователя, ведут в 404

**Comment by vas3k** [comment]
Спасибо, что обратил внимание. Такие баги всегда неприятны. Теперь ссылки должны заработать.
