### ISSUE TITLE
Фича: Вастрик.Бокс - обмен ништяками среди трактористов и не только

### ISSUE THREAD

**Issue by Xamber** [vas3k/vas3k.club#361]
**Что это?**
Учитывая что многие уже добавили свою страну и имя, довольно легко будет, как мне кажется, реализовать платформу, в которой ребята из разных стран состовляют свои "Вастрик.Боксы" и обмениваются с такими же ребятами. 
Как некий тайный санта только работает всегда. 

**Зачем?**
Обмен полезными предметами и сувенирами :gift: 

**Как работает?**
Пользователь выкладывает в спец разделе что он может собрать, кидает фотку. 
Затем люди смотрят и такие "Я это хочу!". Тыкают на кнопку "Я это хочу" и чуваку приходит некий комент мол отылай давай.
Пользователь идет на почту, стоит очередь. Думает ну нафига я на это подписался вообще.
Зато потом на одного человека в другой стране станет больше :+1: 

**Какие проблемы ?**
Налоги в разным странах на посылки.
Лень отправителя.

**Как можно сделать сейчас?**
Пост с диким количеством коментов.

**Comment by vas3k** [comment]
Интересная идея, но я бы начал с чего-нибудь попроще. Secret Santa, например, как на реддите. Тут нужен кто-то, кто сможет всё это продумать, организовать и поддерживать. Технических сложностей здесь особо не вижу, для обмена адресами можно взять один из готовых веб-сервисов или написать свой. Отдельным разделом Клуба я это не вижу.
