### ISSUE TITLE
Использовать счётчик символов из intro в постах тоже

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#364]
Благодаря отличному PR https://github.com/vas3k/vas3k.club/pull/329 у нас есть Vue-компонент [InputLengthCounter](https://github.com/vas3k/vas3k.club/blob/master/frontend/static/js/components/InputLengthCounter.vue), который красиво считает символы в [форме под intro](https://github.com/vas3k/vas3k.club/blob/master/frontend/html/users/intro.html#L158).

Хотелось бы теперь иметь такой же в формах некоторых постов. Например для проектов и ссылок. Там существуют органичения на минимальную длину, потому хотелось бы это как-то явно показывать.

Вот тут: https://github.com/vas3k/vas3k.club/blob/master/frontend/html/posts/compose/project.html#L63

Проблема в том, что компонент работает с голой texarea, а при написании постов используется редактор EasyMDE (внутри использует Codemirror), который не шлёт нужных ивентов onchange (хотя и обновляет как-то текстарею). Нужна помощь фронтенд-богов чтобы решить данную задачу :(

**Comment by dimabory** [comment]
@vas3k Могу взять это на себя.

**Comment by vas3k** [comment]
@dimabory давай, было бы круто!

**Comment by dimabory** [comment]
@vas3k Ты сказал, что там существуют ограничения на минимальную длину, но это ограничение только для проектов https://github.com/vas3k/vas3k.club/blob/638a44957fc9ae86b2eaeff3b4e91e7b0fcf44e9/posts/forms/compose.py#L221-L225

Для ссылок есть только `maxlength` условие https://github.com/vas3k/vas3k.club/blob/638a44957fc9ae86b2eaeff3b4e91e7b0fcf44e9/posts/forms/compose.py#L86-L89
