### ISSUE TITLE
Название поста в виджете комментария 

### ISSUE THREAD

**Issue by OlegWock** [vas3k/vas3k.club#367]
Речь про компоненты которые используются на страницах с не-постами. Вот например в профайле это выглядит вот так
![image](https://user-images.githubusercontent.com/7430438/90984807-2ce4fb00-e580-11ea-8c9d-538bf4b4acfb.png)

Я думаю, что было бы неплохо выводить и название поста тоже, потому что часто без этого коммент становится почти бесполезным для того кто его читает на странице профиля. Я предлагаю что-то такое запилить, например:
![image](https://user-images.githubusercontent.com/7430438/90984993-72ee8e80-e581-11ea-9e39-d370f30b7a47.png)

Опционально можно еще по клику на название поста открывать пост, а не сам коммент.

Или даже вот так, все равно это на странице профиля и юзер уже успел прочитать и понять что Вастрик у нас "Блогер, питонист, мизантроп" 
![image](https://user-images.githubusercontent.com/7430438/90985081-19d32a80-e582-11ea-8bbc-4f664b4c79d4.png)

Я не смог найти других мест где этот компонент использовался бы (ну кроме постов конечно), так что не уверен насколько хорошая идея адаптировать второй вариант, Но первый, как мне кажется, вполне себе ничего

**Comment by vas3k** [comment]
Последний вариант ничо. Я бы посмотрел для референсов как это делают другие проекты тоже и как-то коллективно выбрал бы тут идеальный для всех UI

**Comment by fr33mang** [comment]
Сделаю со вторым вариантом шаблона :)
Если никто не предложит ничего лучше, можно будет вкатить и так

**Comment by skywinder** [comment]
Поддерживаю идею в целом и предложенный последним вариант

**Comment by skywinder** [comment]
Related to #335

**Comment by fr33mang** [comment]
https://github.com/vas3k/vas3k.club/pull/385#issuecomment-706774927

Давайте обсудим здесь дополнительно вот ето предложение по дизайну :)
Мне нравится второй предложенный вариант, с исправлением, которое предложил @skywinder (поменять местами время и название поста)

**Comment by devcooch** [comment]
В целом согласен, надо посмотреть насколько это в других местах повлияет на внешний вид (где комментарии появляются без поста).
Поиск, профиль пользователя. Ещё где-то?

**Comment by fr33mang** [comment]
![image](https://user-images.githubusercontent.com/13254668/96299996-89531c80-0ffd-11eb-984c-420568fff0e6.png)

Иногда названия постов бывают достаточно большими. 

Что предлагается в этом случае делать, обрезать название?
