### ISSUE TITLE
Апвоуты [+1] у комментов выглядят как говно

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#368]
Хочется причесать их получше, но не превращать в типичные прыгающие ЛОЙСЫ с огромными кнопками. Когда комментарий большой — эта маленькая циферка становится почти не заметна. Кажется, из-за этого люди реже лайкают другие комменты (возможно это мое личное заблуждение)

Может их хотя бы выделить цветом? Сделать жирнее плюсик? Что думаете?

**Comment by skywinder** [comment]
Не замечал этой проблемы в своем UX.

Да и даже если первый раз видишь: не у этого длинного комментария, так у следующего увидишь внопку, и методом дедукции можно догадаться что и у этого комента тоже есть эта кнопка.

**Comment by kadron141** [comment]
Может просто сделать рамку как у апвоту в посте? Будет больше выделяться
![image](https://user-images.githubusercontent.com/32163086/94176536-eb0de400-fea0-11ea-99dd-dee0cabd9bef.png)
