### ISSUE TITLE
Не-моноширинный шрифту Ubuntu в стилях у code-блоков

### ISSUE THREAD

**Issue by ewgenius** [vas3k/vas3k.club#370]
Пример - https://vas3k.club/question/4619/#comment-4adaa703-8a5f-4e80-bf43-9ed186880402

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/827338/91106424-74729200-e627-11ea-9ea7-e1d45b46f649.png">

**Comment by jackyfox** [comment]
А что если добавить Ubuntu Mono в список шрифтов? Одно начертание весит ~200 килобайт

**Comment by ewgenius** [comment]
> А что если добавить Ubuntu Mono в список шрифтов? Одно начертание весит ~200 килобайт

А в чем профит? Его придется дополнительно подгружать, так как он установлен под дефолту только на Ubuntu, проще и экономнее использовать один monospace который должен работать везде.

Фонтсет из #369 `SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace;` - это все системные шрифты, один из них так или иначе подтянется на подходящей системе

**Comment by skywinder** [comment]
Закрываю, тк решили отказать от сторонних шрифтов ( #369)
