### ISSUE TITLE
Фича: просмотр всех комментов в профиле, а не только последних трех 

### ISSUE THREAD

**Issue by vlaim** [vas3k/vas3k.club#373]
Сейчас никак не найти свой старый комментарий из профиля :)

**Comment by pankova** [comment]
> Сейчас никак не найти свой старый комментарий из профиля :)

Кажется, дубликат https://github.com/vas3k/vas3k.club/issues/198)

**Comment by vlaim** [comment]
@pankova Спасибо, проглядел. Закрываю :)
