### ISSUE TITLE
Изменить обработчик (Cmd)Ctrl+K hotkey в поле ввода текста

### ISSUE THREAD

**Issue by jackyfox** [vas3k/vas3k.club#374]
Возможно ли перенастроить обработчик горячих клавиш при написании постов и комментариев?

Заметил возможность улучшить юзабилити при вводе ссылок. Меня смущает текущее действие сочетания (Cmd)Ctrl+K. Сейчас при использовании этого сочетания клавиш на выделенном кусочке текста, выделение остается на анкорной части. И в этом нет никакой практической пользы. 

Удобнее будет автоматически перемещать выделение на "https:\\"

Вот два сценария:

- Если у меня уже есть ссылка в буфере обмена, я просто нажимаю (Cmd)Crtl+V
- Если хочу ввести ссылку руками, нажимаю стрелку вправо.

Сейчас в обоих этих случаях нужно прожать дополнительные кнопки, чтобы продолжить ввод.

![image](https://user-images.githubusercontent.com/693161/91212184-8aac4b00-e718-11ea-9d88-46d33e7b823e.png)

**Comment by jackyfox** [comment]
Если это можно сделать, но всем лень, покажите направление, куда копать. Я попробую сам сделать :)

**Comment by skywinder** [comment]
выглядит удобно.

@vas3k что думаешь? если получится сделать такое легким фиксом, даешь апрув попробовать @jackyfox ?

**Comment by jackyfox** [comment]
Нашел [аналогичный запрос](https://github.com/Ionaru/easy-markdown-editor/issues/85) в репозитории EasyMDE от мая прошлого года. Чуваку так никто и не ответил(( Я так понимаю, что надо бранч будет создавать, что может затруднить обновление Клуба. Так что, наверное отмена.
