### ISSUE TITLE
Варианты оплаты сбивают с толку

### ISSUE THREAD

**Issue by ReDetection** [vas3k/vas3k.club#383]
Йо. Я тут чувака к в клуб зазвал, и пока я с ним болтал, мы выяснили, почему все вокруг считают, что проходка в клуб стоит 15 евро, а не доллар. Потому что кнопка "вступить в клуб" показывает только этот вариант. Вот картинка для понимания:
<img width="1552" alt="Screenshot 2020-08-30 at 11 36 26" src="https://user-images.githubusercontent.com/458005/91651369-2c83bd00-eab6-11ea-8cd0-67e5e7d745a2.png">
Имхо надо просто продублировать кнопку патреона и прямо там и написать "доллар в месяц"
<img width="1552" alt="Screenshot 2020-08-30 at 11 37 47" src="https://user-images.githubusercontent.com/458005/91651378-40c7ba00-eab6-11ea-98cf-2ab09f420008.png">

**Comment by vas3k** [comment]
Патреон был объявлен deprecated, регистрация отныне доступна только так. Первые результаты пока неплохие, количество рег не уменьшилось, а качество профилей сильно возросло. Вход через патреон останется, да.

**Comment by vas3k** [comment]
Но спасибо за инсайд, если у кого-то есть идеи как это улучшить — переоткройте тикет с макетом
