### ISSUE TITLE
Фича: Кнопка для скролла вверх

### ISSUE THREAD

**Issue by wtfua92** [vas3k/vas3k.club#386]
**Проблема:** Сегодня читал какой-то топик на телефоне, и когда дошел до последнего комментария, решил вернуться вверх, чтобы уточнить некоторые моменты в оригинальном посте. В итоге пришлось много-много скролить вверх.

**Решение:** добавить (как минимум для мобилок) фиксированную кнопку в виде стрелочки вверх, чтобы можно было быстро вернуться к заглавному сообщению топика.

**Comment by wtfua92** [comment]
В принципе, могу сам же этим и заняться, если коммьюнити посчитает такую кнопку нужной :)

**Comment by vas3k** [comment]
Поднимали тему несколько раз: https://github.com/vas3k/vas3k.club/issues?q=%D0%BD%D0%B0%D0%B2%D0%B5%D1%80%D1%85

Никто не смог предложить UI, который был бы ненавязчивым. Сможешь такой нарисовать — приноси картинку

**Comment by wtfua92** [comment]
Я не особо могу в рисование, но в моей голове я вижу это как-то так - [смотреть тут](https://youtu.be/kNdh0m5Mraw?t=24). Обрати внимание на футер. Когда юзер начинает скролить вверх, кнопка появляется и помогает ему подняться до самого верха. Можно сделать отдельную небольшую кнопку, можно, чтобы была небольшая плашка на ширину экран. Вариант с небольшой кнопкой можно сделать и на мобильном, и на десктопе, плашка - все же решение для телефонов. Тем не менее, таким образом кнопка будет появляться только в нужный момент и пропадать при большинстве других стандартных действий.

**Comment by skywinder** [comment]
Обсуждали на гитхабе вот здесь: #136
предложили решение здесь: #32
Батл на эту тему в клубе здесь: https://vas3k.club/battle/3857/

TLDR: 
> Никто так не убедил @vas3k что плавающий по странице мусор удобнее кнопки PgUp. Всё еще жду.

Закрою как дубликат.
