### ISSUE TITLE
Разный UX ответов на комментарий в desktop и mobile

### ISSUE THREAD

**Issue by VBodrov** [vas3k/vas3k.club#388]
Когда отвечаешь на комментарий в mobile или через бота автоматически добавляется @ с ником. Но когда отвечаешь в desktop  версии, этого не происходит.

В результате уведомление о новом комментарии приходит автору первого комментария, но не попадает в пынь тому, кому хотелось ответить в ветке.

А копировать ник из линка на профиль не удобно. В UI отдельно ник  написан только в ответах к комментарию.

**Comment by vas3k** [comment]
Согласен, я тоже страдаю. Там была какая-то хитрая логика типа не добавлять меншен если отвечают автору треда, но предлагаю на неё забить и добавлять всегда

**Comment by vas3k** [comment]
Пофикшено, был баг

**Comment by VBodrov** [comment]
Теперь когда отвечаешь из мобильного интерфейса не добавляется пынь. 😐
