### ISSUE TITLE
Баг: Возможны CORS запросы на старых браузерах

### ISSUE THREAD

**Issue by LionZXY** [vas3k/vas3k.club#389]
На старых браузерах, отсутствие правил CORS позволяло делать запросы с других страниц. Таким образом, скрипт вида:
```
<script>
var xhr = new XMLHttpRequest();
var url = "https://vas3k.club/post/koteeq/upvote/?is_ajax=true";
xhr.open("POST", url, true);
xhr.send("");
</script>
```

Мог накрутить лайки или что похуже, используя авторизованную куку вастрика.
Сейчас такое невозможно, однако считаю правильным выставлять CORS правила, используя заголовки.
Например, так: https://github.com/zestedesavoir/django-cors-middleware

Нашла @aprosvetova

**Comment by LionZXY** [comment]
https://www.chromium.org/updates/same-site

**Comment by vas3k** [comment]
Хорошая находка, согласен. Пока не сильно критичная, но с ростом аудитории и ценности лайков может всплыть. Для логаута мы уже сделали защиту CSRF (хотя я не уверен, что токен и правда проверяется, хех), для остальных можно тоже плавно вводить. Только давайте не переусложнять компоненты апвойта сильно ради этого. KISS.

**Comment by zyuhel** [comment]
Вроде как это исправили в #423

**Comment by vas3k** [comment]
Надо проверить и закрыть тогда уж

**Comment by skywinder** [comment]
да, походу @zyuhel прав `Access-Control-Allow-*:` хэдер должен решать эту проблему. 
раз CSRF уже сделан, то можно закрывать!
