### ISSUE TITLE
Навигация по новым комментария

### ISSUE THREAD

**Issue by dimabory** [vas3k/vas3k.club#390]
Часто возвращаясь на какой-нибудь пост хочется быстро пройтись по свежим комментариям или/и реплаям. Для этого иногда приходится очень долго скроллить вниз и всматриваться в подсвеченные блоки.
На данный момент вижу простое, безболезненное и быстрое решение - это использовать какой-либо shortcut (например Ctrl+↓).

PS: 🖱️ если что, то могу сам взяться за реализацию.

**Comment by vas3k** [comment]
Я бы начал с UI

**Comment by dmitvitalii** [comment]
Связано с https://github.com/vas3k/vas3k.club/issues/491 и https://github.com/vas3k/vas3k.club/issues/662, решения из #662 не будет достаточно?

**Comment by vas3k** [comment]
Решение из #662 это временный фикс, о нем никто не знает и никогда не узнает, у него даже UI нет. Я бы оставил тикет #491, так как в нем больше всего обсудили, а остальные закрыл
