### ISSUE TITLE
Комментарии с временем жизни

### ISSUE THREAD

**Issue by dimabory** [vas3k/vas3k.club#391]
Идея от [@BonSens](https://vas3k.club/user/BonSens/)

https://vas3k.club/post/4903/#comment-26cc690c-5f58-445d-a7bf-aba5ac855c5a

> Крутые посты, но жаль, что они очень быстро наполняются "мертвыми" комментами. В которых халява прошла, всё раздали, промокоды не работают.
В таких постах не хватает комментов, которые исчезают со временем. Написал про игрушку, которая будет бесплатной до 5 ноября, поставил, чтобы коммент испарился 5 ноября. Так бы в посте постоянно был свежачок.

**Comment by vas3k** [comment]
Оставлю для обсуждения, но лично я практического смысла делать из этого фичу не вижу. Всегда можно просто написать время окончания раздачи прямо в комменте или реплай, что промокоды закончились.

**Comment by skywinder** [comment]
Имхо слишком частный юзкейз, что бы вносить в движок. 

Для этого то этого есть воркэраунд: свой комент можно всегда придти и удалить ручками. 
И автор топика может тоже удалять неугодные (просроченные) комментраии.

Ps: судя по голосованию выше большинство поддерживает￼. Так что предлагаю закрыть топик. ￼
