### ISSUE TITLE
Логин через Patreon

### ISSUE THREAD

**Issue by jacki0** [vas3k/vas3k.club#392]
Если профакапить наличие денег на карте и подписка на Patreon не продлится, а кол-во дней членства в клубе больше чем срок подписки, то нельзя залогиниться через Patreon пока не продлишь подписку.

Понятно, что мало воспроизводимая штука, но лучше знать об этом.

**Comment by vas3k** [comment]
Не понял баг. При входе на сайт через патреон он заново проверяет активность подписки. Если она есть — автоматически продлевает её до конца месяца +7 дней на всякие там банковские задержки. Ты перезаходил через патреон после продления подписки?

**Comment by jacki0** [comment]
Не уверен баг это или нет, но в первый месяц у меня оказалось ~40 дней членства. У меня для подписок отдельная карта, я не закинул вовремя денег на неё, а письма от patreon упали в спам и подписка закончилась. Но в клубе осталось ~10 дней. С браузеров где уже был логин доступ в клуб сохранился, но залогиниться через patreon из нового браузера уже не получалось.

**Comment by vas3k** [comment]
Всё так. Клуб как бы дарит эти дополнительные дни чтобы компенсировать задержки банковских транзакций. Но если транзакция провалилась, то давать войти на сайт больше не должно. То, что где-то остались ещё живые сессии это баг, да, но проще объявить его подарком и забить.
