### ISSUE TITLE
Фича: коллекционные теги в постах с возможность утащить их себе в профиль

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#393]
Человеки постоянно просят сделать тег «Сидр» или «Альпинизм», а мы отказываем, потому что тогда профили раздуются на десять экранов и никто не будет понимать что происходит. В связи с этим поступило интересное предложение: **разрешить юзерам создавать и продвигать свои кастомные теги.**

Суть(тм):

- Создать кастомный тег может автор любого нового поста. Например, я пишу пост про Бёрдвотчинг и прикрепляю к нему новый тег "Бёрдвитчинг", а заинтересованные читатели могут кликнуть и добавить его себе в профили, чтобы находить других бёрдвотчеров
- Любой юзер может добавить этот тег себе в профиль одним кликом. Нужно сделать понятный UX для этого (например такой же тег с кнопкой [+] справа)
- Подумать, может это реально заменит полоски "Экспертизы" в профиле. Они как-то не очень полезны
- Можно сделать уведомление по тегам. Если кто-то еще пишет пост про Бердвотчинг и прикрепляет тот же тег — всем подписавшимся приходит пуш в бота. Так можно собирать мини-коммьюнити по темам внутри

<img width="873" alt="Screen 2021-10-03 at 15 39 01" src="https://user-images.githubusercontent.com/176344/135756055-1849577b-9f86-49d5-809d-fae63ddf92a3.png">

**Comment by skywinder** [comment]
продублирую [мысль из чата](https://t.me/vas3k_club_dev/1971)

>Пока только идея перенять лучшее от других. 
Например Stackoverflow, добавлять тэги могут люди и репутацией больше Х. В нашем случае это могут быть плюсики. 
Ну что-то мне подсказывает что это не очень хорошо сработает в нашем случае. 
Другой вариант, Полу-автоматический но простой: сделать отдельный пост, куда можно предлагать варианты тегов. 
Если какой-то вариант набирает больше, например 10 плюсиков-коментов, то его добавляем. И проводить ревизию раз в месяц.


1. Тег после >ХХХ плюсиков - считаю крутая идея и здравая идея (аля стековерфлоу)

Тут два подхода:
    -  Или  как-то ограничить, сколько тегов можно создавать одному юзеру
    -  Или подумать по каким правилам удалять неактуальные теги
2. Про Добавление тега - согласен, логичная и удобная система.
3. Про то, что бы заменить Экспертизу - скорее нет. там чуть другое -  в экспертизе там есть градация. А тег это `Bool`.


---


4. теги к посту - крутая идея. Хотя они не всегда коррелируют с тегами в профиле. Но я бы рассмотрел эту киллер фичу уже отдельной фичей - сделать хештеги для постов. аля как на хабре (если считаем что на скриншоте Хабы === Комнаты):
<img width="499" alt="image" src="https://user-images.githubusercontent.com/3356474/93475248-9a3b4000-f922-11ea-9874-deacc4edef45.png">

    - И бонусом к пункту 4 сюда предложу еще идею UX:  
        - фильтровать посты по тегам (да, это можно делать в комюнити)
        - показывать сколько раз тег поставило, как на стековерфлоу:
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/3356474/93475572-f900b980-f922-11ea-9cdc-de1b7c4f105d.png">
Можно посмотреть занятную статистику (как часто в клубе обсуждаю НОУШЕН, например) :)

**Comment by vas3k** [comment]
@skywinder 

> Но я бы рассмотрел эту киллер фичу уже отдельной фичей - сделать хештеги для постов. аля как на хабре (если считаем что на скриншоте Хабы === Комнаты):

Наверное ты не так понял идею. Поясню. Я не хочу делать теги к постам как на хабре. Идея делать именно пользовательские теги, которые прикрепляются к постам чтобы другие люди могли найти их там и забрать себе. В твоем примере это может быть пост про электросамокаты и там будет новый кастомный тег «🛴 Самокатинг», который по клику добавится мне в профиль и я смогу похвастаться им перед друзьями. Получится как бы охота за новыми тегами, потому что создавать их смогут только самые жирные пользователи и они же будут прятать их в постах. Как-то так.

**Comment by skywinder** [comment]
@vas3k да, это я понял. Просто 4 пункт - это "Остапа понесло", и я развил идею дальше, чем тут нужно было (может я вынесу эту идею потом в отдельный issue)

Касательно оригинальной задумки - мои мысли в пунктах 1-2-3.

Касательно п.1 (сколько и когда можно создавать теги?)

На этот счет у меня появилась идея после твоего коммента:

Как на счет такого: разрешать создавать теги не по 1000+ плюсиков на морду, а на пост:

т.е. 100+ плюсиков на пост дают автору возможность создать пользовательский тег (прикрепить это в этот пост).
Так решиться проблема чрезмерным размножением тегов.

Пример: набрал "Альпинизм" 100 плюсов - автор добавляет туда тег ( и он отображается у него на страничке )

**Comment by aprosvetova** [comment]
Важно помнить, что все теги перечислены в боковой панели /people/.
Каким бы секретным способом тег ни добавлялся в профили, в «Людях» нужно будет выводить их все.
То есть создание тегов должно быть не просто открыто лишь элитам, но и, наверное, только по разу на человека.

Ну либо «Людей» переделывать, чтобы вмещать туда кучи тегов. Пользовательские под кат прятать, например.

**Comment by madhead** [comment]
Что, если начать с этого:

![image](https://user-images.githubusercontent.com/577360/136107394-1c9d1d2f-1165-427a-bdec-35455df3de24.png)

Сделать как на SO: текстовый ввод с автодополнением. Существующие (в табличке) теги отображены серым, новые — оранжевым. Если есть новые теги — дополнительно заворнить об этом текстом чуть ниже. Крестик для удаления.

Предлагаю обойтись без ограничени по плюсикам автора и количеству тегов: аудитория и так модерируемая и неглупая. На SO ведь кармаволл нужен в первую очередь для защиты от дураков.

При создании поста теги сохранять в ту же табличку `tags`, с какой-нибудь другой `group`, например `suggested`. Это поможет отфильтровать их на странице поиска. Для начала. А потом можно и фильтр усложнить.

В посте рисовать теги сверху:

![image](https://user-images.githubusercontent.com/577360/136109642-2f6d91e2-37c4-427d-bd2d-2d9d31eb4cf1.png)

Что думаете?

**Comment by vas3k** [comment]
@madhead хорошее начало, давай упрощать :) Тегами мы решаем не задачу SEO-оптимизации, а задачу организации микро-коммьюнити по каким-либо темам. Потому создание тегов стоит максимально усложнить и сделать осознанным, а сами теги редкими, но приятными находками.

1. Я думаю стоит жестко закрепить 1 пост = 1 тег. Это подчеркнёт их важность и заставит юзеров включать голову при их выборе, а не херачить как хештеги в твиттере
2. Давай начнём с компоуза. Как юзер выбирает/создает новый тег к посту? Нужно ли разрешать это делать только про-юзерам или сразу всем?
3. Дальше подумаем над уведомлениями. Наверное если я выбрал тег у себя в профиле, я хочу получать через бота уведомления о новых постах с этим тегом. Так?
4.  Нужно ли ограничить это только постами или к вопросам/батлам/идеям тоже можно прикреплять теги-уведомления?
5. Как обезопаситься от "эффекта Максимуса", который стремится разрушить любую построенную нами систему? Он сразу же запостит какую-нибудь шутку и укажет 5000 тегов.
6. Дальше перейдём к отображению тегов. Мне не нравится идея показывать их сверху. Там уже отображается комната, автор, лейбл, короче получается перегружено как новогодняя ёлка. Как на счет разместить тег в конце поста? Чтобы только дочитавшие могли добавить его себе? Тогда теги действительно будут как скрытые бриллиантики, которые нужно находить. Такого эффекта и хочется добиться.

**Comment by devcooch** [comment]
2. Новый тег просто уходит к модераторам на аппрувал. Сначала создаётся неутверждённым, если не утвердили - то удаляется из БД.
3. Уведомления скорее отдельно надо где-то хранить, вообще выглядит так, что уже нужна страничка с настройками уведомлений в профиле.
4. К любой записи в БД типа Post. Или тебя дизайн смущает? можно начать только с постов.
5. Но ведь 1 пост 1 тег, поэтому 5000 не получится. Надо ли делать какие-то теги только для пользователей а какие-то только для постов? Вроде есть смысл, но усложнение возможно не стоит профита.
6. Да можно внизу.
7. Ещё нужно сразу подумать про сайдбар на главной? Или какой-то спецрежим отображения всех страниц с заданным тегом.

**Comment by madhead** [comment]
>Потому создание тегов стоит максимально усложнить и сделать осознанным, а сами теги редкими, но приятными находками.

Хммм, я понял. Я пытаюсь сделать #683 (оповещения о меншенах). И чёт тогда не сходится. Я хочу получать оповещения каждый раз, когда кто-то пишет о чём-то. Ну вот скажем о Финляндии и Котиках. Анальная модерация и ограничение на количество тегов принципиально не позволят авторам указать обе. Да и без модерации сложновато выбрать из них главную. В общем, тегами гибкие оповещения не сделать.

1.

> 1 пост = 1 тег

Это не теги, а категории. Для меня это больно, потому что — да — нужно "включать голову при их выборе". Я хочу теги.

2.

> Нужно ли разрешать это делать только про-юзерам или сразу всем?

> Новый тег просто уходит к модераторам на аппрувал.

Анально. Я бы не стал таким пользоваться. Ещё раз: на том же SO теги доступны про-юзерам и модерируются только потому, что там миллионы пользователей, из которых большая часть… малообразованные. И даже там ограничение 5 тегов на пост. В клубе так-то и народу поменьше, и в целом уровень повыше.

3.

Предлагаю вообще разделить эту ишью (кастомные теги, категории) и оповещения.

4.

И ещё один поинт, почему теги / категории плохо подходят для оповещений. Для эффективных оповещний придётся дать возможность добавлять теги ко всем, включая комментарии. Это сложно, да и выглядеть будет некрасиво. Представьте над каждым комментарием по плашке с тегом. А добавьте сюда ещё премодерацию тегов, это что, теперь потенциально каждый коммент модерировать? Отвязать оповощения от тегов, привязать из непосредственно к содержимому (любого поста, интро или коммента). Проблему теггирования комментов решать отдельно :)

5.

При ограничении количества тегов на пост, такого, конечно, не случится.

6.

Рисовать теги в другом месте — меньшая из проблем :)

**Comment by neonick** [comment]
Моё имхо: 
1) Фичу про подписки на теги вынести вообще в отдельную задачу (если она вообще нужна, мне — нет. Для этого есть Комнаты);
2) Возможность раздавать кастомные теги в зависимости от плюсиков пользователя — годная идея. Но что, если придёт новичок и напишет крутой пост? Может это как-то завязывать еще на плюсиках самого поста?
3) Теги лучше делать в конце поста, как своеобразный CTA после прочтения поста — «зашло, моё»:
![image](https://user-images.githubusercontent.com/557977/144886917-4f3bbee6-acf5-4e4c-970a-1e506100e416.png)


4) Отделять «коллекционные» теги от обычных можно просто — градиентным фоном, например:
![image](https://user-images.githubusercontent.com/557977/144886697-e8ec7daa-062b-4862-ae98-c6598f796230.png)

**Comment by vas3k** [comment]
@neonick 

1. Я запилю на изи, это очень просто
2. Тогда он попросит модератора или парламент и те добавлят тег к посту
3. Да, хочется именно в конце. Твой пример интересный, мне надо подумать. Я думал это будет некая плашка перед блоком с информацией об авторе, мол, вы нашли коллекционный тег, можете добавить его себе в профиль и все такое
4. Вангую, что никто не поймёт такое отличие в тенюшках без дополнительных объяснений. Предлагаю проще — делаем отдельный блок "Коллекционные теги" прямо под "Хобби" и всё

**Comment by neonick** [comment]
@vas3k довольно изящно и просто тогда всё получается 👍🏻

**Comment by vas3k** [comment]
@neonick нужно продумать интерфейс создания еще. Наверное это будет отдельное поле к посту или я хз

**Comment by neonick** [comment]
@vas3k 
![image](https://user-images.githubusercontent.com/557977/144921396-d05dd0fd-9d0d-4c62-9997-51c2fca9af5d.png)

**Comment by vas3k** [comment]
Боюсь, заебемся валидировать эмодзи вначале. Люди не поймут и будут там писать что угодно, кроме эмодзи :)

**Comment by neonick** [comment]
Всё равно ж модерация?

**Comment by vas3k** [comment]
Ну уж нет, это не выглядит как что-то, на что надо тратить человеческое время, если можно делать машиной

**Comment by neonick** [comment]
Тебе виднее, конечно, насколько люди будут дичь писать, но вроде эмоджи — это понятно что такое + пример в описании. Ну еще [регуляркой](https://regex101.com/r/ZP389q/3) полирнуть, на всякий.

**Comment by vas3k** [comment]
В регулярке придется указать все существующие эмодзи? Может как-то это можно обыграть на UI? Той же выпадашкой, я хз

**Comment by vas3k** [comment]
Унес в дискуссии https://github.com/vas3k/vas3k.club/discussions/820
