### ISSUE TITLE
HTML-экскейпнг пролезает плейнтекстом в рассылке

### ISSUE THREAD

**Issue by mutantcornholio** [vas3k/vas3k.club#397]
Две карточки вместо тысячи слов:
<img width="758" alt="Screen Shot 2020-09-21 at 17 17 42" src="https://user-images.githubusercontent.com/588262/93785794-c3afe080-fc2e-11ea-94a5-e13b02eb3786.png">
<img width="774" alt="Screen Shot 2020-09-21 at 17 18 07" src="https://user-images.githubusercontent.com/588262/93785799-c4e10d80-fc2e-11ea-87b9-effd5fa346eb.png">

**Comment by fr33mang** [comment]
Сделал PR, но предполагаю, что такая проблема и с постами в том же weekly digest, так как там все сделано также без markdown. Надо почекать, и возможно, запушить сюда же
