### ISSUE TITLE
Фича: Доступность избранных постов в offline режиме

### ISSUE THREAD

**Issue by meridos** [vas3k/vas3k.club#399]
Не знаю как остальные, но я очень люблю читать лонгриды в самолетах, когда темно, спать не хочешь/не можешь, а делать что-то нужно. Для меня это пожалуй идеальное стечение обстоятельств.

Сейчас снова перед полетом, я собираю информацию которая мне пригодится в оффлайне и подумал что было бы классно иметь возможность прочитать статьи клуба которые добавлены в закладки.

**Что хочется:** в оффлайне иметь 2 функции
- показывать список доступных постов
- просмотр полного конента из поста

Кто что думает? Го обсуждать!

**Comment by skywinder** [comment]
Не представляю, как ты это решишь на уровне сайта. Это скорее фича браузера. 
Есть ли примеры, как это сделано на других сайтах?

+ Не вижу проблем использовать ~~ноушен~~ Pocket и другие специализированные для офлайн закладок тулзы
