### ISSUE TITLE
Стикеры/гифки для реплаев

### ISSUE THREAD

**Issue by AshotPilosian** [vas3k/vas3k.club#4]
Телеграм показал, что стикеры, как статичные, так и анимированные (по-сути, гифки) -- отличная штука для выражения эмоций и мнений в интернете, на мой взгляд, было бы классно иметь подобную систему и в Клубе. Может, для начала, просто интеграцию с gfycat или чем-то таким. 

Конечно, лучше в webp.

**Comment by vas3k** [comment]
Норм. А есть какие-то невсратые референсы UI как это можно сделать, чтобы не раздражало?

**Comment by AshotPilosian** [comment]
Референсов, наверное, нет, я на сайтах особо стикеров не видел никогда, только в мессенджерах. Причем, только в телеге они не раздражают.

**Comment by vas3k** [comment]
Вот в этом пока главная загвоздка. Я хотел сделать реакции как в слаке, но они всех заебали. Из других идей — разве что парсить ссылки на giphy и другие популярные источники, и эмбедить их гифки/видосики прямо в коммент, как сейчас это делается с YouTube. 

Но этим все равно мало кто будет пользоваться. И телодвижений все равно многовато.

**Comment by VBodrov** [comment]
Но Bot API умеет webp как стикеры отсылать. Если отвечать через бота стикером, почему его бы и не вставить на сайте?

Ну да, тогда функционал отвечать стикерами есть только у реплаев через бота. Но разве не этого ты хочешь добиться?

**Comment by AshotPilosian** [comment]
Хммм, в целом, это неплохая опция, особенно с учётом, что предполагается всё большее количество интеракций с ботом. Спасибо, один из путей

**Comment by VBodrov** [comment]
Что можно было бы сделать, это добавить ко всем постам/каментам кнопку, с урлом t.me..., который на бота перебрасывает для ответа через него. Как то так

**Comment by skywinder** [comment]
Закрою, т.к. активности в таске нет и желающих сделать (пока) тоже. 
Если кто захочет взять эту таску - пишите.
