### ISSUE TITLE
Баг: Кнопка Upvote на моб. версии

### ISSUE THREAD

**Issue by dimabory** [vas3k/vas3k.club#402]
![Screenshot_2020-09-27-21-21-25-540_com.android.chrome.jpg](https://user-images.githubusercontent.com/11414342/94372597-bcde0d80-0107-11eb-821d-f1f96a4a8649.jpg)

**Comment by nlopin** [comment]
Хорошо бы еще напистаь, как должно быть. Я давно смотрю на кнопки апвоута, и мне очень хочется зафиксировать их ширину

**Comment by skywinder** [comment]
*тот случай когда гитхаб дает лучшую подборку, что посмотреть в клубе*

**Comment by vas3k** [comment]
@nlopin зафиксировать ширину можно просто превращая длинные цифры в "1.3К", но пока это не нужно. А вот уехавшие плюсики реально бесят

**Comment by nlopin** [comment]
@vas3k у нас еще нет тысяч лайков, а сотни непонятно как сократить

**Comment by vas3k** [comment]
@nlopin непонятно и зачем
