### ISSUE TITLE
Accessibility: Сделать Клуб юзабельным без мыши

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#409]
Надо быть в тренде и запрыгивать в поезд хайпа по Accessibility. Первым делом предлагаю сделать самое полезное — доступность сайта с клавиатуры без каких-либо курсоров итд. Гикам тоже будет приятно.

Нужно выяснить как это принято делать в современном вебе и расставить нужные теги в вёрстке и стили в CSS. Думаю, кто-то может базово этим заняться, на ревью дополним.

**Comment by malitov** [comment]
Как изи вариант - установить vimium в браузер.

По теме, можно вдохновиться Пикабу
![image](https://user-images.githubusercontent.com/10050550/95189618-c423ac00-07d6-11eb-9096-0e3431cf4b28.png)

**Comment by skywinder** [comment]
идея хорошая, но я тоже как и @malitov использую vimium и поэтому все работает из коробки

Но если говорить про другие приложения, 
часто они для навигации  используют `hjkl` -  как в vim (навскидку помню Github, Gmail, Pocket)

Ну и для инспирации, какие шорткаты можно прикрутить вот ман вимиума:

![Screenshot 2020-10-07 at 22 20 04](https://user-images.githubusercontent.com/3356474/95351278-41d8dc00-08eb-11eb-92d4-693ed96b1500.png)


Самые полезные - это скролл и быстрое открытие ссылок (F)

**Comment by Windrushfarer** [comment]
У меня ощущение словно изначально ишью именно про то, чтобы удобно навигировать табом, чтобы был правильный порядок перехода и всякие удобства для читалок экранов, а не про кастомный навигатор с клавы?

**Comment by vas3k** [comment]
Да, @Windrushfarer прав

**Comment by skywinder** [comment]
ок. а что значит "навигировать табом"? всмысле переключение фокуса по нажатию на таб и все?
