### ISSUE TITLE
Баг: Не видно экран редактирования

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#413]
### Env: 
iOS, vertical orientation, Firefox

### Actual behavior:
![image](https://user-images.githubusercontent.com/3356474/95227610-82bbec80-0828-11eb-959a-792f42f1967f.png)

### Expected behavior:
![image](https://user-images.githubusercontent.com/3356474/95227656-8f404500-0828-11eb-9a13-52004256d686.jpeg)

### how to fix:
1. Если так и задумано, чтобы люди не писали на узком экране, то￼ добавить текст и иконку, что нужно повернуть экран. ￼(см скрин)

2. Если это баг верстки, то посмотреть куда пропадает экран редактирования. ￼

### Workaround:
Повернуть мобилу. 

### need to discuss:

@vas3k, какой из вариантов выше реализовывать? 
(Или забить, если это только меня сбивает с толку￼￼)

----

Ps.
Заодно потестируем Template, которые я предлагаю сделать дефолтным для багов 👆

**Comment by Windrushfarer** [comment]
Помнится Вастрик говорил, что это вообще специально сделано, потому что в текущем виде нет смысла что либо писать на телефонах, т.к это неудобно, ну и странно. Насчет неудобно я согласен :)

**Comment by vas3k** [comment]
Да это шутка была :)

**Comment by Windrushfarer** [comment]
@vas3k а может тогда сделать удобный лайаут для мобилок в таком случае? Я как раз вот бегаю по ишью, смотрю чтобы взять или помочь.

**Comment by vas3k** [comment]
@Windrushfarer можно, да. Просто самый удобный лайаут редактора для мобилок, как мне кажется, это просто отключить редактор и оставить голую textarea (так уже сделано в комментах)
