### ISSUE TITLE
Баг: Пропали стили в ежедневном дайджесте

### ISSUE THREAD

**Issue by malitov** [vas3k/vas3k.club#415]
**Env:** Емейл клиент Spark - macos и ios.
После недавнего релиза слетели стили. Начиная с 6 октября письма отображаются некорректно.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/10050550/95310779-791c9e00-0895-11eb-8311-0b934ec6a057.png">

**Comment by nlopin** [comment]
Исправлено
