### ISSUE TITLE
Баг: Не отключается курсив обратно на обычный стиль при редактировании

### ISSUE THREAD

**Issue by bitomaxsp** [vas3k/vas3k.club#418]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/866806/95364330-fdd8dd80-08d0-11eb-8817-766db44df397.png">

**Comment by vas3k** [comment]
Надо пробельчик удалить, а так да, согласен, странно. Но возможно это даже имеет какое-то объяснение в стандарте Markdown

**Comment by bitomaxsp** [comment]
Хех! да. слона то я и не приметил ) Хотя странно, что пробел так влияет.
