### ISSUE TITLE
Нельзя редактировать заголовки у комментариев

### ISSUE THREAD

**Issue by TiraelSedai** [vas3k/vas3k.club#42]
В комментах, которые содержат не только `тело`, но и заголовок (пример: в баттлах),

Actual:
1. При нажатии на эдит, не даёт редактировать заголовок
2. При удалении опять же удаляет комментарий, а заголовок висит - видимо, потому, что вместо реального удаления тут просто замена тела комментария на эмодзи + комментарий удалён?

Expected:
1. Можно редактировать и то, и то
2. Даже не знаю, [deleted]?

**Comment by vas3k** [comment]
Сделал пока нормальное удаление. Должно быть менее больно теперь
