### ISSUE TITLE
Добавить полезных для секьюрити хидеров в конфиг nginx

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#420]
Смотрите чо: https://securityheaders.com/?q=vas3k.club&followRedirects=on

Там рассказывается чего не хватает. По факту нужно просто добавить нужных хидеров, руководствуясь best practices.

**Comment by Windrushfarer** [comment]
А кто-то подскажет как это локально проверить? Девсервер запускается питоном, а не nginx насколько я понимаю

**Comment by vas3k** [comment]
Похоже, никак. Нжинкс стоит перед докером, так что проверить можно только по валидности синтаксиса. Этого достаточно для PR

**Comment by skywinder** [comment]
@vas3k кстати, а как на счет идеи Нжинкс в докер включить для констистентности нашего монолита? :)

**Comment by vas3k** [comment]
@skywinder сейчас nginx работает как прокси или лоад балансер перед всеми докерами на сервере. Это позволяет хостить аппы из разных контейнеров на поддоменах одного сайта, например. Со встроенным nginx такое не получится.

**Comment by devcooch** [comment]
Сделали PR #423.

**Comment by devcooch** [comment]
Однако он не добавляет Content-Security-Policy - пока не критично, наверно?

**Comment by vas3k** [comment]
Пока нет, но можешь потом прислать новый PR, если хочешь :)

**Comment by devcooch** [comment]
Думаю сделаю, ага
