### ISSUE TITLE
Баг: загрузка гифок фейлится с CORS-ошибкой, которая не отображается в UI

### ISSUE THREAD

**Issue by cakeinpanic** [vas3k/vas3k.club#426]
Нашла вот такую багу, гифки фейлятся на корсах.
ссылка на фидео бага(интересно, что он загрузился без ошибок): https://i.vas3k.club/d6688dc2fe938d8c5894508576ef4b7375b8e71e504f3bcf008ece6233fecd7b.mp4

пример гифки, на которй падает:
![20](https://user-images.githubusercontent.com/588916/95850859-1b3afb00-0d5a-11eb-961a-f12a706f3d39.gif)

**Comment by devcooch** [comment]
@vas3k судя по видео я вижу, что он как раз ругался на то, что в исходном vas3k.club не было Access-Control-Allow-Origin, который я добавил в #423.
@cakeinpanic перепроверишь, что заработало?

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
