### ISSUE TITLE
Баг: Stripe -> Подписаться на +1 год членства в Клубе каждый месяц

### ISSUE THREAD

**Issue by liamka** [vas3k/vas3k.club#435]
Оплата через страйп

получается я каждый месяц буду продлевать себе членство в клубе на +1 год

**Comment by vas3k** [comment]
Да. Можно даже каждый месяц продлевать его на 50 лет. Специальная фича для тех, кто хочет максимально поддерживать долором движухи Клуба и его развитие. Почему баг-то? :)
