### ISSUE TITLE
Что делать с постами дубликатами?

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#436]
Клуб растет. Вместе с ростом появляются новые ~проблемы~ задачи: что делать с дубликатми вопросов-постов-батлов.
Таких вещей с ростом комьюнити будет все больше и надо придумать как с этим жить и жить хорошо?

Пока есть вариант только убирать в драфт админам.

Но если не закрыть сразу - там уже появится контент, коментарии. И стирать будет некрасиво по отношению к другим участникам кто это писал.

Вот пример:
1. 
![image](https://user-images.githubusercontent.com/3356474/96864843-45479800-1493-11eb-9a0b-2ad5b8d0f676.png)

actual result: (как это решается сейчас)
![image](https://user-images.githubusercontent.com/3356474/96864875-50022d00-1493-11eb-9b0d-45cee1f45fc3.png)

2.  и вот прямо сейчас в ленте в паралеле два одинаковых батла висят:
![image](https://user-images.githubusercontent.com/3356474/96864928-67d9b100-1493-11eb-8443-dd05aa853454.png) 

Предложение сделать как на стековерфлоу и гитхабе: lock post, те пост оставить read-only.
и в шапке писать что это дубликат с ссылкой на оригинал. Или подумать как еще красиво это решить дабы не плодить сущности.

**Comment by vas3k** [comment]
Сейчас алгоритм действий такой: запостить ссылку в комменты, указав автору на дубликат, и ждать его решения.

Lock post уже есть, а вот с плашкой можно подумать, да. У меня в голове была более универсальная идея — блок «связанные посты», в который будут попадать все линки на другие посты внутри Клуба. Идея в том, что если в комментах кто-то кидает ссылку на другой пост, скорее всего эта инфа важна и интересна всем в контексте данного поста, так что надо как-то поднять её наверх и выделить. Хотя может и глупость, не знаю.

**Comment by devcooch** [comment]
Нет, не глупость, именно то что нужно. Получается сетевой Notion, главное, чтобы бэклинки тоже были.

**Comment by skywinder** [comment]
Слушай, точно! это классная идея с кросс линками. 
￼
SO Посути так и делает:
1. На дубликаты в самый верхушке сразу идёт ссылка￼
2. справа в колонке есть список вопросов, на которые были ссылки в ответах и комментариях￼￼. Я зачастую в первый очередь смотрю туда. 
￼
эти вещи можно объединить в одну плашку. хотя идеологически дубликат - это не связанный пост.￼ 
это можно решить тем, что сделать ссылку серого цвета. 

Или даже пойти дальше И сделать универсально: любую ссылку на пост с закрытыми комментариями отображать серым. ￼

**Comment by nlopin** [comment]
С течением времени темы будут дублироваться и это ок. Знания меняются и писать апдейт в посте трехлетней давности — это так себе. Лучше делать цепочки дубликатов и ранжировать их по датам, чтобы можно было по истории перемещаться.

А иначе всегда будут душнилы, которые будут столетний пост с миллионом комментов показывать. Такие посты сложно читать, потому что вся соль в комментах
