### ISSUE TITLE
Фича: сворачивание комментариев

### ISSUE THREAD

**Issue by Aracturat** [vas3k/vas3k.club#438]
Предлагаю добавить сворачивание веток комментариев.
По умолчанию все показывается, но будет возможность свернуть ветку, если не хочется читать длинное обсуждение на какую-то тему.

К примеру, это может выглядеть так:
![image](https://user-images.githubusercontent.com/1833101/97089368-6a8a0100-1661-11eb-9741-21f6a47363e9.png)

После нажатия на кнопку "свернуть ветку", комментарии прячутся, текст кнопки меняется на "развернуть ветку"
![image](https://user-images.githubusercontent.com/1833101/97089337-3a426280-1661-11eb-9b76-60291f06b3ab.png)

**Comment by vas3k** [comment]
Фича ок, над дизайном надо сильно и много работать :)

**Comment by slonoed** [comment]
Накину ещё немного про это

1. Читаешь камент первого уровня
2. Читаешь первые N каментов
3. Понимаешь, что ветка скучная и хочешь перейти к следующему
4. При этом первый камент уже уехял вверх, а следующий камент верхнего уровня сильно внизу

То есть цель тут не столько скрыть ветку, сколько перейти к следующей.

**Comment by dmitvitalii** [comment]
В клубе можно сделать логику **"Свернуть ветку под комментом"**

### Сейчас в комментариях кнопка ответа находится в разных местах.

![now](https://user-images.githubusercontent.com/14320898/107057735-d2b1bc80-67e4-11eb-8b80-1975d9bf894b.png)

### Можно передвинуть кнопку, чтобы расположение было консистентным

![first_step](https://user-images.githubusercontent.com/14320898/107057851-eeb55e00-67e4-11eb-8ce9-c71e1d08a476.png)
![step_two](https://user-images.githubusercontent.com/14320898/107057982-15739480-67e5-11eb-9bad-419247781b52.png)

### Так мы освободим место для
- Блока с редактированием и удалением
- Кнопки сворачивания/разворачивания у комментариев каждого уровня

![step_one_shown](https://user-images.githubusercontent.com/14320898/107063206-2921f980-67eb-11eb-8d89-70045c498524.png)
![step_two_hidden](https://user-images.githubusercontent.com/14320898/107063239-3212cb00-67eb-11eb-9111-72c731c87fdc.png)

### Так, если не навели мышь или коммент не наш
![step_one_shown_not_an_author](https://user-images.githubusercontent.com/14320898/107063736-c54c0080-67eb-11eb-9dd1-375cb8f55bd8.png)


### Когда несколько комментариев, показываются только те имена, которые следующие по уровню.

![step_five](https://user-images.githubusercontent.com/14320898/107061609-72714980-67e9-11eb-8c5c-354f017a9949.png)

[Иконки отсюда](https://material.io/resources/icons/?search=%20expan&icon=expand_less&style=outline)

**Comment by vas3k** [comment]
@dmitvitalii а мне нравится! Вот теперь буду рад если кто-то запилит такое :)

**Comment by devcooch** [comment]
Вроде есть уже такое.

**Comment by dmitvitalii** [comment]
@devcooch есть сворачивание топ-комментов, но нет сворачивания комментов внутри + тут небольшой редизайн комментариев

**Comment by devcooch** [comment]
![image](https://user-images.githubusercontent.com/2089015/129723928-5ef6c8ae-31ac-4c58-8601-42464c408214.png)
думаю ты ошибаешься

**Comment by dmitvitalii** [comment]
![IMG_20210817_152149_833](https://user-images.githubusercontent.com/14320898/129724898-ba7897b5-f988-4397-94c8-c27b4fb80022.jpg)
![IMG_20210817_152147_726](https://user-images.githubusercontent.com/14320898/129724905-0a8f617e-9c15-4462-aaf0-ea8a905ef424.jpg)

Ладно, переформулирую
Комментарии сворачивать можно, но нельзя свернуть ветку под комментарием. Сейчас чтобы так сделать надо проклинать все комментарии в ветке, потому что иначе исходный коммент свернётся.

**Comment by devcooch** [comment]
не, ну нет проблемы переоткрыть тикет. имхо нет разницы, если хочешь свернуть всю ветку - сверни и комментарий, оно все равно всё не персистентно и на релоад опять откроется. если есть желание поработать и прислать тут ПР - я не против. Если конкретных предложений на UI нет, то вряд ли кто-то будет над этим работать кроме тебя.

**Comment by vas3k** [comment]
Готов посмотреть на редизайн "до" и "после". Можно в отдельном тикете. Я по-моему перебрал 3 варианта пока нашел наименее раздражающий (текущий)
