### ISSUE TITLE
DevOps: Запускать тесты при мерже в мастер (перед деплоем)

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#439]
Кажется, сейчас тесты не запускаются, потому очень легко сломать мастер и не заметить. Предлагаю добавить их запуск отдельным шагом сюда: https://github.com/vas3k/vas3k.club/blob/master/.github/workflows/deploy.yml

Пример запуска можно взять из CI.yml, который лежит рядом и запускается при каждом PR (там шаг прям так и называется test).

**Comment by ujlbu4** [comment]
Привет!

Да, тесты сейчас запускаются только в созданном PR'е, т.к. предполагал, что все правки вносятся через отдельные ветки и соответственно PR'ы. И в основном было сделано, чтобы не гонять лишний раз те же самые тесты еще и в мастере. 

Правильно понимаю, что проблема именно в кейсе, когда коммиты сразу в мастер идут?

**Comment by vas3k** [comment]
Ага :)

**Comment by ujlbu4** [comment]
Пушнул PR.

(тесты если что сейчас в мастере сломаны, гляну в отдельном pr'е)
