### ISSUE TITLE
Баг: не зайти в Питерский чат

### ISSUE THREAD

**Issue by kniazevgeny** [vas3k/vas3k.club#440]
Битая ссылка в [vas3k.club/network/](https://vas3k.club/network/)
![image](https://user-images.githubusercontent.com/41857481/97106563-8e862a80-16d3-11eb-9401-a5982d9aa6cb.png)

**Comment by vas3k** [comment]
Потыкай за одно остальные чаты, раз уж вызвался. Скажи какие ещё протухли :)

**Comment by kniazevgeny** [comment]
Потыкал, остальные живы!

**Comment by vas3k** [comment]
Хорошо! Просто кто-то мне жаловался, что у ФинНезависимости тоже битая, вот пытаюсь понять это они сами протухают или есть какая-то закономерность

**Comment by nlopin** [comment]
Дайте небитую, вставлю
