### ISSUE TITLE
Баг: несобирается фронтэнд

### ISSUE THREAD

**Issue by uMag** [vas3k/vas3k.club#450]
При сборке фронта 
npm run build

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  fonts/fa-brands-400.svg (699 KiB)
  fonts/fa-solid-900.svg (876 KiB)
  main-efe0652f78f41c35281c.js (1.2 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (1.39 MiB)
      main-efe0652f78f41c35281c.css
      main-efe0652f78f41c35281c.js
```
В результате в dist каталоге нет собранных js  и css файлов

CC: @nikolay-govorov увидел что ты с этим копался

**Comment by nikolay-govorov** [comment]
Привет. Это не я, это всё вебпак. Для прода есть две найтройки: `performance.maxAssetSize == 100000`, `performance.maxEntrypointSize == 400000`: [webpack.js.org/configuration/performance](https://webpack.js.org/configuration/performance/#performancemaxentrypointsize);

Чтобы заработало вот прям сейчас, можно просто поднять лимиты. А вообще, вебпак дело говорит и это повод к оптимизации.

**Comment by vas3k** [comment]
Давайте придумаем как оптимизировать, а то не дело это совсем

**Comment by dimabory** [comment]
Для этого бы стоило конечно открыть отдельное issue.

Вот будет очень полезно откуда берется размер бандла:

- Разархивируй [stats.zip](https://github.com/vas3k/vas3k.club/files/5464140/stats.zip)
- Открой https://statoscope.tech/ и дропни туда файлик 

Вот пример того, что можно увидеть
![image](https://user-images.githubusercontent.com/11414342/97688002-68c99e80-1aa2-11eb-9680-90b926c173ce.png)

**Comment by devcooch** [comment]
Думаю тут уже ничего делать не надо, закрываем.
