### ISSUE TITLE
Реплай к новому комменту налезает на его фон

### ISSUE THREAD

**Issue by Joltd** [vas3k/vas3k.club#46]
- Новый коммент подсвечен фоном
- У коммента есть ответ

AR: Ответ налезает на фон самого коммента, особенно видно по аватарке ответившего и значку +N справа
ER: Ответ на коммент должен быть расположен чуть ниже ну или фон основного комента не должен быть таким высоким

![image](https://user-images.githubusercontent.com/14071504/80535298-9d548480-89b1-11ea-8d7d-cd43d6928d05.png)

**Comment by vas3k** [comment]
Да, я бы поумерил отступы в родительском комменте с 30px до 20, а реплаю добавил сверху 5-10px. Кажется, так будет ок
