### ISSUE TITLE
Фича: дневной лог/фид активности

### ISSUE THREAD

**Issue by dottedmag** [vas3k/vas3k.club#460]
Я заметил, что залипаю на сайте в режиме ”залогиниться, прокликать все новые посты и посты с новыми комментариями, повторить через пять минут“.

Хочется фид или ежедневный e-mail, состоящий из дневной активности (новые посты, новые комментарии к постам), чтобы читать прямо в почте или фидридере.

Телеграм-бот не годится, он выдаёт нотификации мгновенно, а не раз в день.

**Comment by vas3k** [comment]
Ежедневный дайджест существует с самого первого дня. Вот здесь нужно выбрать первую опцию: https://vas3k.club/user/me/edit/notifications/

**Comment by dottedmag** [comment]
> (новые посты, новые комментарии к постам), чтобы читать прямо в почте или фидридере.

Проверил. В дайджесте нет комментариев.

**Comment by vas3k** [comment]
Комментарии есть. Туда попадают все комменты на посты, на которые ты подписан, плюс реплаи, плюс ответы на твои посты. Посты там не все если их слишком много. Конечно текст там не целиком, а только превью. Это же дайджест :)

Если тебе нужно что-то специфическое — ты всегда можешь собрать себе сам такую тулзу из RSS или фида канала Онлайн в телеграмм

**Comment by dottedmag** [comment]
> собрать себе сам такую тулзу из RSS

Спасибо, проверю. Если чего-то в RSS не будет хватать — заведу отдельный баг.

**Comment by vas3k** [comment]
Да, давай. Вполне возможно, что там будет много чего не хватать :)
