### ISSUE TITLE
Фича: Не давать превью по ссылке для черновиков и закрытых постов

### ISSUE THREAD

**Issue by shkaff** [vas3k/vas3k.club#462]
Если постить (например в соцсети или телеграм) ссылку на пост, который закрыт или даже еще в черновиках, превью все равно генерится и отдает название и первые строки поста.

**Comment by LionZXY** [comment]
А это точно баг, а не фича?)

**Comment by shkaff** [comment]
Типа чтобы заманить людей вовнутрь?:) 

Возможно, тогда нужно вешать предупреждение где-то, чтобы важную (чувствительную) инфу не вешали в начале.  Ну и для черновиков это странно в любом случае. Казалось бы, к ним не должно быть доступа совсем.

**Comment by vas3k** [comment]
Можно добавить предупреждение, да. Нужно придумать как сделать так, чтобы оно не мешало. 99.9999% людям все равно похуй.
