### ISSUE TITLE
Батл: в сводке считать уникальные плюсики за сторону

### ISSUE THREAD

**Issue by nizheg** [vas3k/vas3k.club#464]
Батлы вверху страницы содержат статистику вида "3 аргумента и 15 плюсиков". Возможно, подразумевается, что это является неким мерилом "выигрыша" одной из сторон. 
Сейчас есть возможность абьюзить количество плюсиков за сторону (в том числе, не умышленно), если следовать гайдлайну "Один аргумент — один комментарий. Не делайте списков, так сложнее вести дискуссию и подсчитывать статистику.". Допустим за одну из сторон написать 10 аргументов и в каждой из них поставить плюс, то это уже 10 плюс от одного человека.
На мой взгляд, будет логичнее, если в шапке будет считаться количество плюсов за аргумент, при этом так же можно ставить плюс нескольким аргументам, но он всё равно в общей статистике будет засчитан как один.

**Comment by vas3k** [comment]
Скопипащу из чата

Вастрик, [8 Dec 2020, 14:33:09]:

Хз, мне пока не нравится. Потому что не очень понятно есть ли вообще такая проблема. Не думаю, что кто-то всерьез воспринимает заплюсованность одной из сторон как победу. Суть батлов скорее в сборе разных аргументов, а не победе одной из сторон

Но даже если принять гипотезу, что это правда смущает людей, то учет уникальных плюсиков тоже не решит проблему

Он лишь покажет приверженцев какой из сторон больше в Клубе, что тоже нерепрезентативно
