### ISSUE TITLE
В "Коммьюнити" при выборе тэгов из разных блоков при переходе на следующую страницу отваливается тег

### ISSUE THREAD

**Issue by VBodrov** [vas3k/vas3k.club#466]
Может быть это, конечно, не баг, а фича, но:

Скажем я хочу посмотреть людей, кто "Может проинвестировать" (При выборе фильтруется автоматически) и любит "космос" (Уже нужно нажать "Отфильтровать"). Получаем ссылку:
https://vas3k.club/people/?query=&country=&tags=can_invest&tags=space
Ссылка на вторую страницу уже выглядит вот так:
https://vas3k.club/people/?query=&country=&tags=space&page=2
Тэг отвалился.

Повторяется и с другими тэгами. Тэги из блока выше отваливаются.

**Comment by manushichev** [comment]
Это похоже уже не актуально, на проде у меня не воспроизвелось.

**Comment by devcooch** [comment]
Спасибо!
