### ISSUE TITLE
В клубе нет ссылки на vas3k.ru

### ISSUE THREAD

**Issue by jacki0** [vas3k/vas3k.club#467]
Неоднократно ловил себя на мысли  что хочется уйти в блог именно через интерфейс клуба.
Я это вижу примерно как у Яндекса сделано, но можно подумать и о другой реализации.
![photo_2020-12-19_19-16-09](https://user-images.githubusercontent.com/56176644/102694518-97f2c580-4232-11eb-9b74-01b6a64718b1.png)

**Comment by vas3k** [comment]
Ссылка в лого — это уже слишком, имхо. Она есть в футере как ссылка на создателя. Ассоциировать же клуб полностью с личностью одного человека было бы неправильно.
