### ISSUE TITLE
Показывать в секции последних комментариев, к каким постам они сделаны

### ISSUE THREAD

**Issue by kirillku** [vas3k/vas3k.club#468]
Кода смотришь секцию последних комментариев для пользователя, не понятен их контекст. Особенно если комментарий короткий.

![image](https://user-images.githubusercontent.com/3331461/102714896-7a793680-42da-11eb-81e9-8d588c6c8a1f.png)

Было бы здорово показывать название поста, к которому был комментарий. Тем более имя пользователя и так понятно. Можно например использовать то как это сделано в рассылке журнала.

![image](https://user-images.githubusercontent.com/3331461/102714992-068b5e00-42db-11eb-9041-0cf070ba78b9.png)

Related to #198

**Comment by vas3k** [comment]
Да, это отличная идея. Тем более в недавнем PR мы наконец-то сделали универсальный шаблон для этих комментов. Там простейший HTML-файл, кто-нибудь может заняться и сделать.

P.S.: Из рассылки взять не получится, там совершенно другая верстка, оптимизированная под имейлы

**Comment by fr33mang** [comment]
#367 

Что-то такое уже было, не нашел тогда сил доделать.
