### ISSUE TITLE
Использовать системную тему

### ISSUE THREAD

**Issue by nikolay-govorov** [vas3k/vas3k.club#47]
Днём хочется видеть светлую тему, а ночью тёмную. Большинство современных ОС умеют переключать тему по графику, и безумно удобно когда сайт использует именно системную.

Из CSS/JS можно задетектить по [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by FMajesty** [comment]
Не дубликат #44?

**Comment by nikolay-govorov** [comment]
Разве? Вроде @Vadimkin говорит про ручное сохранение в localStorage, а я про постоянное использование системной без ручки. Нет?

**Comment by Vadimkin** [comment]
В #44 только слайдер имелется ввиду

Но то, о чем упоминается здесь, вроде как уже работает (только что в сафари проверил, и всё гуд):
https://github.com/vas3k/vas3k.club/blob/d45b2b381297a4a6596b13351f6e208712c66c12/frontend/static/css/theme.css#L64

**Comment by vas3k** [comment]
Да, по-умолчанию используется именно системная тема, но если ты поклацал слайдер туда-сюда, то он запоминает положение и больше не меняется. Тут надо думать скорее как сделать это удобно с точки зрения UI. Не делать же трехпозиционный слайдер :)

У меня пока нет правильного ответа здесь

**Comment by sermelipharo** [comment]
> если ты поклацал слайдер туда-сюда

Так может добавить дабл-клик ту резет?
 
![Vas3k-ThemeSelector](https://user-images.githubusercontent.com/9950381/170485234-6facaa85-f68c-40da-b2a4-07bc0e292738.png)

**Comment by vas3k** [comment]
> Так может добавить дабл-клик ту резет?

А круто выглядит, я бы хотел такое!

**Comment by sashaqred** [comment]
> Так может добавить дабл-клик ту резет?

Выглядит очень сложно 🤯


> Не делать же трехпозиционный слайдер :)

Зато просто и понятно)

Например https://doka.guide/, у них в футере застилизованные радиокнопки.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/7117660/176478209-540e7f11-0efc-4457-81a2-c091be4ad4e4.png">

Можно еще сделать селект или что-то что похоже на него. Например у [mdn](https://developer.mozilla.org/en-US/) такой селект для темы 

<img width="503" alt="image" src="https://user-images.githubusercontent.com/7117660/176478469-9be875d6-4686-4dab-b106-a2a415eba283.png">

**Comment by PeterMinin** [comment]
Очень плюсую запрос. Приходится натравливать Dark Reader, игноря родную тёмную тему.

По оформлению я бы голосовал за вариант Доки из предыдущего коммента, когда видны все 3 варианта. Располагается это в футере, поэтому экономия места не так приоритетна.

**Comment by PeterMinin** [comment]
А пока вот workaround: в консоли ввести `localStorage.removeItem('theme')`.
