### ISSUE TITLE
Иногда при загрузке вертикального изображения (фото) в комментарии, добавляются черные прямоугольники

### ISSUE THREAD

**Issue by araslanov-e** [vas3k/vas3k.club#473]
https://vas3k.club/post/6232/#comment-a4ecb8fe-68a1-450c-b829-aa215b27639d пример
Фото просто перетащил в поле для ввода
Добавлю одну ещё сюда
![1608786456036](https://user-images.githubusercontent.com/1290711/103082968-271a2780-45fd-11eb-8477-62d55da58cb3.jpg)

**Comment by vas3k** [comment]
А загрузи прям совсем-совсем оригинал куда-нибудь типа дропбокса или яндекс диска? Хочется посмотреть конкретно почему так. Если подозрение, что это так криво отрабатывает алгоритм автоматического переворачивания фотографий по EXIF.

**Comment by araslanov-e** [comment]
@vas3k https://www.dropbox.com/s/f9dbq1eypy6513x/1608786456036.jpg?dl=0

**Comment by vas3k** [comment]
Починил в https://github.com/vas3k/pepic/commit/9a25ac33d0b49e1e4e55a85c28cd48d74c90c784

Спасибо за пример, баг был действительно с авто-поворотом
