### ISSUE TITLE
Плохо читается счётчик на аватарках в разделе people

### ISSUE THREAD

**Issue by Krakabek** [vas3k/vas3k.club#478]
На белом фоне белый текст вообще не читается, на светлом еле-еле
![image](https://user-images.githubusercontent.com/6443205/103301062-29b7bb00-4a09-11eb-850c-5c9aa779b688.png)

Предлагаю запилить тенюшку непосредственно на текст
```
.people-map-user-cluster {
    text-shadow: 0 0 2px black;
}
```
Результат:
![image](https://user-images.githubusercontent.com/6443205/103301079-33d9b980-4a09-11eb-839c-3e7828496856.png)

Если никто не против, то могу оформить PR

**Comment by devcooch** [comment]
Кидай конечно PR

**Comment by Krakabek** [comment]
Забираю задачу
