### ISSUE TITLE
Поломанные стили в фиде под Firefox 84.0.1

### ISSUE THREAD

**Issue by ogabelok** [vas3k/vas3k.club#479]
Привет !
Записи в фиде о новых членах клуба немного съехали на Firefox.

<img width="1089" alt="Вастрик Клуб 🤘✖️👩‍💻‍ 2020-12-30 11-37-50" src="https://user-images.githubusercontent.com/13370861/103342952-7f38aa00-4a93-11eb-8641-708f1febf968.png">

**Comment by vas3k** [comment]
Проверь щас, должно стать лучше

**Comment by ogabelok** [comment]
и правда лучше! закрыто
