### ISSUE TITLE
Возможность привязывать пост в "Тракторе" к стране

### ISSUE THREAD

**Issue by tyhonchik** [vas3k/vas3k.club#48]
Хочуха: фильтровать посты в Тракторе по интересующей стране.
А для этого надо привязывать посты к странам, о которых идёт речь в посте.
Пока что постов немного, но в будущем может пригодиться

**Comment by vas3k** [comment]
Вообще норм, мне эта идея нравится. Я еще думал привязать ее к пользователям из этой страны, типа кидать им нотифы. Но все это возможно только если будут динамические формы (aka нормальный фронтенд) и подписка-отписка от уведомлений. Пока положу в идеи :)

**Comment by skywinder** [comment]
думал как раз  как это сделать лучше - что бы не плодить кучу вложенный стран - -регионов - городов.

Предлагаю просто дать возможность ставить к постам теги. 

тогда после можно легко фильтром посмотреть интересующие тебя.

**Comment by vas3k** [comment]
Я не фанат тегов. Не видел ни одного сайта, где бы люди их правильно использовали, а не просто проставляли от балды. Даже по профилям видно, что люди пишут один и тот же город 4 разными способами. Теги не помогут.

Я думал о глобальной карте, к которой можно прикреплять посты и пользователей. Но тоже пока не уверен

**Comment by ktaranov** [comment]
@skywinder пока закрываем, когда сделаем справочники городов и стран - вернемся к идее.
