### ISSUE TITLE
Фича: списки 

### ISSUE THREAD

**Issue by kvasdopil** [vas3k/vas3k.club#482]
Суть токова. Довольно большое количество постов имеют формат "Давайте соберём лучшие сорта пивка в 1.5л. бутылках" т.е. вместе с каментами представляют собой попытку создать список чего-либо. Для таких постов хочется иметь кастомный формат поста - список (по аналогии с постами-батлами например). 

- Выглядеть это может как заголовок + краткое описание, а затем, собственно, список пунктов чего-либо. Пользователи могут добавлять свои пункты.
- К каждому пункту чтобы можно было оставлять комментарии и устраивать там токсичные срачи
- К каждому пункту хотелось бы ставить плюсики и минусики, ну и показывать количество плюсиков и минусиков (2 счётчика а не один пушто хочется видеть записи которые вызывают ПРОТИВОРЕЧИЯ)
- Хочется чтобы пункты можно было сортировать по плюсам\минусам.
- Возможно, каждый пункт имеет смысл сделать раскрываемым, чтобы в закрытом виде показывался только заголовок.

Джва года жду эту фичу!

**Comment by omnster** [comment]
Подписываюсь под идеей, но не вполне в том виде, как автор написал.

Хотелось бы, чтобы вдобавок к посту с обсуждением можно было бы добавлять что-то похожее на голосование по списку.  То есть, компактный список вариантов, чтобы можно было поставить галки у подходящих вариантов или добавить свой. 

С текущим интерфейсом клуба голосование по спискам не работает, потому что
1. никто не соблюдает вариант "один коммент - один вариант", ну почти никто.
2. даже если бы соблюдали, сейчас один пост обмазан метаинформацией - сверху аватар и имя, снизу кнопка ответить, и вообще плашка поста очень большая.  Возможно поэтому, если хочешь посоветовать пять, например, книг, неловко оставлять пять отдельных постов.
3. часто варианты дублируются, потому что мало кто читает все каменты или может кто-то согласен с одним вариантом из восьми, предложенных кем-то еще.
4. кто-то может не голосовать за уже предложенный вариант, потому что ему не нравится обоснование.  Типа, если мы выбираем лучшее пиво, я готов проголосовать скажем за "Клинское", но не за "Клинское, потому что бутылка красивая".

Чтобы вышел список, нужно как-то спровоцировать пользователя писать ровно один коммент с ровно одним вариантом. Кмк, для этого нужо отделить элементы от обсуждения и ограничить длину ответа.  Возможно надо отвязать список от плюсиков в карму, чтобы не важно было, кто первый предложил вариант.

пс. Видит бох, вчера пока с собакой гулял придумал то же самое.

**Comment by vas3k** [comment]
Сделали треды, закрываем
