### ISSUE TITLE
Не включается spell checker из-за markdown-редактора

### ISSUE THREAD

**Issue by Jipok** [vas3k/vas3k.club#486]
Нигде такой проблемы не встречал

https://user-images.githubusercontent.com/25588359/103649416-52363c80-4f56-11eb-886a-347e21e0c347.mp4

Firefox 84
Отключение всех аддонов не помогает

**Comment by vas3k** [comment]
Ага, это из-за маркдаун-редактора. Пока никто не смог предложить альтернативу лучше. Ждем.

**Comment by vvzvlad** [comment]
Ну, там же это специально выключено в коде:
`<textarea autocorrect="off" autocapitalize="off" spellcheck="false" ...</textarea>`
Насколько я вижу, в EasyMDE есть настройки spellChecker, nativeSpellcheck. Оно не поможет?

**Comment by vas3k** [comment]
@vvzvlad проверь :) Кажется, кто-то уже пробовал с этим играться
