### ISSUE TITLE
Фича: Скроллинг по непрочитанным комментариям + кнопка «наверх»

### ISSUE THREAD

**Issue by 1g0rrr** [vas3k/vas3k.club#491]
Тут уже обсуждались варианты как улучшить взаимодействие со страницей #32 #438 и #315.

Но я хотел обратить внимание именно на перемещение юзера по непрочитанным комментариям. Этой темы кажется еще не касались.

### **Проблема:**
Неудобно читать новые комментарии, когда комментов под постом большое 100.

Наше сообщество мотивирует к тому, чтобы под постами было большое количество комментариев. Это происходит благодаря хорошей культуре общения и благодаря тому что у нас нет понятия "некропост".
Поэтому возникает частый сценарий когда юзер заходит в пост спустя какое-то время чтобы посмотреть новые комментарии. Но читать их на практике не очень удобно. Да, они подсвечиваются другим цветом, но нужно внимательно просмотреть всё полотно страницы, чтобы вычленить новое.

### **Предложение**
Сделать систему аналогичную Хабру. 

![image](https://user-images.githubusercontent.com/51457/104130810-84db9d00-537b-11eb-9056-98fefe048386.png)

Как у них это устроено:
Есть небольшая панель с плавающими кнопками 
Если есть непрочитанные комментарии, то появляется цифра с их количеством и стрелки для перехода.
- При нажатии на стрелки - страница прокручивается к следующему / предедущему непрочитанному комментарию.
- При нажатии на кнопку с цифрой - переходим к следующему непрочитанному комментарию, отмечая его прочитанным.

### **Достоинства:**
+ По личному ощущению - пробегаться по новым комментариям с этими кнопками приятно и быстро. Все же пробовали?
+ Это проверенный временем интерфейс. На Хабре он работает несколько лет. А там как раз тоже посты с большим количеством комментариев и схожая (ну относительно) аудитория.

### **Недостатки**
- Не очень лаконичный интерфейс с которым надо чуть разобраться. Но у меня проблем с освоением не возникло.
- Плавающее окно - может мозолить глаз. Это можно частично решить, сделав его полу-прозрачным пока не наведёшь мышку.

ps. Я тут не касаюсь скрола наверх, но это тоже можно было бы скопировать с Хабра. У них на левой стороне скрол наверх, а на правой - стрелки для хождения по комментарием. Скрол вверх, кстати, у них сделан как в ВК в виде вертикальной панели и при повторном нажатии он возвращает вниз.
![image](https://user-images.githubusercontent.com/51457/104130846-ac326a00-537b-11eb-8f31-b0491e34959c.png)

### Вопросы:
1. Внедряем систему прыгания по новым комментариям?
2. Делаем панель для быстрого скрола вверх и вниз?

**Comment by vas3k** [comment]
Выскажу своё имхо, можете с ним спорить. Панель навигации по комментам на хабре мне никогда не нравилась. Она раздражает, постоянно бегает, как будто какашка прилипла. Предлагаю устроить опрос как много людей вообще знала зачем она и как ей пользоваться.

Я бы объединил эти стрелочки с кнопкой наверх, взяв за основу дизайн ВК. Надо придумать как сделать это невсрато

**Comment by 1g0rrr** [comment]
Да. Ну я соглаен, что хабровский вид панели - "непривычный". ) Попробую тогда подумать как еще можно оформить.

Опрос - хорошая идея. Т.к. если уж стрелочки как-то оставлять, то полезно спросить мнение о них. Как его провести лучше?

**Comment by 1g0rrr** [comment]
Подсобрал тут референсы. 

### vc.ru 
**Скролл наверх:** нет кнопки
**Удобство лайка:** апвоут находится вконце поста.
**Обход непрочитанных:**  При наличии непрочитанных - плавающее окно справа. Причём, вертикально - не по центру.    При нажатии на кнопку - переход к следующему непрочитанному комментарию. 
**Сворачивание:** Есть полоска возле комментария, при нажатии - ветка сворачивается.
![image](https://user-images.githubusercontent.com/51457/104240686-225ecb80-5465-11eb-9827-4ffbe32490c9.png)

### Indiehackers
**Скролл наверх:** нет кнопки
**Удобство лайка:** Плавающая кнопка слева с возможностью лайка и шаринга поста.
**Обход непрочитанных:** Нет кнопки. Но если смотреть посты то у большинства вообще 0 коментов. Тоесть там общение в коментах не такое общепринятое. Хотя популярные посты есть.
**Сворачивание:** нет сворачивания
![image](https://user-images.githubusercontent.com/51457/104241166-eaa45380-5465-11eb-9b61-99c54685c3af.png)

### Reddit
**Скролл наверх:** При доскраливании до самого низа - есть кнопка "Back to top"
**Удобство лайка:** Плавающая панель для апвоута сверху с названием топика.
**Обход непрочитанных:** Нет кнопки
**Сворачивание:** Вертикальные полосы у комментариев, которыми можно свернуть ветку вручную. Часть комментов свёрнуто по дефолту по некому алгоритму
**Дополнительно:** Широкие полосы по краям страницы ведут на главную.
![image](https://user-images.githubusercontent.com/51457/104241253-0f003000-5466-11eb-972e-9653986175c3.png)

### Hackernews
**Скролл наверх:** нет кнопки
**Удобство лайка:** апвоут сверху. Но текст у постов минимальный.
**Обход непрочитанных:** Нет кнопки
**Сворачивание:** Есть кнопка сворачивания веток рядом с комментарием. Если коментов слишком много, появляется аналоговая пагинация.
![image](https://user-images.githubusercontent.com/51457/104240766-41f5f400-5465-11eb-87a9-55a5549cb444.png)

### Dev.to
**Скролл наверх:** нет кнопки
**Удобство лайка**: Плавающая кнопка слева с возможностью лайка и шаринга поста. (Как на Индихакерс)
**Обход непрочитанных:** Нет кнопки
**Сворачивание:** Есть кнопка сворачивания рядом с комментарием. 
![image](https://user-images.githubusercontent.com/51457/104240816-53d79700-5465-11eb-84d0-c036df9cd25b.png)

**Comment by vas3k** [comment]
@1g0rrr отличный рисерч, спасибо тебе за структуризацию! Я ушел думать. Другие могут тоже высказывать мнения и приносить еще референсы

**Comment by tripolitov** [comment]
Можно сделать что бы с клавы работала навигация по комментариям Ctrl + ↓ и Ctrl + ↑, но при этом на экране никаких прилипалок не было.

### Лепра

Скролл наверх: нет кнопки, в футере есть ссылка "Назад на заглавную" которая ведёт к списку постов
Удобство лайка: у поста и у коммента рейтинг при наведении на который появляются + и - для голосования
Обход непрочитанных: Есть прикрепленная сбоку панелька со стрелочками + есть управление с клавиатуры Ctrl + ↓ и Ctrl + ↑ позволяет перемещаться по непрочитаннам комментам
Сворачивание: Есть кнопка сворачивания комментарием, комментарии с низким рейтингом по умолчанию свёрнуты

#### Общий вид комментов
![image](https://user-images.githubusercontent.com/1122523/104278398-988d1d80-54b9-11eb-81a2-7e2d5458997f.png)

#### Интересная фича
![image](https://user-images.githubusercontent.com/1122523/104278522-c8d4bc00-54b9-11eb-95b8-a46ee5d58b00.png)

**Comment by Krakabek** [comment]
Накликал в инспекторе за пару минут вот такую кнопку вверх из элемента с плюсиками
![image](https://user-images.githubusercontent.com/6443205/107992707-eda0df80-6fe1-11eb-85ec-5316f5834f4a.png)

Можно её слева снизу впихнуть примерно 48x48 по размеру и делать подскролл наверх страницы. Как бонус, после подскролла наверх кнопка переворачивается и смотрит вниз, по повторному клику делает в предыдущее положение.

Для 1024px переключается лейаут, так что даже там хватит места на 48 пикселей слева снизу

В общей картине может выглядеть вот так:
![ezgif-3-b63b1eb276a5](https://user-images.githubusercontent.com/6443205/107992958-7e77bb00-6fe2-11eb-8fe0-bd748f913c75.gif)

**Comment by jtraub** [comment]
Я смотрю, что не только я страдаю от неоходимости в посте на 200 комментов искать 2-3 новых. 

Я себе написал давным-давно юзерскрипт для Tampermonkey и только что выложил его [вот тут](https://gist.github.com/jtraub/b4976939bd3c0f4ca08f098bfeb48f95). Возможно кому-то еще он будет интересен пока в самом клубе не придумано решение.

**Comment by vas3k** [comment]
Если кто-то соберется делать, мне лично нравится вариант с черной стрелочкой из коммента выше https://github.com/vas3k/vas3k.club/issues/491#issuecomment-779448537

Он самый простой и не выделяется по стилю.

По логике после всех миллионов обсуждений кто как видит эту фичу, я собрал такое поведение:

1. Загружается страница, стрелочка появляется в углу (правый или левый еще надо будет решить чтобы вписывалось во все типы постов)
2. Если под постом уже есть новые комменты, то по клику она переносит к первому непрочитанному комменту
3. Если новых комментов нет, она переносит просто к первому комменту сразу после поста (чтобы утолить желание "сразу читать комменты")
4. Дальнейшие клики листают по непрочитанным комментам и подсвечивают каждый
5. Если больше непрочитанных нет — стрелочка переносит на форму написания коммента
6. Дальше стрелочка меняется на стрелочку вверх и по еще одному клику переносит на самый верх страницы
7. Цикл повторяется

Непрочитанные комменты можно просто определять по CSS-классам на фронте. Не нужно держать их список или еще что-то. Просто ищем следующий блок с непрочитанным комментом ниже текущего центра экрана и всё.

**Comment by devcooch** [comment]
Честно говоря больше раздражает, что после первого же ответа список непрочитанных сбрасывается. Есть идеи как такое устроить?

**Comment by vas3k** [comment]
Тебе в другой тикет, давай не засорять этот еще большим количеством дискуссий, тут и так уже год никто не может разобраться что делать :(

**Comment by Zhurbin** [comment]
Закинул ПР решения из коммента https://github.com/vas3k/vas3k.club/issues/491#issuecomment-932042851, по-сути добавил графический интерфейс к этой вот https://github.com/vas3k/vas3k.club/pull/663 реализации.
