### ISSUE TITLE
Фича: Новый тип поста с анонимными комментариями

### ISSUE THREAD

**Issue by tripolitov** [vas3k/vas3k.club#495]
### Цель
Дать возможность высказать непопулярное менение или написать отзыв о компании в которой работаешь без риска быть осуждённым или наказанным за это.

### Предложение
Напрограммировать новый тип поста, у которого все комментарии будут анонимны. 

- Сделать так что бы даже в базу не сохранялось кто создал комментарий
- Ограничить чтоб такой пост нельзя было сделать публичным. Анонимность только внутри клуба
- При открытии такого поста комментатору яркими красивыми буквами писать, что тут всё анонимно, но ессно тереть мат
- Что бы не устроить анонимокханалию в клубе запретить создание подобных постов членам клуба у которых рейтинг ниже некого порога

**Comment by vlaim** [comment]
vas3k.2ch? :)

**Comment by vas3k** [comment]
Обдумал эту идею. Пока мне кажется, что она не вяжется с идеей клуба и спровоцирует лишь ненужную дополнительную агрессию согласно старой аксиоме https://knowyourmeme.com/memes/greater-internet-fuckwad-theory
