### ISSUE TITLE
Баг: "Политика в отношении обработки персональных данных" противоречит краткому содержанию

### ISSUE THREAD

**Issue by yeputons** [vas3k/vas3k.club#498]
Цитирую описание наверху страницы https://vas3k.club/docs/privacy_policy/ :

> У нас нет таргетированной рекламы, алгоритмических лент, гуглоаналитики и других сомнительных практик. 

При этом в, собственно, имеющем юридическую силу документе ниже написано:

> 3. Оператор может обрабатывать следующие персональные данные Пользователя
> ...  Также на сайте происходит сбор и обработка обезличенных данных о посетителях (в т.ч. файлов «cookie») с помощью сервисов интернет-статистики (Яндекс Метрика и Гугл Аналитика и других).

**Comment by vas3k** [comment]
Повтор. Я там объяснял уже, что прайваси полиси будем обновлять, но эти описания не противоречат друг другу  https://github.com/vas3k/vas3k.club/issues/480
