### ISSUE TITLE
Баг: некорректное описание лицензии CC BY-SA 4.0

### ISSUE THREAD

**Issue by yeputons** [vas3k/vas3k.club#499]
В правилах клуба сообщается, что используется лицензия "как на Википедии" — CC BY-SA 4.0: https://vas3k.club/docs/about/ (на самом деле на Википедии двойное лицензирование — как по CC BY-SA 3.0, так и по одной из модификаций GNU FDL, но это неважно).

Далее поясняется:

> Любые производные работы должны распространяться на тех же условиях. Иными словами, пост, опубликованный закрытым, нельзя скопировать и перевыложить в открытую и наоборот. Всегда спрашивайте разрешения автора.

Я не юрист, но мне кажется, что это может сильно вводить в заблуждение. Как я понимаю, дух клуба — в общении за закрытыми дверьми, однако лицензия CC BY-SA 4.0 этому напрямую противоречит. [В исходном тексте](https://creativecommons.org/licenses/by-sa/4.0/legalcode) нет никаких дополнительных ограничений на вынос из-под замка, наоборот, разрешается произвольное копирование куда угодно как угодно, пока а) есть ссылка на автора; б) производные работы распространяются под ровной такой же лицензией или совместимой; в) не добавляется дополнительных ограничений.

Да и в целом по духу лицензия CC BY-SA 4.0 — копилефтная, за свободное распространение: кто получил — может распространять дальше по любым каналам на таких же свободных условиях. Без уточнений про целевую аудиторию.

Я так понимаю, что прецедентов с выносом ещё не было (всё-таки закрытое сообщество с фильтрами), но, мне кажется, было бы честнее, если бы заявленная лицензия соответствовала реальной.

**Comment by yeputons** [comment]
Вроде по сравнению с #498 тут как раз противоречие, а не более широкое трактовка: краткое описание говорит, что выносить из-под замка нельзя, и оно же говорит, что используется копилефт, который разрешает выносить из-под замка.

**Comment by vas3k** [comment]
Тут соглашусь, нужна консультация тех, кто разбирается что значит Share Alike. Напомню, что суть лицензии СС не в том, чтобы запретить воровать подзамочные посты, а скорее чтобы защитить читателей (да и сам Клуб) от злонамеренных авторов, которые могут опубликовать пост, а потом попытаться засудить за его цитирование. Если кто-то не согласен со стандартной лицензией — он имеет полное право выложить пост под той, которая ему нравится больше, сделав это явно.

**Comment by vas3k** [comment]
Пофикшено. Убраны сравнения с википедией и пояснение про вынос из под замка
