### ISSUE TITLE
Не могу смотреть закрытые посты

### ISSUE THREAD

**Issue by mmyslyvyi** [vas3k/vas3k.club#5]
При попытке посмотреть посты только для клуба вылазит плашка с просьбой войти или вступить в клуб, при этом я уже авторизирован (см. правый верхний угол). После того как нажимаю войти, меня перебрасывает на мой профиль и ничего не меняется.
Возможно это связано с тем, что у меня 1$ подписка на патреон, а клуб вроде как пока для $3+.
<img width="1033" alt="Screenshot 2020-04-25 at 14 56 58" src="https://user-images.githubusercontent.com/16464827/80279261-0499dc80-8705-11ea-9bcb-5c0e47d8ed1f.png">

**Comment by vas3k** [comment]
Ого, а ты прав. Это баг, из-за которого людям, не прошедшим модерацию, показывалось неверное окошко. Попробуй открыть еще раз? Сейчас тебе должно показаться окошко, что ты не прошел, и кнопка «исправить и податься еще раз».

**Comment by mmyslyvyi** [comment]
Да, теперь все ок, окошко есть. Меня смутило то, что сначало я прошел модерацию и мог читать все посты. Наверное позже кто-то отключил меня вручную.

**Comment by mmyslyvyi** [comment]
А еще, меня только что заапрувили, но интро (и возможно описание профиля тоже) осталось старое и не изменилось.

**Comment by vas3k** [comment]
Возможно, какие-то траблы с кешом. Буду наблюдать, не знаю пока. Сейчас интро нормальное?

**Comment by mmyslyvyi** [comment]
Сейчас все ок
