### ISSUE TITLE
Узнать, за что поставили плюсики

### ISSUE THREAD

**Issue by bel0v** [vas3k/vas3k.club#50]
В дополнение к #22 было бы круто видеть, за что тебе плюсанули

**Comment by skywinder** [comment]
Пока такой возможности пока нет. 
Я был бы более чем счастлив увидеть PR с этой возможностью.  Это наверняка было бы полезно. 

Есть много похожих запросов (#3 #198 #22  #285).
 за что поставили  плюсики  - одна из подфич других. поэтому закрою, что бы не плодить сущности.
