### ISSUE TITLE
Фича: предпросмотр постов

### ISSUE THREAD

**Issue by dmitvitalii** [vas3k/vas3k.club#501]
### Как сейчас
В постах и комментариях поддерживается _markdown_ и есть отображение разметки во время изменения комментария. 

Также, сочетание **Ctrl+P/Cmd+P** покажет превью, но
1. Недоступно на мобилках
2. На белом фоне комментария
3. При длинных комментариях, отрендеренный Markdown "убегает" наверх, оставляя пустое поле.

https://user-images.githubusercontent.com/14320898/104820346-39c2fd80-5845-11eb-966a-1bc59c640951.mp4

### Как хочется
Было бы удобно иметь кнопку предпросмотра типа "Посмотреть, что получилось" чтобы оценить пост до его отправки. Например, как у гитхаба.

<img width="803" alt="Screenshot 2021-01-16 at 09 14 55" src="https://user-images.githubusercontent.com/14320898/104798867-4dd21500-57db-11eb-9a27-231f8a38e240.png">

**Comment by vas3k** [comment]
Кто-то даже начинал делать https://github.com/vas3k/vas3k.club/pull/289

**Comment by dimabory** [comment]
Главная проблема, как уже упоминалось, это UI/UX. Если есть предложения, то можно прям в PR предлагать, я доделаю.

**Comment by vas3k** [comment]
Чисто случайно сделали обходную реализацию этой фичи. Теперь при отправке поста автор всегда обязан пройти через стадию предпросмотра и пропустить ее нельзя. Это еще и добавит дополнительный шаг проверки "а не говно ли я пишу". 

Кому нужно предпросматривать много раз — можно открыть пост и редактор в соседних вкладках и обновлять по мере необходимости. Пока мне кажется это достаточно хорошо, чтобы не усложнять. Закрою.
