### ISSUE TITLE
Фича: новый тип поста с анонимным автором

### ISSUE THREAD

**Issue by dmitvitalii** [vas3k/vas3k.club#502]
Как в [Тинькофф-Журнале](https://journal.tinkoff.ru/diary-seo-specialistka-spb-90k/)
<img width="318" alt="Screenshot 2021-01-16 at 09 52 56" src="https://user-images.githubusercontent.com/14320898/104799497-9fc96980-57e0-11eb-9f15-64e8a6ccfc71.png">

Комментарии при этом не анонимны, анонимно может писать только автор анонимного поста.
Сами посты модерируются жёстко, перед полем с текстом – дисклеймер вида: "Анонимный пост – только если **действительно** есть что сказать". 

Как вариант, можно ограничить список дозволенных тем для анонимных постов.

Это покроет цель #495: _"Дать возможность высказать непопулярное менение или написать отзыв о компании в которой работаешь без риска быть осуждённым или наказанным за это."_
Это позволит говорить на табуированные темы, если человеку есть чем поделиться, но это может ему навредить: зарплаты, компании, проблемы, здоровье, хакинг ([как тут, например](https://www.youtube.com/watch?v=GUjDNvq2yNM)).

**Comment by nlopin** [comment]
Проминусил. 

Анонимным штукам место во внешнем интернете. Клуб — площадка, где неанонимность стоит во главе угла.

**Comment by uburuntu** [comment]
ebanoe.it

**Comment by vas3k** [comment]
Вот да. Не хочется превращать клуб в ебаное.айти или двач, а анонимность неминуемо спровицирует это
