### ISSUE TITLE
Баг: Связанные посты отображаются с лишним скроллом в Safari/Mac OS

### ISSUE THREAD

**Issue by cpatracker** [vas3k/vas3k.club#505]
При отображении блока «Связанные посты» на Macbook Air, 11,6-inch (1366 × 768), latest Mac OS (Big Sur 11.1), Safari выводится лишний скроллбар, пр. https://vas3k.club/post/beta/, блоки помещаются и без прокрутки.

![Screenshot 2021-01-18 at 12 46 16](https://user-images.githubusercontent.com/6206398/104911717-95979e80-598b-11eb-9538-9e9a61617733.png)

При отсутствии скроллбара остается полоска, пр. https://vas3k.club/post/7614/

![Screenshot 2021-01-18 at 12 44 01](https://user-images.githubusercontent.com/6206398/104911734-9a5c5280-598b-11eb-970f-21d8b6bab575.png)

Конкретная проблема решается удалением overflow-y:scroll из CSS блока, но это решение приведет к отсутствию скролла если связанных ссылок будет больше.

**Comment by vas3k** [comment]
> Конкретная проблема решается удалением overflow-y:scroll из CSS блока, но это решение приведет к отсутствию скролла если связанных ссылок будет больше.

Ну то есть не решается, да? :D Думаем дальше

**Comment by dimabory** [comment]
> > Конкретная проблема решается удалением overflow-y:scroll из CSS блока, но это решение приведет к отсутствию скролла если связанных ссылок будет больше.
> 
> Ну то есть не решается, да? :D Думаем дальше

Попробуй поставить `overflow-y: auto;`

![image](https://user-images.githubusercontent.com/11414342/104913530-689cb900-5996-11eb-859b-73dec099ec7f.png)

**Comment by batirko** [comment]
MacBook Pro 2019, 13.3-inch (2560 × 1600), latest Mac OS (Big Sur 11.1), Chrome, черная тема сайта.


https://user-images.githubusercontent.com/29608855/104913420-3ab77480-5996-11eb-9ab0-cf2f3070630b.mov

Присутсвует 2 вида скорла:
- обычная черная полоска, если курсор не указывает на скролбар
- белый фон скролбара (а ля "дефолтный скрол"), если курсор наведен на сам скрол бар

**Comment by cpatracker** [comment]
> Попробуй поставить `overflow-y: auto;`
Safari утверждает, что такого свойства не бывает.

![Screenshot 2021-01-18 at 13 10 29](https://user-images.githubusercontent.com/6206398/104913918-9c73e080-598e-11eb-941f-30cebcacec57.png)

**Comment by roandudel** [comment]
В Chrome 87.0.4280.141 и Firefox 84.0.2 на Windows тоже самое:

![image](https://user-images.githubusercontent.com/17112618/104919784-19a35380-5997-11eb-9af6-449348c1716d.png)

**Comment by nitso** [comment]
Windows/vivaldi (chrome 87) аналогичная проблема с отображением скролла, когда не нужно. Для себя решил в user-стилях так: 

    .linked-posts-scroll {
      overflow-y: auto;
    }

Но на это регресс нужно гонять в других браузерах 🤷‍♀️

**Comment by vas3k** [comment]
Добавили overflow: auto. Стало лучше? Будем увеличивать размеры чтобы влезало три поста без скролла или пофиг?

**Comment by cpatracker** [comment]
Проблема #2 ушла. Будем, конечно.
Изменение .linked-posts-scroll {padding: 30px 30px 30px 5px} на {padding: 30px 30px 10px 5px} у меня решает проблему. Не уверен, правда, что правильно понимаю область применимости этого класса, чтобы точно сказать что ничего больше никуда не съедет.

**Comment by vas3k** [comment]
> область применимости этого класса

Зона скроллинга — единственное место, где он применяется. Так что все ок, можно попробовать и так, тут вопрос чисто визуальной красоты

**Comment by cpatracker** [comment]
Отправил PR. Надеюсь, нигде не ошибся.
