### ISSUE TITLE
idea: background-image -> <img />

### ISSUE THREAD

**Issue by e965** [vas3k/vas3k.club#506]
Заметил, что по проекту прям очень много мест, где, по-хорошему (и по html-семантике!) должен стоять обыкновенный красивый `<img src="./image.jpg" alt="nice image" />`, но вместо этого стоят `<div>` (а то и вообще `<span>`), у которых через CSS-свойство `background-image` прокинута картинка.

Понимаю, что это, конечно, мелочь, но всё равно вопрос - зачем?

**Comment by vas3k** [comment]
Ты про аватарки юзеров? Там они нужны ради background-size: cover (автокропа по центру) и скругления. Семантика для автарок пофиг. Если сможешь сделать такое картинками — дерзай. У меня не получилось. Все аватарки разных размеров.
