### ISSUE TITLE
Вместе с никами регулярочка выделяет еще и остальные надписи

### ISSUE THREAD

**Issue by FMajesty** [vas3k/vas3k.club#51]
![Screenshot_20200429_015748](https://user-images.githubusercontent.com/14141649/80549234-f7a71280-89bc-11ea-80d1-b68567fa2ad7.png)

**Comment by FMajesty** [comment]
Как вариант - добавить вместе с проверкой по регулярке существование такого ника

**Comment by vas3k** [comment]
Прочерку на существование делать не хочу, слишком большой оверхед и не защитит от проблемы выше если кто-то зарегает ник gmail. Для имейлов надо добавить исключение. Подумаю как
