### ISSUE TITLE
Баг: Некорректное отображение количества комментариев в intro 

### ISSUE THREAD

**Issue by vlaim** [vas3k/vas3k.club#512]
Увидел тут https://vas3k.club/intro/lena/

![Screenshot 2021-01-19 at 13 20 46](https://user-images.githubusercontent.com/1304775/105034278-87b04f00-5a59-11eb-92b8-b2ef0c95e4be.png)

**Comment by vas3k** [comment]
Ок, обнулю. На Лене часто тестим новые фичи, у нее может ломаться
