### ISSUE TITLE
Идея: "Мне повезет" для постов и людей

### ISSUE THREAD

**Issue by Austinate** [vas3k/vas3k.club#520]
Предлагаю добавить в меню нечто вроде "Мне повезет" и при нажатии открывать рандомный пост.
Как вариант, можно еще и сделать такое для /people 

Прямая полезность сомнительна, но может быть весело тем кто уже прочитал всё в общем фиде или ищет контакты для знакомства.

**Comment by vas3k** [comment]
Сделали команду бота /random, наслаждайся
