### ISSUE TITLE
Система веток для комментариев.

### ISSUE THREAD

**Issue by murka** [vas3k/vas3k.club#521]
Сейчас если слишком много ответов к комментариям, приходится долго скроллить до следующего комментария.

Предлагаю решение сделанное как Habr, TJournal, VC - система веток.

Пример на Habr:
![image](https://user-images.githubusercontent.com/41015519/105340410-a7817780-5bff-11eb-9873-57206fbdbf0c.png)

**Comment by vas3k** [comment]
Поддерживаю, в моем личном TODO этот пункт давно висит. Нужны дизайны и референсы. Предлагаю постить в этот тред кому что нравится.

**Comment by dshuran** [comment]
Сильно плюсую, фича очень нужна. Говорю, как человек, который читает посты раз в неделю и пролистывает кучу комментов к первому ответу на пост. Залез сюда именно для того, чтобы предложить нечто подобное, а оно уже даже в закрепе. Уже начал ковыряться со Vue и попробовал бы запилить эту фичу, когда придём к единому решению. 

Я адекватной системы веток не видел практически нигде. На том же хабре, оказывается, можно так делать, судя по скрину выше, но нахаляву я такой кнопки не увидел, как и на vc. Предлагаю что-то такое: под каждым ответом к посту отображается два субкоммента. Чтобы раскрыть остальные комментарии необходимо тыкнуть на кнопку "Раскрыть ветку", как на скрине выше.  

Почему так:

- Это не засоряет страницу и позволяет быстро просмотреть заплюсованные ответы к посту, не вдаваясь в подробности самого верхнего ответа и дискуссии на 100500 комментариев.
- Два верхних коммента (можно чуть больше) под ответом к посту позволяют понять, в каком направлении дальше двинулась дискуссия, и если есть желание, можно раскрыть эту ветку и читать до конца. 
- Потенциально это не противоречит созданию более сложной системы веток, если вдруг захочется сделать для субкомментов субсубкомменты. 

Суммируем. Итоговая реализация будет выглядеть так:

Пост

Ответ к посту №1
  - Субкоммент1
  - Субкоммент2
  - Показать ещё...
Ответ к посту №2
  - Субкоммент1
  - Субкоммент2
  - Показать ещё

**Comment by vas3k** [comment]
@dshuran честно говоря, я бы не скрывал комменты по-умолчанию, а наоборот — давал возможность свернуть ветку, если она неинтересна. Мне такая система всегда нравилась больше, плюс у нас комменты очень важны, чтобы их безжалостно скрывать. Я это вижу как кнопку "минусик" типа как на Hacker News, но только в дизайне не из 90-х :D

**Comment by dshuran** [comment]
> @dshuran честно говоря, я бы не скрывал комменты по-умолчанию, а наоборот — давал возможность свернуть ветку, если она неинтересна. Мне такая система всегда нравилась больше, плюс у нас комменты очень важны, чтобы их безжалостно скрывать. Я это вижу как кнопку "минусик" типа как на Hacker News, но только в дизайне не из 90-х :D

Да, клёво! Ещё немного соображений: вот прочитал я пост, начал ответы к этому посту, и мне правда интересно, но спустя 5-6 хочется уже свернуть всю ветку. А при данном подходе так не получится сделать. Придётся листать вверх, чтобы свернуть основной ответ. Или уже продолжить сворачивать все комменты вниз пока не дойдём до следующего ответа на пост. 

С другой стороны, можно разбить на два этапа. Первым сделать всё так, как на Hacker News, а вторым добавить справа внизу стрелочку, которая быстро позволяет перейти к следующему ответу на пост. Если в этом будет необходимость.

**Comment by vas3k** [comment]
@dshuran да, сделать навигационную штуку по новым комментам тоже надо, про это уже даже есть отдельный ишью. Но давай разделим это на два тикета, иначе это превратится в монстра. Сначала делаем ветки, релизим, потом навигацию по ним.

Там тоже куча подводных камней будет с дизайном. В том тикете вроде накидали годных идей в конце

**Comment by dshuran** [comment]
> @dshuran да, сделать навигационную штуку по новым комментам тоже надо, про это уже даже есть отдельный ишью. Но давай разделим это на два тикета, иначе это превратится в монстра. Сначала делаем ветки, релизим, потом навигацию по ним.
> 
> Там тоже куча подводных камней будет с дизайном. В том тикете вроде накидали годных идей в конце

Да, ок, тогда по идеям дизайна. Посмотрел разные варианты. Прикрепляю их - https://imgur.com/a/A8WmXbh

Мне нравится идея галочки (1-я и 3-я фотки). А расположить её можно слева от плюсика. 
Если не нравится такой вариант, то можно рассмотреть а-ля треугольник на второй фотке, который идёт слева от заголовка. Это позволит исключить мисклики, когда хотел тыкнуть на плюсик, а свернул пост, но думаю, что так менее удобно.

**Comment by vas3k** [comment]
Галочка ок. Еще бы как-то визуально подсвечивать тред ниже при наведении на неё чтобы было понятно что она скрывает

**Comment by vas3k** [comment]
Сделали!
