### ISSUE TITLE
Баг: блок связанных постов отображается на всю ширину экрана

### ISSUE THREAD

**Issue by Galichev** [vas3k/vas3k.club#522]
Safari, MacOS
https://vas3k.club/link/54/
В других публикациях все в порядке.

![Screenshot 2021-01-21 at 11 54 52](https://user-images.githubusercontent.com/6612793/105341683-afc9ba80-5bdf-11eb-9604-7e3f71398d75.png)

**Comment by MartOleks** [comment]
Еще один пример
Windows 10, Chrome Version 88.0.4324.96 (Official Build) (64-bit), Firefox 84.0.2 (64-bit)
https://vas3k.club/link/2609/

![image](https://user-images.githubusercontent.com/77833996/105476872-6d68b200-5ca1-11eb-9e78-ec42875a3422.png)
