### ISSUE TITLE
Фичареквест: добавить кнопку "Вернуться наверх" в постах

### ISSUE THREAD

**Issue by vorant94** [vas3k/vas3k.club#524]
Бывает зашел в топовый тред с кучей комментариев, пролистал все под пивко и хочешь вернуться обратно на главную поискать еще чего почитать, а приходится наматывать колесико мышки как не знаю кто, потому что пост-то топовый и комментов реально много

Можно было бы просто возвращаться назад по истории браузера, но я часто захожу в посты из вне сайта/главной страницы, поэтому этот вариант не доступен...

Что думаете?

**Comment by dmitvitalii** [comment]
В #491 уже обсуждается такая фича

**Comment by vorant94** [comment]
Сорри
