### ISSUE TITLE
Баг: Не могу чистить реплаи на аргументы под своим баттлом

### ISSUE THREAD

**Issue by vorant94** [vas3k/vas3k.club#525]
в сообщении про бету было написано, что “Автор имеет практически власть модераторов под своими постами”

я, да, вижу кнопки припинивания и удаления комментов в вопросах и идеях, а вот в баттлах кнопка удаления есть только на аргументах. при наведении на реплай на аргумент ничего не появляется

Хавер на аргументе | Хавер на реплае
------------------ | - 
<img width="839" alt="Screen Shot 2021-01-23 at 19 46 08" src="https://user-images.githubusercontent.com/9719319/105610062-fec94880-5db5-11eb-8c7f-c69d531f3b8b.png"> | <img width="724" alt="Screen Shot 2021-01-23 at 19 46 24" src="https://user-images.githubusercontent.com/9719319/105610063-00930c00-5db6-11eb-8c40-cbfbf56cafb5.png">

не то, чтобы эти скрины подтверждают, что я навел курсор, но ничего лучше предложить не могу😅

**Comment by vas3k** [comment]
Проверь через минут пять, должно заработать
