### ISSUE TITLE
Не работает поиск по сайту

### ISSUE THREAD

**Issue by nialvi** [vas3k/vas3k.club#529]
**Условия**
- воспроизвел на всех своих устройствах window/mac/android (кажется дело не в них)

Шаги
- в поиске вбить любой запрос

например:
https://vas3k.club/search/?q=%D0%B8%D0%BF%D0%BE%D1%82%D0%B5%D0%BA%D0%B0

![Снимок экрана 2021-01-25 в 08 20 51](https://user-images.githubusercontent.com/6734579/105664672-4b13a600-5ee6-11eb-92f3-044d2b804cb9.png)

**Comment by vas3k** [comment]
Починил, странно
