### ISSUE TITLE
Идея: выдавать список юзеров по ачивкам

### ISSUE THREAD

**Issue by shkaff** [vas3k/vas3k.club#532]
Было бы круто по нажатию на бейдж ачивки выдавать юзеров с такими же. Интересно посмотреть, кто пилит лучшие посты, кто - среди олдов, а кто хорошо разбирается в тракторе. В поиске людей фильтров и так полно, а вот отсюда можно было бы переходить: https://vas3k.club/achievements/

**Comment by vas3k** [comment]
Ок идея, можно передизайнить страницу ачивок чтобы показывало юзеров под каждой. Кто-нибудь может надеть мантию дизайнера и порисовать на досуге :)

**Comment by dmitvitalii** [comment]
Уже реализовано
