### ISSUE TITLE
Баг:  ломается ссылка читать все интро

### ISSUE THREAD

**Issue by MartSlaaf** [vas3k/vas3k.club#533]
В последнем обзоре недели (скрина не будет по соображениям конфиденциальности) у второго пользователя из популярных новичков сломана ссылка.

Ожидаемое поведение: как и остальных ведет на профиль
Реальное поведение: ведет вникуда с обрывками разметки прямо в ссылке

**Comment by MartSlaaf** [comment]
Причина: ревью кропается как плейн-текст и в превью влезает кусок кода ссылки, вместо реального текста.

**Comment by araslanov-e** [comment]
@vas3k https://vas3k.club/weekly_digest/2021_15/ первая ссылка на интро

**Comment by skywinder** [comment]
пофиксили.
