### ISSUE TITLE
Фича: скопировать ссылку на комментарий

### ISSUE THREAD

**Issue by alexkhismatulin** [vas3k/vas3k.club#536]
Предлагаю добавить кнопку копирования ссылки на комментарий. Технически уже есть возможность открывать конкретный комментарий, но нет возможности получить ссылку для произвольного коммента. Пару раз нужно было поделиться ссылкой, и пришлось решать это путем ручного построения урла :)
Выглядеть это может примерно так:
![image](https://user-images.githubusercontent.com/23404496/105802451-40234900-5fac-11eb-96f8-f3f26837264b.png)

**Comment by Brawlence** [comment]
![Нажми на время](https://user-images.githubusercontent.com/42910943/105913342-bd4ace80-603d-11eb-8f1b-52d2d93b4a85.png)

**Comment by alexkhismatulin** [comment]
@Brawlence Да, спасибо, это работает, но функционал максимально скрыт от пользователей. Это, наверное, последняя вещь, на которую я бы посмотрел.

**Comment by vas3k** [comment]
Значит ты очень обрадуешься когда узнаешь, что в Фейсбуке, Твиттере и даже вот здесь на гитхабе эта фича работает так же! :)
