### ISSUE TITLE
Фича: /whois для пересланных сообщений

### ISSUE THREAD

**Issue by yeputons** [vas3k/vas3k.club#541]
Сейчас `/whois` можно использовать в чате, но это всем видно + засоряет чат. Предлагаемый юзкейс: переслать сообщение боту в личку, дать ему команду `/whois`, а он ответит, кто автор пересланного сообщения, а не кто его переслал.

Кажется, в [`bot/handlers/whois.py`](https://github.com/vas3k/vas3k.club/blob/4dfc2b0ab8432d67ae9dc41c3a01fbe47ef410a5/bot/handlers/whois.py) можно сделать следующее:

1. Если нет `message.forward_date` — работает в точности как раньше (это кейс для групповых чатов).
2. Иначе первой строчкой выдать сообщение как раньше (про того, кто переслал) с пометкой вроде "Сообщение переслал: ", а на второй строчке:
3. Если нет `message.forward_user` — то выдать сообщение вроде "Кажется, {message.forward_sender_name} скрыл свой профиль для пересылаемых сообщений, попробуй дать команду в ответ на исходное сообщение".
4. Иначе выдать на второй строчке инфу про `message.forward_user` с пометкой "Исходный автор: ...".

Разумеется, можно сделать и нормальные сообщения об ошибках со связным текстом, но тогда надо случаи поразбирать.

**Comment by vas3k** [comment]
Поддержку форвардов можно смело добавлять

**Comment by devcooch** [comment]
Работает. Необходимо сделать сначала боту форвард, а потом на этот форвард ответить /whois.
