### ISSUE TITLE
Баг: заголовки черновиков видны неавторизованым пользователям, но не обычным пользователям

### ISSUE THREAD

**Issue by yeputons** [vas3k/vas3k.club#545]
Например: https://vas3k.club/battle/8067/ в инкогнито прекрасно открывается с заголовком "Батл: Видеоигры - плохо или Видеоигры - хорошо — Вастрик.Клуб" и кодом 200, а вот если залогиниться — 404 Not Found.

Неконсистентно.

Кажется, надо как минимум в [`posts/views/posts.py`](https://github.com/vas3k/vas3k.club/blob/4dfc2b0ab8432d67ae9dc41c3a01fbe47ef410a5/posts/views/posts.py#L24-L33) поменять местами два ифа и сначала выдавать 404, а потом уже светить в публичный интернет заглушку.

Возможно, есть похожие проблемы где-то ещё.

**Comment by uhbif19** [comment]
Я дурак, и не заметил существования PR. @dmitvitalii извиняюсь за возможный конфликт интересов.

Но мой PR содержит тесты, так что предлагаю брать его.
