### ISSUE TITLE
Фича: Благодарности участникам

### ISSUE THREAD

**Issue by batirko** [vas3k/vas3k.club#553]
### Контекст
Участники клуба делают классные штуки для других участников клуба. Создают АМА, что-то объясняют друг-другу в комментариях и в чатах, помогают чем-то мелким. Иногда хочется сделать чуть больше, чем плюсик поставить.

### Идея
Секция на сайте, где можно указать человека из клуба и написать текст благодарности. В конце недели выводить эти благодарности в дайджесте.

### Реализация секции
- Поле для ввода никнейма в клубе с @ (если будет подсказка, то вообще отлично)
- Textarea для благодраности с лимитом в 300(?) символов
- Кнопка сабмит

После отправки комменты не видно никому, отображаются только в дайджесте.

Кнопка на благодарность может также быть в профиле у человека > откроет эту секцию с уже вставленным никнеймом.

> Дополнительно: благодарность может приносить плюсик тому, кого благодорят.

**Comment by vas3k** [comment]
> Секция на сайте, где можно указать человека из клуба и написать текст благодарности

Как на счет интро? По-моему идеально

**Comment by Galichev** [comment]
Мне кажется, речь идет об анонимной благодарности. Как анонимная благотворительность.

**Comment by batirko** [comment]
Не уверен насчет фактора анонимности, но тоже тема.

А так, основная идея была в том, чтобы в дайджесте наблюдать последние крутые активности, которые выходят за рамки самых обсуждаемых постов и лайкнутых комментов. А не чтобы это копилось в профиле участника.

**Comment by devcooch** [comment]
А в чём отличается от ачивок?

**Comment by devcooch** [comment]
Анонимно ничего делать не надо иначе люди будут писать "ты какаха, благодарю".

**Comment by Galichev** [comment]
> Анонимно ничего делать не надо иначе люди будут писать "ты какаха, благодарю".

Администратору все видно, так что это бан.
У нас уже есть анонимное голосование за посты, не вижу проблемы с анонимной благодарностью. Если речь идет о том, чтобы потом публиковать эти сообщения в дайджесте, этот комментарий уже становится публичным. Если у него будет еще и имя - ура, мы получили секцию «комментарии» в интро. Попросим начинать сообщение со слова «Спасибо» и тикет можно закрывать.

**Comment by batirko** [comment]
Если честно, то я не то чтобы очень отстаиваю эту идею и сильно хочу чтобы ее воплотили. Просто обсуждали это в баре, показалось неплохой мыслью - решил занести ее сюда. Если закроете ишью, то я не расстроюсь))

**Comment by Galichev** [comment]
> Если честно, то я не то чтобы очень отстаиваю эту идею и сильно хочу чтобы ее воплотили. Просто обсуждали это в баре, показалось неплохой мыслью - решил занести ее сюда. Если закроете ишью, то я не расстроюсь))

Я очень отстаиваю. Держать строй!

**Comment by vas3k** [comment]
Мне бы хотелось иметь что-то типа книги благодарностей Клубу или другим его участникам, это круто в том числе как хороший пример для новичков, чтобы они понимали что здесь вообще происходит и как конкретно люди здесь самоорганизуются и помогают друг другу. Но пока я не придумал в каком формате это сделать, как стимулировать людей писать туда, ну и как защищаться от попыток абузить такую гостевуху мемами и дикпиками. Отмечу как idea, буду ждать, что кто-нибудь возьмет на себя и проработает продуктовую часть.

**Comment by vas3k** [comment]
Сделали награды, получилось заебись
