### ISSUE TITLE
Баг: изменения в посте, сделанные после превью, не сохраняются

### ISSUE THREAD

**Issue by shkaff** [vas3k/vas3k.club#556]
Когда при публикации нажимаешь: "Предпросмотр", а потом "Черновик" и пытаешься внести изменения, они не сохраняются. Публикуется та версия, которая была на момент нажатия "Предпросмотр".

**Comment by vas3k** [comment]
А как ты редактируешь во второй раз пост? По кнопке back или открытием черновика заново?

**Comment by shkaff** [comment]
После того, как открывается предпросмотр, там сверху под названием большая кнопка "черновик". Я нажимаю на нее
<img width="332" alt="Screenshot 2021-02-14 at 14 39 28" src="https://user-images.githubusercontent.com/2661956/107878368-11710200-6eca-11eb-975a-8f0dbd4d0904.png">
Оно переходит в редактор, но изменения, сделанные в нем, не сохраняются.

**Comment by vas3k** [comment]
Только что проверил, у меня сохраняется. Можешь записать видео что конкретно ты нажимаешь и как?

**Comment by shkaff** [comment]
Вот запись
![Screen Recording 2021-02-14 at 14 46 58](https://user-images.githubusercontent.com/2661956/107878645-0b7c2080-6ecc-11eb-9553-84eed58fa000.gif)

**Comment by vas3k** [comment]
О, теперь кажется понял, спасибо

**Comment by vas3k** [comment]
Видосик правда помог, неприятный косяк был, пофиксил
