### ISSUE TITLE
Баг: в разделе Люди (карта) не работает фильтр по тегам

### ISSUE THREAD

**Issue by ogroleg** [vas3k/vas3k.club#559]
Например, "в моем городе" + "велосипед" возвращает 0 результатов. У меня в профиле добавлен "велосипед", т.е. должен бьіть как минимум 1 результат.
https://vas3k.club/people/?query=&country=&filters=same_city&tags=cycle

**Comment by ogroleg** [comment]
upd. похоже не только теги не работают 
![image](https://user-images.githubusercontent.com/9316141/107875333-f43b3400-6ec7-11eb-88f0-1663cba33d25.png)

**Comment by vas3k** [comment]
По воскресеньям поиск переиндексируется, а сегодня что-то пошло не так и скрипт упал  :) Разбил на чанки, теперь не должен падать
