### ISSUE TITLE
Форма комментариев едет от длинных ссылок

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#56]
Пример ссылки: 
`https://ru.wikipedia.org/wiki/%D0%A1%D1%83%D0%B1%D0%BB%D0%B8%D0%BC%D0%B0%D1%86%D0%B8%D1%8F_(%D0%BF%D1%81%D0%B8%D1%85%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F)`

Если вставить такое в коммент, все поедет. Но если просто добавить overflow: hidden — это ломает тени. Печаль. Надо что-то с этим придумать (в реплаях то же самое)

<img width="1098" alt="Screenshot 2020-04-29 at 09 36 57" src="https://user-images.githubusercontent.com/176344/80571490-fe557a00-89fc-11ea-95ad-7e11e46e5b5c.png">

**Comment by tyhonchik** [comment]
Можно max-width выставить для .comment-form .CodeMirror, это если ты прям знаешь кол-во пикселей.
![image](https://user-images.githubusercontent.com/30229764/80573585-e552c600-8a08-11ea-9628-e741f0b1aa6c.png)

Ну а в идеале, наверно, шортенить ссылки

**Comment by vas3k** [comment]
@tyhonchik неа, это криво, на мобилочках и планшетиках тогда всё равно будет ехать. Я тоже пытался придумать решение и за 10 минут не смог. Потому пометил как CRITICAL и жду помощь коммьюнити :D

**Comment by ganqqwerty** [comment]
Может быть, я банальность скажу, но ведь можно к классу  `CodeMirror-line` приделать  css-свойство `word-break: break-word` ? [Должно работать на обычных браузерах](https://caniuse.com/#search=word-break).
![image](https://user-images.githubusercontent.com/697308/80582212-94de6700-8a0e-11ea-826a-c2145fa207ce.png)

**Comment by vas3k** [comment]
@ganqqwerty хм, а это и правда интересно. Попробую добавить на сайт, потестим

**Comment by vas3k** [comment]
По ходу больше не едет. Закрою тогда, всем спасибо!
