### ISSUE TITLE
Не сохраняются правки в режиме предпросмотра

### ISSUE THREAD

**Issue by lobotomoe** [vas3k/vas3k.club#560]
Есть кейс, который хотелось бы проверить, но я не могу это сделать, так как это связано с публикацией поста.

1. Жмем "Написать", пишем пост
2. Кнопка "Предпросмотр" (пост попадает в черновик)
3. Переходим в "правка"
4.  **Правим (!)**
5. Жмем "Опубликовать"

Кажется то, что я правил на шаге 4, не сохранилось при публикации на шаге 5.

**Comment by vas3k** [comment]
Пофикшено, спасибо
