### ISSUE TITLE
Идея: значок за реализацию рецептов в Вастрик.Кухня

### ISSUE THREAD

**Issue by Pavel216989** [vas3k/vas3k.club#564]
Привет!
Мы тут в Вастрик.Кухня придумали публиковать рецепты блюд и готовить их всем сообществом. 
В первую неделю делали ризотто, а сейчас мусаку. 
Возникла идея давать значки тем, кто приготовит определенное количество блюд. Например, 3 рецепта подряд = значок. Как тебе?

**Comment by vas3k** [comment]
Это офигительная идея. Как на счет такого:

<img width="364" alt="Screen 2021-02-18 at 00 39 51" src="https://user-images.githubusercontent.com/176344/108282419-def12e80-7181-11eb-8cb3-e94a5d0ec4a9.png">

**Comment by vas3k** [comment]
Нужно только чтобы кто-то следил за этим и писал на почту moderator@vas3k.club когда кто-то достоен этого почетного звания. Можешь ты сам или просить кого-то в комментах. Норм же?

**Comment by devcooch** [comment]
Я слежу :) Давайте за три рецепта выдавать )

**Comment by devcooch** [comment]
> Вот список ачивок: https://vas3k.club/achievements/

а.. оо! она уже была!

**Comment by vas3k** [comment]
>  а.. оо! она уже была!

Еще как была. Я знал ваши кулинарные наклонности с самого начала. Просто никто не обращался :)

По ачивкам вообще норм писать на почту и рекомендовать кого-то, там реквесты очень удобно трекаются.

**Comment by devcooch** [comment]
А где кстати вот эта ссылка видна пользователям?  не нашёл https://vas3k.club/achievements/

**Comment by vas3k** [comment]
А нигде :) Это секретная ссылка для тех, кто шарит. Таких будет еще много. Easy to learn, hard to master
