### ISSUE TITLE
Странно сами удаляются комментарии 

### ISSUE THREAD

**Issue by Tkhorik** [vas3k/vas3k.club#569]
Chrome Version 88.0.4324.192 (Official Build) (x86_64)
Mac

открываем тему
пишем комментарии на чейто комментарии. в топике
пишем еще комментарии в топике
первый комментарии самовыпиливается
[видос](https://drive.google.com/file/d/1Wt97zFuJApccx1dMCtYOFiSb_Wtf08Rq/view?usp=sharing)

**Comment by vas3k** [comment]
Спасибо за репорт. Если у кого-то еще воспроизводится, пожалуйста, отпишитесь здесь в комментах. 

Звучит как дичь, конечно. Если бы она была правдой — нас бы уже завалили письмами с жалобами :)

**Comment by Tkhorik** [comment]
я встречал комментарии в телего о подобном. Типа: "Говорили что цензуры нет, а тут вот такое..."

**Comment by vas3k** [comment]
> Говорили что цензуры нет, а тут вот такое...

Такие комментарии появляются на каждое удаление модераторами чьей-то гифки с какашками с главной
