### ISSUE TITLE
Идея - редакторские контролы в комментариях

### ISSUE THREAD

**Issue by maurezen** [vas3k/vas3k.club#573]
What it says on the tin. 

Возможно, я просто слишком зеленый нуб и все работает как задумано, но - в отличие от формы для написания поста, форма написания комментариев девственно чиста. Мне, как зеленому нубу, пришлось пойти в форму написания поста, чтобы узнать, как именно здесь полагается прикреплять картинку в комментарий. 

Это, конечно, markdown, но, во-первых, не все им ловко пользуются из головы, а во-вторых - может, имеет смысл в форме комментария если не кнопочки редакторские добавить, то хотя бы напомнить, что, мол, здесь можно markdown?

**Comment by ktaranov** [comment]
@maurezen Сделаем в интро про фишки клуба, благодарю за идею.
