### ISSUE TITLE
Не получается удалить свой ответ к баттл-посту

### ISSUE THREAD

**Issue by ganqqwerty** [vas3k/vas3k.club#58]
Заходим в один из батлов, пишем пост за одну из сторон. Пытаемся удалить пост, нажав на кнопочку с урной. 
**Ожидаемый результат**: заголовок поста и длинное описание удаляются и заменяется на сообщение о том, что автор его удалил.
**Сегодняшний результат**: удаляется лишь длинное описание поста. Похоже кнопочка с урной относится лишь к комментарию, а не ко всему посту.
Результат выглядит так: 
![image](https://user-images.githubusercontent.com/697308/80581268-36fd4f80-8a0d-11ea-8f7c-cd20c8ac8123.png)

**Предложение**: добавить кнопочку с урной также к заголовку и дать возможность удалять весь пост целиком.

**Comment by FMajesty** [comment]
Дубликат #42

**Comment by vas3k** [comment]
Не, это отдельно. Я предлагаю из батлов вообще скрывать удаленные комменты первого уровня. Они занимают слишком много места, ну и это не создаст логических противоречий

**Comment by vas3k** [comment]
Пофикшено
