### ISSUE TITLE
Баг: некорректная сортировка при использовании поиска

### ISSUE THREAD

**Issue by Galichev** [vas3k/vas3k.club#581]
Поиск по @galichev, сортировка «по свежести», даты не идут в хронологическом порядке

![Screenshot 2021-03-16 at 18 42 11](https://user-images.githubusercontent.com/6612793/111355940-25a24d80-8688-11eb-8f2d-65cd4d549594.png)

**Comment by llirikcmb** [comment]
Я что-то не понимаю в этой системе. Баг вроде закрыт еще в марте. Сам перепроверил действительно проблема с сортировкой уже не повторяется. Зачем добавили плашку hacktoberfest? Тут есть еще чем помочь?

**Comment by vas3k** [comment]
Убрал плашку, а вот про баг не знаю, можно проверить

**Comment by Galichev** [comment]
> Я что-то не понимаю в этой системе. Баг вроде закрыт еще в марте. Сам перепроверил действительно проблема с сортировкой уже не повторяется. Зачем добавили плашку hacktoberfest? Тут есть еще чем помочь?

Проблема на месте, прикрепил более полный скриншот

![Screenshot 2021-10-10 at 21 01 16](https://user-images.githubusercontent.com/6612793/136709697-b2945631-8e5d-46b4-baf1-f6a9a9971e37.png)

**Comment by vas3k** [comment]
Наконец-то пофиксил
