### ISSUE TITLE
Фича: якори для заголовков внутри статьи

### ISSUE THREAD

**Issue by dmitvitalii** [vas3k/vas3k.club#584]
Автоматически делать заголовки якорями. Хотя бы первых двух уровней (`##` и `###`).

[Вот как тут](https://vas3k.club/docs/about/)

При наведении менять яркость заголовка.
При клике копировать ссылку в буфер обмена.

**Comment by vas3k** [comment]
Норм фича, у меня в блоге так сделано. Только давайте без копирования в буфер, просто хеш в строке менять

**Comment by ktaranov** [comment]
> Норм фича, у меня в блоге так сделано. Только давайте без копирования в буфер, просто хеш в строке менять

Можешь линк бросить на реализацию? это готов сделать, самому нужно.

**Comment by vas3k** [comment]
@ktaranov у меня в блоге так сделано, но там код не опенсорснут. Я просто в маркдауне назначаю каждому заголовку его уникальный хеш. Можно порядковый номер, но тогда при редактировании собьется, можно брать первые 6-8 символов от sha1

**Comment by dmitvitalii** [comment]
Судя по 
https://vas3k.club/post/10963/#Doroga
фича реализована
