### ISSUE TITLE
Баг: Невозможно восстановить удалённые мной же комментарии

### ISSUE THREAD

**Issue by coralmess** [vas3k/vas3k.club#588]
При удалении чужого комментария под постом появляется вот такая надпись
![image](https://user-images.githubusercontent.com/47054302/112968277-d0b90980-9154-11eb-90b1-dec4d8c46b50.png)
На которой всё ещё остаётся кнопка удаления, хотя комментарий уже удалён

При повторном нажатии на кнопку вылазит аналогичный alert тому, что был при удалении с вопросом "Удаляем?" и при нажатии на Ок - возникает вот такое окно
![image](https://user-images.githubusercontent.com/47054302/112968529-0fe75a80-9155-11eb-8f3a-4dc4c4de1f42.png)
Хотя комментарий удалил я.

**Comment by vas3k** [comment]
Надо проверить. А дай линк на удаленный комментарий? (клик по дате)

**Comment by coralmess** [comment]
https://vas3k.club/question/9198/#comment-b681ced3-ea1b-4368-8f66-b4b57c0cb3ba

**Comment by dmitvitalii** [comment]
Тоже не смог воспроизвести. Пишет "😱 Комментарий удален его автором..."
