### ISSUE TITLE
Исправить ссылку в политике приватности

### ISSUE THREAD

**Issue by mrnkov** [vas3k/vas3k.club#59]
В последнем абзаце [политики безопасности](https://vas3k.club/docs/privacy_policy/) указана неправильная гиперссылка

Сейчас: https://vas3k.club/doc/privacy_policy
Нужно: https://vas3k.club/docs/privacy_policy/

**Comment by mrnkov** [comment]
Баг остался. Опечатка именно в **doc** вместо **docs**

**Comment by vas3k** [comment]
О, спасибо, не заметил
