### ISSUE TITLE
Баг: в некоторых случаях ломается счётчик новых комментариев

### ISSUE THREAD

**Issue by ngrishanov** [vas3k/vas3k.club#592]
<img width="759" alt="Снимок экрана 2021-04-08 в 13 53 21" src="https://user-images.githubusercontent.com/6131548/113998012-16bb4f00-9872-11eb-986d-a9c314f531eb.png">

Не уверен, как так получилось, но в треде много удалённых комментариев, возможно связано с этим.

<img width="794" alt="Снимок экрана 2021-04-08 в 13 56 42" src="https://user-images.githubusercontent.com/6131548/113998208-4702ed80-9872-11eb-8958-d9cfcdac0489.png">

**Comment by vas3k** [comment]
Можно, конечно, уменьшать всем счетчики непрочитанных при удалении комментов, но это технически нелегко, так что я бы забил пока :D

**Comment by skywinder** [comment]
забили. закрываю
