### ISSUE TITLE
Фича: id аттрибут у заголовков или автогенерация table of contents для постов

### ISSUE THREAD

**Issue by m0rtyn** [vas3k/vas3k.club#593]
Не один Вастрик любит писать лонгриды и в таких случаях не хватает возможности видеть содержание по заголовкам.

Больше расстраивает, что содержание нельзя сделать даже своими силами в markdown, потому что у заголовков нет якорных аттрибутов. Один из альтернативных путей это добавление базовых html-тегов внутри markdown (как на Habr'е).

Стартую ишью для понимания почему этого нет сейчас и какие есть сложности в реализации. Возможно сам смогу выполнить запрос.

**Comment by vas3k** [comment]
Сделали
