### ISSUE TITLE
Поиск по комментариям

### ISSUE THREAD

**Issue by uPagge** [vas3k/vas3k.club#602]
Предлагаю прикрутить поиск по комментариям к посту.

Вот допустим есть пост

https://vas3k.club/question/2166/

там уже набежало 209 комментариев, я хочу написать про свой рюкзак, но не хотел бы повториться, если про него уже писали. Если прикрутить поиск, то я мог бы поискать название рюкзака, тезисов ну и проч.

**Comment by vas3k** [comment]
Cmd+F?

**Comment by uPagge** [comment]
> Cmd+F?

Эм, а все комментарии загружаются разом, это конечно тоже не круто :D

**Comment by uPagge** [comment]
> > > Cmd+F?
> > 
> > 
> > Эм, а все комментарии загружаются разом, это конечно тоже не круто :D
> 
> Чем же это плохо?

Например вот этим? Загрузилось миллион всякого дерьма, а я даже не прокрутил страницу ниже шапки. Судя по всему это только аватарки юзеров, хорошо хоть картинки в самих комментариях с ленивой загрузкой.

![image](https://user-images.githubusercontent.com/40397740/117871370-fa159b00-b2a5-11eb-9ca6-d563d848f28b.png)

**Comment by uPagge** [comment]
Просто мне кажется странным загружать все комменты к посту разом. Чисто мое мнение, может конечно я и не прав, но я еще не видел порталов без пагинации

**Comment by vas3k** [comment]
Что нам даст такая экономия трафика? У нас разве много пользователей на диалапе с помегабайтной оплатой? Мне кажется весь этот тред какая-то попытка натянуть сову на глобус без понимания зачем это всё надо
