### ISSUE TITLE
Баг: Всратое превью недельного дайджеста в Teleram

### ISSUE THREAD

**Issue by standin-glhf** [vas3k/vas3k.club#603]
В превью под [ссылкой](https://vas3k.club/weekly_digest/2021_17/) на дайджест в Телеграме виден код:
![4B6BE652-5423-4AD6-8411-45160AD9CD84](https://user-images.githubusercontent.com/36379441/117657830-b71ecf00-b1a2-11eb-9d94-793e5b9f4117.jpeg)

**Comment by alexriabtsev** [comment]
у меня вообще нет превью в тг на Дайджесте
