### ISSUE TITLE
Нидс импрувмент: хде наша 404

### ISSUE THREAD

**Issue by maurezen** [vas3k/vas3k.club#608]
Вот не далее как 5 минут назад открыл с час назад загруженной ленты клуба баттл про права. Ну то есть как открыл? Попытался. 

Не вопрос, неформат (наверное. хз что там было), удалили. Но хотелось бы видеть что-то более юзер-френдли, чем дефолтная заглушка вебсервера, мол, not found, сучечки, реквестед ресурс на этом this server.

Даёшь юзерфрендли 404 для народа!
Возможно, нужны разные сорта 404: для удаленных постов одна, для удаленных юзеров другая, для [vas3k.club/foobar](vas3k.club/foobar) (a.k.a. совершенно левых запросов) - третья.  
Для удаленных каментов заглушка, кажется, уже есть.

Разумно звучит?

**Comment by vas3k** [comment]
Разумно, набросай дизайны, поревьювим

**Comment by maurezen** [comment]
Пруф оф концепт рисую на салфетке, что-то другое в пятницу вечером грешновато:
404 юзера
![404 юзера](https://user-images.githubusercontent.com/569536/119202925-22fe1300-ba92-11eb-810d-8f1d140cef57.jpg)
404 поста
![404 поста](https://user-images.githubusercontent.com/569536/119202950-3a3d0080-ba92-11eb-9eb9-320ae36c636a.jpg)
404 для левых запросов
![404 для левых запросов](https://user-images.githubusercontent.com/569536/119202980-4de86700-ba92-11eb-8f7e-1110904e1756.jpg)

**Comment by vas3k** [comment]
Закрою как дубликат, но задача все еще актуальна, нужен дизайн https://github.com/vas3k/vas3k.club/issues/167
