### ISSUE TITLE
Фича: коллективные посты

### ISSUE THREAD

**Issue by shkaff** [vas3k/vas3k.club#611]
У нас много чатов, в которых одна и та же инфа всплывает каждые пару недель. Или где классные ссылки и полезная инфа утопают в обсуждениях. Я попробовал создать мета-посты, где собирал ссылки на важные посты в клубе и в чатах (для карапузов и науки): https://vas3k.club/post/8633/ и https://vas3k.club/post/7925/. Но в одиночку поддерживать их сложно.

Было бы круто иметь возможность добавить авторов, которые также могут модифицировать пост (или делать его полностью коллективным с самого начала). Комменты не очень работают для этого, так как суть подобных постов в возможности использовать структуру поста. 

Представляю и другие юзкейсы:)

**Comment by devcooch** [comment]
Можно сделать так:
1) К посту добавить список редакторов. Автор остаётся один. Редактор может редактировать текст поста. Автор может редактировать текст и редакторов.
2) Если у поста ненулевое количество редакторов - добавить плашку "Коллективный пост".

Если такой объём функционала устраивает - я мог бы довольно быстро запилить.
Какие-то ещё нужны функции? Уведомление об изменениях в посте? Но тогда надо как-то дифф генерить..

**Comment by vas3k** [comment]
А чем вас не устраивает секция комментариев? У нас есть треды, где люди коллективно собирают обзоры городов, например. Автор может пинить их и тем самым делать подборки. Зачем давать редактировать прямо пост, может лучше подумать как лучше организовать такие вот треды в комментах? (дать возможность задавать шаблоны, например, или скрывать реплаи по-умолчанию, я хз, куча вариантов)

**Comment by devcooch** [comment]
Ну вот варианты что ты предлагаешь типа шаблонов итп с точки зрения реализации сильно сложнее, чем то, что я написал.
Я люблю красивый пост а-ля лонгрид, а не свалку. Комментарии все равно выглядят как свалка. Если бы их инлайнить в пост было можно - было бы круто, но опять сложна.

**Comment by vas3k** [comment]
Хмм, в моей голове мои варианты технически более легки в реализации, чем делать википедию в постах. Ты ведь наверняка писал в своей жизни коллективные редакторы, понимаешь как там всё тяжело с ролями, а если начнутся конфликты версий так вообще пиздец.

Для меня комментарии не свалка. Не понимаю почему ты их так называешь. Комменты ко многим постам для меня интереснее самих постов, потому мы и вкладываемся в их развитие (разметка, треды, сворачивание)

Я не вижу разницу между ембедом комментариев и пином, который уже есть

**Comment by nDmitry** [comment]
Без истории ревизий поста несколько авторов делать опасно, затрутся чьи-нибудь изменения.

Есть альтернативная Википедии идея у меня, по сути аналог Summarize в Discourse, что дает примерно тот же результат. Я не знаю какой там точно алгоритм, но работает так: жмешь кнопку Summarize и у тебя в треде остаются только лучшие комменты (скажем, можно выбрать верхние 25 процентилей по рейтингу). Так можно быстро прочитать самое важное. Кнопку можно назвать Дайджест.

Кроме лучших по рейтингу можно дать кнопку автору поста для включения комментария в этот дайджест. Получается, что комменты для дайджеста будут и автоматически выбираться (коллективным голосованием), и возможность ручной корректировки будет (может быть нужна и кнопка исключения коммента из дайджеста - для устаревшей инфы, например). Если уже есть функционал пиннинга комментов автором поста, можно его для этого как-то реиспользовать.

**Comment by shkaff** [comment]
> А чем вас не устраивает секция комментариев?
Два момента: необходимость вовлеченности автора в жизнь поста и отсутствие струтуры. Первое понятно: если автор не следит за комментами, суть поста пропадает.

Со вторым так: для конкретно этого юзкейса комменты не устраивают отстутствием возможности эти комменты отсортировать по типам. Есть кейсы, когда нужен просто список "топ-10 городов", тогда комменты работают нормально. А вот когда речь идет о подборках, типа той, что я приводил выше, важна некоторая вложенность комментов или хотя бы просто структура, а не просто список лучших. Иначе получится все равно хаос, в котором сложно будет найти что-то тебе интересное.

В теории, можно было бы реализовать это и комментами. Если дать возможность авторам сортировать запиненные комменты в произвольном порядке. Тогда автор может писать комменты - разбивку с названием секций (структуру), а потом туда набирать комменты. 

Но это не решает первой проблемы с необходимость вовлекать автора в процесс постоянно.

**Comment by devcooch** [comment]
@nDmitry , @vas3k , не надо устраивать википедию, модераторы и сейчас могут одновременно с автором редактировать пост и что-то коллизий не случилось. Если очень хочется можно добавить во время редактирования блокировку от второго редактирования, это, конечно, чуть усложнит логику, но тоже в целом не сложно.
Проблема комментариев именно в том, что их невозможно структурировать. Можно пинить и всё. Нельзя, например, создать метакоммент "здесь баги клуба" и переместить в эту ветку все комментарии про баги. Впрочем я это и не предлагаю. Мне казалось, что расширение прав доступ от модераторы+автор к модераторы+редакторы+автор - это как раз MVP и минимальное легко реализуемое за вечер изменение.

**Comment by Fritzenator** [comment]
Поддержу, в свете старта формата путеводителей, которые активно продвигают идею коллаборации, было бы очень кстати. Скажем, если двое людей пишут пост про город 50:50, то автором поста все равно будет числится только один (и ему же это пойдет в зачет, например, для соответствующих ачивок). 

Конечно, можно поблагодарить соавторов словами в самом посте, но это все равно немного не то - создается впечатление, что они трудились над постом меньше, чем основной автор, хотя это может быть далеко не так.

По технической части, на мой (не слишком опытный в вебдеве) взгляд, предложение @devcooch выглядит как решение наименьшей кровью.

**Comment by vas3k** [comment]
Окей, давайте попробуем вариант @devcooch. Скорее интересно посмотреть на это со стороны UI, потому что технически тут всё понятно

Просто как сайдноут, я всё еще волнуюсь на счёт: 

> модераторы и сейчас могут одновременно с автором редактировать пост и что-то коллизий не случилось

Это как с машинами и пробками. Когда пробок нет — люди массово скупают машины, потому это ой как удобно. В итоге тренд быстро разворачивается в обратную сторону

**Comment by devcooch** [comment]
Дальнейшие улучшения будем создавать отдельными тикетами.
