### ISSUE TITLE
Баг: Не работает сортировка внутри разделов на главной странице

### ISSUE THREAD

**Issue by ivnmrtk** [vas3k/vas3k.club#614]
Пытался отобразить посты из [раздела АМА](https://vas3k.club/label/ama/) с сортировкой по новизне, но по нажатию кнопки "Новое" происходит редирект на главную страницу, причем с нужной сортировкой (видимо из-за того, что кнопка в этом разделе ведет на урл "_.../all/new/_" вместо  ожидаемого "_.../label/ama/new/_"). По другим режимам сортировки поведение аналогичное, также столкнулся с этой проблемой в разделах "инсайды" и "треды"

**Comment by dmitvitalii** [comment]
Воспроизводится со всеми разделами

**Comment by manushichev** [comment]
![sort_bug_vas3k](https://user-images.githubusercontent.com/38554172/136012835-cf784ffb-7f70-4eeb-8938-6529feebb22d.gif)
Это похоже уже починено.

**Comment by dmitvitalii** [comment]
Тоже не воспроизводится

**Comment by devcooch** [comment]
прастити, забыл закрыть за собой.
