### ISSUE TITLE
Добавить кнопку редактирования интро прям в профиль пользователя

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#62]
А то все спрашивают

**Comment by Windrushfarer** [comment]
Сбоку так нормально будет?
http://s.csssr.ru/U439TP407/20200430143904.png

**Comment by FMajesty** [comment]
@Windrushfarer 
О, отличный вариант

**Comment by FMajesty** [comment]
@Windrushfarer 
Кстати, можно добавлять в название коммита `#номер_иссуя` чтобы они сами закрывались и не висели открытыми:)

**Comment by Windrushfarer** [comment]
Спасибо, я не знал этого

**Comment by FMajesty** [comment]
@vas3k клоуз

**Comment by vas3k** [comment]
@FMajesty сделал тебя коллаборатором, теперь ты тоже можешь в клоуз и лейблы. Попробуй!

**Comment by FMajesty** [comment]
@vas3k опробовано успешно
