### ISSUE TITLE
Баг: неверно определяется категория скиллов при первоначальном выборе кастомного скилла

### ISSUE THREAD

**Issue by iaulitin** [vas3k/vas3k.club#632]
Воспроизводим так:
1. Выбираем "Добавить своё" при заполнении скилла.
2. Вводим название
![изображение](https://user-images.githubusercontent.com/18134455/122378034-45d6f680-cf6e-11eb-9309-2b68cb356fc5.png)
3. Теперь передумываем и меняем на один из стандартных скиллов, которые предопределены в системе. Ползунок "скилла" можем двигать или не двигать - неважно. Жмем "добавить"
![изображение](https://user-images.githubusercontent.com/18134455/122378233-74ed6800-cf6e-11eb-9280-109ff13fe660.png)
4. Скилл сохранился с тем заголовком, который вводился для кастомного скилла на шаге 2.
![изображение](https://user-images.githubusercontent.com/18134455/122378390-9a7a7180-cf6e-11eb-80b4-74cb571f48ca.png)

На мой взгляд, правильным поведением было бы если бы скилл сохранялся со "стандартным" заголовком, выбранным на шаге 3

**Comment by Lamberthassel** [comment]
Пофиксил однострочным изменением тут: https://github.com/vas3k/vas3k.club/pull/649
