### ISSUE TITLE
Фича: Юзабилити: Кнопка Log in with Telegram при подключении бота заставляет логиниться в веб Телеграм

### ISSUE THREAD

**Issue by murfel** [vas3k/vas3k.club#641]
Речь про эту кнопку: [скриншот 1](https://drive.google.com/file/d/1jtq4FJkrKSXmaQDLPxrlu8LTCSPvrU7A/view?usp=sharing)

При нажатии на нее открывается окно: [скриншот 2](https://drive.google.com/file/d/1SIsZdNmDOFfO5qNOhnG3xhJ-0g6eN5YL/view?usp=sharing)

Логин в веб Телеграмм — это лишний шаг, который отделяет пользователя от успеха. Не проще ли оставить только стандартную `t.me/` ссылку? И она уже откроется в приложении или в вебе, если у пользователя нет приложения.

**Comment by vas3k** [comment]
От этой кнопки одни проблемы похоже. Выпилил её нафиг, заменил на диплинк, который открывает бота и автоматом подставляет код по клику на /start. Должно стать лучше
