### ISSUE TITLE
Фича: Расположение тогла темной темы

### ISSUE THREAD

**Issue by naivekook** [vas3k/vas3k.club#642]
Что:
Перенести тогл светлой\темной темы вверх страницы.

Почему:
В текущей версии при открытии клуба приходится неистово скролить в самый низ чтобы переключить тему, хотелось бы иметь тогл вверху для быстрого переключения.

**Comment by devcooch** [comment]
Там на клавиатуре есть кнопка End :)

**Comment by naivekook** [comment]
Наверное мне стоило уточнить, что боль испытываю исключительно на мобильной версии :)

**Comment by vas3k** [comment]
Перенес тему в дискуссии https://github.com/vas3k/vas3k.club/issues/642
