### ISSUE TITLE
ссылка в заголовке раздела не подчеркивается

### ISSUE THREAD

**Issue by djhrum** [vas3k/vas3k.club#643]
![image](https://user-images.githubusercontent.com/431633/123543554-ca3c2d00-d757-11eb-90f5-c144dd9e616d.png)

`## Ксти вот эти [темы](https://vas3k.club/event/10209/#comment-e4914c7d-c939-4952-8f2b-6daea6f44022):`

Весь заголовок является ссылкой на самого себя. 
Часть заголовка почеченная ссылкой  является ссылкой на то, кудаи должны, но пока случайно на нее на ткнеш, невозможно понять, что это отдельная ссылка

**Comment by vas3k** [comment]
Это якоря заголовков, а не ссылки. Подчеркивать их в планах не было пока, но спасибо за репорт

**Comment by djhrum** [comment]
Дык а если делается ссыль заговке?
Как визуально понять, что часть заголовка, это именно внешняя ссыль?

**Comment by vas3k** [comment]
Думаю никак, внешние ссылки в заголовках не поддерживаются, делай его просто ссылкой ниже
