### ISSUE TITLE
Эффективная сортировка комментариев

### ISSUE THREAD

**Issue by grayskripko** [vas3k/vas3k.club#650]
Есть идея, я хочу поделиться.

Мне кажется, что при текущей дефолтной сортировке комментариев (а я даже не обращал внимания, есть ли другие), и особенно если комментариев много, любой новый комментарий имеет все меньше шансов быть прочитанным. Помотаешь два-три экрана, и даже если все нравится, рано или поздно остановишься.

К чему это приводит? 
Чтобы собрать много лайков достаточно написать неплохой коммент, но как можно раньше.
Чем больше лайков собрал комментарий -- тем больше лайков соберет и в будущем.
Новые комментарии к старым постам не хочется писать -- все равно никто их не увидит. Даже если это будет потенциально самый качественный и удачный комментарий в треде.
Чем старше тред -- тем меньше в нем жизни. Даже если его объект принципиально обновился.

Предложение:
Дефолтной сортировкой оставить текущую, по популярности, но вторым комментарием вставлять либо рандомный, либо самый свежий. Типа как работает реклама в Инстаграмме.

**Comment by vas3k** [comment]
Я исходил из того, что заходя в тред (особенно старый), я хочу сначала видеть в нём лучшее. Лайки у нас отлично решают это. Потом у меня должна быть возможность переключиться на более удобный для дискуссии вид. Если я тупой и не нашел этой опции — наверное не нужно для меня придумывать какие-то (((алгоритмы))), это лишь всех запутает и сделает новый фейсбук.

Сортировку можно выбрать прямо с главной страницы. Если кликнуть на "N новых" — будет по свежести. Если на "M комментариев" — по порядку. А если просто на пост — по популярности. Я за осознанный выбор, а не алгоритмы.
