### ISSUE TITLE
Баг: Неверное число месяцев подписки

### ISSUE THREAD

**Issue by Glemhel** [vas3k/vas3k.club#652]
Только вступил в клуб, подписка на год, а количество месяцев подписки отображается 13..
Дата окончания стоит правильная, скрины ниже.
<img width="449" alt="Screenshot 2021-07-25 at 13 52 04" src="https://user-images.githubusercontent.com/36306324/126896540-da0cd7c1-e5e4-4bbc-8cad-7e4baad0b4bc.png">
<img width="580" alt="Screenshot 2021-07-25 at 13 53 35" src="https://user-images.githubusercontent.com/36306324/126896566-522de65a-fa18-4674-8957-eb7a036b7819.png">

**Comment by devcooch** [comment]
Fixed.
