### ISSUE TITLE
Контакт внизу блока Для других членов Клуба я...

### ISSUE THREAD

**Issue by vas1q** [vas3k/vas3k.club#655]
Туда как-то попадает и остаётся неизменной инфа о способе контакта. В моём случает в профиле уже свежее)
Вижу два варианта - подбирать и ставить контакт из профиля или разрешить редачить прямо на страничке интересов

**Comment by devcooch** [comment]
@vas1q  да так же туда попадает как и в профиль - заходишь на редактирование профиля (https://vas3k.club/user/vas1q/edit/profile/), внизу "ссылочки на себя и всякое" - это в шапке, "контакт для обратной связи" - как раз то, что внизу. т.е. ты первое обновил, оно свежее, а второе не стал.

**Comment by vas3k** [comment]
Разобрались? Переокройте если актуально
