### ISSUE TITLE
Добавить поддержку InstantView для постов клуба

### ISSUE THREAD

**Issue by Muntello** [vas3k/vas3k.club#66]
Чтобы не хуже Медиумов всяких там было.
Описание на сайте телеграма — https://instantview.telegram.org

**Comment by Vadimkin** [comment]
Клуб же недоступен для внешних интернетов, а InstantView ожидает то, что материал будет отдаваться для всех. Или что-то другое имеется ввиду?

**Comment by FMajesty** [comment]
Отличная идея!
@Vadimkin, есть открытые посты

**Comment by vas3k** [comment]
Я лично их никогда не понимал, но люди вроде пользуются, так что кому сильно надо — запилите, я не против :)

**Comment by rozhok** [comment]
Эту штуку телеграм добавляет только для больших сайтов. Ты делаешь разметку, добавляешь 10 урлов на тест и ...все. Мой шаблон для моего же блога не аппрувят уже год и судя по интернетам у других такие же проблемы.

**Comment by vas3k** [comment]
С моим блогом то же самое похоже. Окей, тогда тикет не имеет смысла. Можете переоткрыть если телеграм снова начнет прием заявок
