### ISSUE TITLE
Баг: парсер ссылок ломается без http(s)

### ISSUE THREAD

**Issue by shkaff** [vas3k/vas3k.club#676]
Ссылки получает добавку в виде адреса поста, если в маркдауне не добавлен http(s). Например:
`[leo.org](leo.org)` парсится как https://vas3k.club/post/11543/leo.org (в посте https://vas3k.club/post/11543/)
а `[leo.org](https://leo.org)` как https://www.leo.org/

Наверное, связано с якорями. Не знаю, баг ли это, но репорчу.

**Comment by thelebster** [comment]
Предположу что так работает парсер markdown [по умолчанию](https://daringfireball.net/projects/markdown/syntax#link).

**Comment by devcooch** [comment]
Да, ситуация вот эта:
```
If you’re referring to a local resource on the same server, you can use relative paths:
See my [About](/about/) page for details.   
```
нужен или www, или http(s).
