### ISSUE TITLE
Баг: заменить иконку удаленного комментария на восстановление

### ISSUE THREAD

**Issue by dmitvitalii** [vas3k/vas3k.club#677]
Перед тем, как восстановить коммент показывается диалог с вопросом _"Удаляем?"_
<img width="501" alt="Screenshot 2021-08-25 at 15 59 03" src="https://user-images.githubusercontent.com/14320898/130794794-47df9771-cabb-4c6e-aa2e-773391d68213.png">

Можно было бы менять иконку на иконку восстановления
![baseline_restore_from_trash_black_24dp](https://user-images.githubusercontent.com/14320898/130795016-174323d4-87e9-4844-8a86-500f878c3939.png)  ![baseline_restore_from_trash_white_24dp](https://user-images.githubusercontent.com/14320898/130795095-2be0167d-9582-4a61-bdf3-587ebcd3cf7f.png)

Либо на подобие такой

![baseline_settings_backup_restore_black_24dp](https://user-images.githubusercontent.com/14320898/130795474-d1326566-2b77-4b64-b8e6-17a6452c43be.png) ![baseline_settings_backup_restore_white_24dp](https://user-images.githubusercontent.com/14320898/130795549-f084b1e1-f527-4427-9297-6e14973c34ff.png) 

и пофиксить текст

**Comment by vas3k** [comment]
Можно заменить иконку, а так это фича, да

**Comment by Programistich** [comment]
Я возьмусь, попробую сделать свой первый вклад)

**Comment by aovlllo** [comment]
А чего ишшуй не закрыли? Починено же уже вроде)

**Comment by aovlllo** [comment]
Я еще накину: а зачем нужна кнопка редактирования на удаленном комменте? Может и ее убирать заодно?

**Comment by devcooch** [comment]
@aovlllo для модераторов
