### ISSUE TITLE
Фича: Возможность совместного написания постов

### ISSUE THREAD

**Issue by pavel9609** [vas3k/vas3k.club#680]
Предлагаю добавить возможность совместного написания постов. Данный featurerequest навеян гайдом по написанию путеводителя (https://vas3k.club/guide/11625/). Вроде бы предлагается коллабиться, но технической возможности, как понимаю, нет.

Как вариант, можно дать возможность шерить черновик другим, чтобы и другие могли редактировать черновик. Как вариант, можно слать правки к уже готовому посту для пользователей как в git с возможностью приема их автором. В идеале сделать как в гугл-документах, но я думаю это будет сложно.

**Comment by dmitvitalii** [comment]
Такой реквест уже есть https://github.com/vas3k/vas3k.club/issues/611
