### ISSUE TITLE
Баг: модерируемые посты видно через бота THE MACHINE и функцию "Мой чувак"

### ISSUE THREAD

**Issue by j-rheingold** [vas3k/vas3k.club#681]
Если добавить Вастрика (или другого модератора?) в "Мои чуваки", их посты будут видны в боте, даже если они не видны в клубе
![photo_2021-09-01_14-20-26](https://user-images.githubusercontent.com/89143781/131670157-1bbb7425-d2e4-4eb8-a32d-4439eb693a8c.jpg)

**Comment by vas3k** [comment]
Я запостил тестовый пост и сразу его удалил. Забыл, что он высрется всем "моим чувакам", сорян. Больше не буду. Не баг.
