### ISSUE TITLE
Координаты аватарок некорректны на карте в Safari

### ISSUE THREAD

**Issue by slonoed** [vas3k/vas3k.club#682]
<img width="1387" alt="Screen Shot 2021-09-01 at 10 37 55 PM" src="https://user-images.githubusercontent.com/463239/131788034-913351a5-366e-4ba8-af00-3297d48c7a17.png">

А есть у кого-то ещё такая же проблема? На картинки bay area. Похоже, что все аватарки съехали влево.

**Comment by vas3k** [comment]
Координаты рандомизируются иначе все они будут в одной точке и ничего непонятно
