### ISSUE TITLE
Баг: не могу посмотреть новые комментарии

### ISSUE THREAD

**Issue by kirillku** [vas3k/vas3k.club#684]
Возможно это и не баг, но мне доставляет некоторые неудобства. Когда я вижу на главной что у поста появились новые комментарии, хочется их посмотреть. Я открываю пост, проматываю до комментариев и, чтобы посмотреть только новые, изменяю сортировку. Страница перезагружается и все комментарии оказываются помеченными как прочитанные 😔.

Думаю это можно было бы исправить просто делая эту сортировку на клиенте (не перезагружая страницу).

**Comment by vas3k** [comment]
Дубликат https://github.com/vas3k/vas3k.club/issues/577
