### ISSUE TITLE
Баг: почтовые адреса с точкой и без точки считаются разными

### ISSUE THREAD

**Issue by dmitvitalii** [vas3k/vas3k.club#690]
### Как сейчас
При логине, почта super.user@gmail.com не будет найдена, если пользователь регистрировался с почтой superuser@gmail.com

### Как надо
Игнорировать точки
В адресе точка ничего не означает: super.user, superuser и s.u.p.e.r.u.s.e.r - всё это один почтовый ящик.

**Comment by vas3k** [comment]
Почтовый ящик один, а логины разные

**Comment by dmitvitalii** [comment]
Что ты имеешь в виду?

**Comment by vas3k** [comment]
Ок, зайдём с другой стороны. Можешь назвать популярные сервисы (не почтовые), где этот трюк с удалением точки прокатит?

**Comment by vas3k** [comment]
Проверил на твиттере. Нет, так не работает. Закрываем как не баг 
![52413521-9675-43A3-8C1D-A22EDF00B502](https://user-images.githubusercontent.com/176344/132954207-63e5b29b-7df6-4921-91ca-27015c00f023.jpeg)

**Comment by dmitvitalii** [comment]
Только что проверил github и facebook. Так же делают многие другие сервисы.

Кто-то (вот, твиттер, например) на это болт забивают, а чуваки вроде меня, которые изначально указали точку в своем имейле при создании, страдают. Вплоть до геморроя с техподдержкой.

Вот и сейчас я не могу зайти через dmitvitalii@gmail.com в вастрик клуб, потому что через oauth подтянулось, что я dmit.vitalii@gmail.com

Есть сервисы, которые задваивают аккаунты, а потом пароль не восстановить: ведь оба аккаунта шлют восстановление пароля на одну и ту же почту.
Есть сервисы, которые на это обращают внимание, они няшки и большое им спасибо за это. Было бы круто сделать так и для клуба. Тем более, что это сделать дёшево.

**Comment by vas3k** [comment]
Интересно, никогда не думал о таком
