### ISSUE TITLE
Баг: описание ачивки обрезается краем страницы

### ISSUE THREAD

**Issue by psydvl** [vas3k/vas3k.club#694]
![Screenshot.jpg](https://user-images.githubusercontent.com/43755002/133983782-c51cb43e-321a-4290-ab22-b6bd589e63be.jpg)

**Comment by Programistich** [comment]
Как идея, сделать по одной ачивке (столбиком) на моб устройствах?

**Comment by vas3k** [comment]
Лучше две. А можт просто не показывать это описание на мобилах и всё? :) Оно всё равно по ховеру, что ненативно на таче

**Comment by Programistich** [comment]
окс, давай я попробую убрать описание

**Comment by psydvl** [comment]
На мобильных появляется по тапу 
Но если вообще, зачем скрывать описание?

**Comment by Programistich** [comment]
Потому что много места занимает?

**Comment by psydvl** [comment]
А какое значение имеет место на странице с ачивками?

**Comment by dmitvitalii** [comment]
@psydvl если у есть идея как решить проблему красиво и без удаления описания, то опиши тут. В идеале - с примером картинки. Может твой вариант и правда будет лучше

**Comment by alexriabtsev** [comment]
может показывать описание ВМЕСТО картинки при наведении?

**Comment by Programistich** [comment]
А что говорят дизайнеры на такой UI и такие случаи?

**Comment by Programistich** [comment]
Вот так получится если убрать  hover
Вроде збс!
https://user-images.githubusercontent.com/35292229/135887077-cce20dcd-8769-42dc-86f3-ef681402257a.mp4

**Comment by alexriabtsev** [comment]
> Вот так получится если убрать hover Вроде збс! https://user-images.githubusercontent.com/35292229/135887077-cce20dcd-8769-42dc-86f3-ef681402257a.mp4

ты ж вообще убрал описание

**Comment by Programistich** [comment]
```
Лучше две. А можт просто не показывать это описание на мобилах и всё? :) Оно всё равно по ховеру, что ненативно на таче
```
Ну вот да

**Comment by Programistich** [comment]
> Лучше две. А можт просто не показывать это описание на мобилах и всё? :) Оно всё равно по ховеру, что ненативно на таче

Ну да

**Comment by Programistich** [comment]
Просто описание это кучу текста, и не очень красиво со стороны UI

**Comment by wtfua92** [comment]
Альтернативное предложение: по клику на ачивку - расширять блок вправо и показывать описание. Повторный клик - обратно сужать. Понятное дело, с плавным трансформейшном и прочими ништяками
![image](https://user-images.githubusercontent.com/14012934/135994194-fbda93ef-679a-4016-9e70-5a710a3a7f58.png)

**Comment by Programistich** [comment]
но опять же, это решение для ПК больше
на мобилке не удобно будет  + по картинке выше есть впечатление, что оно не влезет

**Comment by wtfua92** [comment]
@Programistich На мобильном одна должна вполне поместиться, для остального - горизонтальный скролл.

**Comment by Programistich** [comment]
![image](https://user-images.githubusercontent.com/35292229/135995912-f9740dcc-4c47-4bd2-b3e0-cd7f566fe46e.png)
Не соглашусь про мобильное

**Comment by vas3k** [comment]
Описание ачивки короткое, нет смысла отдавать ему 2/3 экрана. Если уж совсем хочется его оставить где-то — можно переделать его на переворачивающуюся карточку типа как здесь https://www.w3schools.com/howto/howto_css_flip_card.asp

**Comment by wtfua92** [comment]
@Programistich конкретно по этому решению - можно подшаманить марджины/паддинги и поместится.

Но наверное флип карточки, хоть и выглядит немного старомодно, но будет действительно разумнее с точки зрения полезного использования доступного места.

**Comment by Programistich** [comment]
Я могу попробовать сделать и принесу видео как оно выглядит

**Comment by vas3k** [comment]
На VHS видео!

**Comment by ninedev-i** [comment]
@vas3k можно закрыть
