### ISSUE TITLE
Баг: автор комментария может отобразить удаленный автором поста комментарий

### ISSUE THREAD

**Issue by Galichev** [vas3k/vas3k.club#695]
Если автор публикации удалил комментарий - кнопка редактирования у автора комментария не исчезает и возможно опубликовать этот или другой комментарий на том же месте повторно. Проблема была воспроизведена в https://vas3k.club/guide/berlin/

**Comment by devcooch** [comment]
Так это же ожидается. Тебе дают возможность исправиться и переопубликовать комментарий.

**Comment by vas3k** [comment]
Не, это правда баг, разудалить должен мочь только тот, кто удалил. Для того мы храним deleted_by. Там даже проверка есть, хз почему она не сработала, надо подебажить

**Comment by Galichev** [comment]
> Так это же ожидается. Тебе дают возможность исправиться и переопубликовать комментарий.

В этом случае можно сделать более мягкую формулировку, что-нибудь вроде «Комментарий скрыт автором публикации. Приведите его в соответствие с правилами Клуба и мы с радостью его покажем», по «комментарий удален» вообще не очевидно, что его можно редактировать

**Comment by vas3k** [comment]
Я что-то там пофиксил после того случая, надо проверить воспроизводится ли и если нет — можно закрывать

**Comment by llirikcmb** [comment]
Локально уже не воспроизводится. Пытался только что повторить, еще не видя новых комментариев. Нужно написать что-нибудь токсичное на продакшене или локальной проверки достаточно?

**Comment by vas3k** [comment]
Думаю локальная версия тут не отличается от обычной. Закроем тогда

**Comment by manushichev** [comment]
А вот [https://github.com/vas3k/vas3k.club/commit/068caaf011e0d3dc488599099923d79250f3718a#diff-e27debe06c5dc1d1db5434a01e032045eb898b333d1fe8a898b2b474a2f72681L54](это) - не логика на то, чтобы скрыть иконку восстановления/удаления от тех, кому нельзя этого делать? Если да - то видимо `me.id == comment.deleted_by` что-то не срабатывает - иконки то видны.

**Comment by vas3k** [comment]
> Если да - то видимо me.id == comment.deleted_by что-то не срабатывает - иконки то видны.

Вот это я бы проверил почему, да

**Comment by manushichev** [comment]
#718 
там кажется не во всех шаблонах проверки эти добавили, и по идее можно скрывать кнопку редактирования для удаленного комментария
