### ISSUE TITLE
Фича: предупреждать о конце подписки

### ISSUE THREAD

**Issue by denisSurkov** [vas3k/vas3k.club#696]
**Как сейчас**

Никак. Только если пользователь оформил подписку и нажал на галку "повторять каждый год" (или как-то так). Не знаю, пишут ли провайдеры оплаты о скором снятии.

**Как хочется**

За N дней до конца подписки напомнить пользователю (почта, тг бот), что скоро закончится подписка. Важно, чтобы в сообщении сразу была ссылка на оплату, если что. 

Мотивация простая -- мне никто ничего не сказал, что подписка скоро закончится. После тройки дней я все-таки решил зайти и продлить все это дело.

**Как делать:**

- Конец подписки: https://github.com/vas3k/vas3k.club/blob/068caaf011e0d3dc488599099923d79250f3718a/users/models/user.py#L81
- Непонятно, как запускать таску по времени.
- Отправлять через тг бота и почту.

**Comment by ollkostin** [comment]
Еще нужно учитывать то, что пользователь может завершить подписку сам

**Comment by denisSurkov** [comment]
А может кто-нибудь привести пример, где в коде вызывается какая-нибудь таска по времени?

**Comment by vas3k** [comment]
@denisSurkov мы используем джанговский management commands в кроне, думаю тут то же самое подойдёт без проблем. Вот пример ежедневного дайджеста: https://github.com/vas3k/vas3k.club/blob/master/notifications/management/commands/send_daily_digest.py

**Comment by devcooch** [comment]
ещё есть вроде отложенная очередь, например в `gdpr/archive.py` (ищи по `schedule`), но оно как-то нечётко срабатывает, мы так и не поняли почему.

**Comment by vas3k** [comment]
Она почему-то не работает, да, никто не может понять почему. Крон-джобы все еще делают своё дело лучше всех с самых дневних времён :D

**Comment by kedMertens** [comment]
Ребят, хотел бы поработать над этой задачкой, если еще свободна.
План действий:

- Добавить скрипт на основе send_daily_digest.py из комментария [выше](https://github.com/vas3k/vas3k.club/issues/696#issuecomment-932252432)
  - Ежедневно проверять у кого истекает подписка (есть вопрос - за сколько дней до окончания высылать уведомление ?) 
- Завести бота для рассылки
Пытался найти какие промежутки используются в индустрии :D и понял что обычно сервисы не заинтересованы сообщать об этом и просто провожают подписку автоматически.

**Comment by vavilon95** [comment]
@kedMertens привет. Я начинал работать над ней, но потом кончилось свободное время. Вот, возьми мои наработки, вдруг они тебе помогут. :)
Отправляю в виде patch для пичарма.
[Add_send_email_and_tg_message_when_expire_membership.patch.zip](https://github.com/vas3k/vas3k.club/files/7292659/Add_send_email_and_tg_message_when_expire_membership.patch.zip)

**Comment by kedMertens** [comment]
@vavilon95, спасибо. Порадовало решение высылать за 7, 3 дней и за день до окончания. 
Похоже, ты все сделал, не хочешь открыть PR?

**Comment by vavilon95** [comment]
@kedMertens у меня не было времени тестировать. Если протестируешь и есть время править замечания - пожалуйста, открывай. 👍

**Comment by kedMertens** [comment]
@vavilon95, принял! Сейчас погоняю
