### ISSUE TITLE
Придумать как должны кликаться посты в фиде

### ISSUE THREAD

**Issue by vas3k** [vas3k/vas3k.club#7]
Проблема: хочется чтобы весь блок поста в фиде был кликабельным. Если сделать кликабельным только заголовок — это неудобно. Но обернуть его в тег <a> полностью тоже не выйдет потому что там есть другие ссылки, например, на комменты или на апвоут. Вложенные ссылки в HTML нельзя.

Сейчас там сделано через JS, но это очень сильно раздражает потому что такие ссылки не откроешь в новом окне/табе. Ужасный UX.

Надо придумать что-то получше.

<img width="822" alt="Screenshot 2020-04-26 at 13 53 49" src="https://user-images.githubusercontent.com/176344/80306786-aa148500-87c5-11ea-981f-76bcbb1c35bc.png">

**Comment by FMajesty** [comment]
@vas3k

**Comment by vas3k** [comment]
Да, теперь офигенно!

**Comment by FMajesty** [comment]
не, ты иссуй-то закрой

**Comment by FMajesty** [comment]
а, во
