### ISSUE TITLE
Отправка комментария на Ctrl+Enter

### ISSUE THREAD

**Issue by FMajesty** [vas3k/vas3k.club#70]
Мелочь, а приятно!

**Comment by vas3k** [comment]
Ну и про Cmd не забудь :)

**Comment by FMajesty** [comment]
Ой, маки эти ваши
Ну ладно

**Comment by Windrushfarer** [comment]
`event.ctrlKey` значит и про маки и про все остальное
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey
