### ISSUE TITLE
Фича: Заготовленные Template для разных видов Issue

### ISSUE THREAD

**Issue by LionZXY** [vas3k/vas3k.club#702]
Сейчас при создании Issue у тебя нет шаблона, из-за чего многие люди выражают свои мысли не структурированно. 
Предлагаю добавить шаблоны для багов и для фич.
Сами шаблоны можно взять из ваших самых любимых Issue/PR:
Например, тут неплохо оформлена фича: https://github.com/vas3k/vas3k.club/issues/696
Для багов можно добавить секцию "Актуальное поведение", "Ожидаемое поведение" и "Информация о системе/браузере"

Можно глянуть как это сделано тут, перевести и вставить: https://github.com/flipperdevices/Flipper-Android-App/tree/master/.github/ISSUE_TEMPLATE

**Comment by dmitvitalii** [comment]
Есть такой PR https://github.com/vas3k/vas3k.club/pull/429

**Comment by LionZXY** [comment]
Да, звучит как то что я хочу
