### ISSUE TITLE
Баг: нечёткий поиск слишком уж нечёткий

### ISSUE THREAD

**Issue by hudochenkov** [vas3k/vas3k.club#713]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Ищем по слову [домен](https://vas3k.club/search/?q=%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD), чтобы найти посты, где люди рассказывают, где купить домен. В результатах все посты про «дом» (54 страницы только в Постах). Посты про домен практически невозможно найти.

Поиск с кавычками даёт тот же результат: ["домен"](https://vas3k.club/search/?q=%22%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%22).

## Ожидаемый результат

Посты/комментарии, в которых поисковый запрос встречается «как есть», показаны как минимум в самом начале. В идеале нерелевантные посты вообще отсутствуют в выдаче.

**Comment by reclosedev** [comment]
Тоже натолкнулся. 

Есть решение, если оставить и точный (без стемминга) и нечеткий (домен -> дом) поиск, то это примерно в два раза увеличит размер поискового индекса.

Эксперименты здесь: https://github.com/vas3k/vas3k.club/compare/master...reclosedev:vas3k.club:fix/713-stemming

Вариант рабочий, результаты с точными совпадениями отображаются первыми. Не уверен, что он самый оптимальный.

Еще тут замена `plain` поиска на `websearch` позволяет делать более продвинутые запросы, как в гугле, например `"sad cat" or "fat rat"`, и это вроде бесплатно.

Если вариант подходит, попробую выделить время и добавить тестов, в которых это можно получше проверить и сделаю PR.
