### ISSUE TITLE
Фича: кнопка `Войти` над публичным постом

### ISSUE THREAD

**Issue by TriplEight** [vas3k/vas3k.club#714]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

С точки зрения UX было бы правильно справа сверху иметь кнопку `Войти`, там же где есть юзерпик когда войдено.
![image](https://user-images.githubusercontent.com/17856421/135837651-dcd5aea7-5914-49f0-9c0c-f32609f1869e.png)

## Ожидаемый результат

Наверное, должен быть хедер с кнопкой войти (и может приглашением зарегаться)

## Шаги к воспроизведению

1. Выйти
2. Открыть любой публичный пост <https://vas3k.club/question/12029>
3. Не найти сверху кнопки `Войти`
4. Не догадаться поискать её снизу, ведь не все читают каменты

**Comment by vas3k** [comment]
Неплохая идея. Только сменю с бага на импрувмент, потому что у нас никогда вообще кнопок войти нигде до этого не было :)

**Comment by MrModest** [comment]
По идее, если поменять файл `frontend/html/common/menu-simplified.html` так:

```html
{% load static %}
<nav class="menu menu-simplified">
    <a href="{% url "index" %}" class="menu-logo">
        Вастрик<img src="{% static "images/logo/logo-128.png" %}" alt=" x " width="26" height="26">Клуб
    </a>
    <a href="/auth/login/" class="button button-black">Войти</a>
</nav>
```
и добавить в css-класс `menu-simplified`:
```css
display: flex;
flex-direction: row;
```
то будет выглядеть как-то так:

![image](https://user-images.githubusercontent.com/13031058/139504702-f683e869-8302-4baa-baea-ec06a6be5e76.png)
