### ISSUE TITLE
Результаты Батла с вариантами ответа

### ISSUE THREAD

**Issue by lespaul1488** [vas3k/vas3k.club#72]
Сейчас секция результатов выглядит так 
```
9 аргументов за первое и 12 за второе
17 голосов за первое и 33 за второе 👇
```
Приходится скролить вверх что бы вспомнить, а что первое и второе

Лучше заменить первое/второе на сами варианты
<img width="671" alt="Screenshot 2020-04-30 at 11 40 42" src="https://user-images.githubusercontent.com/6555305/80690604-b8b9af80-8ad7-11ea-8df6-a0c3d5c35287.png">

**Comment by lespaul1488** [comment]
Оперативно лол 
<img width="920" alt="Screenshot 2020-04-30 at 11 48 51" src="https://user-images.githubusercontent.com/6555305/80691205-9d9b6f80-8ad8-11ea-9d72-e9a8befec892.png">

**Comment by FMajesty** [comment]
О, только хотел предложить эту идею, лел.
