### ISSUE TITLE
Фича: Блок комментариев вверху страницы

### ISSUE THREAD

**Issue by tmshchk** [vas3k/vas3k.club#724]
## Чеклист

- [x] Я считаю, что фича офигенная и принесет пользу Клубу 🎩
- [x] Я поискал по трекеру похожие идеи, в том числе в закрытых Issues

## Описание фичи

Предлагаю перенести блок с комментариями под постами в самый верх — сразу после поста. Сейчас блок в самом низу и это неудобно, если хочется сразу откомментить, а комментов уже накидали.

Например, в [посте](https://vas3k.club/thread/12050/) я сразу захотел написать о своей машине, но начал скроллить, а там бесконечность. Пока долистал, уже и запал пропал. Да, можно перевести курсор вправо, зажать, перетащить вниз, но… Это долго и неудобно. А ещё на маке почему-то эта полоска для скролла пропала в Хроме и я не мог её выцепить :D

Отчасти понимаю, почему могли выбрать решение с блоком в самом низу — мол, будь добр прочитать все комменты, прежде чем написать свой. Но… Вдруг новое решение покажется лучше.

На многих подобных сайтах (TJ, DTF) блок с комментами сразу после новости/статьи, что позволяет писать сразу.

Как можно сделать:
![мой-вариант](https://user-images.githubusercontent.com/92025957/136187091-66de360b-5d85-4d63-b95d-274f50d800bf.jpg)

Как это сделано на DTF:
<img width="771" alt="dtf" src="https://user-images.githubusercontent.com/92025957/136187080-cc4e6964-40b9-4869-b452-9496bc616e9e.png">

А под полем для коммента выводится список комментов.

**Comment by vas3k** [comment]
Реорганизуем идеи, перенес в дискуссии https://github.com/vas3k/vas3k.club/discussions/818
