### ISSUE TITLE
Фича: Запоминать свернутость тредов

### ISSUE THREAD

**Issue by merelj** [vas3k/vas3k.club#729]
## Чеклист

- [x] Я считаю, что фича офигенная и принесет пользу Клубу 🎩
- [x] Я поискал по трекеру похожие идеи, в том числе в закрытых Issues

## Описание фичи

Давайте запоминать в localStorage (или url, как вариант), какие треды были пользователем свернуты 👀

Очень бесит, когда после рестарта браузера приходится мотать километры комментариев, чтоб вернуться к прочитанному (особенно в мобилке, где это случается если переключился куда-то из брузера по диплинку, например, а потом вернуться).

Пример в url:
```
https://vas3k.club/link/42/?collapsed=72bfedb2-6b41-4d9a-9b15-1e628125ebc8,72bfedb3-6b41-4d9a-9b15-1e628125ebc2 

// я бы, может, даже предложил обрубать uuid'ы, ибо длинна урла конечная, а шанс на совпадение не очень высокий:
https://vas3k.club/link/42/?collapsed=72bfedb2,72bfedb3
```
В локал сторадж можно чистить то, что появилось дольше недели/месяца назад, чтоб место не выжрать через пару лет 👀

Если нет возражений, прямо я б и запилил оперативно в рамках hacktoberfest 😊

**Comment by vas3k** [comment]
А, вижу ты подумал о чистке выше. Ну короче я за локалсторадж, в URL это кажется громоздким

**Comment by ninedev-i** [comment]
@vas3k судя по всему можно закрывать
