### ISSUE TITLE
Баг: нумерованный список не сохраняет пользовательскую нумерацию

### ISSUE THREAD

**Issue by DakarKaret** [vas3k/vas3k.club#740]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

При создании комментария с нумерованным списком клуб заменяет кастомную номерацуя на номера по порядку 

## Ожидаемый результат

Пишу коммент как:
 <img width="35" alt="Screenshot 2021-10-14 at 22 36 57" src="https://user-images.githubusercontent.com/12764026/137384787-3cce8b73-448f-47f7-b6c9-83cb5ae5fea8.png">
А в результате:
<img width="24" alt="Screenshot 2021-10-14 at 22 36 51" src="https://user-images.githubusercontent.com/12764026/137384802-04f67f5f-74de-49c9-a345-f54979284d72.png">

## Шаги к воспроизведению

1. Создеать комментарий с прономерованным списком но без цифр по порядку
2. Запостить его

**Comment by vas3k** [comment]
Мне кажется это фича 🤔
