### ISSUE TITLE
Фича: смена сортировки каментов показывает сразу каменты

### ISSUE THREAD

**Issue by Anatolt** [vas3k/vas3k.club#743]
Сейчас, если сменить сортировку каментов, то пользователя перемещает к началу поста. А посты частенько бывают довольно длинными. Было бы клёво, если бы при смене типа сортировки каментов пользователя переносило к каментам

**Comment by ninedev-i** [comment]
Я так полагаю это больше не воспроизводится

**Comment by Anatolt** [comment]
да, фичу реализовали. а как пометить её как реализованную?

**Comment by ninedev-i** [comment]
@vas3k можно закрывать
