### ISSUE TITLE
Баг: некоторые комментарии рандомно показываются как удалённые (меняется при перезагрузке страницы)

### ISSUE THREAD

**Issue by keyten** [vas3k/vas3k.club#745]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага
Комментарий показывается как удалённый, при том, что автор его не удалял, и это рандомно изменяется при перезагрузке страницы (для двух своих комментариев я поймал все 4 сочетания).

Спросил в телеграме, у других тоже воспроизводится https://t.me/c/1481658345/455479

Скриншоты ниже.

## Ожидаемый результат

Комментарии должны показываться удалёнными если они удалены, и должны показываться не удалёнными, если они не удалены.

## Шаги к воспроизведению

1. Перейти на https://vas3k.club/thread/12246/#comment-7ab5f943-1e17-469c-bd90-7b63204ea4ad и заметить, если один из двух комментариев Dmitriy Miroshnichenko показывается как удаленный.
2. Перезагрузить страницу. Возможно, иногда нужно подождать секунд 5-10 – есть ощущение, что там какая-то зависимость от времени.

**Comment by keyten** [comment]
<img width="890" alt="Screen Shot 2021-10-18 at 9 56 25 pm" src="https://user-images.githubusercontent.com/1017222/137719989-760a16dc-4368-4c43-967c-b37f1960a4ca.png">
<img width="828" alt="Screen Shot 2021-10-18 at 9 58 22 pm" src="https://user-images.githubusercontent.com/1017222/137720004-383eb55f-f96d-4da3-a503-4df0f886ce3f.png">
<img width="765" alt="Screen Shot 2021-10-18 at 9 58 36 pm" src="https://user-images.githubusercontent.com/1017222/137720020-66a54bba-2bf9-4192-9d46-2924d439778f.png">

<img width="781" alt="Screen Shot 2021-10-18 at 9 56 48 pm" src="https://user-images.githubusercontent.com/1017222/137720033-bc03879d-b1a2-4978-8d7c-18bd15459440.png">

**Comment by vas3k** [comment]
ОПЯТЬ ВИРУСЫ УУУУ!

> Но, кстати, модифицирующие GET-запросы это не очень хорошая идея, открою другой PR про это.

Да, кстати, можно заменить кнопку удаления на form + post, тогда можно будет отбивать всех по GET. Хорошая тема.
