### ISSUE TITLE
Баг: @vas3k_club_bot в Telegram присылает не все комментарии от моих чуваков

### ISSUE THREAD

**Issue by ngrishanov** [vas3k/vas3k.club#748]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [ ] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

@vas3k_club_bot почему-то пропускает часть комментов от моих чуваков.

Пример: я подписан на https://vas3k.club/user/Elly404/. 

<img width="856" alt="Снимок экрана 2021-10-20 в 16 48 54" src="https://user-images.githubusercontent.com/6131548/138087124-bbccbb48-807e-42c0-815f-950bcf3ee942.png">

2 часа назад она написала два коммента:

<img width="887" alt="Снимок экрана 2021-10-20 в 16 44 24" src="https://user-images.githubusercontent.com/6131548/138087186-d28abeeb-bd81-4e88-b7f3-e26bcadb353e.png">

Бот при этом прислал мне только один из них:

<img width="682" alt="Снимок экрана 2021-10-20 в 16 44 16" src="https://user-images.githubusercontent.com/6131548/138087250-9fabec61-10b5-4389-9e85-84fe3ad84f4b.png">

## Ожидаемый результат

Жду, что бот будет пересылать мне все комментарии.

## Шаги к воспроизведению

Хз, но замечаю такое не первый раз и на разных чуваках.

**Comment by vas3k** [comment]
Ну в принципе можем для теста попробовать убрать все эти проверки и посмотреть придёт ли кто-то сюда с обратным "багом", что бот теперь пингует на каждый пук. Будет А/В тест :)
