### ISSUE TITLE
С4 схема архитектуры приложения

### ISSUE THREAD

**Issue by edbond88** [vas3k/vas3k.club#758]
## Чеклист

- [x] Я считаю, что фича офигенная и принесет пользу Клубу 🎩
- [x] Я поискал по трекеру похожие идеи, в том числе в закрытых Issues

## Описание фичи

Предлагаю сделать простенькую схему в формате c4. Думаю будет достаточно level 1 и level 2 схемы.
Схема будет полезна всем, кто хочет законтрибьютить в проект или использовать у себя.

## Немного про C4 Model
Ссылка на подробное описание c4 с крутыми примерами: https://c4model.com

**Диаграммы контекста (level 1):** показывают систему в масштабе ее взаимодействия с пользователями и другими системами

**Диаграммы контейнеров (level 2):** разбивают систему на взаимосвязанные контейнеры. Контейнер - это исполняемая и развертываемая подсистема;

## Решение
Я накидал примерную схемку, чтобы от нее можно было отталкиваться и добавлять нужные блоки. 
[Ссылка на исходник на гугл диск](https://drive.google.com/file/d/1rNwPE-kKDQ9OCxCjURaqZIm7dkBlvfEp/view?usp=sharing) 

Сделал в https://app.diagrams.net/ т.к. там нашел пресет под c4. Возможно будет удобней это сделать в каком-нибудь Miro и расшарить

## Открыть схему в новом окне в большем размере
![vas3k-arch](https://user-images.githubusercontent.com/1949927/138835432-57f41c0b-8138-4e05-bbaa-ba5ff84c49b9.png)

**Comment by vas3k** [comment]
Ну, пока всё звучит разумно. А что дальше? Как планируется обновлять схему и поддерживать в актуальном состоянии?

**Comment by edbond88** [comment]
Ну основные мейнтейнеры проекта по идее должны саппортить такое. Так же можно вносить правки через PRы.
