### ISSUE TITLE
Сортировка по дате добавления поста

### ISSUE THREAD

**Issue by kartashovata** [vas3k/vas3k.club#76]
Классно, что посты пушатся вверх страницы комментами, но, может быть, можно добавить опцию сортировки по дате? А то не очень удобно смотреть на предмет новых постов, когда большую часть ленты занимают прочитанные, но новооткомменченные. 

(Не могу кнопку меток найти =/ sorry )

**Comment by FMajesty** [comment]
Хорошая идея.

**Comment by pavel-voronin** [comment]
То же для комментариев в постах

**Comment by vas3k** [comment]
Она уже даже есть на бекенде, проблема лишь в том, как придумать ей ненавязчивый UI. Делать огромную выпадашку сверху не хочу. Кто покажет картинку как это можно сделать красиво — сразу запилю.

**Comment by FMajesty** [comment]
Мм, вообще можно переключалку какую-нибудь. С текстом. Типа таких:
https://codyhouse.co/ds/components/app/radio-switch-v2
https://codyhouse.co/ds/components/app/radio-switch

Хм!
