### ISSUE TITLE
Баг: Поехали лейблы ачивок в мобильной версии

### ISSUE THREAD

**Issue by vorant94** [vas3k/vas3k.club#761]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Когда ачивок на мобилке две в ряду, то их лейблы с пояснениями выезжают за границы экрана.

| левая ачивка | правая ачивка |
|---|---|
| ![IMG_3462](https://user-images.githubusercontent.com/9719319/139481049-9031d625-35bc-4a96-9a27-558f1ea65c30.PNG) | ![IMG_3463](https://user-images.githubusercontent.com/9719319/139481040-5accb7b2-80f8-40ed-b52f-eb15815dd47f.PNG) |

## Ожидаемый результат

По идее у лейблов крайних ачивок должно быть смещение в противоположную сторону, чтобы лейбл был примерно по центру и весь текст был виден

## Шаги к воспроизведению

1. Зайти с тела в профиль юзера с 2+ ачивками

**Comment by dmitvitalii** [comment]
https://github.com/vas3k/vas3k.club/issues/694
