### ISSUE TITLE
Кастомизировать редактирование интро

### ISSUE THREAD

**Issue by Windrushfarer** [vas3k/vas3k.club#78]
Т.к для интро используется тот же шаблон, что и для поста, то при редактировании у нас есть все элементы поста. Из-за этого неправильный заголовок и `title`. Возможно для интро лучше кастомизировать шаблон, чтобы не было лишнего
![](http://s.csssr.ru/U439TP407/20200430221326.png)

**Comment by vas3k** [comment]
Да, норм, просто создайте для типа intro отдельный шаблон на основе post и удалите из него ненужное. Простой тикет, подойдет для новичков!
