### ISSUE TITLE
Фича: показать в профиле выданные мною награды

### ISSUE THREAD

**Issue by dmitvitalii** [vas3k/vas3k.club#781]
## Чеклист

- [x] Я считаю, что фича офигенная и принесет пользу Клубу 🎩
- [x] Я поискал по трекеру похожие идеи, в том числе в закрытых Issues

## Описание фичи

Добавить возможность посмотреть в профиле, кому и за что выдал награду

**Comment by vas3k** [comment]
Перенес в обсуждения на голосование https://github.com/vas3k/vas3k.club/discussions/817
