### ISSUE TITLE
Баг: На странице профиля вместо текста ссылки HTML

### ISSUE THREAD

**Issue by mecurc** [vas3k/vas3k.club#785]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Ссылка на телеграмм на странице профиля отображается на ШТМЛе:

![Screenshot 2021-11-15 at 23 56 18](https://user-images.githubusercontent.com/33278950/141852760-7e9dcbc1-f540-48b7-a293-3b1a2ae86765.png)

При этом на странице профиля у меня такой текст (доступен при редактировании)
![Screenshot 2021-11-15 at 23 59 40](https://user-images.githubusercontent.com/33278950/141853120-f810b356-33dc-4036-ae02-83424452b713.png)

## Ожидаемый результат
Маркдовн-ссылка должна отображаться корректно

**Comment by devcooch** [comment]
Дубль #736 #570
