### ISSUE TITLE
Фича: Возможность модератору указывать причину удаления комментария

### ISSUE THREAD

**Issue by ifegee** [vas3k/vas3k.club#787]
## Чеклист

- [x] Я считаю, что фича офигенная и принесет пользу Клубу 🎩
- [x] Я поискал по трекеру похожие идеи, в том числе в закрытых Issues

## Описание фичи
Сделать удаление комментов модераторами с выбором причины, которая пробрасывалась бы в такое пояснение в сам комментарий:
![telegram-cloud-photo-size-2-5251564913955026545-y](https://user-images.githubusercontent.com/56275431/143234512-e913c91c-2386-4d8f-9cde-91ef9133f610.jpg)

Примеры причин:
👹 Комментарий удален модератором из-за провокаций на срач.
🤬 Комментарий удален модератором из-за агрессии.
🙅 Комментарий удален модератором за несоблюдение шаблона треда.
😱 Комментарий удален модератором без объяснения причин.
etc.

**Comment by vas3k** [comment]
Реорганизуем ишьюсы, перенес в дискуссии https://github.com/vas3k/vas3k.club/discussions/814
