### ISSUE TITLE
Баг: поиск по людям не работает

### ISSUE THREAD

**Issue by ngrishanov** [vas3k/vas3k.club#789]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Поиск по людям всегда возвращает пустой результат, вне зависимости от запроса.
Пример для https://vas3k.club/search/?q=Nikita&type=user

<img width="1121" alt="Снимок экрана 2021-11-28 в 22 23 41" src="https://user-images.githubusercontent.com/6131548/143778972-fb433b88-9e6e-4bd4-8ae0-9d2310a94a1a.png">

## Ожидаемый результат

Поиск по людям возвращает что-то.

## Шаги к воспроизведению

1. Написать запрос в строке поиска
2. Кликнуть на вкладку "Люди"

**Comment by ngrishanov** [comment]
Сейчас всё работает, поэтому закрыл 🤷‍♂️

**Comment by vas3k** [comment]
Переиндексация срабатывает пару раз в неделю, ага
