### ISSUE TITLE
Баг: 404 после того, как пытаюсь сохранить пост или идею

### ISSUE THREAD

**Issue by eliseealex** [vas3k/vas3k.club#792]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Попытался написать написать идею, сохранил черновик, после этого меня перенаправило на страницу с текстом:
```
Not Found
The requested resource was not found on this server.
```

И кодом ответа 404.

При этом на странице https://vas3k.club/create/ я вижу свои черновики, но если перехожу на их страницу, например: https://vas3k.club/idea/12873/, появляется та же ошибка. Проверил, что для идеи воспроизвелось дважды и один раз для поста

## Ожидаемый результат

Я ожидаю, что смогу увидеть свой черновик.

## Шаги к воспроизведению

1. Перейти на страницу https://vas3k.club/create/idea/
2. Заполнить все обязательные поля
3. Нажать на "Сохранить черновик"
4. Получить ошибку

**Comment by vas3k** [comment]
Ух, мой косяк
