### ISSUE TITLE
Баг: при достижении 10к плюсиков в профиле счетчик показывает 1к

### ISSUE THREAD

**Issue by shkaff** [vas3k/vas3k.club#798]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

По достижении 10к плюсиков стало показывать 1к в профиле (https://vas3k.club/user/MikhailKorobko/). При этом в других профилях c >10к отображается нормально: https://vas3k.club/user/ganqqwerty/

## Ожидаемый результат

По достижении 10к показывает 10к:)

## Шаги к воспроизведению

1. Перейти сюда: https://vas3k.club/user/MikhailKorobko/
2. Увидеть 1к плюсиков под профилем
3. Поверить, что должно быть 10к

**Comment by vas3k** [comment]
Вот с налогами такая же херня!

**Comment by ganqqwerty** [comment]
попробую поковырять функцию [cool_number](https://github.com/vas3k/vas3k.club/blob/f9673afd44a877269a2b4dbdda7a18c0a5d40d98/posts/templatetags/text_filters.py#L43)

**Comment by ganqqwerty** [comment]
![image](https://user-images.githubusercontent.com/697308/147363185-06f6997e-1971-4258-b04e-df6af2235790.png)
