### ISSUE TITLE
Кликабельные интересы в профилях участников

### ISSUE THREAD

**Issue by gavvvr** [vas3k/vas3k.club#80]
Когда захожу в чей-то профиль, могу кликать на интерес, как будто:

- я мог бы активировать или деактивировать хобби другому участнику
- или я мог бы найти всех участников с таким же интересом

Но на самом деле ничего не происходит. Думаю, что интересы других людей должны быть нeкликабельны. Или клик по интересу в чужом профиле должен отображать список всех людей с выбранным интересом

**Comment by vas3k** [comment]
Fixed
