### ISSUE TITLE
Фича: добавить информацию как добавлять картинку в комментарии

### ISSUE THREAD

**Issue by bbakalov** [vas3k/vas3k.club#809]
## Чеклист

- [x] Я считаю, что фича офигенная и принесет пользу Клубу 🎩
- [x] Я поискал по трекеру похожие идеи, в том числе в закрытых Issues

## Описание фичи
В описание правил что и как можно комментировать, добавить текст про возможность вставлять картинки при помощи drag and drop и CTRL + V

![](https://user-images.githubusercontent.com/9625352/146822885-dd647bfe-6e5a-4aaf-8687-85d8a0bf90d5.png)

**Comment by bbakalov** [comment]
Если по быстрому утвердим текст, могу и сам покапаться где это сделать нужно и приготовить PR

**Comment by vas3k** [comment]
Строчка про Markdown по-моему достаточно объясняет как вставлять картинки. Я не фанат объяснять каждую мелкую вещь, там и так уже список из 5 пунктов, что очень плохо. Надо его уменьшать, а не увеличивать

**Comment by vas3k** [comment]
Надо сделать тулбар и всё
