### ISSUE TITLE
Некоторые проблемы с Markdown редактором

### ISSUE THREAD

**Issue by OdSt** [vas3k/vas3k.club#81]
Если набирать текст у себя, а затем его вставить в редактор клуба, то разметка ведет себя странным образом.

* Местами добавляются лишние пробелы, которых не было (например, в начале каждого абзаца).
* Местами добавляются лишние переносы строки доставляются после публикации (например, между некоторыми пунктами списка).
* При вставке пикч (именно с заливкой на вастрик.фотохостинг) едет форматирование текста в списке или абзаце идущем следом за пикчей. Иногда форматирование ломается в других случайных местах (Дело, опять же, в лишних пробелах, которые доставляются в абзацы при вставке пикч).

Проверено на последней лисе

**Comment by FMajesty** [comment]
@OdSt 
Распишешь чуть подробнее?

**Comment by OdSt** [comment]
Стоило поспать сутки, как баги перестали воспроизводиться. Исследование продолжается.

Если кратко, то пробелы доставлялись в начале каждого абзаца, при вставке текста или файла рядом

**Comment by lespaul1488** [comment]
> Если кратко, то пробелы доставлялись в начале каждого абзаца, при вставке текста или файла рядом

Тоже сегодня заметил

**Comment by TiraelSedai** [comment]
Мой любимый смайлик ¯\_(ツ)_/¯ ломается, это ужасно!

**Comment by FMajesty** [comment]
@lespauI, не мог бы подробнее описать?

**Comment by lespauI** [comment]
Я написал текст в поле коммента, потом вырезал его и положил в нотпад чтобы проверить спелчекером, и когда я вставил его обратно в форму комментария впереди стояли два пробела. Хром + мак ос

**Comment by Vostenzuk** [comment]
Если обернуть текст в две звездочки (сделать **болдом**), то если в конце предложения перед звездочками есть лишний пробел, маркдаун не чувствует, что я вроде как закончил болд.
![image](https://user-images.githubusercontent.com/19980512/81021717-78aa5200-8e74-11ea-9e3b-32ddc63f7fb0.png)

**Comment by dimabory** [comment]
@Vostenzuk К сожалению, бага с болдом в third-party library.

https://github.com/Ionaru/easy-markdown-editor/issues/74

**Comment by skywinder** [comment]
@dimabory спасибо за реф. 

Дальше предлагаю обсудить в основном треде про макрдаун эдитор в #103

закрываю, тк это3rd party bug
