### ISSUE TITLE
Фича: возможность делиться драфтом

### ISSUE THREAD

**Issue by skatkov** [vas3k/vas3k.club#811]
## Чеклист

- [x] Я считаю, что фича офигенная и принесет пользу Клубу 🎩
- [x] Я поискал по трекеру похожие идеи, в том числе в закрытых Issues

## Описание фичи
Очень часто, я немного не уверен готов ли пост к тому, чтобы его публиковать. Чтобы бороться с этой напастью, я бы хотел иметь возможность поделиться драфтом с некоторыми участниками сообщества.

Для первого прототипа, просто возможность сделать уникальный урл, с которым можно поделиться приватно -- уже было бы классно.
Но в идеале, было бы классно иметь возможность добавлять комментарии ревьюру. Или выбирать с кем именно из клуба хочется поделиться драфтом.

**Comment by vas3k** [comment]
Вот кстати да, сам ни раз уже сталкивался с нуждой. Надо придумать как-то, но защититься от брутфорсеров. 

Для ревьюеров можешь использовать соавторов. Добавляешь конкретного юзера в соавторы — он может видеть черновик

**Comment by skatkov** [comment]
Соавторы вроде не доступны для всех видов постов? Я пытался вчера про свой проект написать, но там никак не добавить соавтора.

**Comment by vas3k** [comment]
Можно добавить их к проектам. Пока они только у постов и гайдов, ага

**Comment by vas3k** [comment]
Реорганизуем ишьюсы, перенес в дискуссии https://github.com/vas3k/vas3k.club/discussions/815
