### ISSUE TITLE
Баг: Удаление аккаунта поднимает на главную все посты, в которых он комментировал

### ISSUE THREAD

**Issue by ndrewnee** [vas3k/vas3k.club#813]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Заметил, что в фиде появилось очень много старых постов, в которых вроде давно не было новых комментариев

<img width="773" alt="Screen Shot 2021-12-25 at 01 36 24" src="https://user-images.githubusercontent.com/12291467/147371738-01ca1e3e-5253-4862-9f53-60c3dbb273d9.png">

Кажется во всех из них присутствуют комментарии аккаунта, который недавно был удален

<img width="677" alt="Screen Shot 2021-12-25 at 01 36 30" src="https://user-images.githubusercontent.com/12291467/147371761-62218a0a-9fc6-414b-b2a6-58156a003394.png">

Возможно это совпадение или это не баг, а фича, но мне показалось это странным.

## Ожидаемый результат

Удаление аккаунта не поднимает все темы, которые он комментировал на главную

## Шаги к воспроизведению

1. Прокомментировать посты
2. Удалить аккаунт
3. Посты поднимутся на главную

**Comment by vas3k** [comment]
И правда, воспроизвелось. Если автор в предсмертной агонии начинает удалять каждый свой коммент по одному — это поднимает посты. Починим
