### ISSUE TITLE
Посты сортируются по дате создания черновика, а не по дате публикации

### ISSUE THREAD

**Issue by devcooch** [vas3k/vas3k.club#83]
Вижу мой свежеопубликованный пост (https://vas3k.club/post/1072/) не вверху Кухни или всего клуба, а судя по всему по дате создания черновика.

**Comment by vas3k** [comment]
Пост подбрасывается наверх при одобрении модератором. Пока от этой логики отказаться сложно, ибо тогда ломаются другие места

**Comment by devcooch** [comment]
А блин, сорри. Чорт, неочевидно, может какой ворнинг писать, что там ещё модерация.

**Comment by vas3k** [comment]
Там постмодерация, так что ворнинг будет только пугать людей
