### ISSUE TITLE
Bug: возможность замьютить самого себя

### ISSUE THREAD

**Issue by mamadjani** [vas3k/vas3k.club#856]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Пользователь технически может замьюить самого себя, после чего не сможет увидеть свои посты и комментарии.
Отмьютить себя пользователь тоже может самостоятельно (это работает в обе стороны).

## Ожидаемый результат

- При вызове мьюта самого себя система показывает шаблон с заглушкой: нельзя мьютить себя.
- Невозможность мьюта и размьюта самого себя.

## Шаги к воспроизведению

1. **Mute**: перейти на URL `vas3k.club/user/%USERNAME%/mute/`, где `%USERNAME%` — псевдоним пользователя (slug) 
2. Следовать мастеру мьюта.
3. **Unmute**: перейти на URL `vas3k.club/user/%USERNAME%/mute/`, где `%USERNAME%` — псевдоним пользователя (slug) 
4. Следовать мастеру мьюта.

Скриншот со страницы шаблона мьюта (продакшн):
![image](https://user-images.githubusercontent.com/94802477/148997272-685359bd-4d61-4f69-9dee-2b6beb6045d3.png)

**Comment by vas3k** [comment]
Орнул. Да это же пушка!

**Comment by mamadjani** [comment]
@vas3k need review on #858
