### ISSUE TITLE
Баг: ссылка на профиль в комментарии ведёт на пустую страницу (404)

### ISSUE THREAD

**Issue by mamadjani** [vas3k/vas3k.club#864]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

В комментарии ссылка на профиль ведёт на страницу 404.
https://vas3k.club/question/2349/#comment-df4f1bf1-3057-45f6-98ff-ac85886257fc

Автор не заблокирован, отображается аватарка и профиль. 

## Ожидаемый результат

Клик по имени автора ведёт на страницу комментария.

## Шаги к воспроизведению

1. Перейти по ссылке https://vas3k.club/question/2349/#comment-df4f1bf1-3057-45f6-98ff-ac85886257fc
2. Нажать на имя автора комментария (Александр)
3. Перейти на страницу /user/kellas/, получить 404

**Comment by neoromantique** [comment]
https://vas3k.club/user/rip/

Тоже

**Comment by vas3k** [comment]
Ага, починил. Удалённые юзеры действительно показывались как 404 на те 7 дней, что им даётся для восстановления аккаунта. Удалил это условие, теперь все могут увидеть, что юзер сбежал. Через 7 дней всё равно они все превратятся в пыль и их комменты анонимизируются :)

Для размодерированных юзеров пока решения нет.

**Comment by mamadjani** [comment]
> Для размодерированных юзеров пока решения нет.
@vas3k для размодерированных юзеров удобнее создать новый тип Exception с шаблоном страницы: «Пользователь %s размодерирован».

В идеале и для «сбежавших» тоже :-)

**Comment by vas3k** [comment]
> @vas3k для размодерированных юзеров удобнее создать новый тип Exception с шаблоном страницы: «Пользователь %s размодерирован».

В этом и проблема, у нас нет отдельного типа для "размодерированных", они просто становятся как будто не зарегистрированными

**Comment by mamadjani** [comment]
Хм, ситуация интересная. Думаю заняться на днях реализацией, нужно подумать как это сделать без изменения существующих моделей (или с минимальными изменениями).

Так как ты сделал рабочий хотфикс, я закрою этот ишью и открою новый — насчёт статуса размодерированных.
