### ISSUE TITLE
Баг: Если заигнорить человека и нажать кнопку "Назад" в браузере автоматически разблокирует человека.

### ISSUE THREAD

**Issue by neoromantique** [vas3k/vas3k.club#868]
## Чеклист

- [X] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [X] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

Если заигнорить человека и нажать кнопку "Назад" в браузере автоматически разблокирует человека.

## Ожидаемый результат

Не должно ничего происходить без явных действий пользователя(клик по кнопке хотя бы)

## Шаги к воспроизведению

1. Замьютить человека
2. Перейти куда угодно
3. Нажать кнопку назад
4. Получить радосное сообщение что вы разблокировали человека

**Comment by Programistich** [comment]
Разве там получается сообщение о разблокировке человека?
Там просто идет шаг назад и предлагают разблокировать человека, т.е кнопочка

**Comment by neoromantique** [comment]
> Разве там получается сообщение о разблокировке человека? Там просто идет шаг назад и предлагают разблокировать человека, т.е кнопочка

Видимо добавили ибо на прошлой недели кнопки не было а просто сообщение
