### ISSUE TITLE
Баг: Некоторых людей из парламента можно замьютить

### ISSUE THREAD

**Issue by dolshevsk** [vas3k/vas3k.club#872]
## Чеклист

- [X] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [X] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

У некоторых людей из парламента в интро отображается кнопка "Я не хочу видеть его в Клубе", и по коду, кажется, также возможно его отправить в мут.

## Ожидаемый результат

Функция мьюта не должна быть возможна для членов из парламента

## Шаги к воспроизведению

[1](https://vas3k.club/user/anatolt/)
[2](https://vas3k.club/user/JulyJazz/)
[3](https://vas3k.club/user/Sciannadev/)

<img width="1169" alt="Screenshot 2022-01-17 at 10 51 05 PM" src="https://user-images.githubusercontent.com/36140450/149840608-3b897df8-f036-4754-a612-eb120004d5bc.png">

**Comment by dolshevsk** [comment]
Я провел небольшой ресерч и пришел к тому, что такое возможно, если эти люди имеют ачивку парламента, но не имеют роль "Куратора".

Такое могло произойти, в следствие того, что создание ачивки не провоцирует создание роли. Я даже думал это сам пофиксить через сигналы, но, возможно, это не самое лучшее решение, тк не понятно, как именно член в парламент добавляется. 

Если сделать это через сигналы, тогда модераторы через ачивку смогут создавать кураторов, однако если кураторов хочет создавать только вастрик, как он делает с модераторами, то может лучше сделать от обратно и на добавление роли "Куратор" через сигналы давать ачивку?

Так же я бы подумал о том, чтобы в статистике клуба членов парламента фетчить через роль, а не через ачивку, потому что именно роль делает тебя полноценным (в плане функционала и пермишенов) членом парламента.

**Comment by vas3k** [comment]
А ты молодец, всё так и есть :) Куратор выдается пока руками, надо наверное дать возможность модераторам это делать, а не только мне

**Comment by dolshevsk** [comment]
Я вообще готов взять на себя фикс этой баги. Хотелось бы только узнать, каким бы ты хотел видеть этот флоу? 

Отдельный admin_action? Через добавление ачивки и сигналы?

**Comment by vas3k** [comment]
Думаю, еще проще. У модераторов есть отдельная вьюха https://vas3k.club/user/vas3k/admin/

В ней можно менять ник, имя и почту. Туда давно надо добавить и другие поля из базы, например:
- is_email_verified
- is_banned_until
- telegram_id
- stripe_id
- roles (как раз кейс из этого тикета)
- contact
- email_digest_type 
- membership_platform_type
- company
- position

Если добавишь сразу все (и аккуратно учтешь их типы, там есть bool, есть array), то будет очень круто и ты закроешь нам кучу головных болей, которые сейчас требуют моего личного вмешательства. Буду очень благодарен!

**Comment by vas3k** [comment]
Автоматизировать ачивки пока не будем, может потом как-нибудь. Пока мы просто расскажем модераторам, что надо прописывать в roles значение [curator] (да, именно массивом) и они смогут это делать для всех новых парламентариев

**Comment by dolshevsk** [comment]
ок, завтра-послезавтра скину PRP
