### ISSUE TITLE
Search pagination has broken links

### ISSUE THREAD

**Issue by sudodoki** [vas3k/vas3k.club#92]
Links in pagination don't include `query` param so they get redirected to landing page

**Comment by vas3k** [comment]
Clearly a bug. We need to handle GET params better in the [paginator template](https://github.com/vas3k/vas3k.club/blob/e0d71c69a9238107a261b9d51e7a6d8dafae10ef/frontend/html/common/paginator.html#L10).

**Comment by sudodoki** [comment]
@vas3k given pagination is used in different places it's either:
- some `extra_params` argument for pagination
- change search to have /search/:query url and page param would work ok
- custom template for search pagination with extra `query` coming from context (clearly, I'm no django expert). 

Any preferences?

**Comment by vas3k** [comment]
I like the 2nd, if you can get it work with the search forms. If not, we can make a custom template filter to parse the current URI and add the GET parameter instead of overwriting it.
