### ISSUE TITLE
Баг: RSS фид не рендерится из HTML

### ISSUE THREAD

**Issue by Fntquie** [vas3k/vas3k.club#930]
## Чеклист

- [x] Я поискал поиском по трекеру похожие проблемы, в том числе в закрытых Issues
- [x] Баг стабильно воспроизводится и я знаю как это сделать

## Описание бага

**Environment**: MacOS, Chrome 100.0.4896.88 (x86_64)

С десктопа при открытии RSS фида по [ссылке](https://vas3k.ru/rss/private/) стабильно получаю не срендеренный HTML. Выглядит не очень:
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/17274915/164339515-10688fd1-cd61-4a97-ae43-40d602b32e11.png">

## Ожидаемый результат

Если только я не упустил из виду какую-то шутку, то должна быть видна визуально легко читаемая RSS лента, то есть HTML разметка должна генериться в визуал.

## Шаги к воспроизведению

1. Купить Mac
2. Установить Chrome 100.0.4896.88 (x86_64)
3. Залогиниться в Клуб
4. Открыть в Chrome ссылку https://vas3k.ru/rss/private/
5. Получить ошибку
6. Простить меня за несмешные шутки выше

**Comment by Programistich** [comment]
А разве не нужно эту ссылку вставить в rss reader? Она не для браузера же

**Comment by Fntquie** [comment]
Видимо, это моя ошибка. Я почему-то решил, что RSS на сайте будет рендериться в полноценный фид... Тикет закрываю
