### ISSUE TITLE
Баг: каналы распознаются ботом как боты

### ISSUE THREAD

**Issue by Anatolt** [vas3k/vas3k.club#937]
Если человек пишет от имени канала и если на него кинуть whois то клубный бот The Machine пишет что он бот.

**Comment by TiraelSedai** [comment]
https://core.telegram.org/bots/api#user

[Проверяется именно это поле](https://github.com/vas3k/vas3k.club/blob/ee97c1b50166a28213b9fba06e5e3105e8d4ea82/bot/handlers/whois.py#L29)

Судя по всему, сейчас никак не пофиксить

**Comment by TiraelSedai** [comment]
https://core.telegram.org/bots/api#message

Судя по всему, надо проверять `update.message.reply_to_message.sender_chat`

**Comment by vlle** [comment]
Попытался взять на себя ишшью для Хактоберфеста.
Я потыкал в метод `update.message.reply_to_message.sender_chat`, он _по-идее_ подходит, но не могу приручить его с учетом того, что бот написан на python-telegram-bot. Просто вылетает в AttributeError и все, когда я хочу проверить наличие sender_chat в Message. В Aiogram 3.0 такой проблемы нет.  Подумаю еще что делать )

**Comment by skywinder** [comment]
решил порезолвить старые таски.
в целом минорная проблема, которая никому не мешает. я бы просто оставил как есть.
но фикс уже есть, глазами чекнул - решение должно работать.

предлагаю или закрыть или замержить.
