### ISSUE TITLE
Превью для markdown

### ISSUE THREAD

**Issue by Quarezz** [vas3k/vas3k.club#97]
Сейчас приходится перепроверять свой синтаксис перед отправкой, копировать текст из/в markdown редактор, иногда приходится редактировать/удалять коментарий. Было бы удобно иметь какой-нибудь превью режим, который рендерит в окончательное отображение.

**Comment by skywinder** [comment]
+1. Возможно попробую задеплоить и сделать эту страничке пред-отправку

**Comment by vas3k** [comment]
В simpleMDE, редакторе, что я использую, даже есть этот режим. Нужен человек, кто аккуратно и правильно залинкует туда все CSS теги реального поста (не копипастой, конечно же). Потому что лучше отсутствие превью, чем плохое превью :)

А так — пожалуйста

**Comment by altmind** [comment]
ref https://github.com/sparksuite/simplemde-markdown-editor/issues/173

**Comment by dimabory** [comment]
> Превью для markdown

@Quarezz @vas3k 
Это относиться к постам или к комментариям/реплаям?

**Comment by vas3k** [comment]
@dimabory в комментах тоже по идее. Ориентируемся на гитхаб :)

**Comment by skywinder** [comment]
Уже обсуждается эта и другие вопросы с макрдаун в #103.
 TLDR: ищем хорошую либу на замену (WIP)

закрываю, дабы бы не плодить сущности.
