### ISSUE TITLE
[Improvement] Ссылка на комментарий

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#98]
Не нашел, как скопировать ссылку на комментарий, наподобие того, что присылает тебе бот.

# Step to reproduce
например мой коментарий -
https://vas3k.club/question/1122/#comment-59eab3fc-3c29-4ff1-8ef4-6b070b072b0b

Хочу сделать референс к родительскому комментарию (на который ответил).

кнопки с сылкой не нашел, посмотрел на ссылку для upvote к этому коменту: https://vas3k.club/comment/#a2bf6b2e-e8b5-4095-b9a7-6024043cf8fb/upvote/

 - убрал `upvote/` - https://vas3k.club/comment/#a2bf6b2e-e8b5-4095-b9a7-6024043cf8fb не работает
- тогда заменил хеш в своем https://vas3k.club/question/1122/#comment-a2bf6b2e-e8b5-4095-b9a7-6024043cf8fb - заработало.

---

Предлагаю сделать ссылку, наподобие stackoverflow - скопировать ссылку на ответ.

Вот как тут:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/3356474/80934256-8cf93b00-8df1-11ea-86ed-794edb15278c.png">

**Comment by vas3k** [comment]
Это сделано по клику на дату комментария, как во многих других сервисах. Перегружать интерфейс новыми кнопками пока не хочу

**Comment by hamsternik** [comment]
@vas3k а может попробовать добавить рядом, справа от даты, иконку "скопировать"?
Мне кажется, что это будет более очевидно для *конечного юзверя*, при этом не надо будет никаких новых кнопок.

Иконку можно взять довольно простенькую. Парочка вариантов:
* https://icons8.ru/icon/15047/скопировать
* https://icons8.ru/icon/29/скопировать
* https://icons8.ru/icon/pNYOTp5DinZ3/скопировать

ps. вижу что сам issue давно закрыт, но я тут впервые и правил не знаю. Еще вдруг обматюкаете за дубликат старого unresolved тикета. Если что, то я пересоздам как новый и прикреплю Figma, как оно выглядит.
