### ISSUE TITLE
Не отображается превью твитов в лисичке

### ISSUE THREAD

**Issue by skywinder** [vas3k/vas3k.club#99]
- отключил все приват-плагины
- отключил встроеную приватность лисы (слева от урл щит)
- почистил куки
- зашел через инкогнито для чистоты эксперимента

Все равно нет превью для комента https://vas3k.club/question/1122/#comment-a2bf6b2e-e8b5-4095-b9a7-6024043cf8fb

¯\\_(ツ)_/¯

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/3356474/80935129-64734000-8df5-11ea-9ccf-4fe8612d6808.png">

```
Loading failed for the <script> with source “https://vas3k.club/static/dist/main-077947cc13a973207bfd.js”.

->

<script type="text/javascript" src="/static/dist/main-077947cc13a973207bfd.js" ></script>
```

+

```
Loading failed for the <script> with source “https://platform.twitter.com/js/moment~timeline~tweet.99ce5e0e4617985354c5c426d7e1b9f4.js”. 1122:1:1
```

ps. 
(в сафари и хроме работает)

**Comment by TiraelSedai** [comment]
Работает в фаерфоксе 76.0.1, с включенным блокером трекеров; с юблок ориджин; и прайваси бейджер. Вин10

@skywinder перепроверь-ка

**Comment by skywinder** [comment]
@TiraelSedai проверил, теперь работает.
